### ISSUE TITLE
key-bindings.zsh clobbers `l` key in vi-mode

### ISSUE THREAD

**Issue by trevor** [robbyrussell/oh-my-zsh#2067]
key-bindings.zsh contains `bindkey -s '\el' "ls\n"` which is incompatible with vi mode.

**Comment by mcornella** [comment]
Can this be closed? I haven't experienced the `ls` behavior with vi-mode activated...

**Comment by trevor** [comment]
@mcornella is it still in key-bindings?

to replicate, type "who" [esc] "l" for example:

    % bindkey -s '\el' "ls\n"
    % whols
    zsh: command not found: whols

**Comment by mcornella** [comment]
It is still in `key-bindings.zsh` but with `vi-mode` active if I do `ESC`+`L` it doesn't happen. Maybe I'm using vi-mode wrong?

**Comment by trevor** [comment]
essentially any `bindkey -s '\e…'` statements can cause an awkward interjection when switching from vi-insert to vi-normal mode. this just happens to be extra noticable since `l` along with `h` are common movement keys.

if it's not occurring for you, it's likely related to the key typing rate, there's a 0.4s default window after typing `<ESC>` that `l` would need to be pressed to see the issue. (see KEYTIMEOUT in http://zsh.sourceforge.net/Doc/Release/Parameters.html#Parameters-Used-By-The-Shell-1 )

    % bash
    $ which zsh
    $ /usr/local/bin/zsh
    $ zsh --version
    zsh 5.0.7 (x86_64-apple-darwin14.0.0)
    $ exec env -i TERM=xterm-256color zsh --no-globalrcs --no-rcs
    % bindkey -v
    % bindkey -s '\el' "ls\n"
    ;; typed: vim<ESC>l
    % vimls
    zsh: command not found: vimls
    % echo $KEYTIMEOUT
    40

**Comment by mcornella** [comment]
> ```
% bindkey -v
```
Here's where I think the misunderstanding is, if you look at [line 18 of key-bindings.zsh](https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/key-bindings.zsh#L18) you'll see we're using emacs keymap. 
Once the `vi-mode` plugin switches to viins keymap, the defined '\el' key binding does not apply anymore. Please confirm by actually using oh-my-zsh directly instead of running `bindkey -s '\el' "ls\n"` on the command line, which you do _after_ switching to viins mode (therein the incompatibility).

If I run your same commands, it also happens to me, but not because of oh-my-zsh.

**Comment by trevor** [comment]
sounds good, we can close in that case. i'll assme the the issue is stale at this point.

**Comment by mcornella** [comment]
Thanks!

**Comment by mcornella** [comment]
And sorry for the long time to have someone comment (nearly 2 years!) :grin:

**Comment by trevor** [comment]
:) no prob, and thanks for the housekeeping! :+1:
