### ISSUE TITLE
zsh autosuggestions

### ISSUE THREAD

**Issue by tarruda** [robbyrussell/oh-my-zsh#2206]
Hi

I've implemented a fish-like autosuggestions system for zsh: https://github.com/tarruda/zsh-autosuggestions

Would you accept a patch wrapping everything into a oh-my-zsh plugin?

**Comment by mcornella** [comment]
You seem to have a very complete repository created and it's been an ongoing effort to put plugins out of the main repository, because it becomes impossible to mantain. So it's good as it is. I'd encourage you, though, to put instructions in the readme to install via `antigen`, which is a great project.

You can close this PR, thanks!
