### ISSUE TITLE
SVN Plugin messes up Prompt when URL contains Spaces

### ISSUE THREAD

**Issue by salsolatragus** [robbyrussell/oh-my-zsh#2233]
When the repository URL contains spaces, SVN plugin messes up prompt. For example with a folder named "cost model", svn_prompt_info evaluates to "| svn:%{%}[cost%20model%{%}]%{%}". The %20 of course is a problem.

The source of this is in svn_get_repo_name where the repository URL (line 28) is read. The URL should somehow be urldecoded.

Unfortunately, I failed to use the urltools here. Best thing I could come up with so far is adding " | sed 'y/+/ /; s/%/\x/g'". Then the prompt is not messed up any more, but it's not all to nice yet, either.

**Comment by apjanke** [comment]
Despite the filename, that is a URL *encoding* function. Here's a PR that uses a native `zsh` URL decoding function to decode them before including them in the prompt. #4128

It should still go one step further and escape the *decoded* prompt string, in case it had encoded `%` signs or other characters that would be interpreted as prompt escapes.

**Comment by apjanke** [comment]
This is fixed in #3582, which adds `urldecode` support.

Before:

![before](https://cloud.githubusercontent.com/assets/2618447/9809121/75a79486-5833-11e5-9adf-6246ceb243e1.png)

That long bogus directory is due to a non-decoded `%` from the repo URL that got made it in to the prompt string and ended up near a `d` so it got interpreted as `%d`, which prompt expansion expands to the current directory.

After:

![after](https://cloud.githubusercontent.com/assets/2618447/9809124/79879ed4-5833-11e5-9aed-b0a051425feb.png)
