### ISSUE TITLE
 Change in option+arrow keyboard movements in OS X?

### ISSUE THREAD

**Issue by ebsen** [robbyrussell/oh-my-zsh#2369]
Used to be that option+left arrow or option+right arrow would move the cursor in OS X's Terminal.app by word (mimicking, near as I can tell, the meta-f and meta-b keystrokes in *nix environments). I swear that was happening...at least until a week or so ago.

There was an update to OhMyZsh during this time and that's the only thing that I can think of in my Terminal environment that's changed so I thought I would ask. I have no idea where to start investigating this myself.

Thanks for all the hard work on OMZ, by the way. It's been a fantastic tool that I've very much enjoyed using. Props to everyone involved and happy holidays to all. :)

**Comment by apjanke** [comment]
Sounds like this may have been caused by #1355. That changed OMZ to use terminfo for its keybindings, instead of hardcoded terminal control sequences. And Terminal.app's default settings may not match the normal behavior of the `$TERM` it's declaring.

Possible dupe of #2696 and #2750.

Is this still happening for you? It's working for me in Terminal.app on OS X 10.9.5 with the current version of OMZ. If so, what OS version are you on, and what's the value of `$TERM` in your `zsh` session?

**Comment by ebsen** [comment]
This hasn't been an issue for me for some time. In fact, looking back I'm not even sure it was an issue with ZSH but with switching the Terminal.app profile to one that didn't include that keyboard shortcut.

If it helps, `echo $TERM` returns `xterm-256color`.

**Comment by apjanke** [comment]
That profile explanation sounds likely. If it's working for you now, could you close this issue?

**Comment by ebsen** [comment]
Yep.
