### ISSUE TITLE
bower completion error with many commands (list, info, help, etc.)

### ISSUE THREAD

**Issue by simonweil** [robbyrussell/oh-my-zsh#2694]
Here is an example output for the <TAB> for the list command.

```
➜  ~  bower list <TAB>_bower:67: command not found: --no-color[Do not print colors (available in all commands)]
_bower:67: command not found: --no-color[Do not print colors (available in all commands)]
_bower:67: command not found: --no-color[Do not print colors (available in all commands)]
```

**Comment by vko-online** [comment]
`bl jq [+TAB]` still throws 
```bash
bl jq_bower:67: command not found: --no-color[Do not print colors (available in all commands)]
_bower:67: command not found: --no-color[Do not print colors (available in all commands)]
_bower:67: command not found: --no-color[Do not print colors (available in all commands)]
```

**Comment by ncanceill** [comment]
One year without a reply! @dongweiming @miklos-martin please respond!

Would anyone else be willing to submit a patch?

**Comment by miklos-martin** [comment]
I suggest you to keep only one of the two plugins. They can conflict in many ways, I guess.
@ncanceill I don't use bower anymore, so I can't test it for you ATM, but I also think you provided the fix for @dongweiming's version. If I were you, I would just open a PR with that, and kindly ask someone to test it.
