### ISSUE TITLE
Enable managing issues and pull requests to collaborators

### ISSUE THREAD

**Issue by mcornella** [robbyrussell/oh-my-zsh#2771]
Because the _status quo_ of the project makes mantaining the project a real PITA.

@robbyrussell barely has time to keep up. He went on a marathon to drive down like 800+ issues (which was awesome!), but the underlying issues with the current system are still there, and not having someone moderate the project means it gets neglected. 
As a bad, bad consequence, people are less inclined to submit a patch or contribute in any way because it seems that it's all for nothing. 
We need a few moderators to do a little cleanup, because a cluttered room is no good for anyone, as well as a better and more manageable system (#2766 and #2769 take on that).

This has a couple of downsides: 
**1)** we can't have any person managing the codebase for the potential of implanting "bad stuff". <paranoia>Think Heartbleed, the _National Scrabble Association_ and their plan to take on sysadmins</paranoia>. 
**2)** different moderators could mean divergence of opinions and of what-to-do/how-to-do.

But those are easily solved by: 
**1)** having a clear codebase and issues page (not like OpenSSL) and a greater number of contributing users (the more eyes the better) which would make any attempt obvious.
**2)** a written "code of conduct" or whatever you want to call it that ensures a uniform and standard way of managing.

I want to leave here a text that I read a couple of weeks ago, about _gardening_ an open source project, which I think is a great metaphor for what we do: [how to be an open source gardener](http://words.steveklabnik.com/how-to-be-an-open-source-gardener). I think it provides some good advices that we could all get behind, and an inspiring view of why we do this in the first place.

The [Volunteer's page](https://github.com/robbyrussell/oh-my-zsh/wiki/Volunteers) was written 3 years ago, but it's never been put to use. Better late than never.

I'm cc-ing a few users that contribute (or contributed) a lot to drive this discussion. If I'm missing someone please add them: @ncanceill @Stibbons @LFDM

**Comment by mcornella** [comment]
Closing this for the moment since we didn't get anywhere...

**Comment by apjanke** [comment]
Hey, @robbyrussell et al.

I'd like to volunteer some of my time for issue management as discussed at https://github.com/robbyrussell/oh-my-zsh/wiki/Volunteers#issue-management. (I'm dropping a comment on this issue b/c the wiki says "get in touch with @robbyrussell" but there's no email on your profile, and I didn't know if your web page contact form was appropriate for oh-my-zsh or if that's more a business thing. Sorry if I'm spamming y'all.)

I'm new to GitHub and open source development, but I have some experience doing project management and issue tracking/workflow on moderate sized in-house software projects.

It seems like a lot of the concerns (and bad optics) with the issue backlog could be addressed if the issues were all categorized appropriately: most are low-priority things for contributed themes or plugins; few for core oh-my-zsh itself. I'm willing to spend some time going through and labelling them appropriately and defining some search filters that would sort them out in to queues like:
* core oh-my-zsh bugs or feature requests that really need some attention
* plugin and theme stuff that's lower priority
* support requests and discussion
and I think that could be done just with judicious use of the existing issue labels and maybe a couple additions.

An idea for a workaround for GitHub's coarse-grained permissioning problems: a moderator could use a separate account for doing administrative work, which gets granted Contributor permissions for the repository. They would log in to GitHub a browser with that for admin work, but not in their Git clients, so it wouldn't be linked to their normal account that they run `git` with, and there's a low risk of them accidentally pushing changes to the repo. E.g. I have a separate [apjanke-admin](https://github.com/apjanke-admin) GitHub account I could use for this; I'd log in to GitHub on an independent browser session, but not use `git` or SourceTree with it. You'd still have to trust them as humans: this prevents accidents, but not intentional sabotage.

Let me know if you think I could be of use and you want a volunteer.

**Comment by apjanke** [comment]
Oh, and in practical terms, this would let us define a few work queues in terms of GitHub search filters:
* things Robby actually needs to look at: core (not themes/plugins) bugs & feature requests
* low-hanging fruit for new contributors who want to get involved as omz devs
* issues that haven't had a response yet
and you could have an "outstanding" queue as things that haven't been tagged as low-impact one way or another. Which would be good for users thinking about adopting oh-my-zsh to be able to see "14 outstanding serious issues" instead of "600 issues + PRs".

For me personally, I'd like to get involved as an oh-my-zsh developer or power user and help people out, but there's no easy on-ramp for "unadressed issues for people to grind through and do something about" as opposed to "all the pending issues on GitHub" and I end up having to go through several pages of issues and remember what I haven't seen yet. If there were something like a "Pending" tag and categorizations that let you construct a work queue of "things that need addressing" by subtraction, that would be useful, I think.

**Comment by Stibbons** [comment]
What could be the process for plugin maintainance? Different people might want aliases differently, ... ?
