### ISSUE TITLE
terminalapp plugin breaks the prompt

### ISSUE THREAD

**Issue by gabrielecirulli** [robbyrussell/oh-my-zsh#2937]
After noticing that zsh on OS X was not remembering the current directory when I open a new tab as a command is running (in this case, the Rails server), I found a solution [here](http://superuser.com/questions/232835/zsh-open-a-new-tab-in-the-same-directory) and I added `plugins=(git osx terminalapp)` in `.zshrc`.

Even though this made the terminal remember the directory even when a command is running, the problem I'm facing right now is that whenever I'm in a git repository, and I type a command, the command text will overwrite my prompt:

![2048 gabriele mercury_ _work_web_development_projects_personal_2048 personal_2048 zsh zsh 10024](https://cloud.githubusercontent.com/assets/886011/3499879/57615ab0-0605-11e4-94aa-bff4983b0436.png)

When I type, the text just overwrites the `$` prompt:

![2048 gabriele mercury_ _work_web_development_projects_personal_2048 personal_2048 zsh zsh 10024-1](https://cloud.githubusercontent.com/assets/886011/3499886/692d0f8c-0605-11e4-90c8-a3630e13c023.png)

This is how it should actually behave (it behaves correctly in directories that are not git repos):

![gabriele gabriele mercury_ zsh zsh 10024](https://cloud.githubusercontent.com/assets/886011/3499895/89758da0-0605-11e4-9198-14dd035e4453.png)

I pinpointed the problem to the `terminalapp` plugin (`plugins/terminalapp/terminalapp.plugin.zsh`), but I couldn't find a straightforward way to fix it (I am also new to zsh).

Is there a solution to this issue?

**EDIT:** I am using a slightly modified version of the Avit theme, [found here](https://gist.github.com/gabrielecirulli/e297da3e8a318d76fcd3). I noticed that the Avit theme also displays this issue, but other themes don't. Could it be something in the theme itself?

**EDIT 2:** The `bureau` theme seems to display this as well.

**Comment by mcornella** [comment]
See #3582 
@apjanke can you guess what's going on here? I know the terminalapp plugin uses the `chpwd` hook still, can it be that?

**Comment by apjanke** [comment]
I can't reproduce this either, including with that custom theme. I'm on OS X 10.9, oh-my-zsh up to date (commit 77140a2).

Don't know what's going on here. The `terminalapp` plugin is [using `precmd` and not `chpwd`](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/terminalapp/terminalapp.plugin.zsh#L34-35) as far as I can tell. 

I can only guess that this is related to the OP's terminal configuration. Avit2 [uses `echotc` and terminal escape codes to move up and down a line](https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/avit.zsh-theme#L9). If the terminal was moving the cursor back to the beginning of the line as part of that due to some terminal control code issue, that could be consistent with overwriting the prompt: note that in OP's very first screenshot, the insertion point is sitting in column 1 on top of the "$" prompt.

Like you say, need more info, as @ncanceill lays out. Plus the value of the `$TERM` variable, and a screenshot of the whole terminal window so we can see what's going on with the right prompt.
