### ISSUE TITLE
Why is the git plugin slow for large repos?

### ISSUE THREAD

**Issue by landaire** [robbyrussell/oh-my-zsh#3009]
Referring to #1160, why is it that the plugin is so slow for large repositories? I noticed this today when getting oh-my-zsh set up in my vagrant environment which uses [git-prompt](https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh) and has no noticeable performance hit.

**Comment by apjanke** [comment]
Hmm. If someone's interested, it actually might not be that hard to implement a simple timeout for `git status` using zsh's "`coproc`" support. You could fire up the `git status` command using [coproc](http://zsh.sourceforge.net/Doc/Release/Shell-Grammar.html#Shell-Grammar), and then do a timeout-limited [`read -t <seconds> -p <coproc>`](http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html#Shell-Builtin-Commands) to get the results, and just kill the coproc if that read times out.

If I find some spare time this weekend, I might take a stab at it. I've run in to this enough times it would be nice to have a global fix. Would people be interested in having a timeout for `git status` checks used in prompts? The zsh prompt is fundamental enough it would be nice to have a hard timebox on it.

(/cc @slhck @mcornella @rombat since you've run in to this issue lately too)

**Comment by ee0pdt** [comment]
@landaire your tip has just saved my sanity!

> # Uncomment the following line if you want to disable marking untracked files
> # under VCS as dirty. This makes repository status check for large repositories
> # much, much faster.
> # DISABLE_UNTRACKED_FILES_DIRTY="true"

**Comment by MartinMuzatko** [comment]
Still lags in large repos with the option mentioned above enabled

**Comment by ee0pdt** [comment]
@MartinMuzatko I found that a completely fresh clone of the git repo can also help with large repos

**Comment by darol100** [comment]
In my case, I still have a lag of 2.5 seconds, but it used to be like 6 seconds.

**Comment by squatto** [comment]
For a temporary fix, you can also hide the git status for a project by running this in your project directory:

`git config --add oh-my-zsh.hide-status 1`

If you can't get into the directory to run the command, then directly edit `.git/config` and add:

```
[oh-my-zsh]
        hide-status = 1
```
