### ISSUE TITLE
default code style

### ISSUE THREAD

**Issue by voku** [robbyrussell/oh-my-zsh#3137]
Hi, today I was trying to clean the code-style from all this scripts. e.g. function-declaration "thisIsAFunction()", try to use local variables (nearly everything is global, except you are in a function and use the keyword local), no tabs (2 spaces), lowercase for local variables, ... I get the code-style from here -> https://google-styleguide.googlecode.com/svn/trunk/shell.xml

What do you think, would it make sense to add a code-style-guide? 

PS: here are my changes ... and yes I know we can't merge such big changes ;) it was only a idea: https://github.com/voku/oh-my-zsh/compare/robbyrussell:master...master

**Comment by voku** [comment]
"Coding style guide" updated, but I don't know if someone really read it. ;) Maybe you ( @mcornella ) can review it, thx?

**Comment by apjanke** [comment]
A couple items:
* The text of the coding guide suggests to use the `function` keyword in function definitions, but the example code doesn't actually use it.
* Text says to prefer `$()` to backticks, but uses backticks in a lot of the "good example" code
* It talks about using `::`-qualified packages, but I don't think that exists in ZSH; looks like a holdover from a C++ style guide?
* It's written in a pretty authoritative, normative style (e.g. "the following is required for new code", "strongly preferred", "is evil"). Should it be worded so strongly unless it has the blessing of robbyrussell or some core development team?
* The guide discusses "return values" when it seems to be referring to the output emitted on standard out, not the exit status in `$?`. I don't know if "return value" is the typical term for that; I think I've seen "function output" more.

**Comment by apjanke** [comment]
If we're going to discuss style, I'd be interested in working out whether and where double-quotes should be used around scalar parameters regularly. They're not required in ZSH since it doesn't do automatic word splitting upon parameter substitution like other shells. Unless some of its special options like `SH_WORD_SPLIT` or `ksh` emulation are set. but `emulate` could be a cleaner way of protecting against that and other unusual shell settings inside functions.
