### ISSUE TITLE
How do I know if oh-my-zsh is running?

### ISSUE THREAD

**Issue by HuckyDucky** [robbyrussell/oh-my-zsh#3233]
I am on a brand new MBP and upgraded to Yosemite before I did anything else. I have been using oh-my-zsh for a few years on my now crashed old MBP. Unfortunately, I am really struggling with getting it working on Yosemite.

I have tried installing with both curl and via the manual method. I have a .zshrc file.

My problem is that I can't tell if oh-my-zsh is running. The themes are not working for certain. I use "robbyrussell".

It seems like it used to print a big ascii image of "oh-my-zsh" before. Now I get nothing. I'm pretty sure it's not running.

When I try to run .oh-my-zsh/oh-my-zsh.sh by hand, I get:

    ./.oh-my-zsh/oh-my-zsh.sh: line 13: syntax error near unexpected token `('
    ./.oh-my-zsh/oh-my-zsh.sh: line 13: `for config_file ($ZSH/lib/*.zsh); do'

I'm not running in the bash shell though. `ps -f $$` yields:

➜  ~  ps -f $$
  UID   PID  PPID   C STIME   TTY           TIME CMD
  501  1851  1850   0  6:30PM ttys000    0:00.24 -zsh

**Comment by coolgeng** [comment]
I have the same issue in the same line. Is there any update for that? Thanks.

**Comment by coolgeng** [comment]
@mcornella I think you can go through your entries. I find the reason is I have the same entires in bash_profile and zshrc file. When I remove one, it works fine now. I hope it helps you.

**Comment by apjanke** [comment]
@mcornella I think you're in effect right; the script was running in bash or sh, even though the user was running zsh.

To execute oh-my-zsh by hand, you need to use a slightly different syntax. Use this `. ./.oh-my-zsh/oh-my-zsh.sh`, with the leading dot or `source`. This forces zsh to execute it as zsh commands inside the current shell.

(You mention that it seems to do nothing, and return you to the command prompt: that's the expected behavior. Since it's supposed to run on shell startup, it's silent unless something goes wrong (or you're using an odd plugin). The big ASCII-art image of "oh my zsh" is only printed by the installer when you set it up for the first time, or an upgrade happens.)

If you just type `oh-my-zsh.sh` or `./.oh-my-zsh/oh-my-zsh.sh`, that tries to run it as a separate executable. Normally, this would just error out.

    $ ./.oh-my-zsh/oh-my-zsh.sh
    zsh: permission denied: ./.oh-my-zsh/oh-my-zsh.sh

But if you've set the `u+x` execute bit on that file somehow, then the OS will attempt to run it as a separate program like a regular executable. There's no shebang line at the top of `oh-my-zsh.sh`. So... I think whatever's running it (in this case, I think the OS X kernel) will fall back to looking at the executable's file extension to decide what to run it in. And despite being a ZSH-specific script, the extension here is `.sh`, so it gets run in plain old shell.

I can reproduce the behavior by doing a `chmod u+x` on it.
```
janke@eilonwy:~ $ chmod u+x ./.oh-my-zsh/oh-my-zsh.sh
janke@eilonwy:~ $ ./.oh-my-zsh/oh-my-zsh.sh
./.oh-my-zsh/oh-my-zsh.sh: line 26: syntax error near unexpected token `('
./.oh-my-zsh/oh-my-zsh.sh: line 26: `for config_file ($ZSH/lib/*.zsh); do'
```

Now, it *says* "zsh" in the output, but that's a red herring, because the upgrade line is explicitly invoking zsh in a subshell. If I edit `oh-my-zsh.sh` to add some diagnostics (`echo ps pid=$PID; ps; pstree -p $PPID; echo my vars; set`), it's clear that it's actually `sh` that's running it. (Which in this case is `bash` in `sh` emulation mode.) (`pstree` is from a `brew install pstree`; it's not in base OS X.)

```
   \-+= 00296 janke /Applications/iTerm.app/Contents/MacOS/iTerm
     \-+= 05433 root login -fp janke
       \-+= 05434 janke -zsh
         \-+= 05730 janke sh ./.oh-my-zsh/oh-my-zsh.sh
           \-+- 05734 janke pstree -p 5434
```

So, I'm guessing what's going on is: oh-my-zsh was loading fine all along, you just had some minor issues with themes, and maybe got tripped up by a subtle script invocation issue while trying to debug it.

If you can describe in more detail what oh-my-zsh features aren't working for you when you think it's running, we can probably fix those up.

**Comment by mcornella** [comment]
@coolgeng sorry for totally missing your comment. Can you extend on how you solved it? I want to understand the relation between your `.bash_profile` and `.zshrc` files.

**Comment by apjanke** [comment]
Backing up a bit to answer the original question: oh-my-zsh initialization sets the variables `$ZSH_CUSTOM`, `$ZSH_CACHE_DIR`, `$ZSH_COMPDUMP`, and `$SHORT_HOST`. If you do `set | grep -a ZSH\|SHORT_HOST`and see them present, then oh-my-zsh has probably been loaded in your current `zsh` process.

**Comment by mcornella** [comment]
Yeah. Agree with your diagnosis that @HuckyDucky was _running_ the init script instead of _sourcing_ it. This issue can be closed, but I'm still waiting on @coolgeng's response.

**Comment by apjanke** [comment]
Cool.

What do you think about adding a `#!/bin/zsh` shebang line to the top of `oh-my-zsh.sh` to identify it as a zsh-specific script? And maybe have it explicitly check that `$ZSH` is set? That could catch this and related error cases, and produce more useful error messages.
