### ISSUE TITLE
Many of the theme's screenshots not showing

### ISSUE THREAD

**Issue by protechig** [robbyrussell/oh-my-zsh#3327]
Hello,

The screenshots for many of the themes aren't showing, as i'm sure you well know. As I look for new color schemes to spice up my terminal, I notice this every time. Is there any way we can get them back? Is there any way I can help with this?

Cheers!

**Comment by apjanke** [comment]
Here's a list of the broken theme screenshot image links as of today. (2/18/2015)

* fishy  -  http://ompldr.org/vOHN0Ng
* funky  -  http://img.skitch.com/20091228-rgwwappxjmt49dx6ngwuk1xsqd.jpg
* geoffgarside  - http://img.skitch.com/20091228-k27xd6iqn99qe4h5c6fm4i1yws.jpg
* maran  - http://img.skitch.com/20091228-e49wy5f8961gstbiagqre279e1.jpg
* rachel - http://img.skitch.com/20110114-bga7p8qihdu481mmfagsb1as6q.png
* risto - http://img.skitch.com/20091228-n2w6w1cdxyc87e227dgdkymr15.jpg
* sunaku  - http://ompldr.org/vOHcwZg
* theunraveler  - http://dl.dropbox.com/u/5232448/zsh.png
* wezm  - http://img.skitch.com/20091228-nsk66d4jks2tsn1n766i4f84gh.jpg
* xiong-chiamiov  - http://img.skitch.com/20091228-axm1b99qpxdyey6pu4h28tj27.jpg
* xiong-chiamiov-plus  - http://img.skitch.com/20091228-jt31is2wx2tamh1a9cwwk8r4p.jpg

If we want to go with custom screenshots (which I think is the best idea too), I can look up the original authors for each of the themes, ping them for screenshots, and cobble together new screenshots for the ones that don't respond.

**Comment by apjanke** [comment]
The intro paragraph to https://github.com/robbyrussell/oh-my-zsh/wiki/Themes now has a description of how to set `ZSH_THEME` in `~/.zshrc`, so the "To use: Set `ZSH_THEME` in `~/.zshrc` to `<foo>`" under each entry is redundant. Is it cool if I go through and remove them like you suggested, leaving only the special per-theme instructions under each theme? And maybe add a note about the `themes` plugin's `theme`/`lstheme` in the intro section?

**Comment by mcornella** [comment]
Thank you Andrew. Yeah, I'd get rid of those redundant statements. I downloaded screenshots from 3 separate sources. When I can, I'll post those you report to be missing.

An example section would be good as well, detailing how a standard new theme entry should look like:
- theme name (in the correct order)
- custom screenshot of AxB size (something that makes sense and is similar to current screenshots sizes)
- custom instructions if needed
- color scheme used in the screenshot would be nice, too

**Comment by apjanke** [comment]
I removed the redundant per-theme "set *ZSH_THEME* to ..." statements. I'll cobble together an example section when I have some time.

**Comment by mcornella** [comment]
Thanks!

**Comment by mcornella** [comment]
- [x] fishy
![fishy](https://cloud.githubusercontent.com/assets/1441704/6315377/3ee891ce-ba00-11e4-92cc-885bc3c96c6e.png)
- [x] funky
![funky](https://cloud.githubusercontent.com/assets/1441704/6315381/55ccfdb2-ba00-11e4-9fd1-86623b5bba17.png)
- [x] geoffgarside
![geoffgarside](https://cloud.githubusercontent.com/assets/1441704/6315385/701d32e0-ba00-11e4-8c31-ab30a0fd6324.png)
- [x] maran
![maran](https://cloud.githubusercontent.com/assets/1441704/6315389/7df9c496-ba00-11e4-8386-027d324255c4.png)
- [x] rachel  
  not a theme (at least now)
- [x] risto
![risto](https://cloud.githubusercontent.com/assets/1441704/6315405/18aa274c-ba01-11e4-8bb7-0ba9ca166974.png)
- [ ] sunaku

- [ ] theunraveler

- [ ] wezm

- [ ] xiong-chiamiov

- [x] xiong-chiamiov-plus

**Comment by mcornella** [comment]
Done!

**Comment by apjanke** [comment]
And I put together a [format description section](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes#theme-description-format) like you suggested. 

Hosting the screenshots on the GitHub Wiki itself sounds like a good idea, so we don't get broken links again if someone's dropbox or imgur account disappears. Any concerns with just grabbing copies of all the current screenshots and copying them to the wiki? If not, I can start grinding through them or figure out a script to do so. (That may also fix some browser warnings about mixing insecure HTTP content into an HTTPS page for people with finicky browser settings.)

**Comment by mcornella** [comment]
I want to do that in the near future, I already downloaded them.

**Comment by apjanke** [comment]
Cool. If you want me to do the grunt work of uploading them to the wiki, send me a link to the archive. I'm probably going to be snowed in for the evening with not much to do.

**Comment by mcornella** [comment]
Ok thanks for offering, here's the archive: https://dl.dropboxusercontent.com/u/16509376/oh-my-zsh%20themes.7z. Sorry for the delay

**Comment by apjanke** [comment]
Okay, they're all updated to local images hosted on GitHub issues now.

I grabbed copies of the remaining screenshots that weren't in that archive. Here's an updated version of the archive if you're interested. https://www.dropbox.com/s/5uf3n2iczs3sgk1/oh-my-zsh%20themes.zip?dl=0

For reference, we might want to stash that file somewhere on GitHub associated with this repo instead of our Dropbox accounts. (The link on mine won't stay good for long.) The wiki is backed by its own Git repo that you can store arbitrary files in, which seems like an appropriate spot, but doing so requires write permissions to the parent repo, so only Robby could do that.

I made #3619 as a dummy placeholder issue for hosting the image files, so people can upload them there without spamming anyone with notifications.

I also changed the page so all the screenshot images are hyperlinks to themselves, so it's easy to view them at full size by opening them in a new browser tab. (For some reason, Firefox doesn't display a "view image in new window" in the context menu for unlinked images for me. This way will make it easy for people using any browser to do so, and help make it apparent that it's useful to do so.) 

I added some notes about how to upload github issue-hosted images and create the self-linked images to the page.

**Comment by mcornella** [comment]
Thanks @apjanke. Good thinking about using a separate issue to host images, and adding hyperlinks. This has been all taken care of. Now only remains having standard screenshot sizes and styles, but that's just suuuper low-priority.
This can be closed!

**Comment by apjanke** [comment]
This is all fixed now. Could you close the issue, @protechig?

**Comment by protechig** [comment]
Yup, sweet. Great job fixing this everyone :)
