### ISSUE TITLE
complete:13: command not found: compdef

### ISSUE THREAD

**Issue by jprice** [robbyrussell/oh-my-zsh#3356]
I am getting 2 instances of this error when I launch a new terminal window

```
complete:13: command not found: compdef
complete:13: command not found: compdef
complete:13: command not found: compdef
complete:13: command not found: compdef
jprice@xxx:pts/3-> /home » jprice  (0) 
```

I found this: #2315 and I have commented out line 25 in the check_for_upgrades.sh. 

I have also backed up all my dotfiles and removed them, and used a clean install of oh-my-zsh and I still seem to get it.

I'm lost as to what else to do? Any suggestions?

**Comment by mcornella** [comment]
Any updates?

**Comment by jcrben** [comment]
I had this issue for a frustrating hour or so today. There are a lot of old issues and varied suggestions which came up in Google, but the only thing that worked for me was [this](https://github.com/robbyrussell/oh-my-zsh/issues/630#issuecomment-70291622) from #630  

    #This will perform chmod g-w for each file returned by compaudit to remove write access for group
    compaudit | xargs -I % chmod g-w "%"
    #This will perform chown to current user (Windows and Linux) for each file returned by compaudit
    compaudit | xargs -I % chown $USER "%"
    #Remove all dump files (which normally speed up initialization)
    rm ~/.zcompdump*
    #Regenerate completions file
    compinit

**Comment by apjanke** [comment]
Looks like the `rm ~/.zcompdump*` which mcornella suggested. (With a typo fix.)

Next time this happens to someone, could they grab your `~/.zcompdump*` files and post the as gists or a tarball for analysis?

Here's a lead: This looks like an interaction between ZSH's bashcompinit support for bash style completions, and the order in which we load stuff up. Have a look at the `bashcompinit` function in ZSH (ZSH itself, not oh-my-zsh; on my system it's at `/usr/share/zsh/5.0.2/functions/bashcompinit`). It defines the function `complete()`, which AFAIK is not otherwise defined in `zsh`. And on line 13 of complete's function body, it calls `compdef ...`. But it doesn't itself define compdef. So if you load up bashcompinit and call complete without loading up the rest of the zsh completion system, you get that exact `complete:13: command not found: compdef` error message.

Here's me reproducing it in a session with an empty .zshrc.

```
eilonwy% autoload -U +X bashcompinit; bashcompinit
eilonwy% complete foo
complete:13: command not found: compdef
eilonwy%
```

If this is the case, we have to figure out where in the initialization sequence `bashcompinit` and `complete` are getting called. In the oh-my-zsh source tree, the only reference I see is in the `compleat` plugin.

Folks having this problem, do you have any bash completion stuff in your initialization files?

**Comment by jcrben** [comment]
I'll try to get around to posting those details later - but I did delete ~/.zcompdump before a few times before doing the commands above and it wasn't working. I also changed all the permissions on these files and the ownership from root (which it was initialized at) manually before running the above commands but I'm not sure if that did anything. With that said, I may have accidentally deleted only one of the two at a time...

**Comment by apjanke** [comment]
I've put together a script that makes grabbing this debugging info easier: https://github.com/apjanke/oh-my-zsh-custom/blob/master/diagnostics.zsh

Download that, source it, and post the `omz_diagnostic_dump -v` output as a gist, and we should have a pretty detailed picture of what's going on in your setup. It'll grab your current ZSH state, OMZ install state, and all the zsh & omz config file contents.

```
curl https://raw.githubusercontent.com/apjanke/oh-my-zsh-custom/master/diagnostics.zsh > diagnostics.zsh
source diagnostics.zsh
omz_diagnostic_dump -v
```

**Comment by jcrben** [comment]
The gist is here: https://gist.github.com/jcrben/89591fbbd8794714f906

I do not have a .profile file on this Macbook Pro other than the Yosemite default /etc/profile. My .bash_profile has some stuff in it, it doesn't seem like that should matter as my understanding is that zsh ignores it.

Your analysis is intriguing although if that is the case it seems like even more people would be running into this problem. Or maybe it only affects people like me who are coming in completely fresh to zsh and haven't initialized it before or something? I didn't have really anything before running the oh-my-zsh install script. I should also note that the error posted five times in a row every time I would open up a new shell. 

I'm not actually using zsh right now (and probably won't for the next couple weeks), but I plan to return to it soon.

**Comment by apjanke** [comment]
Thanks!

I don't see anything in your setup that would cause it or is otherwise problematic. And yeah, ZSH should ignore the bash stuff unless your startup files are explicitly sourcing them.

Hmmmmmmmmm. Maybe it does affect only fresh users. Maybe it only happens during the oh-my-zsh installation process, and not ongoing use.

Consider the last few lines of `tools/install.sh`.

   echo "\n\n \033[0;32mp.p.s. Get stickers and t-shirts at http://shop.planetargon.com.\033[0m"
   env zsh
   . ~/.zshrc

(These contain a bug IMHO.) The way install currently works (using the instructions in the README), `install.sh` is run under `sh`. Which for some people is `bash` or something else. The `env zsh` line runs zsh. But a) it doesn't supply `-l` so (I think) it's not a login shell, and it's inheriting some stuff from the parent non-zsh shell, so it'll be somewhat different from usual zsh runs, and b) it's not run using `exec` so eventually it returns and `install.sh` continues.

Then that last line, `. ~/.zshrc`, is run, but it's run by `sh` and not `zsh. Which means oh-my-zsh and all its setup stuff is being loaded in to that other shell.

Maybe one of those conditions is causing the completion stuff to be confused when it makes the very first `zcompdump` file upon installation of ZSH? And it only happens on installation, and only under some system-dependent circumstances, which is why we don't see it that often.

**Comment by apjanke** [comment]
Wait, I'm wrong about that: the `. ~/.zshrc` *is* run by `zsh`, in the case where this is run inside a `curl .../install.sh | sh`, because `zsh` inherits the parent shell's stdin, which is connected to the script instead of the terminal in that case. But perhaps the combination of being a non-login shell and running from inside `sh` (which may be `bash`) is affecting something.

**Comment by jcrben** [comment]
Out of curiosity, is it run by zsh due to:

    if [ "$SHELL" != "$(which zsh)" ]; then
        echo "\033[0;34mTime to change your default shell to zsh!\033[0m"
        chsh -s `which zsh`
    fi

**Comment by apjanke** [comment]
No, `chsh` will change your default shell stored in `/etc/passwd` (or wherever) so that future login sessions (like a new terminal window, console login, or `ssh` session) will use `zsh` by default, but it doesn't affect the current session.

**Comment by duffqiu** [comment]
maybe this a workrong solution for it:

check where is you library and funtions for zsh 

and then add them in .zshrc and  .oh-my-zsh/tools/check_for_upgrade.sh

here is my example 

```
module_path=(/opt/zsh/lib64/zsh/5.0.2/)
fpath=(/opt/zsh/share/zsh/5.0.2/functions/ /opt/zsh/share/zsh/site-functions/ $fpath)
```

**Comment by denysdovhan** [comment]
![image](https://cloud.githubusercontent.com/assets/3459374/14763672/e4a70bbe-09a4-11e6-8c76-63e0dcb7037b.png)

Today this message was shown. Can anybody help me? I'm on OS X, zsh 5.0.8 (x86_64-apple-darwin15.0).

**Comment by tofagerl** [comment]
Just a little note to myself and others who run into this error while using zgen and loading OMZ moduled: 
What you, and I, did wrong was not loading oh-my-zsh itself before its modules, as described in the readme of zgen: 
https://github.com/tarjoilija/zgen#load-oh-my-zsh-base

**Comment by scotttesler** [comment]
@denysdovhan Can you elaborate on what you did to fix it?

**Comment by denysdovhan** [comment]
I did [this](https://github.com/denysdovhan/dotfiles/commit/e13cbda0ff05e32b0ab81c82040fb12cac92f9eb) and the problem has gone. As I understood, that was caused by conflict between nvm bash completions and nvm plugin for oh-my-zsh.

It it will help you, please, let me know.

**Comment by barberj** [comment]
I'm also getting the issue. I've tried removing `~/.zcomdump*`, but they just generated again with every session.

Here is my latest file.

[~/.zcompdump-5.2](https://github.com/asdf-vm/asdf/files/657164/zcompdump-glitch-5.2.txt)

**Comment by collegeimprovements** [comment]
Same as @barberj here.

**Comment by mcornella** [comment]
It's not `zcomdump`, it's `zcompdump`.

**Comment by barberj** [comment]
sorry. typo.

**Comment by mcornella** [comment]
I'm closing this thread because new messages are always solved with the already mentioned solutions. If you're having this problem: 

Try the 1st solution (from https://github.com/robbyrussell/oh-my-zsh/issues/3356#issuecomment-64946583):
1. Run `rm ~/.zcompdump*` to recreate the completion cache (copy-and-paste or you might miss a letter).
2. Run `exec zsh` to reload the zsh session.

If that doesn't get rid of the errors, try this 2nd solution (adapted from https://github.com/robbyrussell/oh-my-zsh/issues/3356#issuecomment-94344463):
```zsh
compaudit | xargs -I '%' chmod g-w '%'
compaudit | xargs -I '%' chown $USER:$USER '%'
rm ~/.zcompdump*
exec zsh
```

**NOTE: if you are running zsh both as a regular user and as root the solutions above probably won't work. Open a new issue with steps followed, zsh version and other relevant details.**

If nothing here solved your problem, open up a new issue and post what steps did you follow to solve it, as well as the zsh version you have (run `zsh --version`).

Thanks for your understanding.
