### ISSUE TITLE
OSX: move files to the proper Trash

### ISSUE THREAD

**Issue by mzgol** [robbyrussell/oh-my-zsh#3421]
The command:
```sh
trash /Volumes/something/abc
```
moves the file/directory to `~/.Trash` on OS X, i.e. moves it to a different drive. It should just move the file/directory to the trash proper for the volume the file is on.

Tested on OS X Yosemite with oh-my-zsh from commit 1978a0923c864cacdc520adff83ed63f62c91073 (current `master`).

Note that Apple provides an API to move files to a proper trash via AppleScript; modules like https://www.npmjs.com/package/trash do it correctly because of that.

Originally erroneously reported at https://github.com/sindresorhus/trash/issues/17.

**Comment by mzgol** [comment]
@mcornella What do you mean by "instead"? Are bug reports unwelcome here?

**Comment by mcornella** [comment]
Yeah sorry, I understood you said there was a system trash command, so using that was the solution. That's why I said to submit a PR, because you recommended a solution. 

I see how my comment could be seen as aggressive or careless because of its brevity, though. Really I was just replying a bunch of issues in a rush, and so it came off that way. 

The solution we agreed upon was just plainly removing the trash command and using homebrew trash, see #3445.

**Comment by mzgol** [comment]
Thanks! :)
