### ISSUE TITLE
New commands don't completing

### ISSUE THREAD

**Issue by mhalano** [robbyrussell/oh-my-zsh#3440]
Zsh is unable to complete new commands. Example: If I install (or purge) a package, I need to reload the shell (hit enter, ctrl-c, etc.).

**Comment by apjanke** [comment]
@mhalano Do you have a link to the Pull Request you made?

**Comment by mhalano** [comment]
https://github.com/robbyrussell/oh-my-zsh/pull/3456

2015-04-01 0:25 GMT-03:00 Andrew Janke <notifications@github.com>:

> @mhalano <https://github.com/mhalano> Do you have a link to the Pull
> Request you made?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robbyrussell/oh-my-zsh/issues/3440#issuecomment-88335738>
> .
>



-- 
Marcos Alano
----------------------------------------------
P: Por que este email é tão curto?
R: http://five.sentenc.es
----------------------------------------------

**Comment by MightyCreak** [comment]
Tested the PR on my machine (Fedora 22), it works as expected! Please pull this request in master.

**Comment by Lyuuuu** [comment]
after i install o-m-z,
zsh:command not found:npm(or node)

**Comment by mcornella** [comment]
@MightyCreak we decided not to merge it because it could be a significant performance hit on systems with network drives in `$PATH`, and a setting wouldn't be a good solution since it's a oneline change and it can be added to zshrc as easily.

@Lyuuuu that seems to be a separate issue. If you just installed `node` or `npm`, just run `rehash` to refresh the commands from `$PATH`. If that's not the case or the solution doesn't work, you might have to change the `$PATH` in the zshrc file (`$HOME/.zshrc`). If it worked before have a look at PATH modifications in the rc file for your last shell; this will most commonly be `$HOME/.bashrc` or `$HOME/.bash_profile`.
