### ISSUE TITLE
Users are instructed to run a script downloaded via HTTP

### ISSUE THREAD

**Issue by gtklocker** [robbyrussell/oh-my-zsh#3459]
On ohmyz.sh and the project's README file, users are instructed to run commands such as

``curl -L http://install.ohmyz.sh | sh`` and
``wget --no-check-certificate http://install.ohmyz.sh -O - | sh``

While this may be practical, it's totally unsafe and dangerous. The script is susceptible to multiple kinds of man-in-the-middle attacks. This problem could be solved by one of the following methods:

* Using HTTPS on ohmyz.sh.
* Using the direct link to the file in question (https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh) and getting rid of the install.ohmyz.sh link.
* Having some kind of checksum check in place.

**Comment by Bengt** [comment]
Using a self-signed certificate on ohmyz.sh would work for the wget command as the certificate checking is supressed, but most web browsers would prompt the user with a warning. So to avoid this, one has to either use a certificate signed by an accepted signing authority or separate the website from the installer. For example by using a subdomain `secure.ohmyz.sh`.

The direct link is very long and does not look good in a `README.md` instead one could use a shortened url, for example this: <http://goo.gl/4CHFnu> Google however tracks and analyses all link resolutions and any url shortener can do so. http://git.io/ only works for urls starting with github.com, so there is no obvious solution to this.

A checksum does not help against MITM attacks since it can be manipulated to match a manipulated installer script. Using a checksum to assert the integrity of the downloaded file would be advisable, but solves another problem.

**Comment by dionyziz** [comment]
I recommend that:

1. My #3461 patch with checksums served over HTTPS is merged. These checksums can be used for both integrity and security and are not susceptible to MitM attacks.
2. A free but not self-signed HTTPS certificate for the ohmyz.sh domain is obtained. Self-signed certificates are useless against MitM attacks.

**Comment by robbyrussell** [comment]
If we acquired a paid HTTPS certificate, would that help this out? (I want to keep the install process as simple as possible...)

**Comment by mcornella** [comment]
I was thinking of using `gh-pages` to host the website, and the install script as well. That way we may be able to use the Github certificate with the custom domain Github provides.

I'm not sure how the final URL will look like though, because I think we won't be able to alias the current ohmyz.sh domain to the *.github.io domain *and* have a green-lighted certificate. I could set up a test in my fork to see how the final result will look like.

@robbyrussell if you want, we can discuss implementation details via email. Thanks for the latest round of merged PRs! :smile: 

----
Regarding the checksum suggestion, and correct me if I'm wrong, it doesn't apply very well with an automated install. The process is always: download some file, run checksum on file, compare with value written somewhere. If we automated this, it would still be subject to tampering. Only solution is **https**.

Now, I want to have this as bad as the next guy, but I want to remind you that it's still possible for those that have big security concerns to use `git clone` instead of the install script.

Finally, to those few that got so worked up about this issue, just lending a hand to pull out weeds will do much more than getting angry over how "little" work gets done on a free project that has just a handful of long-term contributors. Nobody is preventing anyone from triaging issues or cleaning and tidying pull requests.

Sadly, this is the never-ending story of OSS. This is not the place for hate-fests and neither is any other open source project. I don't understand why this seems acceptable behavior. A suggestion I have is that you can write your thoughts out without worry, but don't press send once you're finished. An understanding, emphatic response is always better. We're all busy people.

That is all.

BTW, I never explicitly informed Robby of this demand, as well as many others that I have missed because of limited time and lack of foresight. Help is always appreciated.
