### ISSUE TITLE
Error with Github plugin

### ISSUE THREAD

**Issue by mswanson** [robbyrussell/oh-my-zsh#3488]
I am trying to use the github plugin but I am seeing the following error when opening a new iTerm2 window:

```
zsh:12: command not found: ___main
_default:compcall:12: can only be called from completion function
```

I have isolated it to the github plugin but I am not familiar enough with zsh autocompletions to really understand how to fix it.  Please help.

Thanks

**Comment by mcornella** [comment]
They talked about **disabling `gitfast` plugin** over at #1727. Also, in #2394 disabling the `complete_aliases` option with **`unsetopt complete_aliases`** solved it. Both might be due to the same thing. 
That said, @felipec [pushed a fix to git's official completion](https://github.com/robbyrussell/oh-my-zsh/issues/2394#issuecomment-45287624) that solved the issue, maybe it was already pulled into the official git project. What do you know about that, @felipec?

@mswanson try both solutions to see if they work. If they do, perhaps you could try updating git (post which version you're using with `git --version`).

**Comment by mcornella** [comment]
Any updates @mswanson?

**Comment by mswanson** [comment]
Sorry I am just now responding... none of the proposed solutions seems to work for me. I am using homebrew versions of hub v2.2.0 and git v2.3.0. I have tried:

- removing gitfast and adding github
- adding `unsetopt complete_aliases` to .zshrc
- adding 'alias __git-checkout_main=_git_checkout' to .zshrc
- `brew uninstall --force git && brew install git --without-completions`

All with no change. Below is my list of plugins

`plugins=(brew brew-cask common-aliases rsync z git github gitfast git-extras bower cake coffee jsontools node npm nvm composer bundler capistrano gem heroku rails rake rake-fast ruby rvm sublime redis-cli)`
