### ISSUE TITLE
Cd command report 

### ISSUE THREAD

**Issue by leoheck** [robbyrussell/oh-my-zsh#3491]
```bash
➜  ~  cd lala
cd:cd:13: no such file or directory: lala
➜  ~  cat lala
cat: lala: No such file or directory
```
cd command present an annoying double ```cd:cd:``` message info

**Comment by mcornella** [comment]
This is because oh-my-zsh defines a custom cd function to add functionality. You can get rid of it with the command `unfunction cd` (you can put it at the end of your zshrc file). 
There's also #2422 which gets rid of it as well as refactors the whole lib directory, you can check it out (with `hub checkout https://github.com/robbyrussell/oh-my-zsh/pull/2422` if you have [`hub`](https://github.com/github/hub) installed) and +1 it to show your support.
