### ISSUE TITLE
Tailoring 'less'

### ISSUE THREAD

**Issue by pickfire** [robbyrussell/oh-my-zsh#3527]
I think adding `export LESSOPEN='|/usr/bin/lesspipe.sh %s 2>$-'` to [misc.sh] is a good idea as it will use lesspipe if exists.

*lesspipe.sh* is a wrapper around less for more functions such syntax highlighting showing directories, etc.

Take a look at the [sample bashrc](http://tldp.org/LDP/abs/html/sample-bashrc.html) taken from.

**Comment by ncanceill** [comment]
The fix is not as simple as that. There are many different `$LESSOPEN` pipes available, not counting the ones people write for themselves, and many repertories where they could be located. Moreover, users might want to chain several `$LESSOPEN` pipes together.

I believe it is better to let users define their `$LESSOPEN` pipechain in their `.zshrc`, maybe we could add a commented hint in the [template](https://github.com/robbyrussell/oh-my-zsh/blob/master/templates/zshrc.zsh-template)?

**Comment by pickfire** [comment]
I hope you can add it in the [template](https://github.com/robbyrussell/oh-my-zsh/blob/master/templates/zshrc.zsh-template). Thanks.
