### ISSUE TITLE
vi-mode does not update prompt correctly when window resized

### ISSUE THREAD

**Issue by martong** [robbyrussell/oh-my-zsh#3537]
When a window is resized, the prompt is not updated correctly:
$KEYMAP has an empty value.

To fix it we need this in vi-mode plugin:
```
TRAPWINCH() {
  [[ -o zle ]] && zle reset-prompt; zle -R
}
```

**Comment by mcornella** [comment]
Hi @martong, can you link some references and post a pull request?

**Comment by martong** [comment]
Okay, so here is how to reproduce the issue:
1) Have a multiline `PROMPT` , the second line containes `$(vi_mode_prompt_info)`
2) Change into vicmd mode ( vi_mode_prompt_info draws some red `<<<`)
3) Then resize the window. The result is that the red `<<<` is disappeared.

PR is on the way ...

**Comment by martong** [comment]
@mcornella Before the PR, could you check whether you have this issue as well?

**Comment by mcornella** [comment]
Sure, I'll check it tonight. I'll let you know what I find.

**Comment by mcornella** [comment]
I can confirm that this behavior occurs even on a single line prompt, having `$(vi_mode_prompt_info)` in `RPS1` prompt variable.
Your solution works. The check of `zle` option is since it's always enabled by default in interactive sessions, so the code would look like this:
```sh
TRAPWINCH() {
  zle reset-prompt
  zle -R
}
```
Thanks for your contribution, let's get the PR ready and see if more people can confirm this works and doesn't introduce any bugs.
Cheers!

**Comment by martong** [comment]
I am using iTerm2 and during resizing the window I get the following error messages:
TRAPWINCH:zle:1: widgets can only be called when ZLE is active
TRAPWINCH:zle:1: widgets can only be called when ZLE is active

Probably zle is not always active?

**Comment by martong** [comment]
Here is the PR:
https://github.com/robbyrussell/oh-my-zsh/pull/3547

**Comment by 97-109-107** [comment]
I got ``TRAPWINCH:zle:2: widgets can only be called when ZLE is active`` whin on commit``5ee5403``

Upon removing 
````
TRAPWINCH() {
  if [[ -o zle ]]; then
    zle reset-prompt
    zle -R
  fi
}
````

I stopped getting the error; my prompt consists of:
````
PROMPT='%{$fg_no_bold[white]%}%n%{$fg_no_bold[white]%} %{$fg_no_bold[red]%}%3~$(git_prompt_info)%{$reset_color%} '

# git theming
ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[black]%}[%{$fg_no_bold[yellow]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX=""
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg_bold[black]%}]"
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg_bold[yellow]%}⚡%{$fg_bold[black]%}]"
...
````

**Comment by martong** [comment]
The condition in the line `if [[ -o zle ]]; then` is supposed to filter out calling zle widgets when zle is not active.
Could you please check with an other way if your zle is active or not when TRAPWINCH is called?
E.g. could you try this one ?
```
TRAPWINCH() {
  [[ -o zle ]] && zle reset-prompt; zle -R
}
```

**Comment by 97-109-107** [comment]
@martong: I replaced ``TRAPWINCH()`` as you suggested. As a result, I still get:
``TRAPWINCH:zle:1: widgets can only be called when ZLE is active`` upon opening a terminal.

I'm not knowledgeable about zle, or zsh at all, so I can't carry out more unguided investigations. 

**temporary workaround**
Should anybody face a similiar (exotic?) issue, it can be temporarily fixed by copying ``vi-mode.plugin.zsh`` to ``~/.oh-my-zsh/custom/plugins/vi-mode-custom/vi-mode-custom.plugin.zsh`` and replacing ``vi-mode`` with ``vi-mode-custom`` in the plugin part of ``.zshrc``.

**Comment by mcornella** [comment]
@97-109-107 your temporary workaround can be improved further: if you use the same name as a custom plugin, oh-my-zsh will load only the custom plugin, so there's no need to call it `vi-mode-custom`.

@martong the above suggestion should be 
```
TRAPWINCH() {
  [[ -o zle ]] && zle reset-prompt && zle -R
}
```
otherwise `zle -R` will be called always. That said, I don't think that's the issue since that's the same code written differently. A temporary workaround will be adding `&>/dev/null` to zle calls to silence the output, but we need to come with an explanation of why this is happening.

**Comment by mcornella** [comment]
Maybe prefixing the call with `zle &&` like they do in http://www.zsh.org/mla/users/2007/msg00449.html
Try both these versions please: answer (1) does it still work on resize?, and (2) does it spit out the error?

- Just silenced output:
```
TRAPWINCH() {
  if [[ -o zle ]]; then
    zle reset-prompt &>/dev/null
    zle -R &>/dev/null
  fi
}
```
- Prefixed with `zle &&`:
```
TRAPWINCH() {
  [[ -o zle ]] && zle && zle reset-prompt && zle -R
}
```

**Comment by mcornella** [comment]
Hey people, let's continue the conversation in #3605
