### ISSUE TITLE
Consider spring cleanup of non-essentials from lib/

### ISSUE THREAD

**Issue by N4M3Z** [robbyrussell/oh-my-zsh#3614]
Currently, there is a large number of non-essential scripts in the default lib/ directory (e.g. bzr.zsh). While I understand that most of these only define functions, I see simply no reason to load them. Please consider making these into plugins and keep lib/ folder clutter-free.

At this point, it is necessary to keep an empty file of the same name in custom/ for each script provided  in lib/ so they are not loaded automatically. I am running oh-my-zsh on multiple machines and some do not support to full feature set used (e.g. url-quote-magic) making this use case quite inconvenient.

**Comment by alienth** [comment]
+1. Not being able to ignore these libs without hacks feels ugly.

For my own setup, I moved non-essentials libs to plugins and it works quite nicely. If I want the functionality from those libs, I can just load them as plugins: https://github.com/alienth/oh-my-zsh/commit/879bc57788d292aad4336de73c5ed3e665ee4be2

**Comment by N4M3Z** [comment]
Due to lack of interest, I actually moved to zgen (https://github.com/tarjoilija/zgen/blob/master/zgen.zsh) plugin manager and currently only use oh-my-zsh as a source of plugins.

**Comment by ncanceill** [comment]
Hi, and thanks for contributing.

***

Concerning `url-quote-magic` and other potential support issues, we can either add a setting or consider doing an automated check at init time.

***

Concerning _"non-essential scripts"_, you mention `bzr.zsh` and maybe also mean `nvm.zsh` and `prompt_info_functions.zsh`. These define functions to be used in themes, in order to provide various features, usually enhancing the custom prompt.

Granted, `bzr_prompt_info` is only used by the [frisk theme](https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/frisk.zsh-theme), so it is arguable that it should be moved from `lib/` into it.

However, most functions like that in `lib/` are actually shared by several plugins or themes, and moving them over there would require duplicating them.

**Comment by N4M3Z** [comment]
On compatibility: Yes, that would be a good solution to the problem.

On non-essential scripts: My objection to the oh-my-zsh approach is that unless I am using a given theme, some files from the lib folder are sourced for no reason. In my opinion, it should be the theme which sources the required libraries by itself. But I guess changing the behaviour would require a larger consensus.

In any case, I am currently using isolated from the oh-my-zsh loading system completely and using only the plugins I find useful.
