### ISSUE TITLE
The nuptial problem about "silversearcher - ag". 

### ISSUE THREAD

**Issue by jachinpy** [robbyrussell/oh-my-zsh#3633]
One small problem, in the ".oh-my-zsh/plugin/ubuntu" alias system,  use ubuntu "ag" command and search tool name repetition problems "silversearcher-ag".

**Comment by apjanke** [comment]
I'm having a hard time understanding this, but it sounds like the problem is that the Silver Searcher program defines the command `ag`, and the Ubuntu plugin redefines `ag` with `alias ag='sudo apt-get' `, which clobbers the Silver Searcher's `ag` command. So when you run `ag`, you intend to call silversearcher, but end up running apt-get.

As a workaround, you can add `unalias ag` in your `~/.zshrc` file, after loading oh-my-zsh. This will remove the ubuntu plugin's alias and make the Silver Searcher `ag` command visible again.

Caused by #3601, which added the ubuntu plugin. @nextgenthemes, what do you think about the issue of `alias ag` masking the Silver Searcher command?

**Comment by nextgenthemes** [comment]
I do not know how things are handled here on oh-my-zsh, this was my first contribution. I do not know Silver Searcher and I do not know how many users will want to use it and the ubuntu plugin at the same time. I would say its not to much to ask to add `unalias ag` if your running into this issue.

Feel free to make a pull request to my plugins readme that warns people about this. Or add some check if silverseacher is active and if so use another alias or something but I would like to keep that alias the way it is. But its not up to me.

**Comment by oryband** [comment]
duplicate or origin of #3866

**Comment by akaihola** [comment]
`unalias ag` solves this only partially. Command line completion is still broken. If I type `ag <tab>`, I get this:
```bash
$ ag (eval):1: command not found: _ag
(eval):1: command not found: _ag
(eval):1: command not found: _ag
```
