### ISSUE TITLE
Can have a special man page for alias of git plugins?

### ISSUE THREAD

**Issue by FinalDes** [robbyrussell/oh-my-zsh#3634]

**Comment by apjanke** [comment]
@Stibbons, @ncanceill – you're listed as the `git` plugin maintainers. What do you think of this?

**Comment by KenanAlptekin** [comment]
There is this [cheatsheet] (https://github.com/robbyrussell/oh-my-zsh/wiki/Cheatsheet#git) page on the wiki for the git plugin aliases. Is that what you were looking for?

**Comment by Stibbons** [comment]
I agree. But I like to clean the plugin first

**Comment by FinalDes** [comment]
the cheat sheet. but at beginning cannot easy to remember the alias, If git and other plugins have the way to look the plugin locally will be good

**Comment by ncanceill** [comment]
Granted, the cheatsheet is not very practical, and probably not up to date either. It would be nice to have a nice (searchable ?) list of aliases for the plugin, however I doubt a manual page is the way to go, for several reasons.

The main use-case of manual pages is to find out information about commands you already know exist, _eg_ the syntax of a particular option. They are not originally meant to help you remember a list of aliases. Moreover, they are designed to provide the user with verbose explanations, while with the aliases the user only needs to know the corresponding commands.

Manual pages require an install process locally. This is neither easily doable nor is it part of OMZ's philosophy.

Granted, it has been a few months since I was maintaining anything (sorry @robbyrussell and @mcornella). Nevertheless, I am still hoping to have shortly refactored the plugin (see #2790 and the comment above from @Stibbons), which I think should be prioritized.

The main upside I see a manual page having is: manual pages are searchable, at least when you read them with `less` (which you do by default). But you can have the same feature without using a manual page (see below).

***

Finally, let me try to understand the use-case you are referring to.
> at beginning cannot easy to remember the alias, If git and other plugins have the way to look the plugin locally will be good

Not sure about your English, here is what I got from it:
- you want an easy tool to remember aliases;
- and you want this tool to be available locally.

Well, there is actually a way to do that through the `alias` command. You can use it with arguments to create aliases, but if you use it without any argument it will echo the list of all aliases.

Then, if you want (for example) to remember aliases for `git log`, you can simply:
```
user@host$> alias | grep "git log"

glg='git log --stat --max-count=10'
glgg='git log --graph --max-count=10'
glgga='git log --graph --decorate --all'
glo='git log --oneline --decorate --color'
glog='git log --oneline --decorate --color --graph'
gunwip='git log -n 1 | grep -q -c "\-\-wip\-\-" && git reset HEAD~1'
```

**Comment by ncanceill** [comment]
@FinalDes, the [wiki](https://github.com/robbyrussell/oh-my-zsh/wiki/Plugin:git) will be updated when #2790 is merged, in the meantime are you satisfied with the `alias | grep` technique I mentioned above?
