### ISSUE TITLE
'gap' is a program

### ISSUE THREAD

**Issue by ChrisJefferson** [robbyrussell/oh-my-zsh#3682]
Since installing oh-my-zsh, I kept finding that running 'gap' would start some weird git related thing. 

I have now discovered this is a git alias added by the git package. Perhaps if there is a program called 'gap', that should be used instead of the alias? Or choose a different one?

**Comment by apjanke** [comment]
Sounds like you're referring to `gap` from GAP (https://github.com/gap-system/gap)?

@Stibbons and @ncanceill are the maintainers of the git plugin. Can you folks comment?

@ChrisJefferson, as a workaround, you can `unalias gap` after sourcing `$ZSH/oh-my-zsh.sh` in your `~/.zshrc`.

**Comment by ChrisJefferson** [comment]
Yes, it is that `gap`. I didn't know about unalias (probably should have done), I can at least use that for now to get my machine working again. Don't know if there will always be an argument over these short names.

**Comment by ncanceill** [comment]
Hi @ChrisJefferson,

I had never heard of the [GAP system](http://www.gap-system.org), and I did not know about a GNU program called `gap`. This is obviously a conflict, and there are two choices when it comes to this:
- changing the `gap` alias to something else
- not doing anything

***

We do not like modifying aliases, because it may break backwards-compatibility for existing users of the plugin. This means we need a really good reason for doing so: proof that this conflict affects many users.

This is where you come in. Since you want this problem to be solved, your task is now to find other people like you: people using both GAP and the Git plugin. When you find them, get them to +1 this issue, and we will consider changing the `gap` alias to something else.

If you choose this option, please keep this issue open until you find enough of them or give up.

***

In case you do not complete the above task, the alias will definitely not be modified. This would leave you with a few options:
- use `unalias` in your `~/.zshrc` as [suggested above](#issuecomment-78300671)
- use another alias for your `gap` command, for instance:
```
alias the_real_gap="/path/to/the/real/gap"
```
- maintain your own fork of OMZ and edit `$ZSH/plugins/git/git.plugin.zsh` to your needs

If you choose any of these options, please close this issue.

***

Thank you @apjanke for the ping. Next time @ChrisJefferson please notify the maintainers of the affected plugins.

**Comment by ChrisJefferson** [comment]
I'll just stop using the git plugin.

**Comment by ncanceill** [comment]
OK, this was not in the options I listed, but suit yourself.

Sorry but for the sake of compatibility we cannot easily change plugins aliases. Any other suggestion is welcome.

**Comment by Stibbons** [comment]
gap is (fortunately) not defined in git2 plugin (https://github.com/robbyrussell/oh-my-zsh/pull/2494)

Collision is indeed inevitable, and I think it should be better to rename conflicting git aliases.

Maybe a good solution would be to split the plugin into several one, so anyone can enable only the one that he wants (git-gst.plugin.zsh for git status aliases, git-co.plugin.zsh for git commit aliases, ...)

**Comment by ChrisJefferson** [comment]
@ncanceill : I'm not saying there is an easy fix for you, but I don't really fancy either e-mailing the gap mailing list to see if anyone else uses oh-my-zsh's git plugin (I imagine like me, they won't, as it breaks gap), and I only became a user of oh-my-zsh 2 days ago, beginning to keep a separate version sounds painful!

One thing which might be worth considering (I don't know if it is) would be to produce a more useful error message and fix. Perhaps oh-my-zsh could print out aliases which conflict with programs (although I suppose sometimes this is on purpose, as it is replacing them), and give advice on how to fix the problem. At first I assumed the problem was something like auto-correction.

**Comment by ncanceill** [comment]
Thank you for your input, it only helps up make OMZ better.

I like your idea of checking for conflicts. This could be done by defining a custom `safe_alias` function, based on `alias`. By checking the return value of the `which` command, we can detect if an alias is overriding an existing command, and print a warning.

Would anyone be willing to work on that?

**Comment by Stibbons** [comment]
Hard to do, because it depends whether gap or any other software is installed on your system...

**Comment by ChrisJefferson** [comment]
How about just see if 'which gap'  returns anything?

**Comment by Stibbons** [comment]
it returns none on my system. But on your it will return something. The "which" test is not good enough

**Comment by ChrisJefferson** [comment]
I'm confused now about what we are talking about :)

A `safe_alias` function would (I hope) find that assigning `gap` on your computer was fine, and on my machine would produce a warning, hopefully giving me some useful advice on how to either enable the alias without warning, or disable it.

Of course, finding what commands are valid on anyone's computer anywhere is probably an unreasonable goal.

**Comment by blueyed** [comment]
As @ChrisJefferson suggested, you could use something like:

if [[ -z $commands[gap] ]]; then
    alias gap="git add -p"
fi

**Comment by blueyed** [comment]
@ncanceill 
There's no need for a `safe_alias` wrapper I think.
Do you think this can make it into the fixed git plugin?

**Comment by blueyed** [comment]
OTOH a `safe_alias` wrapper could then be used instead of `alias` everywhere of course, so it's worth adding to the framework probably.

**Comment by ncanceill** [comment]
Yes, I am definitely in favor of a safe aliasing system, to use everywhere throughout OMZ.

Will work on it as soon as the git plugin crisis is solved.

**Comment by unphased** [comment]
If I'm understanding things correctly: 

1. `gap` got taken out for `gapa` because OP complained that `gap` is some tool
2. when #4585 is completed, OP's concern can be dealt with while retaining the `gap` alias
3. presumably along with the completion of #4585 `gapa` will go away...

**Comment by ncanceill** [comment]
@unphased 

Could not have put it better myself. Although we may go with the Micro$oft approach and keep `gapa` around too... retro-compatibility yay.
