### ISSUE TITLE
unable to run source ~/.zshrc successfully, issues found in .oh-my-zsh.sh. Maybe already solved, can someone reference a resolved ticket?

### ISSUE THREAD

**Issue by RichardBansal** [robbyrussell/oh-my-zsh#3691]
I am getting this when I run 
    source ~/.zshrc

    -bash: /Users/ram/.oh-my-zsh/oh-my-zsh.sh: line 26: syntax error near unexpected token `('
    -bash: /Users/ram/.oh-my-zsh/oh-my-zsh.sh: line 26: `for config_file ($ZSH/lib/*.zsh); do'
    -bash: typeset: -g: invalid option
    typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
    -bash: /Users/ram/.oh-my-zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 81: syntax error    near unexpected token `always'
    -bash: /Users/ram/.oh-my-zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 81: `        } always {'

**Comment by mcornella** [comment]
The zshrc file doesn't have to be sourced manually, when you start zsh, it will read the file automatically.
What is happening is that you're running bash instead of zsh, so oh-my-zsh cannot start. 

You have to do 2 things:
- Actually 3 things: make sure you have zsh installed.
- Make sure zsh is your default shell: `echo $SHELL` should say `/some/thing/**zsh**`. If not, run `chsh -s $(which zsh)`.
- Restart your terminal and the prompt should change.

**Comment by RichardBansal** [comment]
Many thanks, I had to manually make the update, it would not complete it via console. System Preferences -> Users & Groups -> Click the lock -> Right click your user -> Advanced Options -> and paste /usr/local/bin/zsh in the login shell field.

**Comment by mcornella** [comment]
Cool, glad to be of help :+1:

**Comment by Flyty** [comment]
run `zsh` and then everything is ok

**Comment by dingolfsson** [comment]
@Flyty it's unreal how much time I spent finding this most obvious solution ever. Thanks a lot!

**Comment by ashishra0** [comment]
@Flyty Unreal

**Comment by bwoodlt** [comment]
Thanks @dingolfsson
