### ISSUE TITLE
Bash completion on systemd shows "_store_cache:46: permission denied"

### ISSUE THREAD

**Issue by yochaigal** [robbyrussell/oh-my-zsh#3700]
On Arch Linux 64bit, running 3000.77140a2-1 from AUR (oh-my-zsh-git), everything works great, except:
If I run:
sudo modprobe vbox (and hit tab twice) it shows:
_store_cache:46: permission denied: /usr/share/oh-my-zsh//cache//modules-3.19.1-1-ck

However, if I enter bash, it does not do this:
➜  ~  bash              
[yochai@copernicus ~]$ sudo modprobe vbox
vboxguest  vboxpci    vboxsf     vboxvideo  

I noticed it happening for other things as well, like systemctl status.

**Comment by thorerik** [comment]
Sounds like the permissions for /usr/share/oh-my-zsh/cache is not allowing you to write to it.

I presume it would be better to contact the AUR maintainer (unless they watch for issues here?) directly.

**Comment by yochaigal** [comment]
Thanks for the response! I'll definitely contact the AUR maintainer, good call.

That said, here is my permissions for reference:

 ls -l /usr/share/oh-my-zsh 
total 48
drwxr-xr-x   2 root root 4096 Mar 18 16:48 cache
drwxr-xr-x   3 root root 4096 Mar 18 16:44 custom
drwxr-xr-x   2 root root 4096 Mar 18 16:44 lib
drwxr-xr-x   2 root root 4096 Mar 18 16:44 log
-rw-r--r--   1 root root 2938 Mar 18 16:44 oh-my-zsh.sh
drwxr-xr-x 191 root root 4096 Mar 18 16:44 plugins
-rw-r--r--   1 root root 7438 Mar 18 16:44 README.markdown
drwxr-xr-x   2 root root 4096 Mar 18 16:44 templates
drwxr-xr-x   2 root root 4096 Mar 18 16:44 themes
drwxr-xr-x   2 root root 4096 Mar 18 16:44 tools
-rw-r--r--   1 root root 2601 Mar 18 16:44 zshrc

**Comment by yantis** [comment]
I am the current maintainer for the package on the AUR.  In the meantime as a work around I added to the post install for users to add this to their .zshrc files as permissions with anything less than 777 would not work.
ZSH_CACHE_DIR="/tmp/zsh_cache"

I thought about patching that into the template but it seems like there should be a better way to do this or maybe it should be done upstream. Any thoughts or recommendations?

**Comment by apjanke** [comment]
Hi, yantis.

Caveat for the following: I'm not an oh-my-zsh designer, just a recent developer, but I've spent some time in its internals.

Oh-my-zsh is designed as a per-user installation, and it expects that users will have write permissions to the whole .oh-my-zsh directory. Usually that's only used for the `$ZSH_CACHE_DIR` directory and the auto-update mechanism, though plugins are not all clean about this and some might write their data into their plugin directory. But I'm pretty sure that `$ZSH_CACHE_DIR` stores per-user state by design, like the last working directory. So each user should have their own `$ZSH_CACHE_DIR`, even if the core oh-my-zsh installation is shared. Besides, having a world-writable cache for arbitrary shell stuff sounds like a security issue.

(IMHO, writing state to places outside `$ZSH_CACHE_DIR` is a bug. We're trying to clean that up in the few places I've seen it.)

The `$ZSH_CACHE_DIR` is expected to be persistent, storing state between login sessions and potentially for a long time, so `/tmp` is probably not the best place for it. ("cache" might be a misnomer, "data" or "var" might be more descriptive.)

I took a look at the AUR oh-my-zsh package. I'm not sure what the Right Way to do this is, since omz isn't currently designed for multi-user installations. But I think auto-creating a per-user cache dir from inside `.zshrc` might be a good approach. Something like this in your customized `zshrc.zsh-template`. (And maybe somewhere under `/var` would be better for your distribution, if you have a mechanism for users to create their own user-writable directories.)

````
ZSH=/usr/share/oh-my-zsh/
DISABLE_AUTO_UPDATE=true
ZSH_CACHE_DIR=$HOME/.oh-my-zsh-cache
if [[ ~ -d $ZSH_CACHE_DIR ]]; then
  mkdir $ZSH_CACHE_DIR
fi
````

There's also a `$ZSH/log/` directory that I'm pretty sure omz expects to be user-writeable, but I don't know how it works or whether it needs to be per-user, too.

Line 42 of `PKGBUILD` is missing `check_for_upgrade` when it removes the installation-related tools.

It looks like PKGBUILD is ignoring `${pkgdir}` relocation when it's customizing `zshrc`. 
```
  mkdir -p "${pkgdir}/usr/share/oh-my-zsh"

  # Fix the path to oh-my-zsh, and disable auto-updating.
  sed -e '2c\ZSH=/usr/share/oh-my-zsh/'\
```
Should that be `ZSH=${pkgdir}/usr/share/oh-my-zsh/`?

As a side note, `git` might be a good `optdepends` or even `depends` for `oh-my-zsh`, since it's used pretty extensively in oh-my-zsh at run time, including in most themes, including the default one, `robbyrussell`. If you want to make `git` truly optional, you should probably also customize the `zshrc.zsh-template` to not enable the `git` plugin by default, and to make the default theme one which does not use `git`, such as `cypher` or `funky`. (`grep -L git themes/*.zsh-theme` will give a list of candidates.)

**Comment by yantis** [comment]
apjanke,

Hello and thank you very much for the in depth and thoughtful reply. I went ahead and updated the PKGBUILD to reflect all of your suggestions (other than then ${pkgdir} relocation one). 

Auto creating the cache per user was a brilliant suggestion.

Thanks!

**Comment by apjanke** [comment]
You're welcome! Glad it was helpful.

@yochaigal, want to see if the updated package fixes your tab-completion issue?

**Comment by yochaigal** [comment]
I just tried it, I get:

sudo modprobe vbox
_store_cache:46: permission denied:
/usr/share/oh-my-zsh//cache//modules-3.19.2-1-ck

After updating from the AUR.

**Comment by apjanke** [comment]
I think you will need to re-setup oh-my-zsh for your user account, since your `~/.zshrc` probably still contains the code from the prior version of the oh-my-zsh package. It looks like you can just copy the omz-related stuff from `/usr/share/oh-my-zsh/zshrc` over the old corresponding stuff, or if you haven't done customization, just `cp -f /usr/share/oh-my-zsh/zshrc ~/.zshrc`.

**Comment by yochaigal** [comment]
I completely blew away my .zshrc file, then copied the source from
/usr/share/oh-my-zsh/, then closed the terminal, and tried the command
again: same problem.

**Comment by apjanke** [comment]
Hmm. Try blowing away the compdump cache files with `rm ~/.zcompdump*`, too. Those are not refreshed automatically with code or system changes (unless the function count changes), and could have stale completion-related settings.

**Comment by mcornella** [comment]
This happened to me just now. 

The **TL;DR** version: some completion cache files have wrong permissions. Run:
```sh
sudo chown -R "$USER:$USER" "$ZSH_CACHE_DIR"
```
then try again.

The long explanation is that you logged in as root using `sudo -E -s`, or some other way such that `$ZSH_CACHE_DIR` was still the same, then triggered a completion that *created* the cached file using root as owner. Then, as normal user, you triggered the same completion which tried to read the cached file, but you didn't have permission to read it. 
Therefore, by changing the owner of all files inside the `ZSH_CACHE_DIR` folder you'll get rid of the error.

**Comment by yochaigal** [comment]
That seemed to do the trick - of course in Arch, the default group is
"users" and not your username.
Thanks!

**Comment by mcornella** [comment]
Ok please close this issue.

**Comment by YayConnolly** [comment]
FYI this was still an issue for me os OSX, `zsh: permission denied: ~/.oh-my-zsh/plugins/wd`. @mcornella's solution resolved the issue (had to open a new terminal window):
```
sudo chown -R [username]:staff "$ZSH_CACHE_DIR"
```

**Comment by glubsy** [comment]
Hah, this just happened to me too (Arch Linux), especially when doing systemctl status *TAB* for example:

> _store_cache:46: permission denied: /usr/share/oh-my-zsh//cache/SYS_ALL_UNITS
> _store_cache:46: permission denied: /usr/share/oh-my-zsh//cache/SYS_REALLY_ALL_UNITS

Even though there are no files in /usr/share/oh-my-zsh/cache except a `.gitkeep` file. I don't like chowning system directories that users aren't supposed to write to, but it did fix the problem it seems. Weird.

**Comment by hardianlawi** [comment]
I got the same error only when using `sudo apt install` autocompletion.

```
_store_cache:46: permission denied: /home/hardianlawi/.oh-my-zsh/cache/DEBS_avail
```

I tried running `sudo chown -R "$USER:$USER" "$ZSH_CACHE_DIR"`, but it didn't fix it for me

**Comment by mcornella** [comment]
This looks like you ran zsh using root and it created that file as root, so you should chown that particular file, not the cache directory.

**Comment by hardianlawi** [comment]
@mcornella sorry, I'm not sure if I understand you. 

I was running zsh as my user and trying to install some packages using `sudo apt install` which then the message appeared after I pressed tab for auto completion.

I think someone (user or root) is trying to create this `/home/hardianlawi/.oh-my-zsh/cache/DEBS_avail`, but the permission was denied so I am thinking of just changing the permission of the `cache`.

```
total 76K
drw-r--r--   2 hardianlawi hardianlawi 4.0K Sep 10 17:40 cache
-rw-r--r--   1 root        root        4.8K Sep 10 17:40 CONTRIBUTING.md
drwxr-xr-x   4 root        root        4.0K Sep 10 17:40 custom
drwxr-xr-x   8 root        root        4.0K Sep 10 17:40 .git
-rw-r--r--   1 root        root         105 Sep 10 17:40 .gitignore
drwxr-xr-x   2 root        root        4.0K Sep 10 17:40 lib
-rw-r--r--   1 root        root        1.2K Sep 10 17:40 LICENSE.txt
drwxr-xr-x   2 root        root        4.0K Sep 10 17:40 log
-rw-r--r--   1 root        root        3.7K Sep 10 17:40 oh-my-zsh.sh
drwxr-xr-x 255 root        root         12K Sep 10 17:40 plugins
-rw-r--r--   1 root        root        9.2K Sep 10 17:40 README.md
drwxr-xr-x   2 root        root        4.0K Sep 10 17:40 templates
drwxr-xr-x   2 root        root        4.0K Sep 10 17:40 themes
drwxr-xr-x   2 root        root        4.0K Sep 10 17:40 tools
```

Sorry, beginner here.

**Comment by mcornella** [comment]
It looks like that file is already created with permissions that you don't have, most probably root. 
You can see that with `ls -l /home/hardianlawi/.oh-my-zsh/cache/DEBS_avail`

So you'll have to do
```
sudo chown $USER:$USER /home/hardianlawi/.oh-my-zsh/cache/DEBS_avail
```

You also have root ownership on the rest of the OMZ directory, which will cause you further problems. So change it to your user as well:
```
sudo chown -R $USER:$USER /home/hardianlawi/.oh-my-zsh/
```

**Comment by hardianlawi** [comment]
Hi @mcornella 

Apparently, it's trying to create the file. I checked the file and it didn't exist after the error happened.



> You also have root ownership on the rest of the OMZ directory, which will cause you further problems. So change it to your user as well:

Regarding this, I thought it was set as root due to some security or best practice reason as I only followed the installation guide and haven't made any changes.

I figured that the error might happen due to the owner issue, so I have changed it to `$USER`, but apparently I need to change the access permission too.

```
total 76K
drwxrwxr--   2 hardianlawi hardianlawi 4.0K Sep 12 21:41 cache
-rw-r--r--   1 hardianlawi hardianlawi 4.8K Sep 10 17:40 CONTRIBUTING.md
drwxr-xr-x   4 hardianlawi hardianlawi 4.0K Sep 10 17:40 custom
drwxr-xr-x   8 hardianlawi hardianlawi 4.0K Sep 13 00:26 .git
-rw-r--r--   1 hardianlawi hardianlawi  105 Sep 10 17:40 .gitignore
drwxr-xr-x   2 hardianlawi hardianlawi 4.0K Sep 10 17:40 lib
-rw-r--r--   1 hardianlawi hardianlawi 1.2K Sep 10 17:40 LICENSE.txt
drwxr-xr-x   2 hardianlawi hardianlawi 4.0K Sep 12 23:51 log
-rw-r--r--   1 hardianlawi hardianlawi 3.7K Sep 10 17:40 oh-my-zsh.sh
drwxr-xr-x 255 hardianlawi hardianlawi  12K Sep 10 17:40 plugins
-rw-r--r--   1 hardianlawi hardianlawi 9.2K Sep 10 17:40 README.md
drwxr-xr-x   2 hardianlawi hardianlawi 4.0K Sep 10 17:40 templates
drwxr-xr-x   2 hardianlawi hardianlawi 4.0K Sep 10 17:40 themes
drwxr-xr-x   2 hardianlawi hardianlawi 4.0K Sep 10 17:40 tools
```

It doesn't give me any error after I changed the access permission
