### ISSUE TITLE
Speed up git check

### ISSUE THREAD

**Issue by fundon** [robbyrussell/oh-my-zsh#3716]
```sh
if [ ! -d .git ]; then
  return
fi
```

**Comment by apjanke** [comment]
Hi fundon. Where is this code intended to go and what problem is it intended to solve? Usually if you have a patch to submit, it's presented as a Pull Request so it's obvious what the exact change is.

**Comment by mcornella** [comment]
@apjanke: I believe this is in relation to the git prompt check, contained in `lib/git.zsh`. 

@fundon: this has been proposed before \*and\* merged, but it led to problems, mainly regarding subfolders in repositories where the git prompt wouldn't show. Search a little in the repository about this and you'll know what I mean. We abandoned this route because of this, but maybe you can find a better solution that works around the different problems it creates.

**Comment by fundon** [comment]
@mcornella Good point.
I ignore the situation - sub dir.

Sorry, guys.

I'm closing it.
