### ISSUE TITLE
Cannot pull with rebase: You have unstaged changes.

### ISSUE THREAD

**Issue by faxotherapy** [robbyrussell/oh-my-zsh#3776]
Hello,

I am unable to upgrade. This is the result:
``Upgrading Oh My Zsh
Cannot pull with rebase: You have unstaged changes.
Please commit or stash them.
There was an error updating. Try again later?``

I initially installed using the basic installation process.

**Comment by ncanceill** [comment]
Hi,

This message means that you made custom changes to OMZ since the last upgrade. (You should be aware of that, since you (or someone using your computer) did it.)

In case you do not know of any changes you made and just want them gone, then this should do it:
```zsh
cd $ZSH && git stash && cd -
```

The upgrade process is not designed to allow local changes. If you want to customize your install, you should use the `$ZSH_CUSTOM` directory (see [wiki](https://github.com/robbyrussell/oh-my-zsh/wiki/Customization)). If you want to keep local changes in OMZ core, you will have to maintain your own fork.

**Comment by faxotherapy** [comment]
Indeed, I understand. I will resort to ``$ZSH_CUSTOM`` Thanks very much for your very prompt help. Problem solved.

**Comment by ncanceill** [comment]
My pleasure. Please close this issue now that your problem is solved ;-)
