### ISSUE TITLE
Git plugin continuously nags about unknown host

### ISSUE THREAD

**Issue by landaire** [robbyrussell/oh-my-zsh#3803]
I've encountered an issue where I've setup a fresh Git repo, then added a remote located at a host I've never communicated with on this machine before. When my theme/prompt (pure theme) checks the remote to see if I'm out of sync, it spits out:

```
The authenticity of host '<REMOTE> (<IP>)' can't be established.
RSA key fingerprint is 30:9a:97:f3:19:4f:d1:6e:28:76:9e:e7:d1:df:2c:31.
Are you sure you want to continue connecting (yes/no)?`
```

And does this every time the prompt is displayed. I'm not sure what indicators can be seen about unknown hosts, but it's worth looking into.

My title may be slightly misleading (I don't know the backend of oh my zsh so well) in that it may not be the git plugin, but it's something related to the prompt fetching the status.

**Comment by ncanceill** [comment]
[Greetings:] Hi,

[Affirmation:] You were right to doubt. This does not come from the git plugin, which you could have checked by disabling the plugin and observing that the behavior persists. Indeed, this behavior is from the [`git-remote-status`](https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/git.zsh#L32-L50) function, which is probably called by your theme's prompt.

[Explanation:] In order to enable your prompt to display the status of the current branch, your OMZ theme needs to get the revision list from the corresponding remote tracking branch; if you configured such remote branch with SSH access, any Git operation like `pull`, `checkout` or `rev-list` will require you to add the Git server's fingerprint to your computer's known hosts.

[Extrapolation:] Before offering you a solution I must try to understand what you want to do. You said your computer has never communicated with the Git server before, which explains why the server's RSA key fingerprint is not in your known hosts yet. I can only assume that you will do so anyway in due time.

[Explanation:] Your best course of action seems to consist in initiating SSH connection to the target Git server in order to add its fingerprint to your computer's known hosts. The easiest way to do so is to replace `<url>` with the address of your Git server in the following command:
```zsh
ssh <url>
```
You could also trigger this by performing any Git command involving the remote, like so:
```zsh
git pull origin master
```

[Clarification:] The above is built on the assumption that your intention of connecting to the Git server remains.

[Inquiry:] Otherwise, please indicate why you would set up a remote tracking branch without using it.

**Comment by apjanke** [comment]
Hi folks,

Totally agree with your analysis of why this happens when `git` gets called from within a prompt info function.

There's a couple other places in the source code it could be coming from, too. The `git_prompt_status` function from the OMZ `lib/git.zsh` also checks ahead/behind, using the `git status -b` option. I think that's the most common place for OMZ themes to pick it up.

But in this case, landaire's using the `pure` theme. `Pure` doesn't use the git support from OMZ's `lib/git.zsh` or most of OMZ's theme stuff. Instead, it's using [ZSH's own user-contributed `zstyle`+`vcs_info` system](http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#Version-Control-Information).

That `vcs_info` stuff is upstream, so I don't think there's anything we can do about it, aside from having you switch to a different theme or twiddle `pure` (in your custom OMZ directory) so it doesn't do the remote ahead/behind checking.

That said, the OMZ `lib/git.zsh` stuff is definitely subject to the same behavior.

I can see a use case where this could be an annoyance and you wouldn't expect to connect to those servers in the regular course of work: when you're in a multi-user environment, and you're cding around through directories that other users have set up. Not a common use case, and switching themes or just turning off `vcs_info` in that case seems like a decent workaround. Or if you're in a multi-machine environment (e.g. a dev setup with a lot of VMs, and multi accounts on each) with shared filesystems that contain the repos.

Anyway, I think @ncanceill's workaround sounds fine. I'd suggest using `git status` instead of `git pull` or whatever: `git status` will connect to the remote, but is nondestructive, and you don't have to bother grabbing the hostname for a manual `ssh` connection. Whenever you see that prompt, just do `git status` as your next command, say "yes", and it should go away for any repos hitting that remote host.

**Comment by apjanke** [comment]
BTW, @landaire – when you see this, does it give you the chance to actually answer yes or no? Or does it just get printed before the zsh prompt? 

It's also a little weird that the host in that message is `' ()'`. Normally you'd see a host name and/or IP address or similar.

**Comment by landaire** [comment]
@ncanceill 

> Before offering you a solution I must try to understand what you want to do. You said your computer has never communicated with the Git server before, which explains why the server's RSA key fingerprint is not in your known hosts yet. I can only assume that you will do so anyway in due time.

I had *only* just added this remote and as soon as I did I got prompted, which really confused me. Then subsequent command or whatever I did that would cause the prompt to refresh would prompt, confusing me even more. This is a little extreme (I hit CTRL + C a lot), but you get the idea

![git](https://cloud.githubusercontent.com/assets/1313522/7301512/f071316e-e997-11e4-96b7-ae14cbb92ed3.png)

I wanted to report this to avoid other people the same confusion in the future if possible.

@apjanke 

No, it doesn't actually give me a chance to answer yes or no. The weird host message is a result of me not properly escaping my angled brackets in my Markdown (sorry!)

**Comment by apjanke** [comment]
Ah! I didn't even think of that case with the just-added remote.

If you're not able to actually interact with the prompt, maybe the cheap and easy thing to do here is to just see if we can quash that ssh warning message and just display an error indicator in the git prompt info. Again, we can't fix it for `pure` because `vcs_info` is upstream ZSH, but we could do so for the OMZ `lib/git.zsh` equivalent.

I'll set up a test to reproduce this when I have some time this afternoon; I'm curious as to how the output is actually flowing here.

**Comment by landaire** [comment]
Sorry for not being clear in my initial report, and thanks for looking into it @apjanke. Let me know if you need any more information.

**Comment by bthibault** [comment]
I'm running into this issue, I clear out my .ssh/.known_hosts file and this thing thing keeps popping up

**Comment by mcornella** [comment]
@bthibault I know this issue is old but can you set up a test to reproduce this, because I haven't been able to. Also tell us what zsh version you use and what theme as well.
