### ISSUE TITLE
Command and current path artifacts printed when used with Neovim terminal

### ISSUE THREAD

**Issue by lynndylanhurley** [robbyrussell/oh-my-zsh#3823]
I get the following output when I type `echo foo` and `echo bar` using the built-in Neovim terminal:

~~~bash
❯ echo "foo"
echofoo
..thbox/dbx-api
~/Code/Healthbox/dbx-api master
❯ echo "bar"
echobar
..thbox/dbx-api
~/Code/Healthbox/dbx-api master
~~~

I've narrowed the issue down to `oh-my-zsh`.

The problem doesn't occur in iTerm or Terminal.app, or anywhere else that I can find, but it does go away when I disable `oh-my-zsh`.

**Comment by ncanceill** [comment]
Hi, and thanks for reporting.

Were you, by any chance, able to track this down further, for instance link it to a particular plugin or theme?

Is the behavior happening for every command or just `echo`?

**Comment by lynndylanhurley** [comment]
@ncanceill thanks for the quick reply!

> Were you, by any chance, able to track this down further, for instance link it to a particular plugin or theme?

The problem occurs when I disable everything but oh-my-zsh itself.

> Is the behavior happening for every command or just echo?

It happens with every command.

Please let me know if there's anything else I can do to help diagnose this issue.

**Comment by ncanceill** [comment]
I have to admit I am quite baffled here.

Can you please [gist](https://gist.github.com) your `~/.zshrc` for me (along with other [startup files](http://zsh.sourceforge.net/Intro/intro_3.html) you may have) please?

Also paste the output of `$SHELL --version`.

**Comment by lynndylanhurley** [comment]
@ncanceill - [here](https://gist.github.com/lynndylanhurley/6a1c1e3a0607e221074b) is my .zshrc file. I've disabled all plugins except for oh-my-zsh. I am using [antigen](https://github.com/zsh-users/antigen), but I don't think that is related because the problem goes away if I omit `antigen use oh-my-zsh` from the file.

Here is the output of `$SHELL --version`:

~~~
zsh 5.0.7 (x86_64-apple-darwin14.0.0)
~~~

I don't have any other startup files.

Thanks for your help with this!

**Comment by mcornella** [comment]
Hi @lynndylanhurley, what theme are you using with oh-my-zsh? Also follow [these instructions](https://github.com/robbyrussell/oh-my-zsh/wiki/Troubleshooting#everything-else) to generate a debugging file.

**Comment by lynndylanhurley** [comment]
@mcaserta - I normally use [pure](https://github.com/sindresorhus/pure), but the issue still occurs when I don't use any theme at all.

Thank you for linking to the troubleshooting instructions. [Here](https://gist.github.com/lynndylanhurley/4b7b87f65937379eb7a0) is output from the debug log when I run it from the Neovim terminal.

**Comment by mcornella** [comment]
Sorry, I can't make enough of that file with the command I gave you. Try this one instead:
```sh
zsh -xv &> >(tee ~/omz-debug.log 2>/dev/null)
```

**Comment by lynndylanhurley** [comment]
[Here](https://gist.github.com/143511c56ac9a53c3dff) is the result of that command.

**Comment by mcornella** [comment]
On the last one you didn't run any command to reproduce the behavior, could you retry again?

Also, this might be related to auto-title functionality. Try running the same offending commands before *and* after running:
```sh
function omz_termsupport_cwd omz_termsupport_precmd omz_termsupport_preexec { }
```
and see what happens.

**Comment by mcornella** [comment]
Updates?

**Comment by apjanke** [comment]
I can partially reproduce. Looks like this is due to a bad `$TERM` value being set in your `~/.zshrc`, not an OMZ or neovim issue.

It appears that your `~/.zshrc` is [forcibly setting the `$TERM`](https://gist.github.com/lynndylanhurley/143511c56ac9a53c3dff#file-omz-debug-log-L93) terminal type when it is run [from inside `tmux` or `nvim`](https://gist.github.com/lynndylanhurley/143511c56ac9a53c3dff#file-omz-debug-log-L10).

```
if [ "$TMUX" ] || [ ! $ZSHRC_LOADED ] || [ "$NVIM_LISTEN_ADDRESS" ]
then
   ...

  export TERM=screen-256color
```

If I put `export TERM=screen-256color` in to a fresh `~/.zshrc` copied from the OMZ template, and run `zsh` in iTerm, then each command that I run results in the command name getting echoed as well, like you have.

```
> echo foo
echofoo
```

The problem is that the by forcing `$TERM`, your `~/.zshrc` is causing programs, including OMZ's `lib/termsupport.zsh`, to use the `screen-256color` escape sequences. But `nvim`'s terminal emulator, along with iTerm/Terminal (unless you have reconfigured them) emulate `xterm-256color`, which uses different escape sequences.

What you are seeing appears to be the terminal commands to [update the window title](https://github.com/robbyrussell/oh-my-zsh/blob/3704fbb71eb4d886aff11cdaff79a1a23a895cd6/lib/termsupport.zsh#L17) with the [running program's name](https://github.com/robbyrussell/oh-my-zsh/blob/3704fbb71eb4d886aff11cdaff79a1a23a895cd6/lib/termsupport.zsh#L46-L49), and [change the title back to the trailing part of the current directory](https://github.com/robbyrussell/oh-my-zsh/blob/3704fbb71eb4d886aff11cdaff79a1a23a895cd6/lib/termsupport.zsh#L24-L34) after the command finishes, but being issued with the wrong escape sequences, so the terminal doesn't interpret them correctly, and echoes the contents as text.

It is an error to set `$TERM` to a value that doesn't match your terminal. That value is usually supplied by the program that's launching the shell, so you don't need to set it yourself in most cases. Fix your `~/.zshrc` to not set `$TERM`, at least not when running inside `nvim`, and this problem should go away.

**Comment by lynndylanhurley** [comment]
@apjanke - that was the issue. I removed `export TERM=screen-256color` from my `~/.zshrc` and now everything works as it should. Thanks!!!
