### ISSUE TITLE
Wrong Directory

### ISSUE THREAD

**Issue by MiteshShah** [robbyrussell/oh-my-zsh#3828]
Issue: There is no directory called proxy but after p press tab its completed to proxy
```
╭─mitesh at RestrictedArea in ~ using 15-04-30 - 15:12:40 
╰─○ cd proxy 
~bin
╭─mitesh at RestrictedArea in /bin using 15-04-30 - 15:12:50 
╰─○ pwd
/bin
╭─mitesh at RestrictedArea in /bin using 15-04-30 - 15:12:55 
╰─○ 
```

**Comment by MiteshShah** [comment]
Tested on bash and default zsh its say 
```
cd: no such file or directory: proxy
```

**Comment by mcornella** [comment]
In this case, `proxy` is a named directory to the "home directory of the proxy user". If you run `grep proxy /etc/password` you'll see the home directory of the proxy user is `/bin`, probably. 

This is because of the option `cdablevars` that is enabled, which allows to cd into "user directories" as well as named directories, which are variables that point to a directory. This means you can do `cd user` instead of `cd ~user`; or `cd var` instead of `cd $var`, where `$var` is a variable pointing to `/some/directory` (in absolute path form).

You can disable this behavior if you're not using it with `unsetopt cdablevars`, or you can also keep it enabled but not have those choices completed by running the following:
```
zstyle ':completion:*:complete:(cd|pushd):*' tag-order 'local-directories path-directories directory-stack' '*'
```

Whichever of those two commands you end up choosing, you can add it at the end of your zshrc file to set it up permanently.

Source: http://www.zsh.org/mla/users/2006/msg00776.html

**Comment by mcornella** [comment]
Any updates? If it's solved please close
