### ISSUE TITLE
uninstalling zsh

### ISSUE THREAD

**Issue by wfayeBerman** [robbyrussell/oh-my-zsh#3863]
there were a lot of left over files after uninstalling on mac.  also many configurations remained in effect.  i think it might be helpful to include some additional uninstall support and how to reset back to bash using chsh -s /bin/bash

**Comment by ncanceill** [comment]
Hi, and thanks for suggesting.

As of now, what happens when you run `uninstall_oh_my_zsh` is
* if you have `~/.zshrc.pre-oh-my-zsh`, it means you had a `~/.zshrc` (and thus were using Zsh) prior to installing OMZ; then your old `~/.zshrc` will simply be restored
* else it means you were not using Zsh; then a `chsh` to `/bin/bash` will be issued

Is this not satisfying? We recently added a section on [Installing Zsh](https://github.com/robbyrussell/oh-my-zsh/wiki/Installing-ZSH) to the wiki, maybe something about uninstalling is needed too?

**Comment by wfayeBerman** [comment]
Thanks for explaining, must have been looking at preinstalled files on my
mac.  An extra section about uninstalling would be great, and thanks for
the cool product!

On Fri, May 8, 2015 at 5:14 AM, Nicolas Canceill <notifications@github.com>
wrote:

> Hi, and thanks for suggesting.
>
> As of now, what happens when you run uninstall_oh_my_zsh is
>
>    - if you have ~/.zshrc.pre-oh-my-zsh, it means you had a ~/.zshrc (and
>    thus were using Zsh) prior to installing OMZ; then your old ~/.zshrc
>    will simply be restored
>    - else it means you were not using Zsh; then a chsh to /bin/bash will
>    be issued
>
> Is this not satisfying? We recently added a section on Installing Zsh
> <https://github.com/robbyrussell/oh-my-zsh/wiki/Installing-ZSH> to the
> wiki, maybe something about uninstalling is needed too?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robbyrussell/oh-my-zsh/issues/3863#issuecomment-100168694>
> .
>



-- 

WALLY FAYE / WEB DIRECTOR



THE BERMAN GROUP / BERMANGRP.COM <http://bermangrp.com/>

WFAYE@BERMANGRP.COM <wfaye@bermangrp.com>

T: 212.450.7300 / M: 413.358.5397

TWITTER <https://twitter.com/TheBermanGrp> / INSTAGRAM
<http://instagram.com/thebermangrp>
