### ISSUE TITLE
Using 'Open Terminal Here' doesn't open it here :-) 

### ISSUE THREAD

**Issue by clement-escolano** [robbyrussell/oh-my-zsh#3867]
Hey everyone !

In Gnome, there is a great feature : when I right-click in a folder, I can select "Open Terminal Here" and a terminal opens with this directory. It used to work while bash was my terminal.
Now, it's not working anymore :-( 

Currently, the terminal launch zsh as a current command, otherwise it launch bash as default. It is certainly why the feature above doesn't work anymore.
I am lokking for a workaround for it :-) If by any chance, someone has one, it will be nice of him !

Thanks !

**Comment by ncanceill** [comment]
Hi,

This is seemingly not due to OMZ itself, but to the way you configured your terminal to run Zsh. Probably running Zsh as a custom command prevents your terminal from doing additional setup stuff — like switching to the appropriate directory.

Have you tried to properly set Zsh as your default shell and then letting your terminal open your default shell?

Anyway, since I suppose the issue happens with vanilla Zsh too, this is clearly not OMZ-related. Unless you have evidence that OMZ is at fault here, please close the issue — I will still try to help you, but this is not an OMZ issue so it should be closed.

**Comment by clement-escolano** [comment]
Thanks for the answer.
I know it's not OMZ related (sorry about that) but OMZ is the reason why I installed zsh so that's why I came here in the first place.
So as you said, I tried to properly set zsh as default with chsh. It didn't work then I had a second thought about 'properly'. I rebooted, remove the custom command and it's working ! 

Thanks

**Comment by ncanceill** [comment]
Excellent!
