### ISSUE TITLE
Git prompt status is incomplete

### ISSUE THREAD

**Issue by amithgeorge** [robbyrussell/oh-my-zsh#3877]
OS X Mavericks. iTerm2. Solarized color scheme. RobbyRussel theme. Enabled plugins - git.

My current git prompt looks as follows - 
![git prompt doesnt display modified files count](https://cloud.githubusercontent.com/assets/307876/7555479/619a1db2-f76a-11e4-94e7-a493c474cf39.png)
Even though there are 2 modified files, it doesn't show their count in the prompt. 

Prior to reinstalling the os, the git prompt showed three numbers along with the current branch. One of the numbers was for the count of modified files. The current branch color also changed depending on whether I was ahead or behind the remote branch. 

From what I understand of the documentation, its supposed to work out of the box.

**Comment by ncanceill** [comment]
I do not think the robbyrussel them does this. Maybe you were using another one?

Did you properly restore your [startup files](http://zsh.sourceforge.net/Intro/intro_3.html) after reinstalling? Are you sure you did not have anything in `$ZSH_CUSTOM` prior to uninstalling?

**Comment by amithgeorge** [comment]
I had only backed up the `~/.zshrc` file. Its the same file I am using currently. Which tells me I was using the robbyrussel theme earlier and I only had the `git` plugin enabled. I don't know what `$ZSH_CUSTOM` is, meaning I am not sure if I had anything in it prior to reinstalling :(. 

@ncanceill, Are you saying that with only the robbyrussel theme and git plugin enabled, the prompt inside a git repo only shows the current branch? I am asking because browsing the closed issues I found many comments suggesting that `git_command_prompt`, or something similarly worded, solved the issue of showing detailed git status prompts. 

Btw, in case the correct behavior is to only show the current branch, can someone help me display the info I want? Googling for this simply suggests to use an appropriate theme (without specifically mentioning one). I like the current theme and would like to make things work with this theme.

**Comment by apjanke** [comment]
Yeah, this is normal for the `robbyrussell` theme. It just shows brief status info using `git_prompt_info` with just the branch and a clean/dirty indicator. That "✗" indicates that your repo is dirty, with either new or untracked files. There's a more verbose `git_prompt_status` function that some themes use to give more detailed information which may what you had read about. But I don't think even that one includes counts of changed files.

To get a list of themes that use the more verbose Git info, do `grep -l git_prompt_status themes/*.zsh-theme` from within the oh-my-zsh directory (`~/.oh-my-zsh` by default). There's also the `agnoster` theme which does its own detailed Git info instead of using the core omz `git_prompt_status` function. 

If you want to make extended git info work with this theme, you can make your own custom theme based on it. Copy `themes/robbyrussell.zsh-theme` to your `$ZSH_CUSTOM/themes` directory, rename it `robbyrussell2.zsh-theme` or `amithgeorge.zsh-theme` or whatever, and just replace `git_prompt_info` with `git_prompt_status`. You'll probably need to add some character definitions to the theme, because not all of the `$GIT_PROMPT_*` variables are defined by default, and this theme doesn't supply them. You can grab a set of reasonable defaults from my theme at https://github.com/apjanke/oh-my-zsh-custom/blob/master/themes/andrewjanke.zsh-theme.

I don't know of any themes which actually have the changed file count in them. Maybe someone else can identify one?

**Comment by amithgeorge** [comment]
@apjanke thanks for all the details. It helped me piece together my solution. 

None of the existing themes were showing me the count. I switched to using `git_super_status` from the repo [zsh-git-prompt](https://github.com/olivierverdier/zsh-git-prompt). The information display is very different from what I originally had, but I can live with this.

As per your suggestion I copied the `robbyrussell.zsh-theme` to the custom themes folder; under a new name. And replaced `git_prompt_info` with `git_super_status`. And updated `.zshrc` to use the new custom theme. It just worked!
