### ISSUE TITLE
autojump is not loaded

### ISSUE THREAD

**Issue by mail6543210** [robbyrussell/oh-my-zsh#3912]
I'm using Ubuntu 14.04 and installed autojump from github into ~/.autojump by cloning and executing `./install.py`.

However, adding "autojump" into "plugins" of `.zshrc` doesn't work.

I guess there's a typo in the file "plugins/autojump/autojump.plugin.zsh".

The first line:
`if [ $commands[autojump] ]; then # check if autojump is installed`
should be
`if [ -z $commands[autojump] ]; then # check if autojump is installed`.

That is, add "-z" in the condition part.

**Comment by apjanke** [comment]
I think that test works as is, with a nonzero string evaluating to true. If you add the `-z`, it'll invert the sense of the test, being true only in the case of an empty string, which happens when there is no `autojump` command installed.

What do you get for the output of `which autojump`? Maybe you need to add another path item or something. The autojump installation script doesn't look like it edits your `~/.zshrc` file itself, but gives you instructions on editing it manually. Did you add those lines? And where? It looks like they will need to go before the oh-my-zsh initialization in your `~/.zshrc`.

**Comment by apjanke** [comment]
Say, @kalos, you're one of the autojump contributors, and it looks like you added the `if [ $commands[autojump] ]` test. Can you comment on this, and maybe help OP out? What's expected as far as installation of autojump is concerned?

**Comment by kalos** [comment]
@mail6543210 you can simply add the ~/.autojump in your PATH or if you have installed autojump in /usr/local/bin, check your PATH.

**Comment by mail6543210** [comment]
OK, now it works. Thank you!
