### ISSUE TITLE
Sublime Text editor for SSH

### ISSUE THREAD

**Issue by brianjking** [robbyrussell/oh-my-zsh#3934]
Is it possible to use the st or stt commands to open a file or directory in Sublime Text while connected via SSH?

**Comment by Kriechi** [comment]
How does this relate to oh-my-zsh?

**Comment by mcornella** [comment]
Well, it's a legitimate helpdesk question.

@brianjking: the short answer is no. The longer one is, it can be done, but you need to mess around with ["ssh x11 forwarding"](http://unix.stackexchange.com/questions/12755/how-to-forward-x-over-ssh-from-ubuntu-machine) because Sublime Text is a window application (i.e. it has a GUI).
Another option, if you want to only edit a specific folder every time, is to [mount the remote folder using `sshfs`](https://www.digitalocean.com/community/tutorials/how-to-use-sshfs-to-mount-remote-file-systems-over-ssh) and you'll have it on your local filesystem and edit it from there.

But specifically, if you have sublime text installed on the remote system you'll want to go for option 1.

**Comment by dfournier** [comment]
:+1:

**Comment by apjanke** [comment]
Note that the X11 forwarding will only work if the remote machine is a Linux machine. The Mac and Windows Sublime Text GUIs don't use X11.

There are some other options using SFTP or SSH from within Sublime Text, too (including that `sshfs` mechanism). This lets you edit remote files using a local Sublime Text process (which would generally give you better responsiveness than running the ST GUI over the network). See [this StackOverflow question](http://stackoverflow.com/questions/15958056/how-to-use-sublime-over-ssh) and [here](https://wrgms.com/editing-files-remotely-via-ssh-on-sublimetext-3/).
