### ISSUE TITLE
oh-my-zsh break tmux config and vim colorscheme

### ISSUE THREAD

**Issue by johnWIll17** [robbyrussell/oh-my-zsh#3937]
When I install oh-my-zsh, it breaks all colorschemes and some settings of tmux and vim. My vim colorscheme is completely different as it was (even when I run :colo it still points to the colorscheme that I used. Of course, uninstall oh-my-zsh gets it back to look-good colorscheme). The same for my tmux

**Comment by apjanke** [comment]
Where were your vim and tmux colorschemes set up?

When OMZ is installed, it moves any existing `~/.zshrc` out of the way to `~/.zshrc-pre-oh-my-zsh`, so anything defined there is turned off, and needs to be copied over to your new `~/.zshrc`. If the colorschemes or settings related to them were defined in your `~/.zshrc`, that could have caused it.

**Comment by alemedeiros** [comment]
I also have this problem. Can't find out why it is happening, both my tmux and vim/nvim configuration are on their on files (.tmux.conf and .[n]vimrc).

I checked the environment variables when running tmux with and without oh-my-zsh, the only differences are a few new variables from oh-my-zsh, speacially, the TERM variable is the same as before.

**Comment by apjanke** [comment]
BTW, if anyone does a PR pursuant to this, consider pulling in the source code reformatting from #4412. I think it makes this more readable and understandable, particularly with the long lines that control options to the `tmux` command.

**Comment by apjanke** [comment]
Could you post the output from `omz_diagnostic_dump` as a gist, along with copies of your .tmux.conf and .[n]vimrc files, so we can try reproducing this?

**Comment by fvdnabee** [comment]
I've been having the same problem with colours disappearing in vim. Both with and without the tmux plugin.

I did some testing and this what I see:
Note TERM=xterm is the default for zsh on my system and that 'set -g default-terminal "screen-256color"' is already set in my .tmux.conf file.
### Without oh-my-zsh:
* TERM=xterm and run 'tmux': vim colour scheme is broken
* TERM=xterm and 'tmux -2': vim colour scheme is working fine
* TERM=xterm and run 'TERM=xterm-256color tmux': vim colour scheme is working fine
* TERM=xterm and run 'TERM=screen-256color tmux': vim colour scheme is working fine
* set 'export TERM=xterm-256color' in .zshrc  and run tmux': vim colour scheme is **working partially**, specifically the empty background (i.e. where there is no character to the right) is black instead of gray as per my vim scheme
* set 'export TERM=screen-256color' in .zshrc and run 'tmux': vim colour scheme is working fine

### With oh-my-zsh loaded and no plugins:
* TERM=xterm and run 'tmux': vim colour scheme is broken
* TERM=xterm and 'tmux -2': vim colour scheme is working fine
* TERM=xterm and run 'TERM=xterm-256color tmux': vim colour scheme is working fine
* TERM=xterm and run 'TERM=screen-256color tmux': vim colour scheme is working fine
* set 'export TERM=xterm-256color' in .zshrc  and run tmux': vim colour scheme is **working partially**,  specifically the empty background (i.e. where there is no character to the right) is black instead of gray as per my vim scheme
* set 'export TERM=screen-256color' in .zshrc and 'tmux': vim colour scheme is working fine, however I see strange Unicode code points in zsh when programs return (e.g. echo 'test' or ls). I read online that setting TERM to screen-256color can give problems so should be avoided (note that this is not a problem when not using oh-my-zsh, i'm using the robbyrussell theme).

### With oh-my-zsh and the tmux plugin.
When I launch xfce4-terminal, it will launch zsh which will start oh-my-zsh which will connect to any existing tmux session or start a new one automatically.
* TERM=xterm and open xfce4-terminal (then start vim in tmux which autostarted): vim colour scheme is broken
* set 'export TERM="xterm-256color"' in .zshrc and open xfce4-terminal: vim colour scheme is **working partially**
* set 'export TERM="screen-256color"' in .zshrc and open xfce4-terminal: vim colour scheme is fine, but the zsh again shows the unicode code points as before
* TERM=xterm, add 'export TERM=xterm-256color' before _zsh_tmux_plugin_run in tmux.plugin.zsh and run xfce4-terminal: vim colour scheme is working fine
* TERM=xterm, add 'export TERM=screen-256color' before _zsh_tmux_plugin_run in tmux.plugin.zsh and run xfce4-terminal: vim colour scheme is working fine

For now I am using the last work-around. I put a patch [here](https://gist.github.com/fvdnabee/87e265487004e2f74575).
I also changed the _zsh_tmux_plugin_run function to call tmux -2 and this is also a work-around.
Note that ZSH_TMUX_FIXTERM_WITH_256COLOR has no effect here (plus this is already set in my .tmux.conf anyway).

Maybe someone with more experience into the TERM env var and tmux can look at the best solution for solving this issue?

My tmux plugin settings:
  ZSH_TMUX_AUTOSTART=true
  ZSH_TMUX_AUTOSTART_ONCE=true
  ZSH_TMUX_AUTOCONNECT=true
  ZSH_TMUX_AUTOQUIT=false

On an unrelated issue, ZSH_TMUX_AUTOSTART_ONCE does not seem to be effective for me.
More specifically it seems that when I open a new terminal, the value of ZSH_TMUX_AUTOSTARTED (set on L91 in tmux.plugin.zsh) is lost (and therefor tmux is started again and connects to the existing session).
This seems normal to me, as an env variable can not be used accross multiple instances of zsh? Is ZSH_TMUX_AUTOSTART_ONCE working for anyone?

**Comment by MatrixManAtYrService** [comment]
I ran across this thread because vim looked funny after switching to zsh.  In my case it was that my `~/bash_aliases` file was not being invoked, particularly the `vi -> vim` part.

**Comment by mcornella** [comment]
The tmux plugin was heavily modified not long ago. Reopen if the recent changes didn't fix this.

**Comment by calvin620707** [comment]
Just upgrade the on-my-zsh and still have this issue.

workaround with following changes to add `-2` in `tmux_cmd`.

```
function _zsh_tmux_plugin_run() {
  if [[ -n "$@" ]]; then
    command tmux "$@"
    return $?
  fi

  local -a tmux_cmd
  tmux_cmd=(command tmux -2)
  [[ "$ZSH_TMUX_ITERM2" == "true" ]] && tmux_cmd+=(-CC)

  # Try to connect to an existing session.
  [[ "$ZSH_TMUX_AUTOCONNECT" == "true" ]] && $tmux_cmd attach

  # If failed, just run tmux, fixing the TERM variable if requested.
  if [[ $? -ne 0 ]]; then
    [[ "$ZSH_TMUX_FIXTERM" == "true" ]] && tmux_cmd+=(-f "$_ZSH_TMUX_FIXED_CONFIG")
    $tmux_cmd new-session
  fi

  if [[ "$ZSH_TMUX_AUTOQUIT" == "true" ]]; then
    exit
  fi
}
```
