### ISSUE TITLE
How to get a blank line after each output?

### ISSUE THREAD

**Issue by fniessen** [robbyrussell/oh-my-zsh#3939]
How could we add a blank line after each output?  How can we redefine the prompt to insert such a blank line before?

**Comment by KhasMek** [comment]
This is how I export my prompt - 
```shell
PROMPT='
%{%f%b%k%}$(build_prompt)
%{$fg[magenta]%}■%{$reset_color%} '
```
So, technically it doesn't inset a line after each commands output, but inserts a blank line before building the prompt. However, the end result is the same. Unless I've misunderstood what you're asking for. I hope this helps you.

**Comment by apjanke** [comment]
You could also do it in a way that composes with other prompts by writing a function to echo a blank line and adding it to your `preexec` or `precmd` hooks.

```
function echo_blank() {
  echo
  preexec_functions+=echo_blank
  precmd_functions+=echo_blank
}
```

**Comment by fniessen** [comment]
Thanks to both of you.

@apjanke, I guess you meant:

    function echo_blank() {
        echo
    }
    precmd_functions+=echo_blank

right?

**Comment by apjanke** [comment]
D'oh! Yes; thank you. Fixed it in my comment.

**Comment by fniessen** [comment]
Thanks a lot!

BTW, is it possible to get a beep as well when the last command fails (returns a non-zero)?  I've tried a bit of everything (with escape chars) on my Cygwin shell, but couldn't yet.

Is there a portable way to do so?

**Comment by apjanke** [comment]
The command `echoti bel` should give you a portable beep sound. (It uses the terminfo database for portability.) Put `$(echoti bel)` next to the red X or whatever for "command failed" in the prompt and that might do it.

**Comment by fniessen** [comment]
`echoti bel` doesn't produce any sound on my machine. Is there something to check, or some prerequisite to add in my .zshrc?

**Comment by apjanke** [comment]
Make sure you don't have your terminal emulator's "silence bell" option set. That's pretty common.

If that doesn't work, tell us about your setup (OS, versions, what terminal emulator you're using, etc).

**Comment by fniessen** [comment]
That was it (thank you very much): option "sound" wasn't enabled (by default) in the "bell" section of my MinTTY Cygwin terminal.

To confirm, `echoti bel` is better than `print '\007'`?

**Comment by apjanke** [comment]
In my opinion, `echoti` is generally better than hardcoding terminal escape sequences, because it's portable and readable. Not all terminals use the same control characters or escape sequences for the same features. `echoti` will look up a capability in your terminfo database to get the sequence right for your current terminal. And it's more readable: `echoti` uses mnemonics like `bel` instead of just numeric codes.

But in this case it probably doesn't matter. BEL is just ASCII 07 in xterm; I'd bet any terminal in common use now uses the same character for it so portability is a concern. So it's probably a matter of whether you will find `\007`or `bel` more readable.

And simply for performance, you're better off using the `$terminfo` variable instead of the `echoti` command. (They're alternate `zsh` interfaces to the same information.) When doing `$(...)` inside a prompt string, that costs you a shell-out. `$terminfo[bel]` doesn't.

**Comment by fniessen** [comment]
Thanks again for your clear and precise instructions. Though, `$terminfo[bel]` does not work for me. See http://screencast.com/t/icfPDXiS6Nz: "command not found: ^G".

**Comment by fniessen** [comment]
BTW, shouldn't `setopt beep` do what I want?  Though I've set it, I do not see it when typing `setopt`... and I don't hear any sound when there are errors...

**Comment by apjanke** [comment]
Yeah, `$terminfo` is a Zsh-specific feature. So is `echoti`; this won't be portable to bash. 

The `beep` option is defined to "Beep on error in ZLE". That's just the line editor component, so it'll beep when there's an error with the command text you're typing in (e.g. if you hit tab and there are no matching files), not as a result of normal commands returning errors.

**Comment by fniessen** [comment]
Thanks for clarifying `setopt beep`.

For the beep "in the prompt", what would you use for Bash, then?  `print '\007'`?

**Comment by apjanke** [comment]
I would try to find a way to do it with terminfo again, for portability and readability. The `tput` command is like zsh's `echoti`, and I think you'll find it in most distributions. But since it's an external command, I'd run it once in `.bashrc` to get the `bel` sequence, and then stick that sequence in the relevant part of your prompt. (For performance, avoiding an unnecessary shellout at each prompt evaluation.) Something like this.

```shell
# in .bashrc
BEL=`tput bel`
PROMPT="...${BEL}..."
```

**Comment by fniessen** [comment]
To update the definition of my Agnoster theme, I tried the following:

    BEL=$(tput bel)

    beep_on_error() {
        RETVAL=$?
        [[ $RETVAL -ne 0 ]] && ${BEL}
    }

    PROMPT+='$(beep_on_error)'

But I must miss something, as that does not work. Any idea what's wrong?

Thanks again!

**Comment by apjanke** [comment]
Well, it's missing an `echo`. As is, it looks like it'll try to run the command named `^g`. :) But I'm not sure if you can use `$?` inside functions called inside prompt construction like that, because `$?` may have already been clobbered by other commands called inside other parts of prompt construction (like `git` status checks and so on).

In `zsh`, you can use the `%(?::)` syntax instead for things that depend on the result of the last user-issued command.


```shell
BEL=$(tput bel)
PROMPT+='%(?::$BEL)'
```

I don't know what the `bash` equivalent would be, if you're looking for portability there.

**Comment by fniessen** [comment]
Thanks A LOT. That works perfectly!

**Comment by ziishaned** [comment]
Or you can simply put following function inside `.zshrc` file:

```bash
preexec() {
  print ""
}
```

**Comment by yzalvov** [comment]
@ziishaned Thanks for a one-liner!

Though for those who is looking for a blank line **after** each output I would go with:
```zsh
precmd() { print "" }
```

**Comment by fniessen** [comment]
Dear @yzalvov , not sure I do understand the diff between preexec and precmd. Could you just give an example where that would make a diff?  Thanks!

**Comment by fniessen** [comment]
And, btw, would this:

    echo_blank() {
        echo
    }

    precmd_functions+=echo_blank

be better?
