### ISSUE TITLE
oh-my-zsh not finding "/etc/paths.d/" for finding the Golang install path

### ISSUE THREAD

**Issue by stuartweir** [robbyrussell/oh-my-zsh#3960]
I'm not entirely sure why, but when I did a fresh install of Golang on my computer, zsh (and particularly oh-my-zsh) would not be able to find the "/etc/paths.d/" path. This was trying to setup the PATH variables in .bashrc, .zshrc, and finally, .preztorc (Prezto worked). Oddly, however, Prezto uses zsh just like oh-my-zsh, which is why I find this strange that oh-my-zsh could not find it. Perhaps it is a bug?

-Stu

**Comment by mcornella** [comment]
Please post your `.bashrc`, `.zshrc` and `.zpreztorc` files. I believe this is a bug with how we're dealing with PATH configuration in [the zshrc template](https://github.com/robbyrussell/oh-my-zsh/blob/master/templates/zshrc.zsh-template#L52). Please check if you also have that line commented and comment it again if that's the case.

**Comment by apjanke** [comment]
What OS and version is this?

Normally, it's not OMZ that's supposed to do the finding of the `/etc/paths.d` paths. Those `/etc/paths.d` paths are picked up by system-wide rc files that are run before your user init files and before OMZ is initialized. In OS X, it's `/etc/zshenv` for zsh, and `/etc/profile` for bash. (I think `/etc/paths.d` is an OS X specific feature, and not supported on other platforms.)

Marc, that line in the template seems like it should be fine, since it includes the existing `$PATH` at the end. That should already have the paths from `/etc/paths.d` in it. Maybe there's something else that's clobbering `$PATH`?

I'm running zsh and oh-my-zsh on OS X 10.9.5, and have a a line like that from the OMZ template in my zshrc. It's working fine with `/etc/paths.d`: the TeX and XQuartz paths defined using that mechanism are in my `$PATH`. (Though my `~.zshrc` is one I wrote, not the stock one from the OMZ installation.)

```
[@ in /etc]
$ grep PATH ~/.zshrc
    PATH="/usr/local/bin:$PATH"
    PATH="$HOME/bin:$PATH"
    PATH="$PATH:$HOME/.gem/ruby/2.0.0/bin"
[@ in /etc]
$ ls /etc/paths.d
40-XQuartz TeX
[@ in /etc]
$ cat /etc/paths.d/*
/opt/X11/bin
/usr/texbin
[@ in /etc]
$ echo $PATH
/Users/janke/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/texbin:/Users/janke/.gem/ruby/2.0.0/bin
```

You can use the `omz_diagnostic_dump` from `diagnostics.zsh` [here](https://github.com/apjanke/oh-my-zsh-custom/blob/master/diagnostics.zsh) to get a dump with the relevant configuration files and system info, except for `.zpreztorc`, which you'll have to add separately.

**Comment by apjanke** [comment]
Oh, [here it is, in the installer](https://github.com/robbyrussell/oh-my-zsh/blob/master/tools/install.sh#L30-L33). The installer tool modifies that line from the `zshrc` template and replaces it with a static copy of the user's `$PATH` value at the time of OMZ installation.

```zsh
echo "\033[0;34mCopying your current PATH and adding it to the end of ~/.zshrc for you.\033[0m"
sed -i -e "/export PATH=/ c\\
export PATH=\"$PATH\"
" ~/.zshrc
```

That's a bug. It will break any `PATH` settings done by upstream system-wide config files, so if they're set dynamically and relevant state changes, or new items are added later, they'll be missed.

This would break path discovery in the way @stuartweir experienced here.

I'm guessing thhere's nothing special about what Prezto does with paths vs plain zsh. I'll bet that Prezto fixed it here because installing it installed a new non-broken `~/.zshrc` file (or reverted to the one Stuart had before the OMZ installation replaced it with a broken one). Just uninstalling OMZ would have had the same effect.

As a cheap hack to fix this particular issue, we could change the installer to leave an explicit `:$PATH` in the path it sets up, so it picks up any path entries added by the system-wide rc files. You'll end up with duplicate entries, but that's less bad than missing things.

For a longer-term fix, maybe we should reconsider how the installer deals with `~/.zshrc`. As it is now, it completely replaces the user's existing `zshrc` so any settings there are lost unless the user manually copies them over. And they'd still have to know to undo this `PATH` change. Maybe OMZ should just add its template stuff and OMZ initialization call to a copy of the user's existing `zshrc` instead of starting from scratch.

**Comment by apjanke** [comment]
Yep, I can reproduce. I did a fresh install of oh-my-zsh, and I ended up with a .zshrc that clobbers `$PATH`.

```
$ grep "export PATH" ~/.zshrc
export PATH="/Users/janke/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/texbin:/Users/janke/.gem/ruby/2.0.0/bin"
```

**Comment by apjanke** [comment]
Looks like this is a known issue, and there's existing discussion on it: #1359.

**Comment by lborg019** [comment]
on my OS X I used
```bash
$ vim /etc/paths.d/go
```
and the file contained:
```bash
/usr/local/go/bin
```
I added this last path to my .zshrc and it worked.
here's what my .zshrc export looked like:

```bash
export PATH="/Users/myusername/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"
```
All I had to do was append `/usr/local/go/bin` to the end of this path, and now Go works on oh-my-zshell. Here's what my .zshrc export looks like now:

```bash
export PATH="/Users/myusername/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin"
```

**Comment by igauravsehrawat** [comment]
I wish OMZ would handle `paths.d` elegantly on Mac. Nevertheless @lborg019 solution worked.
