### ISSUE TITLE
Git function for current branch is not working

### ISSUE THREAD

**Issue by iammichiel** [robbyrussell/oh-my-zsh#3995]
The following fails : 

    ggpush --force

The alias is using the last git commit hash as current branch name. 
This problem appeared after this change 5b75cc7880de1931a0507800d90eb77ed659fa46. 

Stacktrace :

    error: src refspec c3acafc does not match any.
    error: failed to push some refs to 'ssh://git@whateverrepo.git'

**Comment by mcornella** [comment]
This was recently updated. Please upgrade and check that it works again.

**Comment by iammichiel** [comment]
I actually checked this on master branch minutes before I reported the issue.

**Comment by iammichiel** [comment]
And I confirm this on master version.

**Comment by ncanceill** [comment]
Oh, well I did not think anyone used `ggpush` that way... the thing is now if you call `ggpush` with any arguments (in this case `--force`) it will not use the current branch but instead expect a branch name to be specified.

As a result you end up running `git push origin --force` which causes the error you reported.

This change was made to allow you to specify a different branch with `ggpush`, so that:
* `ggpush` pushes to the current branch
* `ggpush other_branch` pushes to `other_branch`

As a result, `ggpush --force other_branch` works but `ggpush --force` does not. Currently you can use `ggf` instead, but it has been [advocated](https://github.com/robbyrussell/oh-my-zsh/issues/3972#issuecomment-111529406) to be removed.

There is also the possibility of reverting back to the old `ggpush` and `ggpull` so they always default to the current branch, and allow forms like `ggpush --force`.

I think the latter is the easiest fix. What do you suggest we should do?

**Comment by iammichiel** [comment]
Well, in my case this is a daily scenario : 
- Work on a local branch
- Push it to a distant branch with same name (`ggpush`)
- Submit it via PR 
- Making corrections based on PR, rebase, squash, ammend and then a push force to update distant branch with corrections thus a `ggpush --force`

As this a long command to type manually, an alias would be nice. I really like the consistency of using `ggpush` and `ggpush --force` with the same behaviour. If I have to switch aliases based on the fact I am forcing, that seems like overkill to me. And as others, I also agree on never included the `force` option as an alias. It should always be explicit from my point of view.

**Comment by ncanceill** [comment]
Duly noted, I will get on it shortly. Thanks for reporting.

**Comment by Calyhre** [comment]
And if you ever set `git config push.default` to `matching`, and use `ggpush -f`, you can cry now.
