### ISSUE TITLE
last-working-dir plugin breaks "Open in Terminal" Nautilus extension

### ISSUE THREAD

**Issue by kappa** [robbyrussell/oh-my-zsh#3999]
This very useful extension provides a one click way to open a terminal window for the current folder in GNOME Nautilus.
The code for the extension is here: https://github.com/GNOME/nautilus-open-terminal
Looks like it just runs "/bin/sh -c 'cd $DIR && exec $SHELL'". So, last-working-dir does not see the first "cd" and happily changes cwd to the cached value.

**Comment by ncanceill** [comment]
cc @op

**Comment by mcornella** [comment]
I can confirm this behavior, and it's due to the fact that on each shell start it runs the `lwd` function, in [lines 23 to 25](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/last-working-dir/last-working-dir.plugin.zsh#L23-L25). If you comment out those lines the extension works again.

**Comment by mcornella** [comment]
In fact, those lines haven't worked well since they were written 3 years ago. If you want to disable this auto-cd behavior you can set `ZSH_LAST_WORKING_DIRECTORY=1` in your zshrc file before sourcing oh-my-zsh.

I believe a better default would be to only do that unless it's specifically set by the user.

**Comment by kappa** [comment]
But those three lines implement the whole idea behind last-working-dir plugin, aren't they?
I mean, yes, the Nautilus extension works again, but all new shells start in $HOME.

**Comment by apjanke** [comment]
How about have your `~/.zshrc` check to see if the shell is starting in `$HOME`. If you're in `$HOME`, start as usual and let last-working-dir run. If you're not in `$HOME`, assume the calling program has take responsibility for placing the shell where it wants to be, and `set ZSH_LAST_WORKING_DIRECTORY=1` to avoid replacing it. (And you can decide if you want to do update the last-working-dir to be that directory.)  Won't work 100% (e.g. if you try to open a shell in your home dir) but might be good enough to be usable.

BTW, that `$cache_file` variable in `last-working-dir.plugin.zsh` is a global variable, and a pretty generic name for one. Should probably be renamed or eliminated.

**Comment by kappa** [comment]
Great idea, thanks!

**Comment by apjanke** [comment]
Can this issue be closed now?
