### ISSUE TITLE
Prompt user input color not preserved after completions triggered

### ISSUE THREAD

**Issue by adraghici** [robbyrussell/oh-my-zsh#4042]
I'm not sure that this is really an issue, but I could just use some help configuring my theme to use a specific different color just for user input.

I am using Solarized + iTerm2 and this is my theme:
```
ZSH_THEME_GIT_PROMPT_PREFIX="["
ZSH_THEME_GIT_PROMPT_SUFFIX="]"
ZSH_THEME_GIT_PROMPT_DIRTY=" %{$fg_bold[red]%}*%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_CLEAN=""

PROMPT='%n@%m %{$fg_bold[white]%}%~%{$reset_color%} $(git_prompt_info)%E
$ %{$fg_no_bold[white]%}'
```

It initially works as expected, starting with a white prompt:
![Initial prompt](https://i.imgur.com/sFy1nUl.png)

However, after hitting tab, the line becomes coloured with the default color:
![Completion prompt](https://i.imgur.com/5W4E4Sq.png)

It sometimes goes back to white after the completion and all is ok after I hit CTRL + C for a new line. Does anyone have any idea on what might be going wrong in here? I couldn't really find any info on how to control the colors on completion time.

**Comment by apjanke** [comment]
I don't think you can just leave an unclosed `%{$some_color%}` in your prompt to change your input text color because if other stuff uses a terminal control sequence to change the foreground color, they don't know to restore it to your special color instead of the default color.

Afraid I don't know the right answer to this, but if you want more info, you can look at the [Prompt Expansion section](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html) of the Zsh reference manual, and the [zsh-syntax-highlighting project](https://github.com/zsh-users/zsh-syntax-highlighting), which does stuff like this with coloring the user input instead of just the prompt. I'm afraid it might involve rebinding `zle` (Zsh Line Editor) widgets.

You can also use the more compact `%F{color}`/`%f` notation instead of `%{$fg_color[color]%}`/`%{$reset_color%}`. It's covered in that Prompt Expansion section.

**Comment by adraghici** [comment]
Yep, that's also what I though about leaving it unclosed. I couldn't find anything that would help solving this exact problem, in the end I just switched to a higher contrast default font.

**Comment by apjanke** [comment]
Hey, [look what I just saw](http://www.zsh.org/mla/workers/2015/msg01486.html) on the [zsh-workers mailing list](http://www.zsh.org/mla/workers/2015/msg01486.html). The `zle_highlight` variable lets you configure the command line text color without doing fancy widget configuration. Do this, and you'll get the colored user-input text you want, in a supported manner that doesn't mess with other color controls.

```
zle_highlight=( default:fg=white )
```

In addition to ANSI color names like `white`, you can also use a number from 1 to 255 if you are running a 256-color terminal (and `$TERM` is properly set to reflect that).

See [Character Highlighting](http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#Character-Highlighting) in the Zsh Line Editor section of the Zsh Reference Manual for details.

**Comment by adraghici** [comment]
Hey, this is great. I've already switched to another color scheme, but should help anyone who has this issue in the future. Thanks!
