### ISSUE TITLE
Git aliases broken with recent update to git plugin

### ISSUE THREAD

**Issue by danielbachhuber** [robbyrussell/oh-my-zsh#4068]
I just updated to 599831b85a5fd4564ab820530e2bb45f37ca3f99 and it broke my existing git aliases :( https://github.com/danielbachhuber/dotfiles/commit/69391606d6ceaa817ebd6d29511336594fff150f

Can I disable the aliases added by the git plugin

**Comment by ncanceill** [comment]
Hi, and thanks for reporting.

Can you be more precise on what is bothering you?

Is it the `gpu` alias? Does it conflict with something?

**Comment by danielbachhuber** [comment]
> Can you be more precise on what is bothering you?

`gpu` (https://github.com/robbyrussell/oh-my-zsh/blob/599831b85a5fd4564ab820530e2bb45f37ca3f99/plugins/git/git.plugin.zsh#L175) became aliased before my own `gpu` alias, so I had to `unalias gpu`.

**Comment by mcornella** [comment]
Regarding your configuration over at https://github.com/danielbachhuber/dotfiles/commit/69391606d6ceaa817ebd6d29511336594fff150f, you don't need the `unalias gpu` since you are redefining the `gpu` alias afterwards. Your problem was that you were sourcing the aliases file before omz, when it is necessary to do any user config afterwards. So, the relevant part in your commit was that you moved the sourcing, the `unalias gpu` was unnecessary. 

Given that, and that other people use the default `gpu` alias, we'll leave it there and you don't need to worry about it breaking your setup now.
