### ISSUE TITLE
Unable to use profiles plugin to extend plugin list

### ISSUE THREAD

**Issue by marknsikora** [robbyrussell/oh-my-zsh#4097]
As stated in the original pull request (#1573), you can't add more plugins to the plugin list with a profile. This strikes me as a useful feature to add. My use case is that I have oh my zsh on both my home and work computer. I have some custom plugins that I only need loaded on my work machines.

I'm going to look into how difficult adding this would be.

**Comment by apjanke** [comment]
Moderately difficult. Right now, there's just one `$plugins` list, and the plugins loading logic steps through it. To get what you want, I think we'd need to break that in to a few variables:

- `$plugins` is the list of requested plugins from the user or whatever, given at the start of OMZ initialization
- The plugin loading logic would copy that list to `$plugins_to_load` and load all the plugins in there, removing each plugin as it's loading it, and then *re-checking the list value after each plugin is loaded* to see if any more were added.
- A `$omz_plugins_loaded` list that holds all the plugins loaded successfully so far, to avoid double-loading plugins or dependency loops where plugins mutually request each other. And then at the end of OMZ initialization, this would reflect all the plugins which were actually loaded.

Then your profile could just do a `plugins_to_load+=some_plugin` to add a plugin to the list to be loaded.

The implementation in code isn't too hard, probably, but since this would become part of the public API for OMZ, some thought should be put in to the design for it. And it'd be part of the core OMZ stuff, so there's a higher bar for getting changes through.

**Comment by marknsikora** [comment]
That was more or less what I've come up with so far. I haven't been able to make something I'm happy with yet. The other idea I'm playing right right now is making profiles a default feature instead of plugin, but that seems to result in a lot of code duplication with the plugin loading.

**Comment by mcornella** [comment]
I don't think we're ever going to be able to implement this. The obvious solution is making a custom zshrc file that loads another file (`.zplugins` or something like that) that is different in each host.
