### ISSUE TITLE
Duplicates command on tab

### ISSUE THREAD

**Issue by Nixpower** [robbyrussell/oh-my-zsh#4107]
Hello, I appear to be having an issue with autocompletion when using oh-my-zsh, where if I type `ls` and press `Tab` it will place a few spaces after `ls` and type `ls` again. e.g.

    $ ls    ls
    LSCOLORS lsa lsblk lsinitcpio
and so on with the tab completion. When I backspace, I can only remove the *second* `ls`, and not the first. I have oh-my-zsh installed on many computers, and only this BeagleBone Black running ArchLinuxARM (through ssh) is having this issue. Not sure if it's caused by a package.

Thanks, 
nixpower

**Comment by apjanke** [comment]
Sounds like maybe a terminal configuration issue, where your terminal is getting confused about what column it's in. The "menu" completion that shows options below the command line needs to use terminal control sequences to move the cursor around, and looks like it's not working quite right.

It might be that it's just not erasing the command line before redrawing it. "ls with some spaces after it" sounds like "ls" and a literal tab character, and than it's redisplaying the command line *after* instead of on top of it once the completion runs.

It might be caused by a bad `terminfo` entry for the terminal you're using. These are generally in packages with names like "terminfo" or "ncurses". Or it could be a bad `$TERM` value.

I don't think we can tell what's going on without more info. What system are you ssh-ing in from: what OS and terminal emulator are you using there?

Run `omz_diagnostic_dump` from [this diagnistocs.zsh file](https://github.com/apjanke/oh-my-zsh-custom/blob/master/diagnostics.zsh) on that BeagleBone where it's not working right and post the output [as a gist](https://gist.github.com/). Tha willl give us all the config files and some of the relevant terminal configuration info, and we can help you debug this.

**Comment by Nixpower** [comment]
Thank you for the response, I was able to fix this by adding my `terminfo` to the remote machine, which wasn't supporting `rxvt-unicode-256color`. I did not think this was caused by the terminal because it was formatting correctly when I wasn't using `oh-my-zsh`.

**Comment by apjanke** [comment]
Cool.

Yeah, oh-my-zsh enables `menu_completion` and some other advanced `zsh` completion features by default, and these use more terminal capabilities. They're off by default in stock `zsh`. Probably why OMZ was what exposed it for you.
