### ISSUE TITLE
Inaccurate case-insensitive completion

### ISSUE THREAD

**Issue by wuyihao14** [robbyrussell/oh-my-zsh#4118]
When two candidates have the "identical" prefix (with case ignored) , for example:
**abc** and **ABd**
type A , press TAB
get Ab

---
I guess this is due to
https://github.com/robbyrussell/oh-my-zsh/blob/599831b85a5fd4564ab820530e2bb45f37ca3f99/lib/completion.zsh#L22
The matcher-list style adds case-insensitity candidates to the list.
I tried to give candidates with correct case, higher priority, by modifying line 22 to
`zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={a-zA-Z} m:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'`
It doesn't make any change

Or 
`zstyle ':completion:*:complete:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'`
If complete function find at least one candidate then case-insensitive matching won't be performed.

**Comment by apjanke** [comment]
I can't reproduce exactly. Using just oh-my-zsh and its default `.zshrc` file.

```
touch abc ABd
```

Typing the following "prefix" after `cat ` (a command that takes a file argument) and hitting tab gives me the corresponding partial completion.

Prefix | Completion
---------- | ----------------
A | AB
a | aB

I don't know if this can actually be changed; it may be normal `zsh` completion behavior. Since after you hit tab, it still only has a partial match, it doesn't necessarily know what case each of the characters is going to end up as. Once you have a complete match, it will correct the case of the characters.

Try this. Do `touch abcfoo ABdfoo`. Type `cat a` and hit tab. It'll complete to `aB`. Then type a `c` and hit tab. It will complete to `abcfoo`, with that `B` corrected to a lower-case `b`.

**Comment by wuyihao14** [comment]
OK, I agree, it do seems like normal completion behavior.
However when you try this:
`touch ABC abc`
`cat A` hit tab
It will complete to Abc and doesn't do correction.

This sounds like a rare case, but it was indeed this case made me noticed it. :smile:

**Comment by apjanke** [comment]
Ahhhh, I see.

So, in this case, when you do `cat A` tab, where does the cursor end up? For me, the cursor stays in the middle of the word, after `A`/"on" `b`. This is indicating it's still a partial match. If you keep hitting tab, it will then bring up a menu that shows both completions, and start cycling through them. When you select one, it will do the case correction.

This behavior is due to a combination of the `auto_menu`, `menu_complete`, and `always_to_end` options. I believe this is normal, expected behavior.

If you `setopt menucomplete`, then it will automatically pick the first option from the menu. This has the effect of presenting the case corrected word and bringing up the menu on the first press of tab, instead of waiting for additional tabs. Give that a try by doing `setopt menucomplete` either in your `.zshrc` *after* loading OMZ, or manually at the prompt, and see how it works for you.

(This completion stuff is pretty complicated.)

**Comment by wuyihao14** [comment]
Thank you so much, this works greatly for me. And helped me understand much more about zsh's completion.:smile:

**Comment by apjanke** [comment]
Excellent! This is a good learning experience for me too; I'm still figuring this out as I go. You're welcome!
