### ISSUE TITLE
open new tab in terminal became extremely slow on my Ubuntu desktop since .zshrc

### ISSUE THREAD

**Issue by guoqiao** [robbyrussell/oh-my-zsh#4119]
This happens since this week.

If I comment out this line in .zshrc:

```
source $ZSH/oh-my-zsh.sh
```

It will be back to normal.

I am not sure it's cause by zsh or some change on my desktop.

Any ideas?

**Comment by apjanke** [comment]
Was this week when you installed Oh My Zsh? Or have you been running it for a while?

**Comment by guoqiao** [comment]
Hi apjanke, I've been using oh-my-zsh on this ubuntu desktop for more than one month. Some how the tab became very slow. No one else has this issue?

**Comment by apjanke** [comment]
Hard to say without knowing more details. There are plenty of things that can cause slowness, and other people have run in to.

How slow is "extremely slow"? 

Is it just opening a new tab? Or is it every time a command prompt is issued?

Which terminal emulator are you using?

Common causes of slowness are often the Git or other VCS info included in the prompt in themes. If you're in a large repo, or one on a slow filesystem (like a network filesystem), they can be quite slow to run. Are the new tabs you're opening in your home directory? Or do they respect the current working directory of your session? Are you working in Git repos? What theme are you using?

What plugins are you using?

If you want, you can  run `omz_diagnostic_dump` from [this diagnostics.zsh file](https://github.com/apjanke/oh-my-zsh/blob/diagnostic-dump-function/lib/diagnostics.zsh) and post the results [as a gist](https://gist.github.com/). This will give us copies of all your `zsh`-related config files and shell state, which could help diagnose this.

**Comment by rkulla** [comment]
For me, plugins make it slower. While running no plugins, a new tab takes 1 second (still pretty slow in my opinion, since i have a very fast macbook pro where new browser tabs are instant). The `npm` plugin in particular adds another second to the load time for me.

Having `source /usr/local/bin/virtualenvwrapper.sh` in .zshrc also slowed it down an additional half-second. The rest of the slowness is caused by `source $ZSH/oh-my-zsh.sh`. If i take all 3 of those out, new tab creation is close enough to instantaneous where I'd like it to be.
