### ISSUE TITLE
compinit: _git not found on OS X 10.11

### ISSUE THREAD

**Issue by noisebai** [robbyrussell/oh-my-zsh#4127]
I want to fix the issue that "compdef: unknown command or service: git". 

I run rm -f ~/.zcompdump*; compinit, then it shown that 
compinit:496: no such file or directory: /usr/local/share/zsh/site-functions/_git

**Comment by apjanke** [comment]
We need some more info, and then we can help diagnose this.

Please run `omz_diagnostic_dump` from [this diagnostics.zsh file](https://github.com/apjanke/oh-my-zsh/blob/diagnostic-dump-function/lib/diagnostics.zsh) and post the results [as a gist](https://gist.github.com/).

**Comment by noisebai** [comment]
This is the output:
https://gist.github.com/f088bc6ab69b7bfa72a2.git

**Comment by noisebai** [comment]
The output:
https://gist.github.com/noisebai/f088bc6ab69b7bfa72a2

**Comment by apjanke** [comment]
Thanks.

Darwin 15? Are you running an El Capitan Beta or Developer Preview?

It's odd that you appear to be running the system `zsh` from `/usr/bin/zsh`, but `/usr/local/share/zsh/site-functions` is on the `$fpath`. Normally, `/usr/local` paths are from Homebrew `zsh` installations, and I don't see anything in your configuration files that would be adding it.

```
$fpath directories:
ls: /Users/baiziyi/.oh-my-zsh/completions: No such file or directory
ls: /Users/baiziyi/.oh-my-zsh/functions: No such file or directory
drwxr-xr-x    4 baiziyi  staff    136 Jul  4 23:14 /Users/baiziyi/.oh-my-zsh/plugins/git
drwxr-xr-x    4 baiziyi  admin    136 Oct 17  2014 /usr/local/share/zsh/site-functions
drwxr-xr-x  957 root     wheel  32538 Jun  8 22:23 /usr/share/zsh/5.0.8/functions
drwxr-xr-x    2 root     wheel     68 May 10 01:47 /usr/share/zsh/site-functions
```

Did this machine previously have a Homebrew `zsh` installed, possibly under an older version of the operating system? Is the `zsh` you're running the default one that came with the OS? Are you running Homebrew now?

I guess that the `/usr/local/share/zsh/site-functions` path that's messing you up is baked in to the `~/.zcompdump*` files. I'd recommend doing `rm ~/.zcompdump*` again, and then completely logging out of all your shell sessions, and then logging back in. (Instead of doing `compinit` in the same session.)

I hope this doesn't mean there's something odd with the `zsh` in El Capitan. I'll see if I can get my own preview copy to test, too.

The `/usr/local/share/zsh/site-functions/_git` file it's asking about is typically provided by the Homebrew `git` installation, and is for use with the Homebrew-provided `zsh`. But you don't need that if you're running Oh My Zsh; OMZ provides its own `git` completion with the `git` plugin.

**Comment by noisebai** [comment]
Yes, I am running an El Capitan Beta. When I have this issue then I uninstalled Oh My Zsh through `uninstall_oh_my_zsh`. And reinstall it `curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | ZSH=~/.dotfiles/zsh sh`. 

I checked my Homebrew list, I didn't install `zsh` by Homebrew. 

As you suggestion, after `rm ~/.zcompdump*` and logging back in: 
```
compinit:496: no such file or directory: /usr/local/share/zsh/site-functions/_git
compdef: unknown command or service: git
compdef: unknown command or service: git
```
and there is a new file:
```
-rw-r--r--   1 baiziyi  staff  37468 Jul  8 22:57 .zcompdump-Ziyi的MacBook Pro-5.0.8
```

**Comment by apjanke** [comment]
Well. I don't know what's going on here.

It's normal for that `.zcompdump` file to reappear; it's regenerated automatically by oh-my-zsh when it's loaded. But I don't know why it's still broken and why your `zsh` is still looking in that `/usr/local` directory. I don't see any obvious problems in that Gist output aside from that `$fpath`.

If I find time, I'll grab a copy of the El Capitan Beta myself and see if I can reproduce this. I don't have any other ideas.

**Comment by apjanke** [comment]
BTW, would you mind updating the title of this issue to something like "compinit: _git not found on OS X 10.11", to distinguish this from the other `compinit`-related issues that have been posted?

**Comment by apjanke** [comment]
One more thing to check: that `/usr/local` site-functions dir does exist. What happens if you remove it (by renaming it to `site-functions-OFF` or similar) and then `rm ~/.zcompdump*` and then launch a new `zsh` session?

```
drwxr-xr-x    4 baiziyi  admin    136 Oct 17  2014 /usr/local/share/zsh/site-functions
```

**Comment by tamamadesu** [comment]
same question and the /usr/local/share/zsh/site-functions/_git   is empty !

**Comment by tamamadesu** [comment]
@noisebai  I add the 'gitfast' plugins  on my .zshrc file, and source ~/.zshrc  ,  solve it !

**Comment by noisebai** [comment]
@tamamadesu It works for me too! Thank you so much!

**Comment by apjanke** [comment]
I put together a test box running the OS X 10.11 public beta, updated as of today (7/21/2015). I'm unable to reproduce this on 10.11 in the default setup. My test box is a fresh install of OS X 10.9 which was then upgraded to 10.11.

When you say the file is empty, you mean that it is present but is 0 bytes long? Is the file a symlink, and if so, what is it pointing to?

The `/usr/local/share` directory doesn't exist by default on OS X 10.11.  It seems likely that that `_git` file on your system was leftover from an installation of a previous piece of software. The current Homebrew `git` formula provides that file, so it's a likely candidate.

I was able to reproduce this error by installing the Homebrew `git` on 10.11 with `brew install git` and then breaking it by doing `cd /usr/local/Cellar/git/2.4.6/share/zsh/site-functions; mv _git _git-OFF`. After `rm ~/.zcompdump*`, I get this error upon starting a new `zsh` session.

```
compinit:496: no such file or directory: /usr/local/share/zsh/site-functions/_git
```

This breakage would not have happened on 10.10 or prior versions of OS X because `/usr/local/share/zsh/site-functions` is not in `$fpath` by default in the system `zsh` in earlier versions of OS X. (This change is probably related to the new "rootless" [System Integrity Feature](http://arstechnica.com/apple/2015/06/preview-os-x-el-capitans-first-beta-is-a-promising-heap-of-refinements/4/#h1) which locks down `/usr/share`.)

It seems likely that this file was just left over from a broken previous installation of Homebrew git or another program that supplied it, and upgrading to 10.11 exposed the error due to the change in `$fpath`.

If that's the case, you could fix it by doing either of:
* Repair the installation of the program that supplied that `/usr/local/share/zsh/site-functions/_git` file
* Delete the broken `/usr/local/share/zsh/site-functions/_git` file

Loading the `gitfast` plugin will take care of it because `gitfast` contains a `_git` file, too, which will be ahead of the broken one on the path. But this will only work if you are running Oh My Zsh and using that plugin. Other `zsh` sessions which run `compinit` would still be affected.

**Comment by billhsu** [comment]
I have the same problem after upgrading to El Capitan.

I'm seeing the below error message when opening a new terminal window.
```
Last login: Sun Oct 11 14:04:50 on console
compdef: unknown command or service: git
compdef: unknown command or service: git
```

**Comment by alirz23** [comment]
Just add 'gitfast' plugin to your .zshrc 

your plugins directive should like following
`plugins=(git gitfast)`

**Comment by apjanke** [comment]
Anyone know why adding the `gitfast` plugin fixes this?

AFAIK, it's a design principle of OMZ that plugins should not depend on other plugins. And loading `gitfast` has not been a requirement in the past.

**Comment by ZacksTsang** [comment]
@apjanke 
> One more thing to check: that /usr/local site-functions dir does exist. What happens if you remove it (by renaming it to site-functions-OFF or similar) and then rm ~/.zcompdump* and then launch a new zsh session?

this help me, thanks!

**Comment by yaonphy** [comment]
@apjanke It works to me,thanks.

**Comment by nyxchung** [comment]
@apjanke It works to me, too...!! So much thanks.

**Comment by zfdang** [comment]
@alirz23  this works in OSX 10.11. thanks

**Comment by mcornella** [comment]
If I understood correctly this same issue was solved by installing homebrew's git without completions. See https://github.com/robbyrussell/oh-my-zsh/issues/1727#issuecomment-22366771.

**Comment by kareypowell** [comment]
Adding `gitfast` to my list of plugins in the .zshrc file worked for me.

**Comment by apjanke** [comment]
Is this still breaking for people? I'm no longer able to reproduce it at all on my non-beta OS X 10.11.1 box. (This one was set up as a clean install, not an upgrade from 10.9. The problem may be specific to the upgrade process.)

**Comment by topikito** [comment]
Just for the record - adding `gitfast` fixed this issue for me too

**Comment by snowleung** [comment]
@allyraza works! thank you

**Comment by apjanke** [comment]
For future reference: the addition of `/usr/local/.../site-functions` to the default `$fpath` was a change in zsh 5.0.7 itself, not necessarily an Apple customization. It's mentioned in the [zsh release notes](http://zsh.sourceforge.net/releases.html).
