### ISSUE TITLE
git plugin: "fork failed: resource temporarily unavailable"

### ISSUE THREAD

**Issue by jamesmartinduffy** [robbyrussell/oh-my-zsh#4142]
Potentially related to: https://github.com/robbyrussell/oh-my-zsh/issues/1898 and https://github.com/robbyrussell/oh-my-zsh/issues/1509

Recently after updating oh-my-zsh when prompted, I found when I spawned a new terminal window, it spit out an endless amount of: `git:1: fork failed: resource temporarily unavailable` and I saw a bunch of zsh processes spawned in activity monitor on Mac.

After a lot of experimentation, removing `git` from my plugins in .zshrc seems to fix the problem.

Any idea if this is a problem with the git plugin or something about my personal setup? What can I do to troubleshoot this so I can continue using the git plugin?

**Comment by apjanke** [comment]
With those other issues, this turned out to be a fork bomb due to individual users' configurations. And this does sound like a similar problem. I don't know anything in the `git` plugin itself that would cause this – it doesn't launch anything when it's loading, much less run `zsh` recursively. So it might be setup-related.

Could we get a snapshot of all your `zsh`-related config files to help debug this? Please run `omz_diagnostic_dump` from [this diagnostics.zsh file](https://github.com/apjanke/oh-my-zsh/blob/diagnostic-dump-function/lib/diagnostics.zsh) and post the results [as a gist](https://gist.github.com/). That'll give us a detailed look at your `zsh` configuration and state.

**Comment by apjanke** [comment]
Any updates? Is this still happening for you?

**Comment by jamesmartinduffy** [comment]
Hi, you can close this if no one else is having the issue and it's specific to my config. I don't have time to troubleshoot the issue, so I just disabled the git plugin.

**Comment by apjanke** [comment]
Cool. Haven't heard of anyone else having it, though I did see someone with a recursive `ssh` fork bomb due to a couple unfortunate alias definitions.

As the reporter, only you and the repo owner have permissions to close this issue. There should be a "Close" button below the comment field for you.

**Comment by allanrsmith** [comment]
hitting it today now.
