### ISSUE TITLE
Atom plugin: problems with Linux and Windows

### ISSUE THREAD

**Issue by ThibaudDauce** [robbyrussell/oh-my-zsh#4144]
The atom plugin doesn't work with Linux (and probably Windows too).

The paths are not good for Linux so the at alias is never defined. Moreover, `open` is not installed in my computer, I think it's a OSX software.

Best,

**Comment by apjanke** [comment]
Yeah. `open` is an OS X command, and those are OS X only paths.

The name `at` is already a standard Unix and Windows command, too. Maybe this should use the name `atom` instead, to avoid collisions?

CC @aforty, as the plugin's original author.

At the code level, `local` does not work at the top level of plugins, because they are not necessarily loaded from within a function call. (That's why the `>/dev/null` redirect is there.) To get `local` to actually make local variables, the plugin code needs to be wrapped in an anonymous function or other function call.

**Comment by robobenklein** [comment]
Figured it's better to overwrite `at` with a working command than a broken one, so Linux support fixed in https://github.com/robbyrussell/oh-my-zsh/pull/4342

**Comment by mcornella** [comment]
Please close this, it was fixed in #4342.
