### ISSUE TITLE
safe-paste is too unsafe for vim

### ISSUE THREAD

**Issue by a-x-** [robbyrussell/oh-my-zsh#4157]
The plugin even in :insert vim mode make nightmare in vim...

**Comment by apjanke** [comment]
Can you elaborate, or provide concrete examples of what would break? Based on a quick reading of the code, I don't see any obvious major vi mode breakage. Have you run in to problems with it while using vi mode?

The main incompatibility with vi mode seems to be that it [unconditionally switches back to the emacs keymap after pasting is finished](https://github.com/robbyrussell/oh-my-zsh/blob/f2b915c56741c846e845b037e9fdeb7c3f063bc3/plugins/safe-paste/safe-paste.plugin.zsh#L33-L35) instead of switching back to whatever keymap you were using. So it will kick you out of vi mode the first time you use a paste.

Another issue is that it detects whether paste mode is supported by checking against a small list of `$TERM` values, including `xterm`. But tons of emulator programs claim to be `xterm`, and may not necessarily support bracketed paste mode, which is what this plugin relies on. So this could cause problems, but would apply to both vi and emacs mode.

**Comment by apjanke** [comment]
Oh, wait – it looks like it also [clobbers the zle-line-init/zle-line-finish bindings](https://github.com/robbyrussell/oh-my-zsh/blob/f2b915c56741c846e845b037e9fdeb7c3f063bc3/plugins/safe-paste/safe-paste.plugin.zsh#L20-L21) that are normally made by `lib/key-bindings.zsh` or the `vi-mode` plugin. That might cause issues.

**Comment by a-x-** [comment]
it's like true. i not use vi-mode, but lib/key-bindings.zsh is good clobber candidate...

**Comment by a-x-** [comment]
i install bracket-mode plugin in vim and
it fix the problem...

**Comment by apjanke** [comment]
What was the problem you were having? That plugin looks like it does the same thing as `safe-paste`, but in `vim` itself instead of `zsh`'s vi mode command line editing. Was loading the `safe-paste` plugin causing `vim` to misbehave for you?

**Comment by mcornella** [comment]
This needs further investigation but we have this tracked in #4344, so I'm closing this one.
