### ISSUE TITLE
Possible to organize plugins as available and enabled?

### ISSUE THREAD

**Issue by kamalx** [robbyrussell/oh-my-zsh#4168]
I really like how https://github.com/Bash-it/bash-it does it. 

They've `available` and `enabled` directories for each of `plugins`, `aliases` and `completion` that makes it super easy to symlink anything when required into the `enabled` directory and just as easily remove it when not required while it safely sits in the `available` directory.

**Comment by apjanke** [comment]
What would be the advantage of doing it this way? Oh My Zsh's `$plugins` variable lets you select which plugins are loaded at run time. That seems to be the equivalent of `bash-it`'s "enabled" functionality, but without making changes to the filesystem. 

Th `$plugins` way lets different `zsh` sessions load different sets of plugins, based on user request or dynamic selection criteria. For example, you could have your `~/.zshrc` synced across different machines, and only load some plugins on certain OSes, or if certain programs are installed. Or launch different sessions with different plugins for debugging them.

**Comment by kamalx** [comment]
@apjanke I was thinking along the lines of how easy it is to place the config line at any arbitrary location 
`plugins=(xyz abc)` in any of the config files and mess things up... while the `available|enabled` system seems to be very explicit and easy to find/understand.

**Comment by kamalx** [comment]
I am just trying to understand the relative pros and cons of the two methods...

> `$plugins` way lets different zsh sessions load different sets of plugins, based on user request or dynamic selection criteria

That is something I am not sure the `available | enabled` directory structure could achieve. 

> you could have your ~/.zshrc synced across different machines, and only load some plugins on certain OSes

Wouldn't this work the same way if the only plugins that loaded are the ones present in the `enabled` directory which could be different on each of the machines?

> or if certain programs are installed. Or launch different sessions with different plugins for debugging them.

However, it does make a lot of sense for the above two use-cases to use the `$plugins` way. I wasn't aware how different sessions with different plugins could be launched. Looks like I need to read up a little. :)

Thanks for taking the time to explain.

**Comment by apjanke** [comment]
No problem.

I don't understand why bash-it uses the symlinks method; I don't see any advantages too it.

The symlinks method seems like the rc.d architecture for startup files on Unix systems, where each startup service has its own file to launch it, and these are sometimes managed by symlinks. A big advantage of this system is that it makes program installation and package management easier: you can add or remove startup items by adding or deleting things on a per-file basis. This means the startup hooks can be included as normal files in the package, permissions can be controlled on a fine-grained basis (since filesystem permissions work at the file level), different programs are isolated from each other, and after installation, you can attribute a startup item back to the package it came from. Modifying the contents of a shared config file would be harder to do programmatically, and not possible to control access to with filesystem permissions. This makes it easier and safer to install multiple programs on a system.

I don't see how those advantages apply to bash-it, since it's a single "application" and the plugin enabling is driven by the same user.



>> you could have your ~/.zshrc synced across different machines, and only load some plugins on certain OSes
>
> Wouldn't this work the same way if the only plugins that loaded are the ones present in the enabled directory which could be different on each of the machines?

Kind of. But this a) assumes that you have a different home directory on each system, and b) you need to set up the appropriate symlinks on each system. With the `$plugins` way, you can write some OS-detection logic in one place in your config file, and reuse that.

> However, it does make a lot of sense for the above two use-cases to use the $plugins way. I wasn't aware how different sessions with different plugins could be launched. Looks like I need to read up a little. :)

There's not great support for it right now in base OMZ; I end up tweaking my `~/.zshrc` file to switch between plugin sets, or write a little bit of logic to control the plugins list internally. (E.g. in `.zshrc`, check for a `$PLUGINS` that's already defined, and if so, use that instead of the `plugins=(...)` line in `.zshrc` itself.) With that, you can do `PLUGINS=git,osx,rvm,whatever zsh -l` to launch a new session with those plugins loaded. But regardless of the current support for it, the `$plugins` way makes this doable; using symlinks on the filesystem would make it difficult and brittle.

**Comment by kamalx** [comment]
Thanks for the explanation, @apjanke. It sure seems advantageous to do it with the `plugins` variable. I never thought about or needed the use-case of launching different sessions with different set of plugins loaded.
