### ISSUE TITLE
Error -- "(eval):1: command not found: You..."

### ISSUE THREAD

**Issue by kamalx** [robbyrussell/oh-my-zsh#4169]
Similar to #2092 here, I am getting an error message that says 
```
(eval):1: command not found: You
(eval):2: command not found: You
``` 
every time I open a new terminal or tab or every time I run `source ~/.zshrc`. I've searched everything from `.zshrc` to my custom files inside the `~/.oh-my-zsh/` folder but could not find any instance of `eval` or a stray uncommented `You` anywhere. 

I don't exactly remember when this started, but as a vague hint, this could have been ever since I installed rvm and ruby on the machine (I can never be sure). All my terminal sessions load ruby 2.2.1 environment by default -- if that means anything -- ever since I installed rvm.

Any help in diagnosing this and making my terminal sessions start without those two ugly lines would be greatly appreciated. Thanks!

**EDIT / UPDATE**

* Restoring the `.zshrc` to a file with just the following line in it

  ```
  PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
  ```
  removes the error messages I mentioned; but I really want to use oh-my-zsh; so I still need help. :)

* `source`ing the theme separately in this new blank `.zshrc` file works for me, along with (and after) `source`ing the   `~/.oh-my-zsh/lib/prompt_info_functions.zsh`. ~~Not all themes would work that way though~~ other themes probably may require other dependencies to be sourced before them -- I am using `half-life` theme. 

* I still have no solution to the above mystery error messages.

**Comment by apjanke** [comment]
Hmmm. Maybe coming from one of the plugins, caused by an interaction with your configuration. Or maybe something else is messed up.

Have you tried deleting the zcompdump files like they did in 2092? Try that.

If that doesn't work, let's get a full config dump for your system to use for debugging this. Please run `omz_diagnostic_dump` from [this diagnostics.zsh file](https://github.com/apjanke/oh-my-zsh/blob/diagnostic-dump-function/lib/diagnostics.zsh) and post the results [as a gist](https://gist.github.com/).

**Comment by kamalx** [comment]
Thanks for your time and help, @apjanke !

> Have you tried deleting the zcompdump files like they did in 2092? 

Yes. I removed that file (there was only one on my system), but it gets recreated on next session launch, and the issue persists. 

Here's the [output of `omz_diagnostic_dump` in a gist](https://gist.github.com/kamalx/24fae1f64059a7acdc6a). That's clever and awesome. :)

Thanks!

**Comment by apjanke** [comment]
Why thank you!

Okay. It's normal for that zcompdump file to get recreated: that's done as part of OMZ startup. Deleting it and letting it get recreated would have taken care of one that had just gotten corrupted. The problem persisting means there's some other underlying issue that we need to track down.

I don't see anything obvious in the files in the diagnostic dump. You do have a few custom files that it didn't pick up. And there's that RVM script too, which could be interacting with things, especially if you remember this starting around when you installed RVM.

Could you add the following files to that gist?

```
~/.oh-my-zsh/custom/aliases.zsh
~/.oh-my-zsh/custom/history.zsh
~/.oh-my-zsh/custom/workspaces.zsh
~/.rvm/scripts/rvm
```

**Comment by kamalx** [comment]
@apjanke Thanks! I've updated [the gist](https://gist.github.com/kamalx/24fae1f64059a7acdc6a) with the files you mentioned above.

**Comment by apjanke** [comment]
Well, I don't think I see anything there, either. Let's haul out the big guns: Run `zsh -lvx | tee zsh-debug-out.txt` and once it's loaded, just do `exit`. The `-x` enables tracing, `-v` turns on verbose command echoing, and `-l` makes it a login shell so all your normal config files are sourced. That will give you a debugging trace of `zsh`'s startup so you can see what context those error messages are coming from and what command produced them.

If that doesn't make it obvious where it's coming from, post the `zsh-debug-out.txt` output (after redacting, as it will include your config file contents), or at least a few hundred lines before and after those `eval` errors appear.

**Comment by kamalx** [comment]
Awesome! Thanks a ton for all the help. I found the offending line finally with this big gun. :dancers: 

Strangely, `zsh -lvx | tee zsh-debut-out.txt` gives me a binary file named `zsh-debut-out.txt` so I had to increase the number of scrollback lines in iTerm's preferences to get some useful log. 

This in my `.zshrc` was the one causing those error messages: 

```
eval "`pip completion --zsh`"
```

Relevant lines from the trace log show where the two `You`s are coming from:

```
# pip magic from
# http://pip.readthedocs.org/en/latest/user_guide.html#configuration
eval "`pip completion --zsh`"
+.zshrc:22> pip completion --zsh
+.zshrc:22> eval 'You are using pip version 6.0.6, however version 7.1.0 is available.
You should consider upgrading via the '\''pip install --upgrade pip'\'' command.

# pip zsh completion start
function _pip_completion {
  local words cword
  read -Ac words
  read -cn cword
  reply=( $( COMP_WORDS="$words[*]" \
             COMP_CWORD=$(( cword-1 )) \
             PIP_AUTO_COMPLETE=1 $words[1] ) )
}
```

Funny, how I totally overlooked that `eval` in the main `.zshrc` file itself. 

Thanks again! My issue is fixed. I need to figure how to get pip completion without those errors popping up again -- perhaps for now, I'll run `pip install --upgrade pip` as it suggests.

**Comment by kamalx** [comment]
Actually, I think doing that `eval` there is not such a good idea after all. Perhaps a better way is to 
```
pip completion --zsh > pip-completion.zsh
```
and source that file in the `.zshrc`... That gives one the opportunity to inspect what's going on in the  output of that command. Just pondering.

**Comment by apjanke** [comment]
Excellent.

Oh my gosh, we're both blind: I totally overlooked that `eval` too, and it's sitting right there.

Weird. Could you still open that binary `.txt` file in an editor? Because of all the wonky special characters involved, zsh logs and stuff (e.g. just the output of `set`) can get misdetected as binary files, but still work okay in many text editors.

I'd call that a bug in `pip completion`, or at least their documentation.  If they're telling you to `eval` it, they should make sure the results are `eval`-clean in all conditions. You should report that upstream to the `pip` maintainers. (IMHO the right thing for them to do would probably be to put that warning message on stderr instead of stdout, and provide an option to suppress the update check entirely if they don't already.)

Yeah, your approach of just running `pip completion` once and keeping it in a static `pip-completion.zsh` file that you source sounds good to me. That's what I'd do. Like you say, you'll be able to inspect it and then have known-good code. The `pip completion` output doesn't seem to depend on run time stuff, so it should work. And it'll give you a slightly faster startup, too: you won't incur the overhead of running the external `pip` program, and that upgrade check is probably doing a network connection to check for the latest version, which is costing you a bit of time.

You could also try using the Oh My Zsh `pip` plugin instead. It appears to have pretty rich completion support.

**Comment by kamalx** [comment]
> Could you still open that binary .txt file in an editor?

Yes, I could. But there was nothing useful in there. 

Here are contents of the file: 
```
~^G1;~^G2;source .zshrc^G1;source^G2;kamal@Dabba: ~^G1;~^G2;kamal@Dabba: ~
^G1;~^G2;source .zshrc^G1;source^G2;source .zshrc^G1;source^G2;kamal@Dabba: ~^G1;~^G2;kamal@Dabba: ~^G1;~^G2;kamal@Dabba: ~^G1;~^G
```
It seemed to have logged only the `source` commands that I invoked a couple of times instead of opening new terminal each time. It was some similar garbled text last time as well, slightly different from this. 

> a bug in pip completion, or at least their documentation

This should, indeed, be reported upstream. I'll do that. 

> You could also try using the Oh My Zsh pip plugin instead. It appears to have pretty rich completion support.

Of course! I got lazy with the seemingly quick and easy trick I found on pip docs. :)

**Comment by apjanke** [comment]
Oops! That was my fault with the bad debug file. The trace output is on `stderr`, so it should have been `zsh -lvx 2>&1 | tee zsh-debug-out.txt` or `zsh -lvx 2>zsh-debug-out.txt`. The file will still be detected as binary, but will have useful contents. Sorry about that. Will try to remember that for next time.

Sounds like this is taken care of. If this is fixed for you, could you Close this issue? (Only you and the repo owner have permissions to do so.)

**Comment by kamalx** [comment]
Awesome, thanks for the corrected format. This issue has been quite educational for me. ;)

I can confirm that both `zsh -lvx 2>&1 | tee zsh-debug-out.txt` and `zsh -lvx 2>zsh-debug-out.txt` worked as advertised and the output file is readable as plain text in my case. 

This fixes my issue, so, closing now. 

Thanks for all your help, Andrew Janke!

**Comment by apjanke** [comment]
You're welcome! Glad we could figure this out.
