### ISSUE TITLE
Vim suspended (tty output) problem

### ISSUE THREAD

**Issue by eduOS** [robbyrussell/oh-my-zsh#4174]
Since I installed oh-my-zsh the vim has failed. Every time I use the editor it just says `suspended (tty output) vim` and brings me back to the command line. 

I thought this issue is not that normal, and the only similar question raised on [StackExchange](http://superuser.com/questions/575305/can-not-bring-a-background-running-vim-to-foreground) two years ago has not been answered satisfactorily. 

What's confusing is that when I go back to bash and run vim it also stops and creates a .swp file at the same time. The root user has no such a problem.

I thought it must results from oh-my-zsh, because it recovers just after I uninstall oh-my-zsh. :disappointed:  and the original zsh functions well with vim. I reinstall it manually and the same problem just occurs again. 

Can you please tell me how can I just make it work?

**Comment by apjanke** [comment]
Strange. This behavior sounds like `vim` runs, but then suspends itself. I wonder if this is due to an interaction between your vim configuration (in `.vimrc`) and Oh My Zsh. Or perhaps and odd key binding or terminal configuration thing that's causing `vim` to receive a Ctrl-Z when it shouldn't.

It's supposed to "just work" without extra setup on your part. Something is going wrong.

Are you running any vim plugins or extensions? I can see one similar-sounding issue at zaiste/vimified#89.

I don't think we've seen this one before. We're going to need some details to debug it. With Oh My Zsh installed, could you run `omz_diagnostic_dump` from [this diagnostics.zsh file](https://github.com/apjanke/oh-my-zsh/blob/diagnostic-dump-function/lib/diagnostics.zsh) and post the results [as a gist](https://gist.github.com/)? And then add your `~/.vimrc` file to the gist, so we can see how they might be interacting?

**Comment by eduOS** [comment]
Here is the result:
```
leo@ubuntu:~/.oh-my-zsh/lib$ source diagnostics.zsh; omz_diagnostic_dump
bash: diagnostics.zsh: line 269: syntax error near unexpected token `('
bash: diagnostics.zsh: line 269: `  version_files=( /etc/*-release(N) /etc/*-version(N) /etc/*_version(N) )'
bash: diagnostics.zsh: line 275: syntax error near unexpected token `}'
bash: diagnostics.zsh: line 275: `}'
emulate: command not found
Generating diagnostic dump; please be patient...
bash: builtin: zparseopts: not a shell builtin
bash: omz_diagdump_20150721-194536.txt: Permission denied
omz_diagnostic_dump: error while creating diagnostic dump; see omz_diagdump_20150721-194536.txt for details

Diagnostic dump file created at: omz_diagdump_20150721-194536.txt

To share this with OMZ developers, post it as a gist on GitHub
at https://gist.github.com and share the link to the gist.

WARNING: This dump file contains all your zsh and omz configuration files,
so don't share it publicly if there's sensitive information in them.
```

And the repo [link](https://github.com/eduOS/vimrc/blob/master/vimrc) of my .vimrc.

**Comment by apjanke** [comment]
That diagnostics function needs to be run in `zsh`, with oh-my-zsh installed, and not in `bash`.

**Comment by eduOS** [comment]
@apjanke Sorry for the mistake I made. I've updated the results.

**Comment by apjanke** [comment]
That's interesting. I don't know why it would have run twice in a row when you ran it as root.

When running it as a normal user, there's no need for `sudo`. Just run the function while in a directory that you have write permission for. It needs to be run as the normal user that's having the problem with `vim`; when run as root like this, it's picking up some of the wrong config files.

**Comment by eduOS** [comment]
@apjanke [Here](https://gist.github.com/eduOS/2acbfc56138be43b2908) is the record.

**Comment by eduOS** [comment]
@apjanke Luckily it runs very well now after changing the mode of that .oh-my-zsh. I thougth the normal user just cannot gain the permission when running the .oh-my-zsh.

**Comment by apjanke** [comment]
Thanks. That's a good diagnostic dump.

I've read through the dump, and I don't see anything that would be causing the `vim` suspension issue itself. But I do see a couple possibly problematic things going on.

####  umask

One unrelated issue: your umask is 002 instead of 022, and some of the dirs on your fpath are "insecure" in zsh's view.

```
compaudit output:
There are insecure directories:
/home/leo/.oh-my-zsh/plugins/git
/home/leo/.oh-my-zsh/plugins
/home/leo/.oh-my-zsh
/home/leo/.oh-my-zsh
```

You should consider switching your umask to `022` if you don't have a specific reason for `002`, and `chmod -R g-w ~/.oh-my-zsh; rm ~/.zcompdump*` to fix up your completion configuration. Bad completion stuff can cause strange behavior. But that's probably not what's causing your vim problems.

(I can't tell from the dumped config files where the `umask 002` is getting set. `022` is the default for most systems I'm familiar with.) 

####  Local modified files

Another possibly related issue: `git` sees a whole bunch of your OMZ files as locally modified. (Under the "oh-my-zsh git state" section.) That's not normal. I don't know if it's significant, but if this is the case, we can't tell if you're running the current OMZ files, and you won't be picking up updates.

I think you should reset the git state of your `~/.oh-my-zsh` directory, or just delete it and re-install OMZ to get back in a known-good state.

####  Other stuff

Looks like you're running `screen`. I don't know `screen` very well; maybe there are some startup files for it that may be interacting.

###   Next steps

How about you take care of the umask and the locally modified files? Without that, we can't really tell if you're running the same code in the repo and a non-corrupt completion setup.

After that, if the issue persists, I will try to configure one of my Ubuntu 14 testing VMs to reproduce your problem. It looks like you have a pretty stock setup, so I'd think I *should* be able to match it.

I'll also see about adding `/etc/commonprofile` to the diagnostic dump function.

**Comment by eduOS** [comment]
Sorry, it turns out to be the same after rebooting the system. :cry: :crying_cat_face:

**Comment by eduOS** [comment]
As Tim Pope said the issue results from a setting `:set shellcmdflag=-ic`. After I comment that out from .vimrc all relevant problems have been solved.

**Comment by apjanke** [comment]
Excellent.

If this is fixed now, could you close this issue? Only you and the repo owner have permissions to do so.

**Comment by eduOS** [comment]
@apjanke Thanks for your help!
