### ISSUE TITLE
Installer fails on cygwin with git not installed error

### ISSUE THREAD

**Issue by TheLaxtSamurai** [robbyrussell/oh-my-zsh#4180]
I installed cygwin, 2.0.3. I added git during cygwin installation. When I try to install oh-my-zsh using the CURL command I get the error below.
![image](https://cloud.githubusercontent.com/assets/662128/8831443/e8f0ea26-3067-11e5-9696-c5fc0157f474.png)

**Comment by apjanke** [comment]
The actual `git` error is earlier in the message where it says `Too many arguments`. The "git not installed" is a spurious error from the installer [where it assumes the only reason a git call would fail is if git was not installed](https://github.com/robbyrussell/oh-my-zsh/blob/a207a38d634cc10441636bc4359cd8a18c502dea/tools/install.sh#L13-L16). PR #3646 improves the error reporting here.

This looks like it's because you have spaces in your username ("Federico V Garcia"), and thus spaces in your home directory, and the installer script [is not quoting `$ZSH` to protect against spaces](https://github.com/robbyrussell/oh-my-zsh/blob/a207a38d634cc10441636bc4359cd8a18c502dea/tools/install.sh#L13).

The installer script should probably be fixed to deal with spaces in the path.

In the mean time, as a workaround, you can install OMZ manually by doing this:

```
cd
git clone https://github.com/robbyrussell/oh-my-zsh.git .oh-my-zsh
```

And then editing your `~/.zshrc` to include these lines near the top:

```
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)

# User configuration
export PATH=$HOME/bin:/usr/local/bin:$PATH

source $ZSH/oh-my-zsh.sh
```

However, there are probably lots of other places (both in Oh My Zsh and in other software) that are not going to be able to handle a home directory path with spaces in it, and you'll have breakage elsewhere too. I would recommend changing your username to one without spaces in it.

**Comment by TheLaxtSamurai** [comment]
Thanks for your response. I did change the name of the user and it worked.

In order to do that I had to:
1. Create a passwd file which does not exist in current version of cygwin.
```
mkpasswd -l >/etc/passwd
```
2. Change the name of the user and home directory in `/etc/passwd`
3. Close cygwin
4. In Windows, rename my home folder within cygwin installation folder, `C:\cygwin64\home`, to match the new user entered in step 2. 
5. Start cygwin
6. Install OMZ
