### ISSUE TITLE
ZSH_THEME random issue on themes w/ RVM prompt

### ISSUE THREAD

**Issue by shinriyo** [robbyrussell/oh-my-zsh#4182]
I wrote `ZSH_THEME="random"` in `~/.zshrc`

sometimes happens the error like below
`
zsh: no such file or directory: /Users/username/.rvm/bin/rvm-prompt
`

**Comment by apjanke** [comment]
This happens when it selects a theme that depends on RVM prompt support but doesn't check for it being installed, so it gets called unconditionally.

Looks like the following themes do this. (Checked by doing `grep bin/rvm-prompt *` in `$ZSH/themes` and examining manually for existence tests.)

3den
eastwood
peepcode
suvash
wedisagree

These themes should be fixed by changing them to use the `rvm_prompt_info()` function (from `lib/prompt_info_functions`) instead of calling rvm-prompt directly, or at least checking for the presence of `rvm-prompt` before including it in the prompt strings.

Relatedly, the macovsky and macovsky-ruby themes appears to not set `$PROMPT` if neither `~/.rvm/bin/rvm-prompt` or `rbenv` are installed. (These themes also appear to be duplicates of each other.)

**Comment by apjanke** [comment]
Could you update the issue title to be more specific, including that it's related to "`rvm-prompt` not found" errors?

**Comment by louisgv** [comment]
This is still an issue :(

**Comment by sandroeiler** [comment]
Is there an easy way for noobs to fix it manually?
I didn't find a solution here nor on stackoverflow.

**Comment by ilhamdoanggg** [comment]
still error for me

![screenshot from 2017-07-22 00 50 03](https://user-images.githubusercontent.com/9218660/28475767-c94c690c-6e77-11e7-92d1-ad60c520eccb.png)

**Comment by vrkansagara** [comment]
Just go to `https://rvm.io/` and install the package.

**Comment by ziyan-junaideen** [comment]
If you are like me an installed Ubuntu RVM the bin dir will be in `/usr/share/rvm` then doing the following will take away your pain.

    ln -s /usr/share/rvm/bin ~/.rvm/bin

**Comment by bradystone** [comment]
I see this is an older thread but I switched to the jonathan theme today and it came up. Then it displayed for all themes after...  I am current on zsh updates.  I ran the two commands below, and added a snippet to .zshrc and it is fixed.

$ rm -rf ~/.rvm
$ curl -L https://get.rvm.io | bash -s stable

Added this to my .zshrc
# FIX RVM_PROMPT
source ~/.rvm/scripts/rvm
