### ISSUE TITLE
Promption seems broken when input apm ~/<tab>

### ISSUE THREAD

**Issue by LeoYuan** [robbyrussell/oh-my-zsh#4187]
## bug description
if you input `apm`, then you will find the zsh promption is broken, have no idea why.

try this:
```sh
$ apm ~/
```
tab will prompt nothing~

**Comment by apjanke** [comment]
This sounds like it is an issue with the completion definitions for `apm`, and not with Oh My Zsh. What OS are you on? Does it happen for any commands besides `apm`?

I can reproduce the same behavior on OS X 10.9.5. Arguments to `apm` will not get tab-completed. But only for the `apm` command. Which sounds specific to its completer, typically `_apm()`.

You can locate the source of the `_apm` autocompletion definition using `find`. I get this.

```
➜  ~  find $fpath -name _apm
find: /Users/janke/.oh-my-zsh/functions: No such file or directory
find: /Users/janke/.oh-my-zsh/completions: No such file or directory
/usr/share/zsh/5.0.2/functions/_apm
```

That's not part of OMZ. Since it's in the regular `functions` directory instead of `site-functions`, that means it probably shipped with `zsh` itself.

```
➜  ~  grep OSTYPE /usr/share/zsh/5.0.2/functions/_apm
if [[ $OSTYPE == linux* ]]; then
elif [[ $OSTYPE == (freebsd|dragonfly)* ]]; then
elif [[ $OSTYPE == openbsd* ]]; then
```

That looks like why it's broken for me. There's no case for `darwin*`, so when it's invoked on OS X, there's no clause it matches, and no default "`else`" clause, so no argument definitions get set up.

From reading that completion definition, it looks like the `apm` name is used by different commands, or at least very different flavors of a command, on different systems, and these have to do with Advanced Power Management. The [Atom text editor](https://atom.io) has also chosen to use `apm` as the name of their Atom Package Manager program. That's what `apm` is on my OS X system, since I have Atom installed, and OS X doesn't seem to ship its own `apm` command.

What command do you expect `apm` to be on your system?

**Comment by LeoYuan** [comment]
## add some backgrounds
1. `apm` is a front-end package management system developed by our team, much like `npm` for nodejs.
2. `apm` is a fork from [spm](https://github.com/spmjs/spm).
3. completion is not broken when using spm.
3. I'm using OSX 10.10.2
4. I'm using iTerms
5. I'm using OMZ

## some researches
1. windows 7 && apm installed && without OMZ, completion works fine.
2. OSX && apm installed && without OMZ, completion works fine.
3. OSX && apm installed && with OMZ, completion is broken.
4. OSX && apm uninstalled && with OMZ, completion is broken. 

**Seems the OMZ is the key factor, so I suspect that OMZ has conflict with apm~**

**Comment by apjanke** [comment]
Interesting. Is your `apm` publicly available so I can try reproducing your tests with it installed?

And what's your output for `find $fpath -name _apm`, with and without OMZ installed?

**Comment by LeoYuan** [comment]
output for `find $fpath -name _apm`
```
$ find $fpath -name _apm
find: /Users/leoyuan/.oh-my-zsh/functions: No such file or directory
find: /Users/leoyuan/.oh-my-zsh/completions: No such file or directory
/usr/share/zsh/5.0.5/functions/_apm
```

`apm` is not public, but you still can try type `apm [tab]`~

**Comment by apjanke** [comment]
What is your output for `find $fpath -name _apm` without OMZ installed, or at least without it loaded?

**Comment by apjanke** [comment]
When you are not running OMZ, are you calling `compinit` in your `~/.zshrc` to initialize zsh's completion system? That could be the difference you're seeing.

If I start up `zsh` with an empty `.zshrc`, then tab completion for `apm ~/<tab>` "works", and autocompletes directories, like you're expecting. If I then do `autoload -U compinit; compinit` to initialize zsh's advanced completion system (instead of doing simple file completion), then it stops working: `apm ~/<tab>` does nothing when hitting `<tab>`.

If this is the case, it basically means that OMZ doesn't define any completions for `apm` itself, but it initializes OMZ's completion system, and their supplied `_apm` isn't compatible with your `apm` command. (OMZ completion definitions can be command-specific, and this one defines completions for the options for the Linux/etc `apm` command.)

Try doing `autoload -U compinit; compinit` without OMZ loaded to verify that for your case.

If this is the case, you could work around it by one of:
* Run `compdef -d apm` after OMZ or `compinit` is initialized, to remove `zsh`'s custom completions for `apm` and have it autocomplete as a generic command again.
* Supply your own `_apm` completion definition for your `apm` program, and put it ahead of zsh's `_apm` (e.g. in `site-functions` or as an OMZ plugin). These could be part of the `apm` program installation if you have appropriate administrator rights.

**Comment by apjanke** [comment]
Could you update the title of this issue to indicate that it's specific to `apm`?

**Comment by LeoYuan** [comment]
without OMZ installed, I tested it on some colleage's machine~
```
shanruo$ find $fpath -name _apm 
find: illegal option -- n
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
``` 

sure, I can update title~

thanks for your detailed solution, but it is just a little complicate for those people who want to use apm~

**Comment by apjanke** [comment]
You're welcome.

Your colleague does not appear to have `$fpath` defined, which probably means they are not running `zsh`.

It is unfortunate. I'm sorry I don't have a better fix. That's a downside of choosing the same command name as an established program that's out in the wild, and how zsh's completion works. (That is, `zsh` is defining completion customizations for `apm`, it's just not *your* `apm`.) 

To make it easier on users of `apm`, the developers of `apm` could provide bash and zsh completion definitions for their version of `apm` as part of the `apm` installation. Then users would get proper completion for your command. This could cause them problems if they wanted to use the power-management or Atom `apm` commands. But there's already a name conflict there that they'll have to work around.

You could also just add a note to the installation instructions that Zsh users should put that `compdef -d apm` in their `.zshrc` file. I think using `compinit` is pretty common, so a lot of Zsh users could be affected.

Since there are conflicts for the `apm` name out in the wild, it might be worth [reporting this upstream to the Zsh maintainers](http://zsh.sourceforge.net/Arc/mlist.html) so they could revise their `_apm` definition. But that's not going to help users of existing versions of `zsh` (which would include any users of OS X 10.11 or earlier, or existing releases of more conservative Linux and BSD distributions).

####  "Fixing" in OMZ?    ####

For that matter, maybe OMZ should knock out the `apm` completion itself: the Linux/BSD `apm` command [appears to be pretty old, replaced by `acpi`](http://archive.oreilly.com/linux/cmd/cmd.csp?path=a/apm) so few current users would actually want that completion. I tested it on a few recent distributions; it's gone from Debian 7 Linux, OS X 10.9 (replaced by `pmset`), and Cygwin. It's present in PC-BSD 10.1. In Ubuntu 14, it's in the `apmd` package. I'd bet the Atom `apm` command is in much wider use among OMZ users.

One approach could be to check for `apmd` being installed and conditionally set up the completion that way. Though that complicates things.

I don't know what's the consensus about handling `zsh` completion configuration for different commands with the same name. The [zsh-workers and zsh-users archives](http://zsh.sourceforge.net/Arc/mlist.html) might have some discussion of it. In OMZ, this is typically handled by creating different plugins for the different commands, and having users select the plugins for the programs they're going to work with.

**Comment by LeoYuan** [comment]
add `compdef -d apm` to `.zshrc` would be the simplest way to fix this problem~

and I still wanna say thank you, I really don't expect that I would get so much help from the community,
bro, it's really impressive~

**Comment by apjanke** [comment]
You're welcome!

**Comment by Rukeith** [comment]
@LeoYuan 
I add `compdef -d apm` to my `.zshrc`. But I still have this problem. can't find any apm command

**Comment by mcornella** [comment]
@Rukeith it seems you don't have the `$PATH` set up correctly. If you run `which apm` and `which atom` what do you get?

**Comment by Rukeith** [comment]
@mcornella 
If I run `which apm` and `which atom`, I will get  `/usr/local/bin/apm` and `/usr/local/bin/atom`
