### ISSUE TITLE
Weird title bug. duplicates folder

### ISSUE THREAD

**Issue by wizsilex** [robbyrussell/oh-my-zsh#4213]
Oh My Zsh makes terminal title weird. this only happens in os x terminal.app, not in iterm2.
If i got at /Applications folder on my Macbook title becomes:
(Icon)Applications - user@Computer: /Applications - /Applications - zsh - 153x24(dimensions of terminal)
pleas look at attached image.

how can I clean up the title to just show?:
(Icon)Applications - user@Computer: /Applications - zsh - 153x24(dimensions of terminal)
not duplicate current folder title

![screen-shot-2015-08-04-at-12 04 22 f](https://cloud.githubusercontent.com/assets/273496/9058485/cf5a43ca-3aa1-11e5-8de4-1c57d4204cb2.png)

**Comment by mcornella** [comment]
My guess is that this is the title that it's terminal.app that adds that second folder but I'm not sure. Try running bash and see if the directory appears on the title as well.
@apjanke knows OSX better than me

**Comment by apjanke** [comment]
Same behavior for me in Terminal.app. I believe what's going on here is that when you have only a single tab, and the tab bar is not displayed, then both the window title and tab/icon title are displayed in the title bar of the window. OMZ's code sets both of these to include the directory name.

The leftmost occurrence of the directory is the one displayed directly by Terminal.app based on the "current directory" state. The second occurrence is from the window title set by OMZ, and the third occurrence is from the icon/tab title.

You can observe how this works by setting `DISABLE_AUTO_TITLE=true` in your `~/.zshrc`, opening a new Terminal.app window, and running `title icon window`. Then choose View > Show Tab Bar from the menu, and watch how the words move.

<img width="692" alt="screen shot 2015-08-04 at 5 32 03 pm" src="https://cloud.githubusercontent.com/assets/2618447/9073350/c5c50566-3ace-11e5-86a4-856d3f293d3a.png">

<img width="692" alt="screen shot 2015-08-04 at 5 32 09 pm" src="https://cloud.githubusercontent.com/assets/2618447/9073352/c859c014-3ace-11e5-8de8-8b6b72afff24.png">

To change how this works, you have a few options:
* Switch to iTerm2 :)
* Set `DISABLE_AUTO_TITLE=true`
* Enable "Show Tab Bar"
* Change `$ZSH_THEME_TERM_TAB_TITLE_IDLE` and `$ZSH_THEME_TERM_TITLE_IDLE` to customize what's in the titles. See `lib/termsupport.zsh` for their default values. The `%~` in them is what's including the current directory. Set them in your `~/.zshrc` after loading OMZ. Since Terminal.app and iTerm2 are both able to display the current directory independently, you might want to just remove the `%~` from both of them, and put something else useful in the tab/icon title.
* Customize `lib/termsupport.zsh`'s code to not set the icon title at all. I believe that will get the exact title form you're asking for, where the last occurrence of the directory is simply removed. I think you'd have to redefine `title()` and/or `omz_termsupport_precmd()`. You could do that in a simple custom file (instead of fully overriding `lib/termsupport.zsh`) since they're loaded after the lib files, and you only need to redefine a couple functions.

**Comment by apjanke** [comment]
[Here's](https://github.com/apjanke/oh-my-zsh-custom/blob/3e30c6b184576c31fc517759be841acf0b6223da/termsupport-extras.zsh#L40-L44) what I ended up doing to handle this. I think I'll probably enable it for iTerm2, too, and other terminal programs that have tabs. Less noise.

```
# Avoid duplication of directory
if [[ $TERM_PROGRAM == Apple_Terminal ]]; then
  ZSH_THEME_TERM_TAB_TITLE_IDLE="%15<..<%~%<<" #15 char left truncated PWD
  ZSH_THEME_TERM_TITLE_IDLE="%n@%m"
fi
```

**Comment by wizsilex** [comment]
Thanks @apjanke your last solution worked perfectly.
It was a nice patch/fix for the problem.

**Comment by mcornella** [comment]
Can we have a PR for this?

**Comment by apjanke** [comment]
PR opened: #4233.
