### ISSUE TITLE
`git status` tries to autocomplete to `git stats`

### ISSUE THREAD

**Issue by hlin117** [robbyrussell/oh-my-zsh#4224]
Whenever I type `git status` now, zsh tries to correct this to `git stats`. `git stats` isn't even a real command =(

<img width="633" alt="screenshot 2015-08-06 13 45 11" src="https://cloud.githubusercontent.com/assets/1865885/9122993/73ea5966-3c41-11e5-8932-efbcc30b2a5e.png">

This is in zsh version 5.0.7.

Possibly related: #4205.

**Comment by Arondight** [comment]
one solution is add next line to your `~/.zshrc`
```zsh
ENABLE_CORRECTION="false"
```
and then run
```
src
```
you can use to plugin [zsh-syntax-highlighting][ID_ZSH] to kown if you type a right command or not.

[ID_ZSH]: https://github.com/zsh-users/zsh-syntax-highlighting.git 'jump to zsh-users/zsh-syntax-highlighting'

**Comment by hlin117** [comment]
That would most definitely fix the problem, but this would defeat the whole purpose of the autocomplete capability.

The point is that one of the recent releases of zsh changed the behavior of this feature.

**Comment by apjanke** [comment]
This sounds like normal `zsh` correction behavior. "Correction" and "completion" are different features.

Do you have a file named `stats` in that directory? I'm wondering where it got the word "stats" from.

This doesn't seem new with `zsh` 5.0.7. I can reproduce the same behavior with `zsh` 5.0.2 with `setopt CORRECT_ALL` and a file named `stats` in the current directory. Perhaps a `stats` file was created recently around the time of a `zsh` upgrade for you?

If you do have a file named `stats` there or on the path: this is just what `CORRECT_ALL` does (`$ENABLE_CORRECTION` in OMZ terms). If you don't want this behavior, turn it off. "Completion" and "correction" are two related, but different things. If you disable correction (which is off by default in both `zsh` and OMZ), completion will still work. 

You can turn off correction entirely with @Arondight's suggestion. (Or probably, since correction is off by default, just finding and removing a `ENABLE_CORRECTION=true` line.) Or you can disable it for `git` specifically by aliasing `git` to `nocorrect git`. See `$ZSH/lib/correction.zsh` for how this is done for some other commands. You could also set `$CORRECT_IGNORE_FILE` to give it patterns to not correct, and include `status` and other `git` subcommands in there. It is documented under `CORRECT_ALL` in [the Options > Input-Output section of the Zsh Reference Manual](http://zsh.sourceforge.net/Doc/Release/Options.html#Input_002fOutput).

I find correction to be clumsy because this sort of confusion between files and arguments is inherent to how it works, and just leave it off.

You could also answer `n` when it asks you if you want to correct it, since you know it should really be `status`.

**Comment by hlin117** [comment]
> Do you have a file named stats in that directory? I'm wondering where it got the word "stats" from.

This is rather embarrassing; there actually was a folder called `stats` in my directory, which was why zsh was correcting to that. I apologize for all the confusion.

Thank you for the clarification between "correction" and "completion" though. I previously didn't know this.
