### ISSUE TITLE
fasd does not work with oh my zsh

### ISSUE THREAD

**Issue by LuoPX-15510486969** [robbyrussell/oh-my-zsh#4236]
i put fasd to the plugins line in .zshrc . 
plugins=(git zsh-syntax-highlighting fasd)
but it does not work ,what should i do .My oh my zsh is the new version.

**Comment by gato-omega** [comment]
Hi there, same issue here, however I have tracked this down to not have to do with the plugin.

I got fasd installed through homebrew, the `fasd` command working just fine in the console but the aliases and autocompletion is not working (i.e. plugin does not load any of that).

If you are using Boxen or some other similar development environment loader, and have OhMyZsh sourced/required before it, the `fasd` binary will not be available for the plugin to check, so it won't be initialized. For example, this will not work:

```bash
plugins=(... fasd)

source $ZSH/oh-my-zsh.sh

# ....and then load boxen...
source /opt/boxen/env.sh
```

But if you move Boxen to load before OhMyZsh, then other plugins may begin to break, so what you can do is explicitly loading the fasd plugin as a one case in your .zshrc file after all your initialization is complete (you may optionally remove it from the plugins list too, since it won't do anything if you leave it there):

```bash
plugins=(...)

source $ZSH/oh-my-zsh.sh

# ....and then load boxen... (which in turn loads homebrew's stuff which loads fasd)
source /opt/boxen/env.sh

#... and finally load the plugin, which will now detect fasd
source $ZSH/plugins/fasd/fasd.plugin.zsh
```

Hopefully this will help, cheers!

**Comment by LuoPX-15510486969** [comment]
i install it manually from github of fasd and i put "source path/to/fasd" t into .zshrc that works.

**Comment by apjanke** [comment]
If this is working now, can this issue be closed?

**Comment by gato-omega** [comment]
hi there! yes I am pretty sure this can be closed. This seems to not really be related with oh-my-zsh, it depends on how things are sourced at the user's custom .zshrc file.

**Comment by nikkolasg** [comment]
Just to bump up, simply putting the plugin in the list of plugins did not work. Also the trick with explicitly calling the fasd plugins neither.
The only solution that worked with me was installing with the sources...
My setup is pretty standard: Archlinux + urxvt + Zsh + OhMyZsh without nothing else fancy.

**Comment by leodutra-aurea** [comment]
Same here, 2018

**Comment by mcornella** [comment]
Is the fasd command available? If you're defining the `$PATH` variable, check that it's done before OMZ is loaded, preferably at the top of your zshrc file.
