### ISSUE TITLE
Theme Not Applying

### ISSUE THREAD

**Issue by arb** [robbyrussell/oh-my-zsh#4314]
In my .zshrc, my theme is set to 

```
ZSH_THEME="junkfood"
```

Yet when I open a new OSX terminal, it looks like this:

![image](https://cloud.githubusercontent.com/assets/1591483/9639940/b35b81ce-517c-11e5-8eb6-5bde41e9cdff.png)

Nothing close to the "junkfood" theme. Is there some other setting or option I need to enable for theme support to work correctly? I have tried several other themes with the same effect. It seems like _parts_ of the theme apply, but not all of it.

**Comment by mcornella** [comment]
You get the same theme as I do. It seems the screenshot from over @thcipriani's [blog post](https://tylercipriani.com/2012/12/18/zsh-prompt-customization.html) was from the bash version of his prompt, which you can actually use in zsh with some modification.

The screenshot should be updated in the theme wiki, let me just do that.

**Comment by arb** [comment]
Ok well that may be the case, but even like the default theme doesn't look right. The background is still white and the colors aren't the same either. Like none of the themes seem to work 100%.

**Comment by mcornella** [comment]
Yes, that is because themes are only the letters and colors that you tell the terminal to print. But there is another layer on top which is that terminal emulators can change what the colors look like (so red looks different than normal, for instance). 

That's called **color scheme**, and in some of the screenshots of the [Themes wiki page](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes) there's an explanation of what color scheme was used. A popular one is Solarized dark. 

If you fiddle around in your terminal emulator's settings you'll find some place dedicated to changing the color scheme.

**Comment by arb** [comment]
I see. Thank you for the explanation.
