### ISSUE TITLE
Chucknorris plugin outputs no fortunes found at first use

### ISSUE THREAD

**Issue by hamadr** [robbyrussell/oh-my-zsh#4329]
Hello,

I just installed the plugin and got the error when running `chuck`
`fortune: /home/adrien/.oh-my-zsh/plugins/chucknorris/fortunes: No fortune files in directory.
fortune:/home/adrien/.oh-my-zsh/plugins/chucknorris/fortunes not a fortune file or directory
No fortunes found
`
To solve the problem I ran `zsh /home/adrien/.oh-my-zsh/plugins/chucknorris/chucknorris.plugin.zsh`

**Comment by apjanke** [comment]
What did you do to install the plugin? Normally it generates that fortune data file as part of its initialization when you start a new `zsh` session and Oh My Zsh initialization runs.

**Comment by hamadr** [comment]
I installed oh-my-zsh on archlinux.
I added the plugin to the conf.
It told me I didn't have the fortune command so I installed "community/fortune-mod".
After that I had the following error
``fortune: /home/adrien/.oh-my-zsh/plugins/chucknorris/fortunes: No fortune files in directory. fortune:/home/adrien/.oh-my-zsh/plugins/chucknorris/fortunes not a fortune file or directory No fortunes found``

**Comment by apjanke** [comment]
That makes sense. In the current implementation, the plugin only gets a chance to generate the fortune file at shell startup time. Restarting your shell session like that will fix it.

The `chuck` command could also be modified to check for the fortune file and generate or update it each time it's called, instead of at shell startup time, to fix this.
