### ISSUE TITLE
After activating Tab completion for longer expressions the rest of line after the prompt contains rubbish characters

### ISSUE THREAD

**Issue by ps-aux** [robbyrussell/oh-my-zsh#4341]
For example when I want to complete the path beyond the first directory like this:
![ohzsh](https://cloud.githubusercontent.com/assets/4789301/9803733/e7ed5d18-5825-11e5-91f2-7110acf4edd2.png)

Then when hitting tab will produce:
![ohzsh1](https://cloud.githubusercontent.com/assets/4789301/9803740/2446f6e8-5826-11e5-9fca-bb1b8bc89b81.png)

When attempting to delete the command in line the resulst is:
![ohzsh2](https://cloud.githubusercontent.com/assets/4789301/9803759/5959a092-5826-11e5-81b1-af3cb91ea4b1.png)
Evidently `cd u` is now part of the prompt.

This  happens while trying several themes (agnoster, robbyrussell, etc )

Enviroment: Arch Linux, Konsole, KDE 4

**Comment by apjanke** [comment]
Sounds like an issue with the terminal (or `zsh`) miscalculating the cursor location when redisplaying a line in ZLE, probably due to wide characters being involved. The `agnoster` and `robbyrussell` themes both use some characters which are two cells wide in their prompts. In the case of `agnoster`, these are non-standard "private use" characters. 

Does the same problem happen with the `cypher` theme? (It doesn't have any wide characters, I think.)

I couldn't reproduce this with Konsole 2.8.4 on Debian 7 Linux, KDE 4.8.4. I set up the Powerline fonts using the "fallback font/fontconfig" method described [here](http://powerline.readthedocs.org/en/latest/installation/linux.html#fonts-installation). Used the `agnoster` theme and that same directory structure, but the characters still appeared in the "right" place after doing the same tab-completion. Don't know what's different about our setups.

How do you have your fonts set up? Are you using the "fallback font" method or "patched fonts"?

**Comment by zobi8225** [comment]
Hi, i got the same problem. I try with cypher and robbyrussell and i got the same things...

**Comment by ps-aux** [comment]
It is related to the locale settings. Workaround is `export LC_ALL="en_US.UTF-8" to .zshrc` as per http://stackoverflow.com/questions/19305291/remnant-characters-when-tab-completing-with-zsh

**Comment by zobi8225** [comment]
Don't work for me :-(

**Comment by zobi8225** [comment]
Ok , but if we are french ? I try  LANG="fr_FR.UTF-8" , but it don't work better ....

**Comment by zobi8225** [comment]
hmmmm i use sakura terminal, i try uxterm and it look working better...
