### ISSUE TITLE
Updated ZSH this morning, get error when SUDOing

### ISSUE THREAD

**Issue by varcharlez** [robbyrussell/oh-my-zsh#4383]
I upgraded ZSH today. When I run `sudo` I see the following output:
```
charlespantoga in ~
❯❯ sudo -s                                                                    1:36PM
[oh-my-zsh] Insecure completion-dependent directories detected:
drwxr-xr-x   15 charlespantoga  staff   510 Sep 22 09:34 /Users/charlespantoga/.oh-my-zsh
drwxr-xr-x  208 charlespantoga  staff  7072 Sep 22 09:34 /Users/charlespantoga/.oh-my-zsh/plugins
drwxr-xr-x    4 charlespantoga  staff   136 Jul 27 16:31 /Users/charlespantoga/.oh-my-zsh/plugins/brew
-rw-r--r--    1 charlespantoga  staff  3790 Jul 27 16:31 /Users/charlespantoga/.oh-my-zsh/plugins/brew/_brew
drwxr-xr-x    4 charlespantoga  staff   136 Sep  8 09:27 /Users/charlespantoga/.oh-my-zsh/plugins/git
[oh-my-zsh] For safety, completions will be disabled until you manually fix all
[oh-my-zsh] insecure directory permissions and ownership and restart oh-my-zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

[oh-my-zsh] Insecure completion caches also detected:
-rw-r--r--  1 charlespantoga  staff  35720 Sep 22 13:34 /Users/charlespantoga/.zcompdump-mac-chapan-5.0.5
-rw-r--r--  1 charlespantoga  staff  37866 Sep 22 13:32 /Users/charlespantoga/.zcompdump-mac-chapan-5.0.8
[oh-my-zsh] Moving to "/Users/charlespantoga/.oh-my-zsh/cache//zcompdump-bad/"...

/Users/charlespantoga/.oh-my-zsh/plugins/git/git.plugin.zsh:81: command not found: compdef
/Users/charlespantoga/.oh-my-zsh/plugins/git/git.plugin.zsh:89: command not found: compdef
/Users/charlespantoga/.oh-my-zsh/plugins/git/git.plugin.zsh:95: command not found: compdef
/Users/charlespantoga/.oh-my-zsh/plugins/git/git.plugin.zsh:104: command not found: compdef
/Users/charlespantoga/.oh-my-zsh/plugins/git/git.plugin.zsh:113: command not found: compdef
/Users/charlespantoga/.oh-my-zsh/plugins/git/git.plugin.zsh:115: command not found: compdef
/Users/charlespantoga/.oh-my-zsh/plugins/git/git.plugin.zsh:124: command not found: compdef
/Users/charlespantoga/.oh-my-zsh/plugins/git/git.plugin.zsh:126: command not found: compdef
/Users/charlespantoga/.oh-my-zsh/plugins/git/git.plugin.zsh:134: command not found: compdef
/Users/charlespantoga/.oh-my-zsh/plugins/git/git.plugin.zsh:140: command not found: compdef
/Users/charlespantoga/.oh-my-zsh/plugins/git/git.plugin.zsh:142: command not found: compdef
/Users/charlespantoga/.oh-my-zsh/plugins/git/git.plugin.zsh:147: command not found: compdef
/Users/charlespantoga/.oh-my-zsh/plugins/git/git.plugin.zsh:150: command not found: compdef
/Users/charlespantoga/.oh-my-zsh/plugins/git/git.plugin.zsh:152: command not found: compdef
/Users/charlespantoga/.oh-my-zsh/plugins/git/git.plugin.zsh:165: command not found: compdef
/Users/charlespantoga/.oh-my-zsh/plugins/git/git.plugin.zsh:176: command not found: compdef
```

**Comment by ShaoXinSen** [comment]
I meet the same problem too.

**Comment by varcharlez** [comment]
FYI I am on OSX Yosemite if that matters, using iTerm2!

**Comment by meisheep** [comment]
Have you upgrade your XCode?

I fix this issue by:
```
brew doctor
xcode-select --install
brew update
brew upgrade
```

**Comment by ShaoXinSen** [comment]
@meisheep  Yes, my Xcode version is 7, and after brew update still have the problem
<img width="819" alt="2015-09-23 15 05 18" src="https://cloud.githubusercontent.com/assets/13616801/10039456/c4d21df8-6204-11e5-8c22-bf720905b7bf.png">
<br>
<img width="704" alt="2015-09-23 15 06 12" src="https://cloud.githubusercontent.com/assets/13616801/10039464/daa75328-6204-11e5-8cf0-d28b8e84d905.png">

**Comment by mcornella** [comment]
It happens the same to me when `sudo -E -s`. Check if your `sudo` is an alias with `alias sudo`.

**Comment by stucki** [comment]
These are actually two problems as it looks to me:
* `command not found: compdef` is already reported in #4378 
* `sudo -s` gives warnings because of wrong permissions

I have therefore created a new issue about the 2nd problem in #4388 and suggest to close this ticket therefore.

**Comment by peterhurford** [comment]
I have this problem too.

**Comment by varcharlez** [comment]
@mccornella I checked my alias and sudo is an alias to `nocorrect sudo`

Also, I'm using the current release of XCode as well as the latest versions of Brew.

**Comment by tobiasboyd** [comment]
Getting `compdef` errors on Mavericks, 10.9.5, too.

**Comment by apjanke** [comment]
The recently merged #3889 affected the completion startup sequence.

In particular, it removed the `-i` option to `compinit`, which tells `compinit` to silently ignore insecure directories. Now that it's gone, if `compinit` finds insecure directories, it will prompt you or balk like this. The "insecure directories" it's mentioning were probably there before, and this is just a change in zsh configuration, and not stuff installed on your system.

See #3889 for discussion.

**Comment by apjanke** [comment]
I think this is a problem with the new `compinit` without an `-i` being incompatible with `sudo -s`, or another `sudo` which launches an interactive shell.  I get the same problem even though my permissions are "right", just like @ShaoXinSen's.

```
[~/.oh-my-zsh on ⇄ master]
$ sudo -s
Password:
[oh-my-zsh] Insecure completion-dependent directories detected:
lrwxr-xr-x    1 janke  staff    23 Sep 15 01:24 /Users/janke/.oh-my-zsh -> local/opp/omz/oh-my-zsh
drwxr-xr-x  208 janke  staff  7072 Sep 23 15:08 /Users/janke/.oh-my-zsh/plugins
drwxr-xr-x    4 janke  staff   136 Sep 19 15:11 /Users/janke/.oh-my-zsh/plugins/brew
-rw-r--r--    1 janke  staff  3790 Sep 19 15:11 /Users/janke/.oh-my-zsh/plugins/brew/_brew
drwxr-xr-x    7 janke  staff   238 Sep 19 15:11 /Users/janke/.oh-my-zsh/plugins/emoji
[...]
[oh-my-zsh] For safety, completions will be disabled until you manually fix all
[oh-my-zsh] insecure directory permissions and ownership and restart oh-my-zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

[oh-my-zsh] Insecure completion caches also detected:
-rw-r--r--  1 janke  staff  35292 Sep 15 01:22 /Users/janke/.zcompdump
-rw-r--r--  1 janke  staff  35453 Sep 15 01:24 /Users/janke/.zcompdump-new-spiffy-5.0.2
-rw-r--r--  1 janke  staff  35453 Sep 21 15:10 /Users/janke/.zcompdump-spiffy-5.0.2
[oh-my-zsh] Moving to "/Users/janke/.oh-my-zsh/cache//zcompdump-bad/"...

[# root@spiffy ~/local/opp/omz/oh-my-zsh on ⇄ master]
```

I think the issue is that when you `sudo`, the security is evaluated from the perspective of your effective user id (`root`), but you still have completions from your ordinary user on the path (`janke` in my case). I don't think there's a way to resolve that with a file configuration. `compinit -i` looks like the Right Thing to gracefully handle the case where your user identity might be changing during a session without redoing all your paths to match it.

Restoring the `-i` to the `compinit` call on `.oh-my-zsh` is probably the the right way to handle this, from what I can see. You could do it with a conditional check to see if you're root, but this problem seems like it would also affect `sudo`-ing to non-root users as well (on systems that support it).

**Comment by wangnan0610** [comment]
Just chmod 755 /Users/charlespantoga/.oh-my-zsh and so on ~
It works fine for me ~

**Comment by apjanke** [comment]
Even when you do `sudo -s`? My `~/.oh-my-zsh` is already mode `755`, and so is the original poster's.

**Comment by nihilnovi** [comment]
Getting similar issues since the last upgrade as well:

`[oh-my-zsh] Insecure completion-dependent directories detected:`
and 
`[oh-my-zsh] Insecure completion caches also detected:`

doing chmod 755 int he zsh folder fixes it somewhat, but the problem returns after a while. Also some completions are not working after the upgrade even after setting permissions to 755, for example git completion for branches that have slashes in them, for instance `feature/123` would not be autocompleted, but `feature123` will.

**Comment by apjanke** [comment]
@nihilnovi: sounds like the permissions-repairing code might not be fixing all of the "insecure" directories for you. What do you get for the output of `compaudit`? (Run from the account that is having the completion problems, in a session where that error message showed up.)

**Comment by nihilnovi** [comment]
@apjanke 

```
There are insecure directories:
/home/mike/.zsh/completion
/home/mike/.zsh

```

**Comment by apjanke** [comment]
Hmm. Those aren't standard OMZ-controlled directories. Did you create them yourself? Is there synchronization software controlling them, maybe? What's `ls -lda` show for their permissions now? I don't know why it would recur if you've already `chmod 755`ed those directories.

And what's your `umask`?

**Comment by nihilnovi** [comment]
No, I've not done anything except running `upgrade_oh_my_zsh`, the errors I got are not from that folder though, they are from `.oh-my-zsh/`.
`.zsh` permissions are `drwxrwxr-x` , I've done nothing to that directory though.

`umask` is `002`

After doing `git reset --hard origin/master` in `.oh-my-zsh/` and removing the `git-extra` plugin in `.zshrc` the errors seem to have gone away, will report if they return.

**Comment by apjanke** [comment]
Your umask should probably be `022`. If it's `002`, any directories you create will be "insecure" from zsh's perspective.

The recent change in OMZ wasn't to create that directory; it was to change how OMZ's initialization of the Zsh completion system (with `compinit`) treated insecure directories. (It used to silently ignore them; now it tries to automatically fix them, and will let Zsh complain about ones that aren't fixed so you can clean them up.) So even if you haven't done anything to that directory lately, its state may be what's causing Zsh to error out.

That `~.zsh` directory is insecure.  `drwxrwxr-x` is mode `775`. (Which is what you will create if your `umask` is `002`.) Change it to `755` with `chmod -R 755 ~/.zsh` and this error may go away.

The errors might have been issued by scripts running from `~/.oh-my-zsh`, but they may be the result of the state of files outside that directory. In particular, the completion system will check the permissions of all directories  The output of `compaudit` is telling you which directories it doesn't like.

**Comment by nihilnovi** [comment]
Thank's a lot of your help and information, I've learnt quite a bit from this :)

It would appear umask is  `002` because of this:

```
Enables setting of the umask group bits to be the same as owner bits (examples: 022 -> 002, 077 -> 007) for non-root users, if the uid is the same as gid, and username is the same as the primary group name.
```

from http://askubuntu.com/questions/44542/what-is-umask-and-how-does-it-work under `A note on the default umask` , so I'm not sure if I should be fiddling with the default Ubuntu umask settings because of OMZ.

**Comment by apjanke** [comment]
Interesting. I didn't know about that USERGROUP `umask` thing; will look in to it. Thanks for the heads-up. (BTW, does anyone know *why* Ubuntu/PAM does `002` instead of `022`?)

It's not just OMZ that needs these directories to be `755`, though, it's Zsh itself: `compaudit` is a base Zsh command.

We'll need to watch out for this with other Ubuntu users.

**Comment by macgeneral** [comment]
Same issue here:
[oh-my-zsh] Insecure completion-dependent directories detected:
dr-xr-xr-x  3 admin  admin  102 11 Sep 17:20 /usr/local/share/zsh
dr-xr-xr-x  3 admin  admin  102 11 Sep 17:20 /usr/local/share/zsh/site-functions
lrwxr-xr-x  1 admin  admin   74 11 Sep 17:20 /usr/local/share/zsh/site-functions/_youtube-dl -> ../../../Cellar/youtube-dl/2015.09.09/share/zsh/site-functions/_youtube-dl
[oh-my-zsh] For safety, completions will be disabled until you manually fix all
[oh-my-zsh] insecure directory permissions and ownership and restart oh-my-zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

/Users/macgeneral/.oh-my-zsh/plugins/git/git.plugin.zsh:81: command not found: compdef
[..]


I just used
sudo mv /usr/local/share/zsh /usr/local/share/zsh.bak and now it's working again - don't know if I broke anything besides the youtube_dl completions ;)

**Comment by apjanke** [comment]
@macgeneral: That will break any Homebrew-installed `zsh` stuff, including zsh completion support installed as part of Homebrew-provided packages. But those completions were already broken anyway, because `zsh` sees those directories as insecure and refuses to load them; it was just silently ignoring them before, due to the `-i` option.

These permissions look like they are secure; it's just that `zsh` doesn't recognize them as such because they're owned by `admin` and not specifically by `root`. `zsh` would only recognize them as secure if they were owned by `root` or yourself (`macgeneral` in this case, I think). So, `chown -R macgeneral /usr/local` would make `zsh` consider them as secure. But that may not be how you want to manage you Homebrew installation. IMHO, having Homebrew or other installations managed by a dedicated non-`root` role user is a legit setup.

In your case, it sounds like `compinit -i` is the Right Thing; maybe OMZ should provide an option for that, and to suppress the announcements about insecure directories. As far as getting `zsh` to work fully with a non-`root`, non-self owned Homebrew installation, I don't know... I think you might be stuck with having to install Homebrew stuff as yourself if you want its `zsh` completions to work, since that's the scenario that Homebrew itself supports.

**Comment by azat-co** [comment]
So what is the best solution?

**Comment by varcharlez** [comment]
I think I've noticed something... I'm not sure if this is a ZSH issue or an oh-my-zsh issue.

This may not be of any help but, when running compaudit as my normal user I no output. When I run `sudo -s` I get:

```
/Users/charlespantoga/.oh-my-zsh/plugins/brew
/Users/charlespantoga/.oh-my-zsh/plugins/git
/Users/charlespantoga/.oh-my-zsh/plugins
/Users/charlespantoga/.oh-my-zsh/plugins
/Users/charlespantoga/.oh-my-zsh
/Users/charlespantoga/.oh-my-zsh
/Users/charlespantoga/.oh-my-zsh/plugins/brew/_brew
```

And when I run `sudo -i` I get a LONGGGGG list of directories that are 'insecure'. In fact, it views every zsh function as insecure.
```
There are insecure directories and files:
/Users/charlespantoga/.oh-my-zsh/plugins/brew
/Users/charlespantoga/.oh-my-zsh/plugins/git
/usr/local/share/zsh/site-functions
/usr/local/Cellar/zsh/5.1.1/share/zsh/functions
/Users/charlespantoga/.oh-my-zsh/plugins
/Users/charlespantoga/.oh-my-zsh/plugins
/Users/charlespantoga/.oh-my-zsh
/Users/charlespantoga/.oh-my-zsh
/usr/local/share/zsh
/usr/local/Cellar/zsh/5.1.1/share/zsh
/Users/charlespantoga/.oh-my-zsh/plugins/brew/_brew
/usr/local/Cellar/zsh/5.1.1/share/zsh/functions/_SUSEconfig
/usr/local/Cellar/zsh/5.1.1/share/zsh/functions/_a2ps
...
/usr/local/Cellar/zsh/5.1.1/share/zsh/functions/_zypper
```
I'm not using the system zsh, I'm using a brew installed ZSH.

I believe compaudit views these files as insecure because root (the user who is logged in via `sudo -s`) does not have write access to them. They are secure whether this is a "bug" or a feature.

@ShaoXinSen @apjanke what are your thoughts?

Perhaps the "bug" in this is that OMZSH should handle compaudit/compinit differently when sudoing to another user. For example, ast @apjanke stated earlier, it should use the `-i` flag when root.

**Comment by apjanke** [comment]
@varcharlez: No, `compaudit` views them as insecure when you are root because they are owned by, and thus writable by, a non-root user. An insecure directory is one which is writable by a user who is a) not root and b) not you. And yeah, I agree that it is a feature and not a bug.

In general, I would recommend *not* running OMZ as root, and thus not doing `sudo -s`.

I don't know what the best thing to do here is. I'm starting to think we should put the `-i` back in for all cases, because there are legit user setups which will have insecure directories that cannot be "fixed" by any configuration change, and we don't want to always nag in those cases. It is not necessary for security to disable completion completely. We should probably also add an option for disabling the completion-disabling feature.

**Comment by Morxander** [comment]
Fixed for me with `chmod 755 /home/myuser/.oh-my-zsh/plugins/git` and `chmod 755 /home/myuser/.oh-my-zsh/plugins/` It happened after the update and I think the reason is just wrong permission in the new version.
See where is the error in your case and change the permission and it will work.

**Comment by stucki** [comment]
The main question here is really whether or not `sudo -s` should be discouraged or not. I understand that it's wrong to write a cache file as user 1 which is then visible to user 2.

However, I think that a lot of users are using `sudo -s` to run certain commands within their home directory using root privileges. There's nothing wrong with this so I rather think that oh-my-zsh should find a solution that can cope with the situation.

My suggestion for it would be to move the cache directory out of the $HOME directory. I see that Midnight Commander is using a directory `/tmp/mc-root` for storing temporary data which has perms `drwx------` (700) and I think we should do the same for oh-my-zsh.

**Comment by apjanke** [comment]
Oh My Zsh is not heavily audited for security or correctness, and it is complex. Even if we fix this issue, I still wouldn't recommend running it as `root` or with `sudo -s`.

But that doesn't mean we can't or shouldn't fix this.

Moving the cache location sounds like a good idea. Maybe not unconditionally: that cache data is intended to persist across a lot of sessions, and `/tmp` is volatile, so for the ordinary case you probably still want it in `$ZSH_CACHE_DIR`. But we could relocate it for the `sudo` case (by checking for `$SUDO_USER != $USER` or similar). Stick it under a per-user subdirectory under `$TMPDIR` with the right permissions.

The `.zcompdump` cache files are not stored under `$ZSH_CACHE_DIR`; they're put directly under `$HOME`. Both these and the `$ZSH_CACHE_DIR` should probably be relocated in the `sudo` case if we do this. Or you could just not use a `.zcompdump` cache when running under `sudo`.

And then we don't need to blow away the existing `.zcompdump` file. That's an inconvenience because you need to spend execution time to regenerate it, and the current mechanism leaves files under your home directory that may not be writable by you.

```
[~/.oh-my-zsh/cache on ⇄ master]
$ ls -l
total 0
drwxr-xr-x  6 root  staff 204 Sep 28 05:50 zcompdump-bad
[~/.oh-my-zsh/cache on ⇄ master]
$ rm zcompdump-bad/.zcompdump
rm: zcompdump-bad/.zcompdump: Permission denied
```

**Comment by apjanke** [comment]
@nihilnovi: It looks like `compaudit` [already has code to detect that per-user-group stuff](https://github.com/zsh-users/zsh/blob/cb596a55d921cb638a3cf0ede3ee60ae13728c10/Completion/compaudit#L132-L144), though it's not effective for the case when you're doing `sudo`.

**Comment by stucki** [comment]
The root of this problem is the merge of #3889 (https://github.com/robbyrussell/oh-my-zsh/commit/56cdec75348cc7c33f54c5441884238c25a6597b) which was introduced by @leycec. If I understand correctly, the intention was to suppress `compdef` warnings and not to improve security.

However, I think that this problem was fixed by moving the `autoload` command up (see diff) and that there was no necessity to remove `-i` from the `compinit` call. Therefore I'm suggesting these three changes:

* skip `compaudit` permission check when running as root
* run `compinit` even if `compaudit` fails
* run `compinit` using the `-i` flag (ignore insecure directories)

See https://github.com/stucki/oh-my-zsh/commits/fix-4383. I'm not creating a pull request yet, waiting for feedback on this approach first.

**Comment by stucki** [comment]
Additionally, if you really want to fix the security problem when using `sudo -s`, I suggest to check if `$ZSH_CACHE_DIR` is owned by `$USER`, and stop with a warning if this is discouraged.

Otherwise, as mentioned earlier already, known issues with `sudo -s` should (and could!) be solved, see #3891.

**Comment by stucki** [comment]
One more thing: I also made an attempt to solve this problem by setting `ZSH_COMPDUMP` to something different (eg. add `$USER` to the filename). It turns out that this is not as easy as it seems:

* compaudit will still throw warnings for other files that belong to OMZ (see #4388)
* `$ZSH_COMPDUMP` is ignored on Ubuntu (at least) when `compinit` is called initially by `/etc/zsh/zshrc`. This happens before my local `.zshrc` is read, so it can't be changed by OMZ:

```
$  tail /etc/zsh/zshrc 
(( ${+aliases[run-help]} )) && unalias run-help
autoload -Uz run-help

# If you don't want compinit called here, place the line
# skip_global_compinit=1
# in your $ZDOTDIR/.zshenv or $ZDOTDIR/.zprofile
if [[ -z "$skip_global_compinit" ]]; then
  autoload -U compinit
  compinit
fi
```
The suggestion from the comment solves the problem, but it requires manual action...

**Comment by fiver22** [comment]
Started seeing this today as well, just after running update on oh-my-zsh. On logging into an affected machine (Debian Testing) with ssh or opening terminal I'd see 
"[oh-my-zsh] Insecure completion-dependent directories detected:
(various /home/user/dirs)"

ran    compaudit    which basically spit out all files in /home/user/oh-my-zsh.
*ran   chmod -R 755 /home/user/.oh-my-zsh   
to resolve. 
*This isn't advice -it's just what I did to get rid of the error.

**Comment by apjanke** [comment]
@fiver22: That `chmod` was the right fix in your case: it's what `compaudit` wants you to do, and why this error message is being exposed in the first place. You could go ahead and call that advice. :)

**Comment by apjanke** [comment]
@stucki: I'm in favor of the general approach of your fix. I think we need to refine it a little bit, so it's not just a roundabout way of reverting #3889.

In particular, a major thing #3889 was trying to do was avoid the creation of degenerate `.zcompdump` files in the case when `compinit -i` ends up ignoring a lot of insecure directories. Maybe that means we should use a `-D` to avoid creating the cache file if `compaudit` sees problems.

> $ZSH_COMPDUMP is ignored on Ubuntu (at least) when compinit is called initially by /etc/zsh/zshrc. This happens before my local .zshrc is read, so it can't be changed by OMZ ...

I *think* we can actually deal with this in `.zshrc`. The first time that `/etc/zsh/zshrc` runs in a login session, it still has the default `$FPATH`, and the directories on it are going to be secure, so it won't bring up the error messages or prompt. And it will produce a `.zcompdump` cache at the default location. Then OMZ, running from the user's `~/.zshrc`, adds the possibly-problematic dirs to `$FPATH`, and makes its own `.zcompdump`. The only time that global `/etc/zsh/zshrc` is going to see the insecure `$FPATH` dirs is when you invoke it from a subshell (e.g. running `zsh -i` from within `zsh`) and it sees the changes that OMZ has made to the exported `$FPATH` and other variables – in which case it could set and export `$skip_global_compinit` from `~/.zshrc`, and `/etc/zsh/zshrc` would see it most of the times it mattered.

This is getting messy.

**Comment by apjanke** [comment]
And, one more complicating factor: there may be a [bug in `compinit -i` itself](http://www.zsh.org/mla/workers/2015/msg02591.html) related to the exclusion of directories with insecure parents, where it should, but actually doesn't, ignore them.

**Comment by stucki** [comment]
> This is getting messy.

So true. I'm still in favour of reverting most of the stuff that #3889 changed. The original problem that it tried to solve is a different one (it's about moving the `autoload` command), and apparently the change has too many unwanted side effects.

See also the discussion in https://github.com/stucki/oh-my-zsh/commit/bcb45cae1295b2dc918125892d404f52ae6ad42f. My current suggestion is to remove both the `compaudit` check and the `handle_completion_insecurities` function.

**Comment by apjanke** [comment]
> The original problem that it tried to solve is a different one (it's about moving the autoload command)

It's not about moving `autoload`. That's an insignificant matter of code formatting, and as far as I can tell has no effect except to make `compaudit` available. The major motivation was to:

* Prevent the creation of degenerate/broken `.zcompdump` files in the case where `compinit -i` ended up excluding a lot of directories. Broken `.zcompdumps` are a frequent problem with OMZ, and this could help some.
* Notify the user that some of their completion definitions are being ignored, so they don't just wonder "why aren't some of my completions working?"
* Something about security, I think.

One of its original goals was also to automatically fix the insecure directories, so completions would just start working. But that was abandoned as being too complex or unworkable, I think.

#3889 is a giant thread, and stuff in there changed a lot during the discussion. Maybe @leycec or someone else could summarize the intent of #3889 and the mechanism that went in to the actual code change in a few paragraphs, so we have a better basis for discussion.

Given the side effects and breakage, I'm also in favor of mostly reverting all the new #3889 stuff until it can be tested further. Preferably by leaving it in the codebase and putting it behind a `$ZSH_DISABLE_COMPFIX` check that defaults to `true` for now, so it's easy to test and see how it interacts with other code.

**Comment by stucki** [comment]
According to the title, #3889 was about Cygwin only. However, as we see it affects a lot more platforms.
Therefore: Yes please, revert the `compaudit` check for now and see if anyone comes up with a general solution...

**Comment by apjanke** [comment]
Here's a PR that turns it off by default: #4426

This will restore the old `compinit` behavior by default for users, makes the `sudo -s` error messages go away, and leaves all the #3889 code intact so you can test it by turning setting `ZSH_DISABLE_COMPFIX=false` in your `~/.zshrc` before loading OMZ.

**Comment by stucki** [comment]
Thank you!

**Comment by azat-co** [comment]
thanks for the fix. it seems that disabling auto-updates is a way to go for me in the future. I've been burned a few times by the updates that make me less productive ;)

```
DISABLE_UPDATE_PROMPT=true
DISABLE_AUTO_UPDATE=true
```

**Comment by bumaociyuan** [comment]
chmod -R 755 <Insecure completion-dependent directories path>

**Comment by apjanke** [comment]
> chmod -R 755 <Insecure completion-dependent directories path>

Doing the chmod is insufficient to fix it for `sudo`, because once you `sudo`, `zsh` does the check considering you to be root, and some of those directories may be owned by the normal user, so `zsh` will consider them insecure while you're in the `sudo`.

**Comment by mcornella** [comment]
Yeah, just upgrading to the current version of oh-my-zsh will do. Sorry for the confusion!

**Comment by ohwutup** [comment]
I'm getting a similar issue, but when i try to call into zsh from bash. Does anyone have an idea as to how to fix this? 

```
‣ bash
bash-3.2$ /bin/zsh -l -c "which fastlane"
complete:13: command not found: compdef
/usr/local/opt/rbenv/shims/fastlane
```

**Comment by mcornella** [comment]
@ohwutup comment on #4771 which is your exact issue.

**Comment by mcornella** [comment]
@ohwutup also if you run on AWS or use aws-cli, we found the solution. Check it out.

**Comment by crunchyintheory** [comment]
Setting the owner of the .oh-my-zsh directory (recursive) to root and changing permissions to `drwxr-xr-x` fixed it for me
