### ISSUE TITLE
tmux plugin cds to its own directory

### ISSUE THREAD

**Issue by akadaedalus** [robbyrussell/oh-my-zsh#4425]
The tmux plugin is using a trick to get the absolute path of itself, which includes changing directory to that directory and printing $PWD.  This interferes with other plugins like autojump and last-working-dir.

This is the `git diff` from my fix:

```
diff --git a/plugins/tmux/tmux.plugin.zsh b/plugins/tmux/tmux.plugin.zsh
index bc32c89..f792228 100644
--- a/plugins/tmux/tmux.plugin.zsh
+++ b/plugins/tmux/tmux.plugin.zsh
@@ -37,7 +37,7 @@ if which tmux &> /dev/null


        # Get the absolute path to the current directory
-       local zsh_tmux_plugin_path="$(cd "$(dirname "$0")" && pwd)"
+       local zsh_tmux_plugin_path=$(dirname $0:A)

        # Determine if the terminal supports 256 colors
        if [[ `tput colors` == "256" ]]
```

I'd normally be hesitant to suggest an unportable syntax, but this is zsh-specific anyway.

**Comment by apjanke** [comment]
One step ahead of you: PR #4412 has [basically the same change](https://github.com/apjanke/oh-my-zsh/blob/245e1350a3928186cb1f48a96e0e903a9d22a30f/plugins/tmux/tmux.plugin.zsh#L55-L59). :smile: Goes one step further and uses `${0:h}` to avoid shell-outs entirely.

Syntax that isn't portable to other shells in Oh My Zsh stuff is fine. We are specific to zsh and trying to expose its power, so feel free to use zsh-only stuff. (Except in plugins which have upstream projects that are trying to be portable across shells.) In fact, we often prefer it when it can replace external commands that may themselves have portability concerns.

Looking ahead further, `$0` is problematic too because it doesn't play well with function calls, including anonymous functions, which are necessary for using `local` variables. We probably need to come up with an idiom for stashing that value when needed without polluting the global namespace too much.

**Comment by apjanke** [comment]
(I don't *think* the `:A` is necessary, since we're just using the paths right away inside the script execution.)

**Comment by akadaedalus** [comment]
Apologies, I did do a search for "tmux" but didn't drill into the details.  Thanks.

**Comment by apjanke** [comment]
Oh, no: my apologies for an inadequate PR name & description. You shouldn't have to read through the source diffs to learn what a PR does, and there's no reason to expect a "reformat source code" PR to do that. I've updated its title to be more accurate.

**Comment by akadaedalus** [comment]
This is still an issue.  I had to resolve a git conflict when I did an update.
