### ISSUE TITLE
OS X El Capitan "command not found: ___main"

### ISSUE THREAD

**Issue by RickCogley** [robbyrussell/oh-my-zsh#4439]
Hello - I just upgraded to El Capitan, and did the bidding of the brew doctor, but I am getting an error when I start my shell: 

~~~
zsh:12: command not found: ___main
(eval):1: no matches found: *:all-files
_tags:comptags:36: can only be called from completion function
_tags:comptry:55: can only be called from completion function
_tags:comptags:60: can only be called from completion function
_tags:comptags:67: can only be called from completion function
~~~

My diag dump is here: 
https://gist.github.com/RickCogley/937578f27a0ee21f7dbb

Could someone kindly take a look? 

Sincerely,
Rick

**Comment by apjanke** [comment]
Hmmm. I can't tell where that `eval` is happening. Looks like something is trying to run a completion as a normal function. But I don't see what in your `.zshrc` or custom files would be doing it.

Try doing a `zsh -lx` to see where that `___main` call is happening. (Don't post the full output without scrubbing it for passwords and API tokens, though.)

**Comment by gchpaco** [comment]
Line in question appears to be `emulate ksh -c ___main` in the `_git` completion file.

**Comment by gchpaco** [comment]
(I also have this problem)

**Comment by apjanke** [comment]
Okay. That `emulate ksh -c ___main` looks like it will happen if the `_git` provided by `git` or `hub`, and not by `zsh`, is run as a normal funciton outside the context of ZLE completion. This section will produce that output because `$service` is empty.

```
	if (( $+functions[__${service}_zsh_main] )); then
		__${service}_zsh_main
	else
		emulate ksh -c __${service}_main
	fi
```

Looks like what was happening in #2394. And I still can't reproduce it, even with the same plugins and custom dir that RickCogley is using.

**Comment by apjanke** [comment]
Aha. I can reproduce this if I have both `git` and `hub` installed via Homebrew and have the `github` OMZ plugin loaded.

The `github` plugin is [actually running the `_git` completion function upon startup](https://github.com/robbyrussell/oh-my-zsh/blob/7bb42fb49a0dcbd0774a0e6efafe766fdfc82268/plugins/github/github.plugin.zsh#L2-L6) instead of autoloading it.

```
if [ "$commands[(I)hub]" ] && [ "$commands[(I)ruby]" ]; then
    # Autoload _git completion functions
    if declare -f _git > /dev/null; then
      _git
    fi
```

I don't know why it's doing that.

As a temporary workaround, if you remove `github` from your `$plugins` list, the error will go away.

**Comment by RickCogley** [comment]
@apjanke much appreciated. I tried removing it, and as you say, the error goes away. 

Also, apologies, I did try ``zsh -lx `` but I cannot seem to capture std-out to a file.

**Comment by apjanke** [comment]
Cool.

For future reference, `zsh -lx &>~/zsh.log` will do the trick. The tracing output seems to go to both stderr and stdout.

**Comment by RickCogley** [comment]
ah, yes, ``&>`` why'd I forget that. Thanks!

**Comment by gchpaco** [comment]
Can confirm fix here.  Thanks!

**Comment by wongzigii** [comment]
I met this same problem.

**Comment by apjanke** [comment]
Folks who this is affecting: could you test PR #4443 and see if that fixes it for you?
