### ISSUE TITLE
Need some help with creating theme(git), thanks

### ISSUE THREAD

**Issue by chinanoahli** [robbyrussell/oh-my-zsh#4446]
I am creating a theme. I want to put the git information in `RPROMPT`. I read `xiong-chiamiov-plus.zsh-theme`, and I found it just used `$(git_prompt_info)` to show the stats of git. But when I put it in my theme, it doesn't work.

This is my code:

```
CURRENTUSER=`whoami`
if [ "$CURRENTUSER" = "root" ]; then USERCOLOR="red"; else USERCOLOR="cyan"; fi

PROMPT="┌\
%{$fg[$USERCOLOR]%}%{$bg[black]%} [%n> %{$reset_color%}\
%{$fg[yellow]%}%{$bg[black]%}[%m> %{$reset_color%}\
%{$fg[black]%}%{$bg[blue]%}[%~> %{$reset_color%}\
%{$fg[white]%} %#%{$reset_color%}
└\
 %(?,%{$fg[green]%}%{$bg[black]%}[%?>%{$reset_color%},%{$fg[red]%}%{$bg[black]%}[%?>%{$reset_color%}) \
"

RPROMPT="### I want to put the git info here###    %{$bg[white]%} %{$fg[black]%}<! %!%{$reset_color%}%{$fg[black]%}%{$bg[blue]%} <%*%{$reset_color%}"

PS2="%{$fg[yellow]%}> %!%{$reset_color%}"
```

When I updated zsh on my OS X, I found if you use `su` to change your login as root, the `$USER` is NOT `root`, it still the name of that you used it to `su`, but if you run `whoami` after `su`, it will return `root`, so I decided use this to find what user is being using.

**Comment by apjanke** [comment]
Those are double-quotes. You need to either escape the `$` inside them with a `\` like this:

```
RPROMPT="\$(git_prompt_info)    %{$bg[white]%} %{$fg[black]%}<! %!%{$reset_color%}%{$fg[black]%}%{$bg[blue]%} <%*%{$reset_color%}"
```

or (better) switch to single quotes:

```
RPROMPT='$(git_prompt_info)    %{$bg[white]%} %{$fg[black]%}<! %!%{$reset_color%}%{$fg[black]%}%{$bg[blue]%} <%*%{$reset_color%}'
```

You'd be better off using [`%F` sequences](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Visual-effects) instead of that `%{$fg[...]}` stuff, too.

```
RPROMPT='$(git_prompt_info)    %F{white} %F{black}<! %!%f%F{black}%K{blue} <%*%f%k'
```

If you want to keep hacking on this, I'd suggest turning your OMZ custom directory in to its own repo and posting it on GitHub, like [I have here](https://github.com/apjanke/oh-my-zsh-custom). That way other people can get your exact code to try out, and submit PRs and stuff using the normal GitHub tools, without having to clutter up the main OMZ repo. (Just don't put any passwords in it!)

**Comment by mcornella** [comment]
Closing for the time being for not responding. Reopen if necessary.
