### ISSUE TITLE
Capistrano completion is too verbose

### ISSUE THREAD

**Issue by nwalke** [robbyrussell/oh-my-zsh#4447]
I have this in my `.zshrc`: `plugins=(git brew capistrano)`

My autocompletion worked before upgrading to El Capitan, but now when I try to autocomplete `cap`, it just acts like I'm trying to select a file and lists the whole directory rather than generation cap tasks.

**Comment by apjanke** [comment]
The El Capitan upgrade might be a red herring. It doesn't work on my 10.9 box either with the current version of OMZ and `zsh` 5.0.2 or 5.1.1.

The `capistrano` plugin does not try to supply completions for `cap` at this point; see #2454 and check out the `capistrano` plugin source. Looks like it's avoiding `cap` because `zsh` has its own `cap` builtin command, and is using `shipit` instead of `cap` as the capistrano command. But the completion function is still named `_capistrano` instead of `_shipit`, so it may not be getting picked up by `compinit`.

**Comment by nwalke** [comment]
@apjanke Yup, you were right.  shipit does work.

I used to be able to arrow key my way through results, it seems that is also broken. :disappointed:

**Comment by apjanke** [comment]
@nwalke: can you be more specific about what "arrow key through the results" means, and the ways it's failing for you now? I've seen a couple weird things related to parentheses lately, but don't know how to interpret them. This completion stuff is complicated (and subject to personal preference). If you could give us an exact sequence of commands and arrow-key presses, with what you expected and what actually happened, we could maybe reproduce and help debug.

**Comment by nwalke** [comment]
Sure, I can try...  This is using the agnoster theme but it seems to be any theme.

This is what I see currently when I type `shipit fms:create:[tab][tab]':
![screen shot 2015-10-06 at 2 28 17 pm](https://cloud.githubusercontent.com/assets/1617620/10319968/882d7df2-6c36-11e5-991c-6edffd9b3027.png)

I much prefer the directory style auto completion which I'm pretty sure used to work:
![screen shot 2015-10-06 at 2 29 00 pm](https://cloud.githubusercontent.com/assets/1617620/10319998/b05923b2-6c36-11e5-8545-af07ec054fdb.png)

It doesn't have the descriptions of the tasks, but at least I can scroll quickly through long lists with the arrow keys.

**Comment by mcornella** [comment]
You still have that available, but only once the whole completion output has been displayed. Here's a screencast of the same with git completion: https://asciinema.org/a/31012. Notice that _`At xx%`_ below which then changes to _`Scrolling active`_ later and enables selecting an entry.

If you want to automatically start selection of the completion choices, you can put [`setopt menucomplete`](http://zsh.sourceforge.net/Doc/Release/Options.html#index-MENUCOMPLETE) in your zshrc and the first entry will be selected automatically.

BTW, the used keyword now is `capit`, because [`shipit` was also used](https://github.com/shipitjs/shipit) :joy: (#4563)

**Comment by nwalke** [comment]
@mcornella In my directory style completion example (without capistrano task descriptions) I can arrow right and left through the results.  That's the piece I'm missing.

**Comment by mcornella** [comment]
That's because this behavior can also be triggered with `zstyle`, which allows to specify which completion commands you want to behave that way. But the `setopt menucomplete` should make it work for every command you complete, does it not?

**Comment by nwalke** [comment]
Once I have that option set in my .zshrc, it only takes one tab press to get autocompletion which is nice, but I still don't have the directory style autocompletion I mentioned.

https://asciinema.org/a/6ujemaxcrqeji69paumhbwwbf

**Comment by mcornella** [comment]
I don't know if that's possible when completion entries contain a description. In directory style, there is no explanation to give for each entry so it just displays all possible values horizontally.

In `capit`, `git` and others there is a description that explains what each argument does, so that's probably why you don't get the same behavior. I could be wrong about this, but an hour of searching hasn't yield any promising results. The completion system is a big beast and there are all sorts of settings to activate, so if I find something else I'll let you know.
