### ISSUE TITLE
Random character added on El Capitan

### ISSUE THREAD

**Issue by agentphoenix** [robbyrussell/oh-my-zsh#4458]
After updating to El Capitan, I'm noticing that whenever I hit enter to run a command, zsh adds an open bracket character to the start of the line. At first I thought it might be my theme, but it happens on every theme. I did a pull from the repo to make sure I have the latest and greatest, but it's still happening.

Has anyone seen this? Any ideas where I might look to see what's happening?

<img width="127" alt="screen shot 2015-10-04 at 10 46 51 am" src="https://cloud.githubusercontent.com/assets/14422/10268395/4ee50428-6a85-11e5-9fe8-d641c97dd5c5.png">

**Comment by apjanke** [comment]
What terminal emulator program and set of plugins are you using? That bracket is so far to the left that it doesn't look like normal terminal character output; more like a visual "start of prompt" indicator. Those are intentional. E.g. the iTerm 3 beta has them; they appear as little triangles. See the "Shell Integration" section [here](https://www.iterm2.com/features.html).

These depend on the terminal setup; the themes can output additional control characters to adjust where they show up (e.g. for multiline prompts), but depending on your terminal configuration, the shell may not have to output anything for them to appear. There's probably a preference in your terminal application to turn them off.

**Comment by apjanke** [comment]
Oh, yep: that's just what Terminal.app does on El Capitan. Happens with plain zsh and bash, too; it's not specific to OMZ. I don't know how to turn it off.

**Comment by agentphoenix** [comment]
Brilliant! Thanks for the response. Was starting to drive me a little batty!
