### ISSUE TITLE
spaces in $HOME

### ISSUE THREAD

**Issue by u-foka** [robbyrussell/oh-my-zsh#4470]
Hy!

My $HOME env variable contains spaces... it's an osx installation with an ssd and a hdd. I call the hdd: "Data HD" and it's the host for my home folder..

Both install.sh and the default .zshrc fails with this setup. I fixed it by replacing ZSH=~/.oh-my-zsh lines in both to ZSH="$HOME/.oh-my-zsh"

Now it seems to work :)

**Comment by apjanke** [comment]
Oh crap! Spaces in directories should totally be supported.

We usually are not completionists about quoting, because it's not required in `zsh`*. But the install script runs under `sh`, so we need to quote aggressively there. Will fix this. Thanks for the heads-up!

*Unless you have certain options set, but `emulate -L zsh` is the way to protect against that.

**Comment by u-foka** [comment]
You are totally right, reverted $ZSH in my .zshrc to the original and it still works!
I was confused because I first changed the installer to $ZSH="~/.oh-my-zsh" and then it cloned the config into "/path to my home/~/.oh-my-zsh"

**Comment by apjanke** [comment]
After thinking about this a bit, I'm not sure OMZ should support it after all. In general, paths with spaces and other special characters should be supported by our code. But the particular case of a home directory with spaces in its name may be different. We could fix the installer and `~/.oh-my-zsh` to work with this. But a lot of other things, both in OMZ and other other software, are probably going to break in this case, with failure modes that could include significant data loss. Lots of software doesn't expect or protect against this case, especially anything that uses tilde expansion in shell scripts.

We might be better off having OMZ check for spaces in the home directory, and refusing to install or run in this case. Thoughts, @mcornella and/or @robbyrussell?

If I were you, I would rename my HD or make some other configuration change so the path to your `$HOME` directory doesn't have spaces in it. You're likely to run in to a lot of other Unix things that break under that setup, even if OMZ works.

**Comment by u-foka** [comment]
Well... what you're saying is totally makes sense, but on the other side, I've been using this setup for years and had no serious problems after all. Once or twice, I had a problem when trying to build software from source, but with some quotation marks, I was always able to fix it. The biggest problem I can remember that the Qt developer package does not work when installed on a path that contains spaces, but I found a neat warm place for it under /opt :) It seemed to be easier than changing my $HOME. I'm a bit afraid of what could possibly break if I suddenly change my home to a different location.

After all it seems to be a good reminder for me when working on my own sw projects, not to forget the quotation marks :))

Anyway in my opinion, refusing the installation might be a bit too strict, but a warning with an additional confirmation seems to be a good idea.

p.s.: OMZ seems to work correctly on this setup, I've already enabled some plugins and played around with it since yesterday, and found no additional problems.

**Comment by apjanke** [comment]
Once you have it installed, core OMZ itself should work pretty well, because it uses `zsh` internally, which normally doesn't care about spaces in variables. It's the things its various functions and plugins call out to that might use other shells or parsing logic internally that would be problems. And we've got a lot of plugins. I'd just be really worried that some installer or something is going to do a `-e ~/Dropbox` existence check, it'll return a spurious false, and it'll feel free to clobber a bunch of your files because it thinks it's working with a blank slate. I seem to remember a system updater that had a bug like that a few years back which would wipe your entire hard drive if it got triggered. (And just in general, I'd be nervous with a setup that required extra care in `bash` or `sh`. But hey, it's your machine...)

On the other hand, if it's working for you, and especially if we put out a warning in the OMZ installer, yeah, we probably shouldn't be that nannyish. And it wouldn't be a ton of work to do. Curious to hear what the core OMZ developers think.

**Comment by fredden** [comment]
I've just discovered this issue having recently installed OMZ on Windows with a space in $HOME. The patch I wrote locally to get this working is in pull request #6587, but the patch in the previously linked commit seems more complete.
