### ISSUE TITLE
When I try to cd to directory with zsh I get an error

### ISSUE THREAD

**Issue by ShaoXinSen** [robbyrussell/oh-my-zsh#4513]
<img width="546" alt="2015-10-18 22 37 33" src="https://cloud.githubusercontent.com/assets/13616801/10564564/5f1024ec-75eb-11e5-97f5-2c01d4fca5df.png">

But it can easily into cp directory in bash environment.

<img width="461" alt="2015-10-18 22 55 24" src="https://cloud.githubusercontent.com/assets/13616801/10564593/6da55cec-75ec-11e5-83b4-74bbce72b2b5.png">

**Comment by mcornella** [comment]
This *may* be related to removing `cdpath=(.)` back in [#3597](https://github.com/robbyrussell/oh-my-zsh/pull/3597/files#diff-c4cfd9553e70a4308cc75baacaf69527L37). Please do an `echo $cdpath`, and try `cdpath+=(.)` to see if it fixes it.

**Comment by ShaoXinSen** [comment]
After do an `echo $cdpath`, it just lik print `\n`

```
 ~  echo $cdpath

 ~ 
```

Do you mean add `cdpath+=(.)` into `completion.zsh`?

I get an error after do this.
`~/.oh-my-zsh/lib/completion.zsh:42: no matches found: -cdpath=(.)`

**Comment by mcornella** [comment]
Ok, no that's not it. Please post the output of `which cd`

**Comment by ShaoXinSen** [comment]
@mcornella 

It output  `cd: shell built-in command`

**Comment by apjanke** [comment]
Does it happen with other directory names? Do you have a global alias set up for `cp`? (Try `which cp`.) This error message happens when using the two-argument form of `cd`. If you have a multi-word global alias for `cp`, that would trigger this issue.

```
[~]
$ which cd
cd: shell built-in command
[~]
$ cd foo bar
cd: string not in pwd: foo
[✘ ~]
$ mkdir cp
[~]
$ alias -g cp="cp --some-switch"
[~]
$ cd cp
cd: string not in pwd: cp
[✘ ~]
$
```

If it's a `cp` alias, make it non-global, or remove it. I'd recommend not using global aliases anywhere, because they break stuff in this manner and are hard to diagnose.

If it's not a `cp` alias or similar, please run `omz_diagnostic_dump` and post the output as a gist, so we can get some detailed diagnostic info.

**Comment by ShaoXinSen** [comment]
@apjanke 

Thank you very much.

 I found that `alias -g cp='cp -i'` in my config `.zshrc`.

Now i have remove it and it's ok.

**Comment by apjanke** [comment]
Excellent.

If that worked, could you close this issue out?

**Comment by mcornella** [comment]
Nice find @apjanke!
