### ISSUE TITLE
Issues on dpoggi theme 

### ISSUE THREAD

**Issue by leoheck** [robbyrussell/oh-my-zsh#4529]
I usually use the `dpogi` theme but it looses itself sometimes. 
It looks like this where the pipe is the input prompt.

```
leco@gaphl12:~ » |
```

Somtimes, the prompt goes before the `»` character.

```
leco@gaphl12:~ | » 
```

Somtimes, some substring from last command polutes the command line, like this example with a cat:

```
leco@gaphl12:~ » cat|cat myfile.txt
```

Someone knows how to improve the theme?

**Comment by apjanke** [comment]
Hmmm.  Might be your terminal emulator or `zsh` itself getting confused about cursor location because of ambiguous widths of some of those special characters in the prompt, or some non-printable character isn't getting guarded correctly? The prompt string itself looks like it's all properly protected.

What OS, terminal emulator, and font are you using?

Are there any command sequences which can reliably reproduce the bad behavior?

**Comment by leoheck** [comment]
This usually happens in ```TERM=xterm-256color```. Which has xterm version ```XTerm(215)```
running on CentOS 5.10 (very old OS) with ```zsh 4.2.6 (x86_64-redhat-linux-gnu)```. The font I don't know how to get.

But (I think) this glitches happens on my Ubuntu 14.04 with ```XTerm(297)``` with ```zsh 5.0.2 (x86_64-pc-linux-gnu```

Actually, I think the problem is related to commands which have multiples lines

**Comment by neochar** [comment]
> This usually happens in `TERM=xterm-256color`
Thanks @leoheck, I fixed it by changing TERM value to default one.

**Comment by mcornella** [comment]
I can't reproduce this issue.
