### ISSUE TITLE
history-substring-search not working after recent update

### ISSUE THREAD

**Issue by fbbdev** [robbyrussell/oh-my-zsh#4540]
I updated oh-my-zsh on monday and the history-substring-search plugin stopped working without error messages. Zsh version is 5.0.8.

**Comment by apjanke** [comment]
Working for me on OS X 10.9.5 with zsh 5.0.2 and 5.1.1, and on OS X 10.11 with zsh 5.0.8.

Could you post the output of `omz_diagnostic_dump` as [a new Gist](https://gist.github.com/), so we can see some details on what's going on with your OMZ setup?

**Comment by fbbdev** [comment]
Here it is https://gist.github.com/fbbdev/b12abaa00c89d6799015
I suspect it's a key mapping problem, home and end keys also stopped working on the command line.

**Comment by apjanke** [comment]
Could well be. Your bindings look right, but that stuff is tricky, and there could be something I'm not seeing. I'm assuming that the "stopped working" part is that up and down arrow no longer do the history substring search? What do they (and home/end) do now, if anything?

These are the up and down arrow bindings from your diagnostic dump.
```
"^[OA" history-substring-search-up
"^[OB" history-substring-search-down
```
And the home and end bindings:
```
"^[OF" end-of-line
"^[OH" beginning-of-line
```

Those look right for an `xterm-256color` tty, which your `$TERM` is set to. (Just make sure the terminal you're using is actually emulating an xterm.)

Those bindings probably depend on the [application mode hooks](https://github.com/robbyrussell/oh-my-zsh/blob/e44aa50301cbdb9c713193263e6c0c5a9a5798c0/lib/key-bindings.zsh#L5-L16) working. If something is messing with those, it could cause you problems. (We should probably add those and other well-known `zsh` hook functions to the diagnostic dump.)

You could try doing Ctrl-V and then up/down arrow to verify what sequences they're sending.

You also have a custom `zsh-syntax-highlighting` plugin. There is at least some interaction between `zsh-syntax-highlighting` and `history-substring-search`, though I don't know the details. Try running without `zsh-syntax-highlighting` and see if that makes a difference.

**Comment by fbbdev** [comment]
Up/Down keys scroll through the history (normal behavior, without substring search).
Home/End keys when pressed emit beeps and do nothing.
I'm using `gnome-terminal` which is based on libvte. It should emulate an xterm.

Using Ctrl-V gives the following results:
- **`↑`:** `^[[A`
- **`↓`:** `^[[B`
- **`Home`:** `^[[H`
- **`End`:** `^[[F`

Disabling `zsh-syntax-highlighting` did not help.

**Comment by apjanke** [comment]
Well, that's a good clue: those up and down arrow sequences do not match the `xterm-256color` key bindings you have for the `history-substring-search-*` actions. However, they do match the key sequences sent by xterm when it's in "local echo" keypad mode instead of "application" (aka "transmit") keypad mode. This is what happens when that [`smkx`/`rmkx` logic in the `lib/key-bindings` hooks](https://github.com/robbyrussell/oh-my-zsh/blob/e44aa50301cbdb9c713193263e6c0c5a9a5798c0/lib/key-bindings.zsh#L5-L16) isn't working. (`smkx`/`rmkx` are what enable "keypad transmit" mode while the command line editor is running.)

You can see #2735 for a full, gnarly example of this in action, where the issue broke this same plugin for other users.

There's at least three possibilities:
* Something in the recent update broke the `smkx`/`rmkx` logic for you, and now your terminal is sending different codes for the keypad button while you're editing the command line
* You were running a really old version  of `history-substring-search` (from early 2014, before [this commit](https://github.com/robbyrussell/oh-my-zsh/commit/c563fe95fbf58721caa7de0ffe5d8117a6ada51a#diff-8a89e17b88cab8e5ddc9a24d7fb78afb) which used hardcoded key bindings and the "local mode" xterm key codes instead of the "transmit mode" key codes. Your terminal has been sending the same codes all along, but `history-substring-search` changed what it was binding to. (The new way is probably what you actually want, since it's what terminfo supports and zsh itself seems to be settling on.)
* Something else outside of OMZ changed recently and it's affecting something in this chain of bindings.

Welcome to the unpleasant fiddly parts of terminal configuration. One of OMZ's goals is to take care of this for you and make it work by default. But we're still getting there.

Regardless of the underlying cause, I think the best approach to fix it (and to determine what went wrong) is to figure out why your `smkx`/`rmkx` isn't working. What are your `zle-line-init` and `zle-line-finish` functions defined as?

```
[~]
$ which zle-line-init
zle-line-init () {
	echoti smkx
}
[~]
$ which zle-line-finish
zle-line-finish () {
	echoti rmkx
}
[~]
$
```

**Comment by jtbairdsr** [comment]
I was having a similar problem just now but I noticed that i had `bindkey -v` set in my `.zshrc`.  when I commented that out it seamed to fix it so you might look into a conflict with vi mode.  I noticed that you do have the same setting in `/etc/zshrc` so commenting that out could solve the problem for you (although then you lose your vi mode which is kind of a big trade off so it is up to you)

I hope this helps some.

**Comment by apjanke** [comment]
@jtbairdsr: Yeah, that's one of the problems. The thing about `bindkey` is that it installs a key binding into the *current* keymap, the one which is aliased to `main`. In OMZ, that is the `emacs` keymap, because [`lib/key-bindings.zsh` sets `bindkey -e`](https://github.com/robbyrussell/oh-my-zsh/blob/e44aa50301cbdb9c713193263e6c0c5a9a5798c0/lib/key-bindings.zsh#L18) early on in the initialization process.

Unless you load the `vi-mode` plugin, which [switches to the `vi` keymap](https://github.com/robbyrussell/oh-my-zsh/blob/e44aa50301cbdb9c713193263e6c0c5a9a5798c0/plugins/vi-mode/vi-mode.plugin.zsh#L28), so all bindings made before loading `vi-mode` are in the `emacs` keymap, and all bindings made after that (including in subsequently loaded plugins) are made in the `vi` keymap.

If you do the `bindkey -v` after loading OMZ, then you lose all the bindings made by OMZ and its plugins (unless you also load the `vi-mode` plugin). (I'm guessing this is what happened to you, @jtbairdsr). If you do `bindkey -v` before loading OMZ, it has no effect (except for key bindings you then make yourself also before loading OMZ), because OMZ switches back to the `emacs` keymap. Same with the setting in `/etc/zshrc`: OMZ will switch back to the `emacs` keymap. So the end effect depends on whatever else is also switching keymaps.

It's a bit of ping-pong, and hard to get things entirely consistent or understandable this way. We might want to add a keymap preference to OMZ to tell it which keymap to default to. And some plugins which are keymap-specific (like `vi-mode`) might want to switch to explicitly installing their bindings into a specific keymap, instead of the current `main` one.

`zsh`'s own keymap default [depends on the values you have set for `$EDITOR` or `$VISUAL`](http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#Keymaps).

**Comment by jtbairdsr** [comment]
@apjanke: That makes things much more clear.  Thanks!  

I have been fiddling with it and I have found that if I have the `vi-mode` plugin active it doesn't like to work even if I put that plugin first.  I think it has to do with detecting the wrong keybinding from terminfo but I don't really know why.

I have found a rather hacky (and therefore temporary) fix.  I put the `vi-mode` plugin first and then simply explicitly declare the binding in the section that says `Customize to your needs...`.  

```
plugins=(
	vi-mode                  # This plugin increase vi-like zsh functionality.
        ...
	zsh-syntax-highlighting  # commandline syntax highlighting
	history-substring-search # This is a clean-room implementation of the Fish shell's history search
)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

# ********************************** BINDKEY ********************************* #

# ----------- hack to fix the broken history-substring-search plugin --------- #
bindkey "^[[A" history-substring-search-up
bindkey "^[[B" history-substring-search-down

```
I know that this isn't really a fix but it is working to give me both `history-substring-search` and `vi-mode` for now until a real fix can be found.

**Comment by apjanke** [comment]
@jtbairdsr: That's a related issue. The `vi-mode` plugin currently breaks the `smkx`/`rmkx` support, so `$terminfo` based key bindings for the up and down arrows won't work if you load `vi-mode`; see #2735. It's waiting on #4191 to fix it.

But @fbbdev doesn't have `vi-mode` loaded, so something else may be breaking it for him.

**Comment by fbbdev** [comment]
Thank you for pointing me to the `zle-line-init` widget. My theme is overriding it, I'm opening an issue there. Closing this since it is not related to oh-my-zsh.
