### ISSUE TITLE
[ASK] [THEME] about tonotdo

### ISSUE THREAD

**Issue by sachin21** [robbyrussell/oh-my-zsh#4546]
# WHAT
- subject: theme
- theme: tonotdo

# ASK
I think space is needed in next to ➜  but I'm not sure.
Is this only my problem?

# SAMPLE
I wrote sample code.
I added a space in next to ➜.

path: ./oh-my-zsh/themes/tonotdo.zsh-theme

```diff
-PROMPT='%{$fg_no_bold[cyan]%}%n%{$fg_no_bold[magenta]%}➜%{$fg_no_bold[green]%}%3~$(git_prompt_info)%{$reset_color%}» '
+PROMPT='%{$fg_no_bold[cyan]%}%n%{$fg_no_bold[magenta]%}➜ %{$fg_no_bold[green]%}%3~$(git_prompt_info)%{$reset_color%}» '
```

# REF
- tonotdo: https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/tonotdo.zsh-theme
- my dotfiles: https://github.com/sachin21/dotfiles/commit/433b3f42a1ed6239aaf303e532e0e3e9fafeb7e2#diff-a2a09db31be38b45553c68ac2a746d46R61

**Comment by apjanke** [comment]
This looks like it might be a problem with certain fonts.

Here's how it looks for me in Terminal.app on OS X.

With Menlo or Meslo, the characters do not overlap, and it looks fine.

<img width="1111" alt="tonotdo - meslo" src="https://cloud.githubusercontent.com/assets/2618447/10865662/3bfc14ae-7fe9-11e5-9009-86c3d0417c8b.png">

With Courier, the ➜ is displayed as two characters wide, and it overlaps with the following text.

<img width="949" alt="tonotdo - courier" src="https://cloud.githubusercontent.com/assets/2618447/10865663/4d46405e-7fe9-11e5-8dea-be13ebdb95f2.png">

Basically, the font and the terminal don't agree on how wide the character should be. Most of the fonts on my Mac OS X system think ➜ is double-width, like Courier. Menlo seems to be the exception. But both Terminal and iTerm think it's single-width. (There may also be complications where some fonts don't actually include the ➜ glyph, so it's actually using some fallback font for that particular character.)

In no case should spaces be necessary to keep characters from overlapping in the terminal display. This is a bug in the font and/or terminal text rendering stack. But it's not an easy fix, because fonts don't include monospace-cell-count info in them, so terminals have to rely on heuristics or their own size tables or some other hack.

You could switch to Menlo for use with this theme. If you want to add the space in for use with other fonts, maybe you could put it inside a conditional like `if [[ $TONOTDO_WIDE_ARROW == true ]]` to enable use of this theme with "wide-arrow" fonts, but leave the default behavior the same, since it seems to be developed for fonts where the arrow is single-wide.

@To1ne, as the original `tonotdo` author, what font(s) were you using when developing this? Thoughts?

**Comment by To1ne** [comment]
I think I've been using Deja Vu at the time.
But to be honest, I do no longer use this theme, I am using [agnoster](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes#agnoster) now. So I do not really care about the changes in this theme. Just file a PR of your suggested change.

**Comment by sachin21** [comment]
Okay, I'll be using agnoster.
Thank you :smile:
