### ISSUE TITLE
exit code not cleared

### ISSUE THREAD

**Issue by sagarjoglekar** [robbyrussell/oh-my-zsh#4560]
Hi, 
I have been observing a strange behaviour with the shell. If you mistype a command and if the command is invalid, the zsh prints command not found with a error code exit 127 or whatever the code it may be. But it fails to clear the buffer and every new line would print the same error again and again unless you type a valid command or manually clear the terminal buffer using clear. 
Is this bug related to oh-my-zsh ? 
Thanks
<img width="914" alt="screenshot 2015-10-29 12 02 43" src="https://cloud.githubusercontent.com/assets/2430919/10817881/f912bd4c-7e34-11e5-85a2-b4064838b004.png">

**Comment by ncanceill** [comment]
Hi,

Actually this behavior has nothing to do with OMZ. It works the same in Bash and in vanilla Zsh.

Also, it is by design: the exit code corresponds to the last command executed by the shell. When you simply type enter, the shell does not execute any command, and thus preserves the last exit code.

If you are looking for a command that does nothing else than set the exit code back to 0, try `true`.

**Comment by sagarjoglekar** [comment]
Thanks for the clarification.. Is this an expected behaviour of zsh ? Because when I switch back to bash, this ceases to happen. 
Thanks

**Comment by ncanceill** [comment]
Oh, maybe I was not clear. There are two things here:
- The exit code of the last command is preserved when enter an empty command
- The prompt displays the exit code when it is not zero

The former is an expected behavior of pretty much all shells, explicitly including Zsh and Bash.

The latter is an expected behavior of your OMZ theme.

**Comment by sagarjoglekar** [comment]
Oh, Now I get it. Thanks.
