### ISSUE TITLE
`du` command completion broken since update to 10.11

### ISSUE THREAD

**Issue by hashier** [robbyrussell/oh-my-zsh#4573]
I upgrade to 10.11 and the `du` command is since then behaving strangely.

I expect `du` to show a list of files (as it always did) but now it only shows options and never shows files again.

Example:
When I write `du<space>` into the console and press TAB I just end up with this:
```
$ du -
```
another TAB
```
$ du -
- option
-H  -- follow symlinks on the command line
-I  -- ignore files/directories matching specified mask
-L  -- follow all symlinks
-P  -- do not follow symlinks (default)
-a  -- report sizes for all files, not just directories
...
```

If I remove the `du` line from the completion file list (~/..zcompdump) for files work but not option. Is there a way to get both working?

**Comment by apjanke** [comment]
I can reproduce on El Capitan with `zsh` 5.0.8.

This seems to be an issue with `zsh` itself, not Oh My Zsh. The same behavior happens if I run `zsh` without OMZ.

Looks like it's fixed in `zsh` 5.1.1: if I install and run the Homebrew `zsh`, which is now at 5.1.1, `du` completion works as expected again. [This change in `zsh`'s `_du`](https://github.com/zsh-users/zsh/commit/806f73a0b3d3959d5af12ce97e0258b4d4fe7d76#diff-f9dc10b05cb3a1fb1e4de69131cab62e) looks like what fixed it. That's the same diff I see between the 5.0.8 and 5.1.1 `_du` functions installed on my machine.

As a hack, you could just grab the [latest version of `_du` from `zsh`](https://github.com/zsh-users/zsh/blob/master/Completion/Unix/Command/_du) and get it on your `$fpath`. The traditional way to do that would be to put it in `/usr/local/share/zsh/site-functions`. This is on the `$fpath` in `zsh` by default. That would fix it on a per-machine basis. You could also make a custom OMZ plugin out of it if you're syncing your custom OMZ between machines and wanted to make it not rely on per-machine configuration.

**Comment by apjanke** [comment]
Ping... is the hack or version bump working for you?

**Comment by hashier** [comment]
Wow, thanks for this verbose answer. I learnt a lot. I just tested it.
I installed zsh via brew and now it works. Will definitely look now into fpath. And thanks a lot for the link to the _du change commit, was really interesting! I'm closing this issue.

**Comment by apjanke** [comment]
You're welcome! Glad to be of help.

**Comment by d0u9** [comment]
Well, I use `gdu` -- a GUN version `du` command instead.

**Comment by johnt337** [comment]
@apjanke works like a charm.

`curl -sL https://raw.githubusercontent.com/zsh-users/zsh/master/Completion/Unix/Command/_du -o /usr/local/share/zsh/site-functions/_du`

Just noticed curl tab completion is doing them same thing, on to the next issue!
