### ISSUE TITLE
POST_1_7_2_GIT on command list 

### ISSUE THREAD

**Issue by muhasturk** [robbyrussell/oh-my-zsh#4583]
When I enter post then press tab button, temrinal shows me a bunch of commands that includes "POST_1_7_2_GIT". What exactly do this command do and why is it on command list? I think it is related  `/lib/git.zsh`

**Comment by ncanceill** [comment]
Hi, and thanks for reporting.

This is correct. This variable was added in order to fix a compatibility problem, because Git versions prior to 1.7.2 do not support the `--ignore-submodules=dirty` flag. Alas, like too many other variables in the OMZ code, it leaks into the shell session.

The solution is to declare it `local` but this has to be done from within a function scope — should be easy, since it is only used in [the `parse_git_dirty` function](https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/git.zsh#L12-L30). Sadly there is an issue: if we move [the declaration](https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/git.zsh#L177) into the function's body, the version comparison will be run every time the function is called, which depending on your theme could occur every time your prompt returns.

@apjanke I vaguely remember that you were tracking this sort of issues, do you have input?

**Comment by apjanke** [comment]
Yeah, moving it inside `parse_git_dirty` and running the check each time it's called could be a problem for responsiveness, especially on Cygwin or other systems where shelling out is more expensive. I'd avoid doing that. A long-term fix might be switching to use `zsh`'s internal VCS info support instead of shelling out to the `git ` command.

An easy mitigation might be to rename it to `$_OMZ_POST_1_7_2_GIT` or `$_OMZ_GIT_POST_1_7_2`. Less likely to show up in completion contexts, and more obvious where it came from.

Or if you wanted to do a more drastic change to make OMZ's settings less visible to the user, you could collect miscellaneous scalar-valued OMZ variables into an `$_OMZ_STATE` associative array and declare it hidden using `typeset -AH`.

**Comment by apjanke** [comment]
Related: #3885 is trying to figure out how to avoid completing variables at all. I don't have a solution for it.

**Comment by Marcholio** [comment]
This could be closed now.
