### ISSUE TITLE
Plugin for Module Environment

### ISSUE THREAD

**Issue by leoheck** [robbyrussell/oh-my-zsh#4587]
Hi, someone knows if there is some plugins for [Environment Modules](http://sourceforge.net/projects/modules/?source=typ_redirect). If the answar is no, is it possible to point some references about how to create plugins and/or commands for auto completion?

**Comment by apjanke** [comment]
Nope, no plugin for Environment Modules. Seems like it would be useful.

We don't have a "how to create a plugin" guide exactly, as far as I know. There's a few Wiki pages that could be useful.

https://github.com/robbyrussell/oh-my-zsh/wiki/Contribution-Technical-Practices
https://github.com/robbyrussell/oh-my-zsh/wiki/Coding-style-guide
https://github.com/robbyrussell/oh-my-zsh/wiki/Design

If you're going to do installation discovery, check for the Homebrew installation on Macs, too. There's a Homebrew formula for Environment Modules (`brew install modules`). And make sure the README for the plugin references the main project page and explains what it is. That's an awful generic sounding name. :)

**Comment by leoheck** [comment]
Yes, this is a bad name, thank you for the references. 

I din't understand what you want to say with "_If you're going to do installation discovery..._" but I know how to install it and I also have the whole modules environment ready. 

I was thinking that will be usefull to have a plugin for the modules autocompletion. I will try to code something.

Ah, I am using linux, not osx.

**Comment by apjanke** [comment]
"Installation discovery": It's not about installing it per se, but about how to find where it's installed and load it in to your `zsh` session conveniently and portably. Depending on how you install Environment Modules, it could end up in different locations on your system. So to load it, you need to know where to find the file. One useful thing a plugin can do is look in several well-known locations to see if and where Environment Modules is installed on the current machine, and then automatically load it from one of the locations it finds. That way, all someone needs to do to use Environment Modules is install it on their machine and put `modules` (or whatever we end up calling it) in their `$plugins` list, and it will get loaded in to their session. The `autojump` plugin has a good example of this where it [looks in several locations for the `autojump` installation](https://github.com/robbyrussell/oh-my-zsh/blob/e44aa50301cbdb9c713193263e6c0c5a9a5798c0/plugins/autojump/autojump.plugin.zsh#L2-L20) and then loads it from whatever it finds.

For example, you probably have it installed in the location that either your Linux distribution's package manager put it, or the default installation location if you built it from source. Other Linux distros might have a different installation path. And if I installed it on my OS X box using `brew install modules`, it might end up somewhere different again. Having the plugin discover where it's installed means users don't have to put hardcoded paths in their `~/.zshrc` file, and that file can be easily synced across different systems.

Yeah, completion would be useful. Completion definitions and installation discovery are two of the main features that OMZ provides. There are two approaches you could take. It looks like `modules` comes with `bash` completion definitions, and `zsh` has a compatibility layer that can load them in. So you can just pull them in from the `modules` installation. Or you could code up `zsh`-specific completion definitions, which would be more work, but would probably end up being more powerful, since `zsh` has a more sophisticated completion system. (If they're good, and the upstream project is active, you could even get them backported to the main project.)

If you coded it up to work on Linux, then I or someone else who runs OS X could tweak it to run there, too.

**Comment by leoheck** [comment]
Thank you for this big answare! I think it is just required to query the Environment Variables for Modules. Look my setup.

```
lheck@saturn:~ » echo $MODULESHOME 
/usr/local/Modules/3.2.10

lheck@saturn:~ » echo $MODULEPATH 
'/usr/local/Modules/modulefiles:/home/lheck/Dropbox/Scripts/Modules/Staturn
```

_I din't notice before_ that autocomplete for modules are already working in my notebook using a stantard instalation. At my work, it is on different path and it still autocompletes :) . We don't need to code! 

Isn't it working on OSX?

**Comment by apjanke** [comment]
That begs the question of how `$MODULESHOME` and `$MODULEPATH` get set. Those aren't provided by `zsh` or the OS by default, at least on OS X; you need to run the Environment Modules init script in your shell startup sequence to set those. Maybe your Linux distro included `zsh` startup hooks for them as part of the installation? I had to add it to my `~/.zshrc` manually on OS X to get it to load.

**Comment by leoheck** [comment]
I am doing with the Environment Modules init script as you said. With `source /soft64/Modules/current/init/zsh` in `.zshrc`.  And the same for the other shells I have like bash and (t)csh. I think this is the right way to do that, isn't it?

**Comment by apjanke** [comment]
Yes. That will work fine for a single installation. Having something do installation discovery would be useful if you wanted to use the same `~/.zshrc` file on multiple machines, where Environment Modules might be installed in different locations on different machines.

**Comment by leoheck** [comment]
This is a good point but I think you should know your environment. You can have a single '.zshrc' but  tou always need to know the environment. With this, you can make the selection considering the hostname or something.

**Comment by mcornella** [comment]
I'm closing this for lack of follow-up.
