### ISSUE TITLE
Parse error since last update

### ISSUE THREAD

**Issue by MrHalfman** [robbyrussell/oh-my-zsh#4610]
Hi,

I have this error since the last update :
``/home/****/.oh-my-zsh/oh-my-zsh.sh:42: parse error near `||'``

Which is preventing zsh from starting.

**Comment by apjanke** [comment]
Hmm. It's still working for me (on OS X Cygwin), and `oh-my-zsh.sh` itself hasn't changed since September 28.

Can you do a `git status` in `~/.oh-my-zsh` to make sure you don't have any local modifications?

If you're all synced up, then doing a `zsh -lx 2>zsh.log` and just doing `exit` in the resulting shell session will get you a trace log of what `zsh` is doing on startup, which could help track down the issue.

**Comment by MrHalfman** [comment]
I found the issue : it's related to #4069 

The autocrlf in my .gitconfig was set to true, setting it to false fixed the problem after a new installation.
