### ISSUE TITLE
call compinit after sourcing plugins

### ISSUE THREAD

**Issue by Konfekt** [robbyrussell/oh-my-zsh#4614]
https://github.com/zsh-users/zsh-completions erroneously says that to install `zsh-completions`, add

``` sh
plugins+=(zsh-completions)
autoload -Uz compinit && compinit -i
```
to `~/.zshrc.`

However, correctly,
```sh
source $ZSH/custom/plugins/zsh-completions/zsh-completions.plugin.zsh
```

must instead be added, because `source $ZSH/oh-my-zsh.sh` FIRST calls `compinit -i -d "${ZSH_COMPDUMP}"` and only then sources the plugins.

If instead `compinit -i` is called again after  `source $ZSH/oh-my-zsh.sh` then zsh starts noticeably slower.

**Comment by apjanke** [comment]
Sounds like this bug should be posted in the `zsh-completions` repo instead.

It looks like their plugin structure isn't entirely compatible with OMZ's. OMZ expects plugins to have all their autoloadable files or completion definitions in the main directory of the plugin, and to let OMZ do the `compinit`. Otherwise, the number of functions on `$fpath` fluctuates, and `compinit` can't use its cached `compdump` file, which is why you're seeing the slowdown.

**Comment by apjanke** [comment]
Hmm. Or maybe `compinit` can use its cached `zcompdump` file if things are aligned correctly? The call OMZ makes is using an explicit `-d` and the extra `compinit` is not, so they should be looking at different dump files. Only the plain `compinit -i` before sourcing OMZ and the plain `compinit -i` afterwards should be having conflicts. Is startup still slow if you just move the explicit `compinit` after sourcing OMZ, instead of adding a second one? (Not that it really matters, since I think doing a second `compinit` after OMZ is loaded will break non-autoloaded completion definitions.)

**Comment by Konfekt** [comment]
Well observed, a secon `compinit -d ~/.zcompdump-linux-9w9w-5.0.5` after `oh-my-zsh.sh` does not noticeably change startup time.

Ok, so in conclusion we advise the `zsh-completions` people to move `./src` into `.` (instead of adding it to the `fpath`, which is what `zsh-completions.plugin.zsh` does) and remove the `compinit` after `plugins+=(zsh-completions)` ?

**Comment by Konfekt** [comment]
Again, to understand better, calling compinit after sourcing the plugins would resolve this issue.  But probably break other things?

**Comment by apjanke** [comment]
> Ok, so in conclusion we advise the zsh-completions people to move ./src into . (instead of adding it to the fpath, which is what zsh-completions.plugin.zsh does) and remove the compinit after plugins+=(zsh-completions) ?

Well, at least to tell them what's going on, and tell them that's an option that would work. Or to build the plugin version as a separate repo. It's kind of a large change to their structure, would break things for the existing non-OMZ users of `zsh-completions`, and is a restriction that would make their source structure kind of ugly. Oh My Zsh is not the primary target of `zsh-completions`.

Might be nice to consider a change on the Oh My Zsh side to support additional plugin structures, including something that would work nicely with repos like `zsh-completions`.

**Comment by apjanke** [comment]
> Again, to understand better, calling compinit after sourcing the plugins would resolve this issue. But probably break other things?

Yes, I believe so.

There's a bunch of completion definition commands in plugin definition files themselves, and not in the autoloaded `_foo` files.

```
[~/.oh-my-zsh/plugins on ⇄ master]
$ grep -r compdef */*.zsh
ant/ant.plugin.zsh:compdef _ant ant
bower/bower.plugin.zsh:compdef _bower bower
brew-cask/brew-cask.plugin.zsh:compdef _brew-cask brew
brew-cask/brew-cask.plugin.zsh:  compdef _brew-cask brew
bundler/bundler.plugin.zsh:    compdef _$cmd bundled_$cmd=$cmd
cabal/cabal.plugin.zsh:compdef _cabal_commands cabal
```

I think (but am not sure) that when `compinit` is called for a second time in the same session, the completion system gets reset, so the effect of these commands would be lost.

**Comment by Konfekt** [comment]
Ok, to clarify: Suggested was that ohmyzsh itself calls compinit once after sourcinflg the plugins. So a single time. This still breaks things? If not my obvious pull request would be to change that order. 

Otherwise perhaps the best bet is to let ohmyzsh take inti account sourcing files from a src folder besides the main folder too,  this project dile structure is quite standard.

**Comment by apjanke** [comment]
>  Suggested was that ohmyzsh itself calls compinit once after sourcinflg the plugins. So a single time. This still breaks things?

Yep, breaks all the same stuff. `compdef` and related commands depend on `compinit` already having been run.

> Otherwise perhaps the best bet is to let ohmyzsh take inti account sourcing files from a src folder besides the main folder too

That sounds good to me. Would allow plugins more flexibility in setting themselves up, and would be easy for `zsh-completions` and so on to adapt to. I think it would make sense to use folders named `functions` or `completions`, since those are conventional `zsh` directory names for storing autoloadable functions in. (And they're the names already used by [core Oh My Zsh for supplementary functions](https://github.com/robbyrussell/oh-my-zsh/blob/135c3763ccfb07c4a5cde9a2529dfa8d6ba19b39/oh-my-zsh.sh#L9), even though the don't exist right now; see also #4102.)

Then all `zsh-completions` would have to do is symlink `functions` to `src` in their repo and they'd be good to go, I think. Simply loading it as a normal plugin would work; no need for additional `compinit` calls. The main `zsh-completions.plugin.zsh` would be changed to be empty or just have a comment (since the existence of that file is used to determine if a plugin really is one.)

**Comment by Konfekt** [comment]
Ok, so how about adding a check if a `completions` or `functions` subfolders in the plugin folder exists, and, if so, add them,

https://github.com/robbyrussell/oh-my-zsh/blob/4589bc6c654650d52a47b5cb86c588f4ab2aca46/oh-my-zsh.sh#L48

? I'd propose a push but would be glad if a zsh expert could come along.

**Comment by apjanke** [comment]
Sorry for long time with no response.

Yeah, that sounds like a good idea to me. Might have to be a bit careful with path ordering and whether these functions should mask core OMZ functions or not.

**Comment by mcornella** [comment]
This is not something we'll implement in the short time. Related: https://github.com/zsh-users/zsh-completions/issues/603
