### ISSUE TITLE
_git-config:1140: permission denied:

### ISSUE THREAD

**Issue by 2Dou** [robbyrussell/oh-my-zsh#4629]
On raspbian, I type the command like this:
`git config remote [TAB]`

it tell me:`_git-config:1140: permission denied:` when I pressed the [TAB] 

my system info:
`zsh 5.0.7`
`Linux raspberrypi 4.1.7-v7+ #817 SMP PREEMPT Sat Sep 19 15:32:00 BST 2015 armv7l GNU/Linux`

thanks.

**Comment by apjanke** [comment]
Try doing `set -x` and then doing that completion again. That will turn on tracing output so you can see what command it was trying to execute when it got that permission denied error.

**Comment by mcornella** [comment]
That won't work to trace a completion function. You need to capture the output by writting the command you want to complete (in this case, `git config remote`) and then pressing `CTRL`+`X` `?`. It will capture the output and put it in a temporary file, post that in a gist please.

**Comment by apjanke** [comment]
Why won't `set -x` work for completion functions? It seems to trace completion functions for me when I enable it and request a completion by hitting Tab.

Regardless, that `Ctrl-X ?` looks like a way better mechanism. Nice find mcornella. Yeah, use that instead. (The `^X ?` key binding only seems to be there in emacs mode, though; if I'm in vi mode the binding isn't present and it doesn't work; looks like you'll need to manually add a binding for it to use in vi mode.)

GitHub refused to let me post the output as a gist using the normal drag-and-drop interface, though. Maybe because it contains terminal escape sequences, and thus looks like a binary file instead of a text file. I had to do a `cat /tmp/zsh62690f2 | pbcopy` and then paste it in to the text area, which seemed to strip off all the control sequences and leave it as plain text.

**Comment by mcornella** [comment]
> Why won't set -x work for completion functions? It seems to trace completion functions for me when I enable it and request a completion by hitting Tab.

That's weird, I couldn't get that to work... Anyway, I managed to reproduce the error, and it looks to me like a *"feature"* in the sense that there is not a possible completion for `git config remote <TAB>`. The right command should be `git config remote<TAB>`, which will expand it to `git config remote.` or `git config remotes.`. 

Regardless, that completion shouldn't trigger an error so there *is* a bug in zsh's completion. But don't panic, for that is a zsh upstream bug and not an oh-my-zsh one.

So, **TL;DR**, don't try to do `git config remote <TAB>`; instead, do `git config remote.<TAB>`.
