### ISSUE TITLE
Weird issue with $ZSH

### ISSUE THREAD

**Issue by cleung2010** [robbyrussell/oh-my-zsh#4668]
I am encountering a bizarre issue with the `$ZSH` path

```shell
LEXMAC1758% echo $ZSH
~/.dotfiles/oh-my-zsh

LEXMAC1758% ls ~/.dotfiles/oh-my-zsh
ls: /Users/cleung/.dotfiles/oh-my-zsh: No such file or directory

LEXMAC1758% ls $ZSH
MIT-LICENSE.txt	cache		lib		oh-my-zsh.sh	templates	tools
README.markdown	custom		log		plugins		themes

```

**Comment by mcornella** [comment]
See if there's any directory with the literal name `~`. I don't know how it would have ended like that but it's a possibility...

**Comment by apjanke** [comment]
Oh, nice call!

Tilde expansion happens before or at the same time as parameter expansion, and is stopped by quotes. So if you had set `ZSH="~/.dotfiles/oh-my-zsh"` instead of `ZSH=~/.dotfiles/oh-my-zsh` and then run the installer, it could have installed to a literal `./~/.dotfiles/oh-my-zsh` instead of expanding `~` to `$HOME`.

```
➜  tmp  pwd
/Users/janke/tmp
➜  tmp  echo $ZSH
/Users/janke/.oh-my-zsh
➜  tmp  ls $ZSH
MIT-LICENSE.txt  cache   lib  oh-my-zsh.sh  templates  tools
README.markdown  custom  log  plugins       themes
➜  tmp  ZSH="~/.oh-my-zsh"
➜  tmp  ls $ZSH
gls: cannot access ~/.oh-my-zsh: No such file or directory
➜  tmp  ls ~/.oh-my-zsh
MIT-LICENSE.txt  cache   lib  oh-my-zsh.sh  templates  tools
README.markdown  custom  log  plugins       themes
➜  tmp
```

I think this is our fault. The [Advanced Installation instructions](https://github.com/robbyrussell/oh-my-zsh/#custom-directory) for custom directories show an example of using a tilde inside quotes.

```
export ZSH="~/.dotfiles/oh-my-zsh"; sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
```

I believe that will cause exactly the breakage that @cleung2010 is seeing here. Should probably be changed to one of these.

```
# Without quotes
export ZSH=~/.dotfiles/oh-my-zsh; sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
# With variables, which will expand inside quotes
export ZSH="$HOME/.dotfiles/oh-my-zsh"; sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
```

**Comment by cleung2010** [comment]
@apjanke Awesome, thanks for the explanation!

**Comment by mcornella** [comment]
> I think this is our fault. The Advanced Installation instructions for custom directories show an example of using a tilde inside quotes.

Woops, my bad :sweat_smile:. Thank you for the investigation! I've just changed that to `$HOME`.

I assume your issue is solved now @cleung2010, so I'll close it as solved.

**Comment by apjanke** [comment]
:+1:

**Comment by cleung2010** [comment]
:+1:
