### ISSUE TITLE
OAuth access tokens in repo

### ISSUE THREAD

**Issue by dbkaplun** [robbyrussell/oh-my-zsh#4748]
I just got this email:
```
Hello dbkaplun,

We noticed that a valid OAuth access token of yours was committed to a public GitHub repository. Publicly disclosing a valid access token would allow other people to interact with GitHub on your behalf, potentially altering data, your contact information, and billing data.

As a precautionary measure, we have revoked the OAuth token. A new token will need to be generated in order to continue using OAuth to authenticate to GitHub. Here are a couple of steps you can do to ensure your account security has not been compromised:

* Review any unauthorized OAuth applications, and remove any you don’t recognize: https://help.github.com/articles/keeping-your-ssh-keys-and-application-access-tokens-safe/#reviewing-your-authorized-applications-oauth
* Review you security log to ensure that no other malicious activity has occured: https://help.github.com/articles/reviewing-your-security-log/

The commit in question is at https://github.com/robbyrussell/oh-my-zsh

Please feel free to contact us at https://github.com/contact if you have any questions or concerns.

Thanks,
GitHub.com
```

I couldn't find where access tokens might be in the repo so I didn't file a PR. Can we remove them please?

**Comment by mcornella** [comment]
I haven't found any commit that you made that could contain an oauth key, and not a single commit that contains "oauth", and I don't know of a more sophisticated method to search for strings that look like an oauth key. And I can only recall one instance of some weird commit containing a key and it's [this one](https://github.com/robbyrussell/oh-my-zsh/pull/1962/files).

I've searched both the main repo and the wiki for a commit, as well as your own fork. This looks like a false positive, but perhaps you can email me the details and I'll look for the specific key.

**Comment by apjanke** [comment]
From what I've seen, the GitHub OAuth tokens ("Personal Access Tokens") are usually just represented as 40-character hex values, like SHA commit identifiers. Something like `grep -r -E '[a-fA-F0-9]{40}' *` would pick up candidates. I looked through the current repo and wiki with that and didn't find anything that looked like an oath key either.

Tried a `git log -p | grep -E '[a-fA-F0-9]{20}' | grep -v '^commit' | less` to see if it was maybe in a commit message or comment; nothing jumped out at me there either.

You could do a grep for the first several characters in your token through `git log -p` to find that particular key, which should be pretty exhaustive. (Since it's already revoked, sharing a partial substring of that token with people is low risk, if you want to have others help you look for it.)

Also, `Review you security log` looks like a typo. Should be "your". Maybe reply to GitHub to let them know, and see if they can point you at something more specific?

**Comment by apjanke** [comment]
Also possible it showed up in a commit in a PR which was later superseded by an amended commit, in which case it wouldn't show up in the repo history at all, but would still be publicly visible through GitHub-specific mechanisms. I don't know how one would search through those, aside from scraping all the PRs through the GitHub API.

**Comment by mcornella** [comment]
I think it's safe to assume this is either a false positive or a low-impact issue, so I'm closing this one for the time being. @dbkaplun reopen if you find anything else.
