### ISSUE TITLE
Bang history

### ISSUE THREAD

**Issue by kmentch** [robbyrussell/oh-my-zsh#4770]
I used to type !bundle [TAB] and then I could arrow up/down to look through history of commands that started with bundle, however this has stopped working. Did something change with how this works or did it just break?

**Comment by apjanke** [comment]
I don't know what exactly broke with the `!bundle [TAB]` version of it, but you can get the same behavior by just typing `bundle` and hitting up arrow: it will cycle through your history items that start with `bundle`. This is the `up-line-or-begining-search` behavior which [OMZ binds to up arrow by default](https://github.com/robbyrussell/oh-my-zsh/blob/078cd4ae2b97bf9cd08dc9455fbef80145cc5191/lib/key-bindings.zsh#L23-L28) (in `emacs` mode; if you're using `vi` mode things will be different).

As far as recent changes, if something broke this for you, it might be the key bindings/terminfo related stuff in `lib/key-bindings` or `plugins/vi-mode` or `plugins/history-substring-search`.

**Comment by mcornella** [comment]
We changed the default up/down arrow behavior to cycle through the whole entered command. For example, if you write `git clone` it will cycle through other `git clone` commands instead of `git` commands.

When you do `!bundle[TAB]`, zsh will expand it to the last `bundle` command you run, which is probably `bundle <something> <something> ...`; so up/down will cycle through commands that start with that exact phrase, which are potentially very few or even the exact same command. That may give the impression of the cycling not working.

A better, shorter way to cycle through bundle commands is just writing `bundle` and then doing up/down arrow. Let me know if that works for you; if not, there may be some key binding stuff going on.

**Comment by kmentch** [comment]
Not using the bang at the beginning works great. I was afraid I lost my way of going through history like I have done for so long. I will close this as the feature still works just in a different way.

**Comment by mcornella** [comment]
Thanks! 

To clarify though, this feature of cycling without the bang always worked. You may've been using the bang history wrong: it's main use is to expand to the last executed command. The cycling with up/down arrow is a separate, independent feature. 

Cheers!
