### ISSUE TITLE
improper path expander when path includes an underline char

### ISSUE THREAD

**Issue by hu6360567** [robbyrussell/oh-my-zsh#4777]
I have a folder named with a underline char (_).
The folder structure is like this.
├── ODL_Development
│      └── syslogsvr

When I type ```odl/svr``` in terminal and press tab, zsh cannot expand the path as expected.
But it can works fine when I input ```odl```, press tab, input ```svr```, press tab.

**Comment by apjanke** [comment]
I don't know if this is due to the underscore. I get similar behavior if I set up test dirs with `mkdir -p ODLDevelopment/syslogsvr`.

This might be about [how the `matcher-list` is set up](https://github.com/robbyrussell/oh-my-zsh/blob/078cd4ae2b97bf9cd08dc9455fbef80145cc5191/lib/completion.zsh#L22), in that the case insensitivity and matching at the end of a word instead of only at the beginning appear to be different items.

```
matcher-list
        :completion:* 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
```
In order to get `odl/svr` to expand to `ODL_Development/syslogsvr`, the matcher must do both case-insensitive completion, and do a right-anchored (end of word) match at the same time. Either one alone works: when I test this, both `ODL/svr` and `odl/sys` will complete to `ODL_Development/syslogsvr`, just not `odl/svr`. To get `ODL/svr` to expand like that, you'll need to include a matcher-list item that does both case insensitivity and left/right anchoring.

I was able to get this to work by doing the following, adding an item which combines the `m:...` case-insensitivity and `l:... r:...` left/right anchoring.

```
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*' 'm:{a-zA-Z}={A-Za-z} l:|=* r:|=*'
```

You could add that to your `~/.zshrc` after loading OMZ. We could also change it to be the default; I don't know if should be the default because the increased sensitivity could lead to additional false positives or ambiguous matches, though the risk of that is probably pretty low if it's at the end of the `matcher-list`.

**Comment by hu6360567** [comment]
Thanks a lot!

**Comment by apjanke** [comment]
If this is working now, could you close this issue?
