### ISSUE TITLE
rvm error after starting zsh

### ISSUE THREAD

**Issue by emedlr** [robbyrussell/oh-my-zsh#4787]
I'm getting this error when opening new zshell:
````
/Users/mgmerino/.rvm/scripts/initialize:48: __rvm_cleanse_variables: function definition file not found
/Users/mgmerino/.rvm/scripts/initialize:50: command not found: rvm_error
````
As suggested on other related answers, I've
````
rm -r ~/.zcompdump
````
but the folder is generated every time I open a new shell, so this does nothing. Any idea?
 
system info:
osx 10.11.2
rvm 1.26.11

**Comment by mcornella** [comment]
Follow [this instructions to capture a debugging session](https://github.com/robbyrussell/oh-my-zsh/wiki/Troubleshooting#everything-else) and post back the results in a gist.

**Comment by emedlr** [comment]
https://gist.github.com/emedlr/f6daf3bb53a35746e3cb

**Comment by mcornella** [comment]
Here's the relevant part of the results:

```
 6206 +/Users/mgmerino/zgen.zsh:471> ZGEN_AUTOLOAD_COMPINIT=true 
 6207 if $ZGEN_AUTOLOAD_COMPINIT; then
 6208     autoload -U compinit
 6209     compinit -d "${ZGEN_DIR}/zcompdump"
 6210 fi
 6211 +/Users/mgmerino/zgen.zsh:472> true
 6212 +/Users/mgmerino/zgen.zsh:473> autoload -U compinit
 6213 +/Users/mgmerino/zgen.zsh:474> compinit -d /Users/mgmerino/.zgen/zcompdump
```

It seems you're using zgen after loading Oh My Zsh─which is not the intended way to be done, see [the example zshrc](https://github.com/tarjoilija/zgen#example-zshrc)─but that is not the culprit though, and it's more than possible that it can work either way.

The problem is that zgen is generating its own zcompdump file, so you should `rm ~/.zgen/zcompdump` instead of the `~/.zcompdump*` which is where Oh My Zsh stores the completion cache file.

You can delete the gist now, and tell me if doing that solves your problem.

**Comment by emedlr** [comment]
Thanks @mcornella, finally `rm ~/.zgen/zcompdump` solved the issue.

**Comment by mcornella** [comment]
:+1:

**Comment by mikedfunk** [comment]
similar thing for zplug: `rm ~/.zplug/zcompdump`

**Comment by cyyyu** [comment]
For me it is `rm ~/.zcomp*`

**Comment by anniehswong** [comment]
@cyyyu  rm ~/.zcomp* fixed the issue for me too. thanks!

**Comment by barpeed** [comment]
@cyyyu rm ~/.zcomp* fixed the issue for me too in mac os!! thank you

**Comment by v-dorosh** [comment]
@cyyyu rm ~/.zcomp* fixed the issue. Thanks!

**Comment by iiewad** [comment]
Thanks!

**Comment by imansyaefulloh** [comment]
Thanks @cyyyu,  rm ~/.zcomp* fix the issue on mac osx.

**Comment by mwcm** [comment]
@mgmerino thank you!! rm ~/.zplug/zcompdump for those using zplug

**Comment by Chyroc** [comment]
for me `rm ~/.zlogin` fixed the issue, thank you.
