### ISSUE TITLE
Rude installation behaviour

### ISSUE THREAD

**Issue by slavaGanzin** [robbyrussell/oh-my-zsh#4831]
Guys, I appreciate your work, but what your installer should do is adding
```
echo "#Some silly comment
  export ZSH=/home/vganzin/.oh-my-zsh
  source $ZSH/oh-my-zsh.sh" >> .zshrc
```
And not  rewriting my precious .zshrc without even questioning about.

**Comment by ayttew** [comment]
lol I agree. "Rude" is the best definition. But I believe that this behavior is not without reason.

**Comment by mcornella** [comment]
First of all, I agree with the general sentiment there. The installer is one of many pain points of Oh My Zsh, and we're tracking it's many issues at #4355 as well as accepting suggestions at #4393.

That said, the proposed behavior would not be without its issues, the main one being that user configurations would be done before loading Oh My Zsh, and possibly get overwritten by OMZ settings. A possible alternative would be to put that at the top of the `zshrc` file.

Possibly we implement some kind of alternative in the next version of the installer, so that the user can choose between using the full zshrc template or using this simpler method.

**Comment by slavaGanzin** [comment]
Closing as duplicate of https://github.com/robbyrussell/oh-my-zsh/issues/4390
