### ISSUE TITLE
Golang and Git gfa alias collide

### ISSUE THREAD

**Issue by masterkorp** [robbyrussell/oh-my-zsh#4919]
The git plugin [gfa](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh#L87) alias and Go plugin [gfa](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/golang/golang.plugin.zsh#L183) collide. 

I will open a Pull Request renaming Golang `gfa` to `gfmt`if you agree.

**Comment by mcornella** [comment]
You can `unalias gfa` in your zshrc file to delete the git plugin alias. Aliases are a difficult thing to get right because there're all sorts of short-named commands that we might be overriding.

We're working on a safe aliasing system (#4585) to avoid having this problem, so don't bother submitting a PR that we probably won't pull. In the meantime, use the above temporary fix or disable the git plugin altogether.

Thanks!
