### ISSUE TITLE
Backtick in .zshrc file causing real issues

### ISSUE THREAD

**Issue by hobakill** [robbyrussell/oh-my-zsh#4921]
I have the following line in my ~/.zshrc file:
![screen shot 2016-03-14 at 3 46 38 pm](https://cloud.githubusercontent.com/assets/4466324/13759392/fe77a62a-e9fb-11e5-85f5-fffc66f6160b.png)
I've specifically done a screen grab so you can see the `Name` insanity. I have to have those backticks in the string to make the aws call work properly. If i try to :wq that as is and source ~/.zshrc I get: command not found: Name

What am I missing?
sorry for the tiny screen grab

-----
Alias
```zsh
#aws cli
alias list-aws-public="aws ec2 describe-instances --output table --query 'Reservations[].Instances[].[Tags[?Key==`Name`] | [0].Value, PublicIpAddress]'"
```

**Comment by varCharlie** [comment]
Do you have a function called `Name` that you're trying to execute and return the value of?

Backticks in ZSH (and also in bash) are used for command substitution. You you want the backticks without this behavior--which is the expected behavior--you will need to escape them or place the enclosing string inside of single quotes.

**Comment by mcornella** [comment]
This is an issue with how zsh (and bash and other shells) handle quoting. Double quotes will substitute variables and other things, like inline commands (`$(command)` or ``command``). Single quotes don't. More info [about quoting here](http://zsh.sourceforge.net/Guide/zshguide05.html#l112).

Thus, a possible fix for your alias is using single quotes everywhere, with a little help of backslashes to quote inner single quotes:
```diff
-alias list-aws-public="aws ec2 describe-instances --output table --query 'Reservations[].Instances[].[Tags[?Key==`Name`] | [0].Value, PublicIpAddress]'"
+alias list-aws-public='aws ec2 describe-instances --output table --query '\''Reservations[].Instances[].[Tags[?Key==`Name`] | [0].Value, PublicIpAddress]'\'''
```
That looks a bit confusing because [you can't quote a single quote inside single quotes](http://zsh.sourceforge.net/Guide/zshguide05.html#l114).

A better fix, which is the first one proposed by @varCharlie, is escaping the backticks with a backslash, like so:
```diff
-alias list-aws-public="aws ec2 describe-instances --output table --query 'Reservations[].Instances[].[Tags[?Key==`Name`] | [0].Value, PublicIpAddress]'"
+alias list-aws-public="aws ec2 describe-instances --output table --query 'Reservations[].Instances[].[Tags[?Key==\`Name\`] | [0].Value, PublicIpAddress]'"
```

This just uses a couple of characters more, and you don't end up with the ugly syntax of quoting single characters. 

I hope that explains a bit more about how zsh works. Let me know if you have trouble with something else!
