### ISSUE TITLE
simple theme for linux console

### ISSUE THREAD

**Issue by Kallin** [robbyrussell/oh-my-zsh#4923]
I've noticed with a couple linux distributions (debian/arch) that the default linux console can't render the fonts from the default robby-russel oh-my-zsh theme. I imagine most people aren't faced with the linux console and are using some terminal emulator, but it is a bit odd to see. Perhaps oh-my-zsh could load a simpler theme if it detects it's being run in a linux console. Thoughts?

![screen shot 2016-03-15 at 10 13 23 am](https://cloud.githubusercontent.com/assets/158169/13780640/b653f880-ea96-11e5-8889-ab238e686567.png)

**Comment by varCharlie** [comment]
What character set is your terminal using? utf-8?

**Comment by mcornella** [comment]
Oh My Zsh doesn't have the ability to know when a particular character is displayed correctly, that's a competency of the terminal emulator and no shell script has the ability of peaking into that realm.

You have two alternatives to use here:

- Change the default font your TTYs use. These are special fonts (PSF fonts) since tty emulators don't have the same ability to display any font as normal terminal emulators do. Since you're using Debian I can tell you exactly how, see below.

- Use [`fbterm`](https://code.google.com/archive/p/fbterm/) which will display a full-blown terminal emulator, capable of displaying whatever font you use in your default terminal emulator.

If you decide to use the first approach, here's how you do it in Debian:

1. Put a custom font capable of display the symbols you need in `/usr/share/consolefonts`. This can be a powerline font or a normal one that can display other unicode symbols. I'm using [Terminus PSF fonts from Powerline](https://github.com/powerline/fonts/tree/master/Terminus/PSF). The `vNNx` part of the font name is the size (`NN`) and style (`x`, **n**ormal or **b**old).

2. Change your `/etc/default/console-setup` file to use the newly downloaded font. In my case, that's:
```
# CONFIGURATION FILE FOR SETUPCON

# Consult the console-setup(5) manual page.

ACTIVE_CONSOLES="/dev/tty[1-6]"

CHARMAP="UTF-8"
FONT="ter-powerline-v16n.psf.gz"
```

3. Note that I have `CHARMAP="UTF-8"` in there as well. I don't remember if that's a default setting, but if you don't have it you should add it just in case.
