### ISSUE TITLE
.zshenv not being sourced

### ISSUE THREAD

**Issue by johndierks** [robbyrussell/oh-my-zsh#4928]
I created `~/.zshenv` and moved some stuff from from `~/.zshrc`, but it appears that `~/.zshenv` is not being sourced. 

Where is `~/.zshenv` sourced from? How can I get oh-my-zsh (or zsh) to source it?

**Comment by mcornella** [comment]
First, look at how [`zsh` loads startup files](http://zsh.sourceforge.net/Guide/zshguide02.html#l9). Then, try putting a canary statement in your `.zshenv` file (like an `echo zshenv loaded` command) to see if it's really loading it or not.

If it turns out that it is loading the file, post both your zshenv and zshrc files to see what exactly is not working.
