### ISSUE TITLE
common aliases produces strange freeze

### ISSUE THREAD

**Issue by ghost** [robbyrussell/oh-my-zsh#4980]
when typing a link in the terminal (try `http://www.a.org`) with the common-aliases plugin on, zsh strangely locks up. disabling the common-aliases plugin fixes this issue. I'm not sure if packages or aliases are conflicting with the plugin and causing this issue, so let me know if this is reproducible.

This occurs under multiple terminals as well.

**Comment by yongqli** [comment]
Something very similar happens to me as well:

If I run the command `~/a.txt`, zsh freezes. It doesn't matter if the file actually exists or not.

Disabling `common-aliases` fixes the issue.

**Comment by mcornella** [comment]
@yongqli `common-aliases` uses `alias -s` to autorun some command on files depending on its extension. For example, [it runs `$EDITOR` on text commands](https://github.com/robbyrussell/oh-my-zsh/blob/1b1315a777328095cd8b5f364fd4345eeae7c4bf/plugins/common-aliases/common-aliases.plugin.zsh#L60-L61). In my case, it opens `nano` because that's my `$EDITOR`. Check what's you `$EDITOR` variable.

@bigmittens I cannot reproduce, can you post your full zshrc file?

**Comment by yongqli** [comment]
@mcornella my `$EDITOR` is also set to `nano`.

**Comment by mcornella** [comment]
Open a new issue if it's still happening.
