### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Tsutsukakushi** [robbyrussell/oh-my-zsh#5049]
Are you aware how retarded the installation method of oh-my-zsh is?

Curling or wgetting and blindly executing scripts is a TERRIBLE idea.

PS. You're now on my brand new [wall of shame](https://gnu.moe/wallofshame.html)

**Comment by Tsutsukakushi** [comment]
Are you guys lazy or what?

**Comment by piyushcsiitd** [comment]
@Tsutsukakushi: I understand the lazy part, but why would executing 'curl/sh' be any extra malicious than using packaged installer scripts, can't the bad stuff can be as easily disguised in builds as well?

**Comment by jncornett** [comment]
"Blindly executing scripts is a bad idea" is generally true, but don't tell me you read the content of every package installer you've ever ran. If the intent is ultimately to execute the install script, then it is quite irrelevant what specific tools (curl, wget, git clone, etc) are used to retrieve the script.

**Comment by christoga** [comment]
What about brewing oh-my-zsh?

**Comment by vsiegel** [comment]
Installing by directly piping from an url - like with curl or wget is not only  
"installing something you have not seen". 
It means also **installing something you had not the possibility to see**. 
And, more severe, **installing something you could not even see after the installation**.

With just any kind of package, you could **take a look before** - but mostly do not because you trust the source.

But the important part is: you can take a look at what you just installed if something seems to be wrong. Often, it's just that something else is not broken by a side effect. Or a harmless log file entries that irritate you. Or just plain an attack.

**Comment by robbyrussell** [comment]
This pops up from time-to-time. I'm okay with being on the wall of shame.

**Comment by Tsutsukakushi** [comment]
@vsiegel Also would like to add that the adversary will know that you had no chance to see it.
