### ISSUE TITLE
Why is the behavior of `!!` changed?

### ISSUE THREAD

**Issue by esdoppio** [robbyrussell/oh-my-zsh#5054]
The default behavior of running `!!` is to rerun the last cmd in history. But with oh-my-zsh enabled, the behavior becomes the same as one keystroke of <kbd>up</kbd>, which is not favorable.

Is the change intended?
Reason of the change?
How can I regain the old behavior?

**Comment by mcornella** [comment]
That's the [`hist_verify` option](http://zsh.sourceforge.net/Doc/Release/Options.html#index-HISTVERIFY). You can disable that behavior by running `unsetopt histverify`.

As to why that change is there, it looks like it was introduced in 5da20b9d, therefore it's been in OMZ since the beginning. I'd say that's a useful command to make sure you know what you're running. 

Personally, I've been expanding `!!`  using <kbd>TAB</kbd>, so this setting doesn't affect me much. But if it bothers more people I'll get rid of the setting.

**Comment by esdoppio** [comment]
Thanks for the info : D

I've changed from doing `!!` to using <kbd>UP</kbd> instead. After all, it's just a matter of habit.

The intent was good, but I'd argue if i want to verify my last command, I'd just <kbd>UP</kbd>, in one stroke, instead of 4 with `!!` when the option is set.

**Comment by esdoppio** [comment]
Maybe u can open a PR to hear more opinions : )

**Comment by mcornella** [comment]
> Thanks for the info : D
> 
> I've changed from doing !! to using UP instead. After all, it's just a matter of habit.
> 
> The intent was good, but I'd argue if i want to verify my last command, I'd just UP, in one stroke, instead of 4 with !! when the option is set.

The fix above will also work for other history expansions, like `!$`, so feel free to use it. I'll probably remove that option on #3422. Thanks!

**Comment by mcornella** [comment]
I've updated #3422 with the change.

**Comment by esdoppio** [comment]
👍 @mcornella
