### ISSUE TITLE
Showing only the first character of prior directories like Fish?

### ISSUE THREAD

**Issue by koesherbacon** [robbyrussell/oh-my-zsh#5068]
Is there a function I could use that would show only the first character of the prior directories followed by the full title of the current one?

For instance, if I'm in `~/.oh-my-zsh/themes` it would show a more suscint path as `~/.o/themes/`

I'm currently using this format: `%B%F{blue}%~%F%b` which shows everything without abbreviating the heirarchy.

Any advice would be awesome!  Thanks a lot!

~ Ev

**Comment by mcornella** [comment]
I'm not aware of any builtin solution, but you can use `$PWD` and variable expansion to have a similar functionality. Here's what I came up with:
```zsh
echo /${(j:/:)${(M)${(s:/:)PWD:h}#(|.)[^.]}}/${PWD:t}
```
Example:
```
$ pwd
/usr/share/zsh/functions
$ echo /${(j:/:)${(M)${(s:/:)PWD:h}#(|.)[^.]}}/${PWD:t}
/u/s/z/functions
```
If on a hidden directory it will also show the dot and the letter next to it. It doesn't use `~` (tilde) to mark the home directory though. Everything used here is based on [this zsh documentation](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Parameter-Expansion).

You would put that whole expression (all except the `echo`) instead of the `%~` in your prompt variable. Make sure to use single quotes (`'`) instead of double quotes (`"`) so that `$PWD` isn't expanded when right when defining the prompt.

**Comment by mcornella** [comment]
Here's one that also uses `~` tilde if possible: 
```zsh
echo ${${:-/${(j:/:)${(M)${(s:/:)${(D)PWD:h}}#(|.)[^.]}}/${PWD:t}}//\/~/\~}
```

It can probably be optimised but I've already spent a significant portion of my time on this.

**Comment by kalsan** [comment]
As a follow-up question (I'm a zsh newbie): Is there a more elegant way to use this than:

```
setopt PROMPT_SUBST
PROMPT='%n@%m:%{$(echo ${${:-/${(j:/:)${(M)${(s:/:)${(D)PWD:h}}#(|.)[^.]}}/${PWD:t}}//\/~/\~})%}%# '

```

**Comment by mcornella** [comment]
You can put it in a function:
```
shpwd() {
  echo ${${:-/${(j:/:)${(M)${(s:/:)${(D)PWD:h}}#(|.)[^.]}}/${PWD:t}}//\/~/\~}
}
PROMPT='%n@%m:$(shpwd)%# '
```

**Comment by kalsan** [comment]
Cool, makes sense. Thanks!

**Comment by ar1a** [comment]
interesting, on mine 

```
		echo ${${:-/${(j:/:)${(M)${(s:/:)${(D)PWD:h}}#(|.)[^.]}}/${PWD:t}}//\/~/\~}
```

in my home directory will return `/h/aria`, but if i cd into a directory, say, projects, it returns `~/projects`

**Comment by mcornella** [comment]
Try the [shrink-path plugin](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/shrink-path), it's more advanced and probably fixes this specific edge case.
