### ISSUE TITLE
Best way to switch back to Oh-my-zsh from Prezto

### ISSUE THREAD

**Issue by brianjking** [robbyrussell/oh-my-zsh#5074]
Hi,

I'm considering switching back to Oh-My-Zsh from Prezto (https://github.com/sorin-ionescu/prezto). Is there a suggested/easiest method of backing up my Prezto config and/or porting it into Oh-my-zsh to ensure everything lines up and doesn't have conflicts?

Thanks!

**Comment by mcornella** [comment]
Hi @brianjking, there's not much shared code between both projects. I guess if you want to come back is because you need some functionality that ohmyzsh has, not because prezto's isn't working (given its high code quality).

In that case, you could go the [`antigen`](https://github.com/zsh-users/antigen) or [`zgen`](https://github.com/tarjoilija/zgen) way, which gives the option of cherry-picking from multiple projects.

Let me know if I didn't understand that precisely. Cheers!
