### ISSUE TITLE
gcam alias question

### ISSUE THREAD

**Issue by Benjamski** [robbyrussell/oh-my-zsh#5138]
In reference to the [gcam alias](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh) can somebody explain to me why that's ```git commit -a -m``` and not just ```git commit -m``` I'm unclear on why we have the -a flag there. Isn't that the shorthand for ```git commit --ammend```?

Thanks for the clarification and apologies if this is stupidly simple, I couldn't come up with a clear answer reading through the git docs but assume it was aliased this way with good reason.

**Comment by mcornella** [comment]
The `-a` flag is a shorthand for `--all`, which means that all modifications will be commited. Since we're using zsh, you can take advantage of zsh's awesome completion and test yourself what the argument does. Have a look at this asciinema screencast: https://asciinema.org/a/cca8wx9d5q6zvvgjon7d9dmbs

**Comment by mcornella** [comment]
If you want to do only `git commit -m` you have the `gcmsg` alias.

**Comment by Benjamski** [comment]
@mcornella Thank you! That's exactly what I was looking for. Is there any bad practice concerns with using ```gcam``` It's not the equivalent of doing something like ```git add .``` and then ``git commit -m``` right? It's only going to stage deleted or already tracked files?

**Comment by mcornella** [comment]
Untracked files are not included. Only tracked files that have been modified or deleted.

Regarding best practice, I tend to not use inline messages (`-m`) and instead use `gc` and `gca`, which then prompts me using `$EDITOR` to write the whole commit. That way I always write a full commit message instead of a quick summary, and I have more time to think about what the commit message should be.

Regarding adding all files at once or not, I always use `gst` (`git status`) before adding files, so there's very little chance of adding something that shouldn't be there. 

Have a look at the [rest of aliases](https://github.com/robbyrussell/oh-my-zsh/wiki/Plugin:git) of the git plugin for more goodness.

**Comment by Benjamski** [comment]
Thank you for such helpful responses!

I think I knew ```gc``` or ```gca``` would be the best practices but I always prefer to understand the lesser ones beyond just "don't" That's what I usually use too, but I have been falling back on ````gcam``` during presentions where I'm quickly demo-ing something or on the rare occasion i'm experimenting on a branch or repo i plan on deleting.

I'm also a huge fan of using ```gapa``` as well, but those effectively provide me the same benefits of seeing my staged diffs in detail.
