### ISSUE TITLE
Plugin 'safe-paste' messes with 'history-substring-search'

### ISSUE THREAD

**Issue by sumitsahrawat** [robbyrussell/oh-my-zsh#5149]
`history-substring-search` doesn't work after enabling `safe-paste`, disabling it fixes the problem.

**Comment by norberto5757** [comment]
look with deep sincerity do not know when or I receive your e'm just a
systems programmer with a very broad curriculum right through 37 years of
living today than my children offer me forgiveness if at any time
incosiente were taxed. my data but not. nothing to disturb my social
environment much less in a country that I admire ye visited for several
years my name is norberto gonzalez rojas and my mobile in mexico is
6645872021 my address from my home in Tijuana, Baja californa is Andador A
#, 31 elRubi apologies please delete my information from your database ever
and hurt anyone thanks blessings also I inform you that do not speak
English use the Google translator only thing that 100% are programming
terms what I do on social networks is to speak God does not send me anyone
is not charging its own initiative or annoying people tendencista'm not
religious and I am apolotitico only love God above all things blessings.
Please don't more way email tanks

**Comment by sumitsahrawat** [comment]
Hi @norberto5757, if you do not want to recieve more e-mails, just unwatch the repository.

**Comment by apjanke** [comment]
`history-substring-search` uses terminfo-based key bindings, which in turn require the cursor keypad to be in application mode. The main OMZ code uses `zle-line-init`/`zle-line-finish` to do so. `safe-paste` clobbers `zle-line-init` and `zle-line-finish` in ways which don't do SMKX/RMKX, so history-substring-serach's key bindings are no longer valid.

Basically the same as #5237.

Will be fixed by #5113.

**Comment by sumitsahrawat** [comment]
Closing as there's a equivalent issue.
