### ISSUE TITLE
SCP don't accept wildcard

### ISSUE THREAD

**Issue by jlruizmlg** [robbyrussell/oh-my-zsh#5150]
When i try to do a SCP  from other server to my system with wildcards i have an error:

```
jlruizmlg@MacBook-Pro-de-Jose  ~  scp jlruizmlg@192.168.78.140:/tmp/wazuh-ossec-2.0.12.tar.*  Desktop
zsh: no matches found: jlruizmlg@192.168.78.140:/tmp/wazuh-ossec-2.0.12.tar.*
```

**Comment by mcornella** [comment]
Put the path including the wildcard between quotes so that zsh doesn't try to expand it to a local file. Another solution is putting `noglob` before the scp command.

**Comment by jlruizmlg** [comment]
Thanks @mcornella fir the fix, its not a real solution but can works for now.

**Comment by mcornella** [comment]
You can alias scp to `noglob scp` so that you don't have to do it yourself all the time.

**Comment by norberto5757** [comment]
look with deep sincerity do not know when or I receive your e'm just a
systems programmer with a very broad curriculum right through 37 years of
living today than my children offer me forgiveness if at any time
incosiente were taxed. my data but not. nothing to disturb my social
environment much less in a country that I admire ye visited for several
years my name is norberto gonzalez rojas and my mobile in mexico is
6645872021 my address from my home in Tijuana, Baja californa is Andador A
#, 31 elRubi apologies please delete my information from your database ever
and hurt anyone thanks blessings also I inform you that do not speak
English use the Google translator only thing that 100% are programming
terms what I do on social networks is to speak God does not send me anyone
is not charging its own initiative or annoying people tendencista'm not
religious and I am apolotitico only love God above all things blessings.
Yes in you sitie vicos is not produced money an Glory is more an name don't
prunucied exactly tanks
El jun 9, 2016 6:33 AM, "Marc Cornellà" <notifications@github.com> escribió:

Closed #5150 <https://github.com/robbyrussell/oh-my-zsh/issues/5150>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/robbyrussell/oh-my-zsh/issues/5150#event-687236484>,
or mute
the thread
<https://github.com/notifications/unsubscribe/AK079mbfComRnXd19tx_1CcTqFWxSNEJks5qKBYngaJpZM4Ix9dI>
.

**Comment by itsSaad** [comment]
I was using `cap staging logs:tail[unicorn]` and would get `zsh: no matches found: logs:tail[unicorn]`
appending `noglob`  to the above command solved it. But it shouldnt be this way. As i understand. Can someone explain?

**Comment by mcornella** [comment]
@itsSaad brackets (`[` `]`) are globbing characters, which means they are used to expand to file names. For example, `print -l [a-z]*` would print all files and directories starting with a lowercase letter.

`noglob` makes zsh interpret it literally. If you want `cap` to always disregard globbing characters you can alias it in your zshrc file, like so:
```
alias cap='noglob cap'
```

**Comment by kangxin** [comment]
The alias solution does not work for me. This has been a real problem to me since bash was changed to oh-my-zsh on Mac.

The zsh version
`zsh 5.7.1 (x86_64-apple-darwin19.0)`

For ~/.zshrc
`ZSH_CUSTOM=$ZSH/custom`

For $ZSH_CUSTOM
alias scp='noglob scp'

The scp command does not recognize *.py in the local directory:
scp *.py some_remote_dir
*.py: No such file or directory

**Comment by mcornella** [comment]
> For $ZSH_CUSTOM
> `alias scp='noglob scp'`

In which file is this written? `$ZSH_CUSTOM` has to be a directory.

**Comment by kangxin** [comment]
For $ZSH_CUSTOM/aliases.zsh
`alias scp='noglob scp'`

I tested `alias up='cd ..'` and it works. But unfortunately`'noglob scp'` doesn't work.

**Comment by mcornella** [comment]
Is it still `noglob scp` in your command line? Maybe there's an `unalias scp` somewhere else? What does `alias scp` return? What's the command that's failing to work?

**Comment by kangxin** [comment]
Please let me explain my environment.

This is my zsh version.
`zsh --version`
`zsh 5.7.1 (x86_64-apple-darwin19.0)`

This is my setting of ZSH_CUSTOM in .zshrc.
`grep ZSH_CUSTOM ~/.zshrc`
`ZSH_CUSTOM=$ZSH/custom`
`# users are encouraged to define aliases within the ZSH_CUSTOM folder.`

This is my setting of alias scp in $ZSH_CUSTOM/aliases.zsh.
`grep scp $ZSH_CUSTOM/aliases.zsh`
`alias scp='noglob scp'`

These are the files in my local directory.
`ls *.py`
`a.py   b.py   c.py   d.py`

These are the scp command that I used to copy local files to a directory of a remote server and the response.
`scp *.py some_ip_address:some_remote_dir`
`*.py: No such file or directory`

These are the no glob scp command that I used to copy local files to a directory of a remote server and the response.
`noglob scp *.py some_ip_address:some_remote_dir`
`*.py: No such file or directory`

By the way, scp a single file from local to remote dir is fine.
`scp a.py some_ip_address:some_remote_dir`
`a.py                                     100% 2569     1.0MB/s   00:00`

`noglob scp a.py some_ip_address:some_remote_dir`
`a.py                                     100% 2569    83.7KB/s   00:00`

There is no `unalias scp` in files under `~/.oh-my-zsh`.
`grep -r 'unalias scp' ~/.oh-my-zsh`

There are indeed some `unalias` which I think were not set by myself.
`grep -r 'unalias' .oh-my-zsh`
`.oh-my-zsh/plugins/nvm/_nvm:  'unalias:deletes an alias'`
`.oh-my-zsh/plugins/gb/README.md:If you're having trouble with it, remove it by adding `unalias gb` at the end of your`
`.oh-my-zsh/plugins/shell-proxy/proxy.py:        cmdline("unalias", *self.aliases.keys())`
`.oh-my-zsh/plugins/scd/_scd:    - unalias`
`.oh-my-zsh/plugins/scd/_scd:    "--unalias[remove definition of directory alias]"`
`.oh-my-zsh/plugins/scd/_scd:            complete_unalias=${+opt_args[unalias---unalias]}`
`.oh-my-zsh/plugins/scd/_scd:            if (( complete_unalias && ! ${+nameddirs[OLD]} )); then`
`.oh-my-zsh/plugins/scd/README.md:--unalias</dt><dd>`
`.oh-my-zsh/plugins/scd/scd:  --unalias         remove ALIAS definition for the current or specified`
`.oh-my-zsh/plugins/scd/scd:local opt_alias opt_unalias opt_all opt_push opt_list`
`.oh-my-zsh/plugins/scd/scd:    -alias:=opt_alias -unalias=opt_unalias \`
`.oh-my-zsh/plugins/scd/scd:        unalias -m "*"`
`.oh-my-zsh/plugins/scd/scd:if [[ -n $opt_unalias ]]; then`
`.oh-my-zsh/plugins/scd/scd:        # unalias in the current shell and remember to update the alias file`
`.oh-my-zsh/lib/diagnostics.zsh:    source suspend test times trap true ttyctl type ulimit umask unalias`

@mcornella  Thank you for your time. I just want to make my problem clear and see if there is anything wrong.

**Comment by mcornella** [comment]
To be clear, you need to quote the wildcard when it's in the remote path position, but *not* quote it when it's in the local path position.

**Comment by kangxin** [comment]
> Wait, scp doesn't accept wildcards. You need to run `scp` without noglob, so undo any alias and then try the scp command again.

@mcornella Thanks a lot for your help! I removed `alias scp='noglob scp'` from `$ZSH_CUSTOM/aliases.zsh`, and it works for me now.

**Comment by thizmo** [comment]
Dear all,

i happen to have a similar problem. Yet your solution did not work for this case.
Of course it is not wildcard. ;-)

Yet it is a very identical problem.

Within ansible backups (from configs) end up like this names:
`config.2023-03-08@11:45:14`

The secure copy will be:
`scp config.2023-03-08@11:45:14 user@remote:Backup/folder/`

Every attempt to scp these files to a remote location files with errors like this:
`ssh: connect to host 0.0.0.15 port 22: Connection timed out`

Which if course the host is not 0.0.0.15....

It also does not work with excludes or scp (without alias).

This is my setup, within ohmyzsh and custom aliases.
`alias scp`
`scp='noglob scp'`

`zsh --version`
`zsh 5.8 (x86_64-redhat-linux-gnu)`
Maybe i just don`t see the error.... If it is the wrong issue, feel free to redirect it.

Thx.

**Comment by thizmo** [comment]
Hi @mcornella 
> @thizmo the issue you report is not the same, and does not actually come from Oh My Zsh or zsh itself.
> 
> It looks like the `remote` you used is getting translated into the `0.0.0.15` address, either by your DNS server or much more likely because of a configuration in the `~/.ssh/config` file.

I don't think so. A normal file (without @ or :) in between copies directly and without any hustle.
There are no configurations in .ssh/config having anything to do with this setup.

If it is not the same here, where should i open the issue?

**Comment by mcornella** [comment]
OK I got the issue now. A good site for these questions is StackExchange, in fact you're looking for this: https://unix.stackexchange.com/a/148934.

**Comment by thizmo** [comment]
Awesome. Strange, yet this works. 
Did not found this problem while searching for it....

Thx a lot!
