### ISSUE TITLE
Help with application mode

### ISSUE THREAD

**Issue by richarddavenport** [robbyrussell/oh-my-zsh#5228]
Not sure how to ask for help on this. I'm using [VS Code](https://github.com/Microsoft/vscode) and there is an integrated terminal that uses [xterm.js](https://github.com/sourcelair/xterm.js). I use oh my zsh for my default shell on my mac. I'm using OS X 10.11.5. The issue I'm having (and not sure where the actual problem lies) is that xterm.js is being put into `Application Keypad` mode because of `echoti smkx` ([this line](https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/key-bindings.zsh#L9)). Here is [the bug](https://github.com/sourcelair/xterm.js/issues/151) that we have filled with xterm.js.
Not sure where to go from here, any advice would be great.

**Comment by mcornella** [comment]
This should be solved with https://github.com/robbyrussell/oh-my-zsh/pull/5113, can you test it?

**Comment by richarddavenport** [comment]
So, this is a stupid question...how do I test that commit?

**Comment by richarddavenport** [comment]
@mcornella nevermind, got it. I can confirm this fixes the issue! Thanks!

**Comment by mcornella** [comment]
Sorry for the late response. [Here is a good resource to learn how to test pull requests](https://help.github.com/articles/checking-out-pull-requests-locally/).

**Comment by apjanke** [comment]
This sounds like you're running in to a bug in `xterm.js` – it disables mouse wheel scrolling when the numeric keypad is in application mode, for some reason. I don't think that's expected behavior for application keypad mode.

But I think this is still a reason to do the #5113 "ditch smkx" thing: application keypad mode is used less commonly than normal mode, so you're more likely to run in to wonky behavior in various terminal emulators when using it.
