### ISSUE TITLE
gulp -v display bug

### ISSUE THREAD

**Issue by zhangjingjing2020** [robbyrussell/oh-my-zsh#5421]
![image](https://cloud.githubusercontent.com/assets/12322141/18660666/51bb461a-7f44-11e6-9df5-31387221f6e2.png)
can not  display the time when i using command 'gulp -v'

**Comment by mcornella** [comment]
That's a color issue, try highlighting the whole text and you'll see there's something there.

After following the gulp source, I've managed to find the ultimate culprit: [the fancy-log package](https://github.com/js-cli/fancy-log/blob/349e046/index.js#L9) outputs the timestamp in grey color. 

You should fix your terminal color scheme so that grey is more visible. Cheers.
