### ISSUE TITLE
Syntax highlighting very verbose, after update in Sierra OSX

### ISSUE THREAD

**Issue by lbronsdijk** [robbyrussell/oh-my-zsh#5469]
Very strange line appears after updating to Sierra OSX:

```
:~ $ cd
_zsh_highlight_main_highlighter_expand_path:7: scalar parameter REPLY created globally in function _zsh_highlight_main_highlighter_expand_path
```
... followed by the actual command highlighted and executing.

Suggestions, anyone?

**Comment by lbronsdijk** [comment]
Problem solved. Reinstalled zsh-syntax-highlighting.

**Comment by ronanguilloux** [comment]
For whom it may help, I faced the same issue, and solved it this way:

- I re-read the [installation process](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md)
- since my version was installed via antigen, I re-read the antigen part of the install doc
- I updated all my antigen-managed plugins, included syntax-highlighting, via the `antigen update` command
- all was fixed.
