### ISSUE TITLE
gradle -? fails with omz

### ISSUE THREAD

**Issue by johnament** [robbyrussell/oh-my-zsh#5577]
```
╰─[:)] % gradle -?  
zsh: no matches found: -?
```

Need some way to make -? work in some cases.

**Comment by mcornella** [comment]
`?` is a glob character, which means it's used to match files and directories. To disable parsing that as a globbing character you can either quote it with double or single quotes, or alias `gradle` so that it doesn't treat it as globbing characters, like so: `alias gradle='noglob gradle'`.
Not this last one will also get rid of asterisk `*` and other globbing characters.
