### ISSUE TITLE
strange Symbol when in a git Repo

### ISSUE THREAD

**Issue by CDitzel** [robbyrussell/oh-my-zsh#5682]
Using the Agnoster Theme and the Git Plugin, I do experience some strange display when changing into an git repository. On my server everything seems to work ok but ion my personal computer I get the following 

![111](https://cloud.githubusercontent.com/assets/22954412/20786190/d3c0a996-b7a4-11e6-909f-8e8b2f0b9b89.png)

does anyone why?

**Comment by mcornella** [comment]
That's the [`unstagedstr` symbol that agnoster shows](https://github.com/robbyrussell/oh-my-zsh/blob/6ee6a73/themes/agnoster.zsh-theme#L122) when you have new unstaged changes in your git project ([+info](https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository)). 

It's definitely normal, but it might look weird because of your powerline font. Here's how it looks on my Windows with [Source Code Pro](https://github.com/powerline/fonts/tree/master/SourceCodePro):

![agnoster unstaged changes screenshot](https://cloud.githubusercontent.com/assets/1441704/20792296/52a01050-b7c1-11e6-9d22-a6cc90882038.png)
