### ISSUE TITLE
installer should trigger zsh installation for main distros whenever this is needed

### ISSUE THREAD

**Issue by ssbarnea** [robbyrussell/oh-my-zsh#5692]
The one line installer should trigger zsh installer using distro installer when this is available. This should work very easy well for `brew`, `apt-get`, `yum`, `dnf`.

**Comment by mcornella** [comment]
This is not possible at the moment because we don't have a good cross-platform database of commands to use. I would think about adding that if we had it, but first I would like to have a wide enough coverage of that in the [wiki section](https://github.com/robbyrussell/oh-my-zsh/wiki/Installing-ZSH#howto-install-zsh-in-many-platforms).
