### ISSUE TITLE
how to know my current theme ?

### ISSUE THREAD

**Issue by shirishag75** [robbyrussell/oh-my-zsh#5725]
I have .oh-my-zsh running and some theme, is there a way to know what is the current theme without looking into .zshrc ?

Similarly, is it possible to have a  list of all themes similar to 

`$ prompt -l `

as can be done in plain .zsh session ?

**Comment by mcornella** [comment]
`echo $ZSH_THEME`. Yeah we don't have a function to run, but we could fix that with `prompt`. 

Regarding the list of themes with zsh's built-in prompt manager: that would be nice to have. I'm not entirely sure how it works and if we should modify themes for that to work. But we're planning on making a new milestone checklist for the things we need ohmyzsh to have (i.e. testing, CI checks,...), so I'll add this request to the list.

IIRC that's how prezto loads their themes, and they have other stuff that makes their maintenance easier—which we've never been able to add for lack of time and dedication—so that's one more feature to try implementing.

Thanks for the suggestion!

**Comment by rockmkd** [comment]
@luvpreetsingh 
Maybe it would work

```
print $RANDOM_THEME
```

**Comment by michelalbers** [comment]
@rockmkd - thats it!

**Comment by ankit-indexnine** [comment]
@rockmkd - You rock man !!

**Comment by mcornella** [comment]
You can use `omz theme list` now:
```console
➜  ohmyzsh git:(master) omz theme list
Current theme: robbyrussell

...
```
