### ISSUE TITLE
segfault in zsh (with help from oh-my-zsh)

### ISSUE THREAD

**Issue by kontrafiktion** [robbyrussell/oh-my-zsh#5755]
I got a segfault whenever I am pasting into my terminal window!
The minimal way to reproduce it:

1) start `zsh -f`
2) source the following script:

        source $ZSH/oh-my-zsh.sh
        alias h='history'
        h() {
          echo "foo"
        }

3) paste something 

I also reported it to zsh-workers (http://www.zsh.org/mla/workers/2017/msg00025.html), but wanted to make this known here as well. Since it only happens when I am sourcing oh-my-zsh

Environment:
  OS X 10.12.2
  iTerm 2 (3.0.13)
  zsh 5.3.1 (x86_64-apple-darwin16.3.0) # via homebrew
  oh-my-zsh: cae540f899b1e302e514e190f7d51331a5a689e0

**Comment by mcornella** [comment]
Can't reproduce. If this is still happening, narrow down the specific file inside OMZ's lib folder that triggers this, then test it line by line. 

It needs to be said though that defining a function without the function keyword is error-prone because zsh will expand the name of the function to the value of the alias. So, in your example, you're actually defining a function named history, since that's the value of the h alias.

Reopen if necessary.

**Comment by kontrafiktion** [comment]
Has been fixed in zsh

**Comment by pwhite2** [comment]
For those who have an older version of ZSH and are encountering this issue, I found the culprit to be ~/.oh-my-zsh/lib/misc.zsh.

Setting "DISABLE_MAGIC_FUNCTIONS=true" in my ~/.zshrc immediately before "source $ZSH/oh-my-zsh.sh" resolved the problem.

**Comment by nicain** [comment]
@pwhite2 I just hit this on zsh 5.7.1 (x86_64-debian-linux-gnu), and fixed it with your suggestion!

**Comment by pwhite2** [comment]
@nicain I'm glad to hear that helped!
