### ISSUE TITLE
ls alias conflict ?

### ISSUE THREAD

**Issue by Jucgshu** [robbyrussell/oh-my-zsh#5783]
Hi guys,

I'm trying to add an alias ls='ls -N --group-directories-first' with no effect.
I tried either in my ~/.zshrc or ./plugins/common-aliases/common-aliases.plugin.zsh files.
Is there a conflict on the ls command somewher ?

Thanks for your help.

**Comment by GreatBahram** [comment]
you have to put your alias in this file : 
**~/.oh-my-zsh/lib/directories.zsh**

**Comment by Jucgshu** [comment]
Thanks for your answer. Unfortunately that didn't work.

(also, I don't get why I shouldn't put my aliases in my zshrc file)

-j

**Comment by GreatBahram** [comment]
actually you can put it in you zshrc  and it should works , but in  ./plugins/common-aliases/common-aliases.plugin.zsh  not works because you have to tell zshrc use this zsh file 
can you give your output ? which error you see after you put your alias in your .zshrc file ?

**Comment by Jucgshu** [comment]
It's not working wherever I try to add my 'ls' alias. Also I have other aliases that work fine when I add them in my ~/.zshrc file.

Don't see any error btw. Is there any log file I can check in particular ?

**Comment by shinenelson** [comment]
Where are you defining the aliases in your `$HOME/.zshrc` file? It could be that you're defining them before the shell is initialized which probably over-rides your aliases with the aliases by the plugins.

Check whether you're defining your aliases after the line that reads `source $ZSH/oh-my-zsh.sh` in `$HOME/.zshrc`.

If you're using a custom file that's not `$ZSH/custom`, then make sure that is set as the `$ZSH_CUSTOM` variable in `$HOME/.zshrc`. (Or, though you don't have to do this, source the file / directory after the `source $ZSH/oh-my-zsh.sh` line)

The best place to define your custom aliases is in `$ZSH/custom`, but if you have a use-case where you need to put it elsewhere and link it in, use the `$ZSH_CUSTOM` variable. If `$ZSH_CUSTOM` doesn't work for you either, then `source` the file after `source $ZSH/oh-my-zsh.sh` line. And if you really want to put all your aliases in your `$HOME/.zshrc` file, then you should put them at the end of the file under the `# User configuration > aliases` (Yes, there's a special section for aliases at the end of the file)

**Comment by Jucgshu** [comment]
Hi @shinenelson & thanks a lot for your answer.

I defined 2 aliases in my ~/.zshrc file.
* One "Tmux" alias that works just fine
* One "ls" alias that just doesn't want to work.

I checked my ~/.oh-my-zsh/custom folder & deleted it to be sure, but it didn't make any difference. 

Regarding the position in the file, it goes like this : 
```# Alias
alias ls='ls -N --group-directories-first'
alias tmux="tmux new-session -A -s main"

ZSH_CACHE_DIR=$HOME/.oh-my-zsh-cache
if [[ ! -d $ZSH_CACHE_DIR ]]; then
  mkdir $ZSH_CACHE_DIR
fi

source $ZSH/oh-my-zsh.sh
```

**Comment by shinenelson** [comment]
I thought my answer was well-described as to what you have to do to fix your issue @Jucgshu. Even though I did ask some questions, those were for you to ask them yourself and figure out the solution.

And like I had clearly predicted, your alias definitions are above the `source $ZSH/oh-my-zsh.sh` line. This makes oh-my-zsh to override your alias definitions if they are in conflict. It's not a design bug, it's just how oh-my-zsh follows instructions, top-down.

By default, oh-my-zsh has the in-built alias for `ls`, so, during the execution of the `.zshrc`, zsh (not oh-my-zsh) aliases `ls` to your preferred alias and then `source $ZSH/oh-my-zsh.sh` which has its own alias for `ls` which then overrides your alias definition of `ls`. That is precisely why `.zshrc` has this section at the end of `.zshrc`.
> \# Set personal aliases, overriding those provided by oh-my-zsh libs,
> \# plugins, and themes. Aliases can be placed here, though oh-my-zsh
> \# users are encouraged to define aliases within the ZSH_CUSTOM folder.
> \# For a full list of active aliases, run `alias`.
> \#
> \# Example aliases
> \# alias zshconfig="mate ~/.zshrc"
> \# alias ohmyzsh="mate ~/.oh-my-zsh"

The reason why your alias for `tmux` works from the same position where it is defined is because it doesn't have an equivalent alias that might override it from the oh-my-zsh plugins.

Please read my previous answer for the solution to your problem. Especially the second paragraph and the last line of the answer.

PS : You shouldn't be removing the `$ZSH/custom` directory. Instead, you should be putting all of your custom definitions (aliases, functions, plugins, whatever) there (rather than the `.zshrc` file itself; but meh, that's your choice to make).

**Comment by Jucgshu** [comment]
Yup. Working now.

Thanks.
