### ISSUE TITLE
lscolors -not colorize, just bold

### ISSUE THREAD

**Issue by ansyor** [robbyrussell/oh-my-zsh#5827]
I just new in oh-my-zsh. But I have a problem with colors.

So in my iterm, the 'l' command will show like the image, the folder name do not will colorize just bold
![snip20170129_1](https://cloud.githubusercontent.com/assets/8895399/22400932/d374e33e-e5f4-11e6-998b-fecb0fe7643b.png)

And I only change in .zshrc, set the theme to agnoster and in last line I override the prompt_context to hide my username and hostname.
![snip20170129_2](https://cloud.githubusercontent.com/assets/8895399/22400934/d74f37d4-e5f4-11e6-82a8-f73840b3e365.png)

I have tried to see other issues and tried the solution like set LSCOLORS and set plugin like warhol and dircolor. But in same goes wrong. Maybe I just dont do the right track the solution.

So is there a simple solution to this color issues?

**Comment by seagle0128** [comment]
I think you should change the color/theme of the iTerm.

**Comment by mcornella** [comment]
You need to change the color scheme of your terminal emulator, as said above.

**Comment by amejiarosario** [comment]
@ansyor I had the same issue. It was because I was using a color theme that made all gray.

# Before using gray color thme
![image](https://user-images.githubusercontent.com/418605/49827259-e7a27a80-fd56-11e8-9d6c-d4421224fe60.png)

# After using another color theme
![image](https://user-images.githubusercontent.com/418605/49827221-cb064280-fd56-11e8-8920-7d84e57cd5ca.png)
