### ISSUE TITLE
return "1" when open a new tab

### ISSUE THREAD

**Issue by troyliu0105** [robbyrussell/oh-my-zsh#5845]
Every time when I open a new tab, it return error, code 1... no matter I use iTerm2 or Terminal of system. 
If I just press "enter", it continues to show error, when I enter some other command, then the error will disappear.

But when after I opened tab, and run a new zsh in current tab, it works fine.
<img width="762" alt="2017-02-04 4 57 06" src="https://cloud.githubusercontent.com/assets/5518286/22608430/c96ec31c-ea97-11e6-852b-5cd9643dcf68.png">

**Comment by mcornella** [comment]
This means that the very last command run when starting a zsh session finishes with an exit code. That is probably the last command in your zshrc file. Have a look at that.

**Comment by kjleitz** [comment]
I just ran into this, and the given resolution is very possibly **not** the actual cause of this issue. On my machine, the issue came from `/etc/zshrc` with no modification. There is, however, a fix/workaround. For posterity, I'll detail here.

If you check `/etc/zshrc`, the last lines in a vanilla install on macOS are:

```zsh
# Useful support for interacting with Terminal.app or other terminal programs
[ -r "/etc/zshrc_$TERM_PROGRAM" ] && . "/etc/zshrc_$TERM_PROGRAM"
```

`$TERM_PROGRAM` in Terminal.app is, for example, `Apple Terminal`. In iTerm2, it's `iTerm.app`. There is a file called `/etc/zshrc_Apple_Terminal` on my system by default, but there is no file named `/etc/zshrc_iTerm.app` on my system. As a result, this line results in an exit code of `1` when `/etc/zshrc` is sourced for a new shell.

The workaround is to create a new file called `/etc/zshrc_iTerm.app` (i.e., `/etc/zshrc_$TERM_PROGRAM` for your preferred terminal emulator):

```zsh
sudo touch /etc/zshrc_$TERM_PROGRAM
```

**NOTE:** For the `/etc/zshrc_Apple_Terminal` file on my machine, the permissions are `-rw-r--r--` and owned by `root`/`wheel`, so I used `sudo` as a shortcut to set those options automatically. Your machine may differ.

Once I touched that file, new shells didn't annoyingly start out with `$?` being `1`.
