### ISSUE TITLE
Install oh-my-zsh in a script

### ISSUE THREAD

**Issue by mkitby** [robbyrussell/oh-my-zsh#5873]
Hello,

I use this script to install oh-my-zsh
```
#!/bin/bash
sudo apt-get update
sudo apt-get install zsh -y
chsh -s $(which zsh)
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
########################
mkdir ~/bin

stuff...
```

After install the oh-my-zsh, the script will exit and the reamining commands are not executed. What should I do if I want to execute it?

Thanks

**Comment by loket** [comment]
Just ran into the same problem. The reason is the `env zsh` command in [install.sh](https://github.com/robbyrussell/oh-my-zsh/blob/551abfcbb48a0c001eadef80abc3276af4e9ad26/tools/install.sh#L113), which launches zsh at the very end of the installation.

So I was thinking the script could take in an additional argument (like `--no-env` or something more intuitive), which could be checked before running `env zsh` in the script.

That way you can install Oh My Zsh from a script, without breaking the existing install procedure.

I'll try to create a pull request when I have time.

**Comment by mkitby** [comment]
Hi loket, Thanks for your input.

**Comment by loket** [comment]
Obviously, while waiting for review of the pull request, you can use the script in my repo instead:

```shell
sh -c "$(curl -fsSL https://raw.githubusercontent.com/loket/oh-my-zsh/feature/batch-mode/tools/install.sh)" -s --batch || {
  echo "Could not install Oh My Zsh" >/dev/stderr
  exit 1
}
```

Comments are welcome! 😄

**Comment by Ferrer-Jeremy** [comment]
You can also do:
```shell
wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh
sed -i.tmp 's:env zsh::g' install.sh
sh install.sh
```
The `sed` will remove the `env zsh` at the end

**Comment by richardlock** [comment]
You can also run the following to do this in a one liner similar to the normal install:

```
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sed 's:env zsh::g' | sed 's:chsh -s .*$::g')"
```

**Comment by C0rn3j** [comment]
`env zsh` is now `env zsh -l` so the workaround would now be as follows:

```
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sed 's:env zsh -l::g' | sed 's:chsh -s .*$::g')"
```

**Comment by looneym** [comment]
For anyone else landing here because their sed hack on the install script broke recently: there's now an  `unattended` option on the install script. https://github.com/robbyrussell/oh-my-zsh#unattended-install
