### ISSUE TITLE
Write a function in zshrc that can take a parameter and can handle flags on MacOS

### ISSUE THREAD

**Issue by bythckr** [robbyrussell/oh-my-zsh#5917]
I usually need a chrome page opened to localhost:3000 when I am developing. So, I just run the following cmd: 
`/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --app=http://localhost:3000`

Since I use this frequently and sometimes my port changes. I want to write a function in zsh where ch will open chrome in localhost:3000 while ch 2500 will open chrome in localhost:2500.

So far, this is what I have managed to do:
```
ch () {
    command "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
}
```
This opens a new chrome window but displays an error/warning in the console: `/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-9.1.12/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 3
`
But when I add a flag:
```
ch () {
    command "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome --app=http://localhost:3000"
}
```
Nothing happens and I end up getting an error: `ch:1: no such file or directory: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --app=http://localhost:3000`

**Comment by Thubo** [comment]
Hi there,

I don't think this is a oh-my-zsh problem per se. Nevertheless, you can create new function like this:

```
ch () {
  /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --app=http://localhost:$1
}
```

Store it in a file and source the file with `source file.zsh` now you should be able to run `ch 3000` to launch your Google Chrome in app-mode on `http://localhost:3000`

Note:
* I've added a `\` before the spaces, otherwise your shell wouldn't know that it is still part for the filepath for the application you want to launch
* I've added the `$1` which represents the first string after the call of the function, this way you can easily modify the port while calling it.

Hope this helps.

**Comment by bythckr** [comment]
@Thubo Thank you.
