### ISSUE TITLE
battery percentage is different from the one in the menu bar

### ISSUE THREAD

**Issue by cscetbon** [robbyrussell/oh-my-zsh#5969]
the menu bar shows me 100% while oh-my-zsh shows me 95% : 
http://www.picpaste.com/Screen_Shot_2017-03-16_at_10.12.26_AM-c77I5TcO.png
http://www.picpaste.com/Screen_Shot_2017-03-16_at_10.12.35_AM-75WarLr2.png

**Comment by mcornella** [comment]
Reopen if this still happens.

**Comment by cscetbon** [comment]
Can you add more information ? Was an issue like that fixed ? 2 years passed ...

**Comment by mcornella** [comment]
This is old yes, that's why I closed it. If this still happens you can reopen the issue, and update your information (the screenshots are dead for instance, and it would be nice knowing which plugin do you use to know the battery percentatge), then I can do followup. Otherwise I don't know where even to start.
