### ISSUE TITLE
Please make some of the stuff in lib/* optional

### ISSUE THREAD

**Issue by madduck** [robbyrussell/oh-my-zsh#5970]
I don't need or want some of the stuff that omz autoloads from `lib/*.zsh`. I know I can put empty files into `$ZSH_CUSTOM/lib`, but I wonder what the criteria are anyway, i.e. why does some of the stuff that should probably be in a plugin (`nvm.zsh` or `bzr.zsh`) or is way too specific (e.g. `misc.zsh`) gets loaded unconditionally?

Would you accept a patch that honoured an array like `plugins`, or maybe an array of lib modules to skip?

**Comment by mcornella** [comment]
The criteria for lib files are things that are common to plugins or themes, as well as baseline configuration for zsh. Loading these normally don't cause side effects nor performance issues, and will only be used if a plugin or theme uses them. That's why I don't see the need for overcomplication the init script more than it is now.
