### ISSUE TITLE
ZSH Theme adds 1 extra space

### ISSUE THREAD

**Issue by AnthonyWC** [robbyrussell/oh-my-zsh#6007]
I notice when I enable ZSH theme that I can an extra space to the left of the prompt, is this by design or a bug? Is it something that I can change?

No theme:
![image](https://cloud.githubusercontent.com/assets/6215805/24582199/806f84f2-16f8-11e7-8fb5-bc1928f11c83.png)

ZSH_THEME="robbyrussell"
![image](https://cloud.githubusercontent.com/assets/6215805/24582179/35939248-16f8-11e7-8981-02ea0be0c74a.png)

ZSH_THEME="powerlevel9k/powerlevel9k"
![image](https://cloud.githubusercontent.com/assets/6215805/24582170/ff387416-16f7-11e7-9c72-01866bfe1c0c.png)

More clearly seen from the left.

**Comment by beebird** [comment]
I have similar problem, not sure how it happened but I didn't do any config change recently, there're two extra spaces when I logged in.

The command I used to log in is:

> ssh xxx@xx.xx.xx.xx -t tmux new-session -A -s xxx

![image](https://cloud.githubusercontent.com/assets/3321149/24784777/6dccf92c-1b87-11e7-9a96-b381140cf37a.png)

Another weird thing is that those extra spaces are gone  if I do a normal login:  

> ssh xxx@xx.xx.xx.xx

![screen shot 2017-04-07 at 11 47 01 am](https://cloud.githubusercontent.com/assets/3321149/24784885/30dafc0c-1b88-11e7-8ddf-875470f0b46e.png)

The PROMPT variable here is '${ret_status} %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)' 

The issue can be reproduced on Mac from both iTerm and Terminal.

**Comment by beebird** [comment]
any update?

**Comment by kokutoukiritsugu** [comment]
add a spece between cursor and commands.
conemu and realconsole:
![snipaste_20170413_165438](https://cloud.githubusercontent.com/assets/5471433/24998079/8579b5ea-206b-11e7-8f8d-5400063975fe.png)

**Comment by snowzjx** [comment]
I have the same problem when I use Cmder for Linux subsystem on windows.

**Comment by kokutoukiritsugu** [comment]
https://github.com/Maximus5/ConEmu/issues/1106

**Comment by KuromiAK** [comment]
After some testing (161206 stable), it appears that ConEmu is confused about character '➜' (arrow in robbyrussell), '' (powerline arrow) and '' (powerline branch symbol). The symbols are supposed to be 1 character wide but ConEmu advances cursor by 2 characters when they are inputed. ConEmu also only retracts by 1 character when these symbols are deleted.

**Comment by mcornella** [comment]
Extra spaces can also happen on themes that use UTF-8 characters and the `locale` is not set to a language with UTF-8 charset.

**Comment by apresvous** [comment]
Has anyone been able to find a fix this?
I'm experiencing the same issue with iterm2 on macOS

```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by DYW972** [comment]
> Extra spaces can also happen on themes that use UTF-8 characters and the `locale` is not set to a language with UTF-8 charset.

Hello,

Thank you for your answer but can you explain a bit more  ?

Thank you

**Comment by mcornella** [comment]
> Thank you for your answer but can you explain a bit more ?

See https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#how-do-i-change-my-locale

Also bear in mind that some themes do add an extra space, like the robbyrussell one, so knowing which theme you're using and a screenshot would be great.

**Comment by DYW972** [comment]
Hello @mcornella 🖖

Thank you for you answer !

I'm not using Oh My Zsh and I don't have a theme on my terminal. I just configured my terminal with some features from OMZsh and I've found an issue with fonts if the terminal is configure in French. Some characters like "é", "è", "ô", etc... don't appear.

This happened when I added zsh-syntax-highlighting script in my config.

I found this issues when I was searching some informations about it. What you wrote intrigued me and I wanted to have more explanations in order to understand much more. 

So, I've made some research and I found that my locale was like this :

LANG="fr_FR.UTF-8"
LC_COLLATE=""
LC_CTYPE=""
LC_MESSAGES=""
LC_MONETARY=""
LC_NUMERIC=""
LC_TIME=""
LC_ALL=

Don't know why and if it's even possible so I decided to change it like this :

LANG="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_CTYPE="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_ALL="fr_FR.UTF-8"

But still the same issue...

So I decided to change my 'LANG' to 'en_US' like this :

`# Force translation in English to fix zsh French font troubles
export LANG=${LANG/fr_FR/en_US}`

Do you have any suggestions about locale LANG ? Just a lead.
