### ISSUE TITLE
gitfast: support git's worktree command in tab completion

### ISSUE THREAD

**Issue by hjpotter92** [robbyrussell/oh-my-zsh#6137]
The `compdef` files for git and gitfast plugins can be extended to include `worktree` definitions.

**Comment by mcornella** [comment]
Can you expand further? What do you mean by worktree definitions? What commands should be completed?

**Comment by mortenfyhn** [comment]
I think the idea is that commands starting with `git --work-tree=$SOME_DIR` should be able to autocomplete. Usually you can do, say, `git add <some file>` with autocompletion for the file because you run the command from the directory the file is in, but when you have a git repo where the work tree is somewhere else, that doesn't work, and it would be neat with autocompletion of files in the directory specified in the `--work-tree` option.

**Comment by hjpotter92** [comment]
@mortenfyhn The `--work-tree` autocompletion is already supported by the gitfast plugin. Check the definition [here][1].

@mcornella I was referring to the [git-worktree][2] subcommand:

    git worktree add [-f] [--detach] [--checkout] [--lock] [-b <new-branch>] <path> [<commit-ish>]
    git worktree list [--porcelain]
    git worktree lock [--reason <string>] <worktree>
    git worktree move <worktree> <new-path>
    git worktree prune [-n] [-v] [--expire <expire>]
    git worktree remove [--force] <worktree>
    git worktree unlock <worktree>

  [1]: https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/gitfast/_git#L174
  [2]: https://devdocs.io/git/git-worktree

**Comment by mortenfyhn** [comment]
@hjpotter92 Didn't know about gitfast, that's wonderful, thank you!

**Comment by mcornella** [comment]
You can also use the latest version of [zsh's official git completion](https://github.com/zsh-users/zsh/blob/master/Completion/Unix/Command/_git), which supports all these subcommands: 
https://github.com/zsh-users/zsh/blob/14fa595f66748912326dc1320edea29add93a170/Completion/Unix/Command/_git#L2043-L2116

We at OMZ can't do anything else but recommend either that or upgrading your zsh version if you can, since completion for certain commands like git are handled by the official zsh project.

**Comment by hjpotter92** [comment]
I'm using zsh-5.5.1, and according to [the tagged version][1] on repository, it should be autocompleting worktree sub-commands.

I wonder if it might be some other issue. I'll raise this issue at zsh channel itself.

Thanks.

  [1]: https://github.com/zsh-users/zsh/blob/zsh-5.5.1/Completion/Unix/Command/_git#L2034

**Comment by mcornella** [comment]
I'm on 5.3.1 and I'm at least getting these:
```
$ git worktree
add     -- create a new working tree
list    -- list details of each worktree
lock    -- prevent a working tree from being pruned
prune   -- prune working tree information
unlock  -- allow working tree to be pruned, moved or deleted
```

Make sure you're loading the official zsh completion and there isn't another `_git` file that's getting loaded instead.

This little script will tell you where there are _git paths and the order in which they're being loaded (first appearance means first load):
```
for d ($fpath); do [[ -f $d/_git ]] && echo $d; done
/usr/share/zsh/functions/Completion/Unix
```

**Comment by hjpotter92** [comment]
@mcornella The `gitfast` plugin's `_git` definition is taking precedence. :/ Any suggestions on how to disable this without removing gitfast itself?

Also, as you mentioned earlier, since omz won't be covering git autocompletion, should I submit a PR which removes the same?

**Comment by mcornella** [comment]
The gitfast plugin is an exception, because it overrides zsh completion with git's completion. I meant that we don't ship zsh's official git completion because they already ship it.

A better solution is updating gitfast with the latest versions of [git's completion](https://github.com/git/git/tree/master/contrib/completion), which I think has support for worktree.

**Comment by mcornella** [comment]
I've pushed a newer completion from v2.10 which has some worktree commands. I haven't used newer git versions for fear of breaking something (v2.19 threw errors on my 2.11 installation).
