### ISSUE TITLE
Auto-completion of java in zsh is extremely slow

### ISSUE THREAD

**Issue by lxhao** [robbyrussell/oh-my-zsh#6150]
hello!
when I need to use java command run a class file,  the auto-completion of zsh is  slow extremely.
such as  when I inputed `java Tes` and pressed tab to auto-completion rest part assume there are have Test.class in current direction.

**Comment by mcornella** [comment]
That's because zsh's java completion looks for any .class file in your $CLASSPATH, which is normally your current working directory. That means that it will look for `.class` files in any subdirectory, and if you have many directories it'll take time.

See this example:
```
$ mkdir -p tech/ohmyzsh/src
$ touch tech/ohmyzsh/src/Main.class tech.class
$ java te[TAB]
tech.ohmyzsh.src.Main  test
```

There is nothing we can do at OMZ, this is a problem in zsh's official completion.
