### ISSUE TITLE
issue: showed me "argument too long"

### ISSUE THREAD

**Issue by zyimin** [robbyrussell/oh-my-zsh#6174]
I wanted to delete all mail files with "rm *". Because there's more than 10thousands files, zsh told me argument too long.

**Comment by eremit** [comment]
I'm sorry to let you down, but is neither an oh-my-zsh issue nor a zsh-specific issue at all since this will also happen with bash.

Anyhow quick answer to this: the reason for this is that the asterisk is expanded to every matching file which produces a very long command line. This apparently hits the limit of how long a command line is allowed to be (you can check with xargs --show-limits)
