### ISSUE TITLE
Google Cloud SDK support

### ISSUE THREAD

**Issue by CicoZhang** [robbyrussell/oh-my-zsh#6205]
Does oh-my-zsh have such a plugin that supports the auto completion of Google Cloud SDK (i.e., gcloud)?

**Comment by rafee** [comment]
I am using this one https://github.com/littleq0903/gcloud-zsh-completion with antigen. A bit of manual override is involved though. After using antigen bundle and and antigen apply, I have to hard link the files to external directory as well.

**Comment by magicalbanana** [comment]
Hmm, anyone make this works successfully with the completion script that's part of the SDK?

**Comment by CristianCantoro** [comment]
Since `google-cloud-sdk` provides already the necessary functions in `"${CLOUD_SDK_HOME}/completion.zsh.inc` the only hard thing to do to write a working plugin is having a reliable way to find where the file is, and this depends on how `google-cloud-sdk` has been installed.

For example, using the repo on Ubuntu 16.04, the completion files are in `/usr/share/google-cloud-sdk`.

**Comment by mcornella** [comment]
Anyone willing to step up and make a plugin?

**Comment by chuckstar76** [comment]
@mcornella it sounds like we just need to gather the relevant OS locations for the google-cloud-sdk?

I think @steshaw  and @CristianCantoro have provided those for MacOS and Ubuntu.
What other OS's are required?

Sounds like MacOS is already catered for anyway... as like @steshaw indicated the ~./zshrc tends to get populated correctly anyway - particularly if you use homebrew.

**Comment by daallgeier** [comment]
Debian and CentOS are quite popular OS's on GCP.

**Comment by ianchesal** [comment]
Pull request #8144 adds a `glcoud` plugin that works for most methods for installing the SDK on most platforms. For non-standard installation locations you can set `CLOUDSDK_HOME` in your `zshrc` before loading oh-my-zsh and the plugin will use that instead of trying to find the location of your installation.
