### ISSUE TITLE
env: node: No such file or directory! oh-my-zsh nuked my npm/node install??

### ISSUE THREAD

**Issue by sw-yx** [robbyrussell/oh-my-zsh#6257]
Hello.. i installed oh-my-zsh, edited the .zshrc file to tweak the theme (and nothing else) and now i realized i can't run `npm` or `node`! any suggestion on how to diagnose what's wrong?

**Comment by sw-yx** [comment]
to people from the future: i completely [uninstalled node](https://stackoverflow.com/questions/43465086/env-node-no-such-file-or-directory-in-mac) and then reinstalled node again. was not very happy with having to do that but it fixed the emergency problem. i would still very much like to know what went on

**Comment by sw-yx** [comment]
i have been advised that [oh-my-zsh screws with the $PATH variable](http://www.jacobsingh.name/content/adding-your-path-oh-my-zsh). i would suggest adding some sort of warning or instructions for people...

**Comment by jnugh** [comment]
Whichever shell you used before has a file that is used to change the default settings of your system.
In this case it seems to have added something to the path. When you start using another shell (zsh in this case) another file is being used. Let's assume you used bash before, whenever you open a shell bash will look at your system defaults, and at `~/.bashrc`. Whatever is in there will be added / will override the defaults.
You changed to zsh now, which will use `~/.zshrc` instead of `~/.bashrc`.

It seems like `node` has not been installed into a folder that is part of `$PATH` on your system by default. When you first installed nodejs you (or the installer) changed the shell's rc file to add another path to `$PATH`.

A simple solution would have been to copy the additions made to your environment variables from your old RC file. No need to reinstall node - installing a shell will not mess with your binaries.

The blog post you linked here was about setting `$PATH` in plugins - which is probably not related to your problem.

**Comment by sw-yx** [comment]
thank you.

**Comment by jordanmccollam** [comment]
@jnugh I am having this issue and I just came across this post. I am a bit new at coding. . . Can you explain how to "copy the additions made to your environment variables from your old RC file"?

**Comment by jnugh** [comment]
You should have a .bashrc and a .zshrc file in your home directory.
Your bashrc file probably contains lines like `export PATH=... ` just copy those to zshrc and reopen the terminal ;)

**Comment by amirgohar-AG** [comment]
If you installed ohmyzsh with the installation script, it will backup your older settings into the home directory 
`~/.zshrc.pre-oh-my-zsh`
You can copy the content from their and paste in the end of the new ~/.zshrc

**Comment by daviddossantos** [comment]
thanks @amirgohar-AG
