### ISSUE TITLE
bad math expression: illegal character with zsh 5.4.1

### ISSUE THREAD

**Issue by runningman84** [robbyrussell/oh-my-zsh#6258]
It looks like the latest arch linux zsh update broke the oh-my-zsh config:

```
aladin% sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
Cloning Oh My Zsh...
Klone nach '/home/user/.oh-my-zsh' ...
remote: Counting objects: 831, done.
remote: Compressing objects: 100% (700/700), done.
remote: Total 831 (delta 14), reused 776 (delta 10), pack-reused 0
Empfange Objekte: 100% (831/831), 567.67 KiB | 4.05 MiB/s, Fertig.
Löse Unterschiede auf: 100% (14/14), Fertig.
Looking for an existing zsh config...
Found ~/.zshrc. Backing up to ~/.zshrc.pre-oh-my-zsh
Using the Oh My Zsh template file and adding it to ~/.zshrc
         __                                     __   
  ____  / /_     ____ ___  __  __   ____  _____/ /_  
 / __ \/ __ \   / __ `__ \/ / / /  /_  / / ___/ __ \ 
/ /_/ / / / /  / / / / / / /_/ /    / /_(__  ) / / / 
\____/_/ /_/  /_/ /_/ /_/\__, /    /___/____/_/ /_/  
                        /____/                       ....is now installed!


Please look over the ~/.zshrc file to select plugins, themes, and options.

p.s. Follow us at https://twitter.com/ohmyzsh.

p.p.s. Get stickers and t-shirts at http://shop.planetargon.com.

compinit:480: bad math expression: illegal character: '
user@aladin:~% zsh --version
zsh 5.4.1 (x86_64-unknown-linux-gnu)
```

**Comment by GChicha** [comment]
Same problem here, deleting ~/.zcompdump seems to temporarily fix it

**Comment by runningman84** [comment]
Deleting the file only helps once, because a new session will recreate it and the next shell session will fail again. I added rm ~/.zcompdump* in my .zshrc which seems to help.

**Comment by sitic** [comment]
I have the same problem on one of my Arch machine, but not on others. This bug is not caused by oh-my-zsh, see [here](https://forum.manjaro.org/t/zsh-error-compinit-bad-math-expression/29120).

As hotfix either add `export ZSH_COMPDUMP=/tmp/zcompdump-$USER` to `.zshrc` before the `source $ZSH/oh-my-zsh.sh` command (for reasons unkown this works for me), or edit `~/.oh-my-zsh/oh-my-zsh.sh` and replace the `compinit` commands on line 74 and 77 with `compinit -D` (this disables the dump file which is used for speed improvements for completions).

**Comment by codermikael** [comment]
The hotfix  suggested by @sitic does not work for me

**Comment by dpisklov** [comment]
Thanks @sitic that works for me
