### ISSUE TITLE
Move all oh-my-zsh completions out plugins

### ISSUE THREAD

**Issue by marcthe12** [robbyrussell/oh-my-zsh#6280]
There are many plugins with just completions, I suggest that we have all the completions moved to $ZSH/completions. Then we add the zsh completion plugin from [here](https://github.com/zsh-users/zsh-completions). This simply addition of plugins, reduce the duplication of work in completion and also make a common place for all completions reducing the plugins we need to use

PS: If possible, move the completion to zsh-completions

**Comment by okapia** [comment]
I'd actually suggest that completions should if possible be contributed to zsh itself or to the upstream project for which the completions apply. Zsh includes a large number of completions and by contributing them there, they would benefit all users of zsh who run compinit. The only exception would be for things like _cargo that are copies of completions from upstream projects: having them in omz makes sense because sometimes the Linux distribution packages are lax about installing them.

I don't really understand what the point of zsh-completions is.

**Comment by marcthe12** [comment]
That zsh completion plugin does, it maintains completions that are missing in zsh or upstream.

**Comment by okapia** [comment]
> it maintains completions that are missing in zsh or upstream.

That isn't an explanation of what the point of it is. What is its reason for existing? In other words, why were the functions not simply contributed to zsh or to upstream. My guess is that someone perceived the mailing list as being too intimidating or something like that.

**Comment by marcthe12** [comment]
This projects aims at gathering/developing new completion scripts that are not available in Zsh yet. The scripts may be contributed to the Zsh project when stable enough.

Copied from the readme. It's also part of zsh users which are close to upstream zsh. Let's put it this way. So they are not afraid of the mail information list rather I believe they share the mailing zsh itself. Also upstream may not accept it.

**Comment by mcornella** [comment]
Won't fix. The way it's now guarantees that we only load completion from the plugins enabled.
