### ISSUE TITLE
oh-my-zsh.sh issues

### ISSUE THREAD

**Issue by hylrf0** [robbyrussell/oh-my-zsh#6417]
this morning I updated oh-my-zsh, when I open a new terminal it reminder me that 
![image](https://user-images.githubusercontent.com/18202558/32761495-4b2ad936-c8b9-11e7-9950-93997ef5b625.png)
 and I can't use zsh anymore, please help me to solve this problem, thanks

**Comment by nintra** [comment]
#6387 
I had to do the procedure also to some other files.

**Comment by eugenpirogoff** [comment]
I had the same issue after updating with Homebrew and git in Oh-My-ZSH. Deactivating git plugins lead me to the issue that my path was not correct and ```^M``` attached in it. The issue was triggered by a git configuration. 

The solution was to set ```autocrlf = false``` in ```~/.gitconfig``` and reinstall Oh-My-ZSH after deleting your installation. The installation script will clone the repo with correct settings.

**Comment by pjhalsli** [comment]
anyone on Linux who can confirm this?
I dont even have ~/.gitconfig
I do have ~/.oh-my-zsh/.git/config
But in there there's nothing about autocrif at all.

**Comment by pjhalsli** [comment]
Well everything works fine now  :)

**Comment by ojongerius** [comment]
Case closed?

**Comment by wederer** [comment]
I had similar issues and fixed it by running: `find ~/.oh-my-zsh/ -type f -print0 | xargs -0 sed -i -e 's/\r$//'`
