### ISSUE TITLE
The terminal will stuck when exec source ~/.zshrc

### ISSUE THREAD

**Issue by yangbin1994** [robbyrussell/oh-my-zsh#6446]
It takes a few seconds to respond

**Comment by pjhalsli** [comment]
Same here - I timed it. it took 3 seconds to start.
When I typed exit it took 17 seconds to exit (close the terminal)

**Comment by yangbin1994** [comment]
i find a `.git` under of the `~`, delete it and resolve

**Comment by pjhalsli** [comment]
@bronze  lm just curious - you mean you found ~/.git
You deleted it and everhthing is fine.
All is fine for me to. After an update everything was back to normal. I had
lots of problems though. Would be nice to know what went wrong instead of
just been given medicin i like to know why i am sick in the first place.
Glad everything worked out fine for you too

Regards
PJ
Den lør. 25. nov. 2017, 08:24 skrev bzone <notifications@github.com>:
