### ISSUE TITLE
installation script does not work for windows subsystem linux behind firewall & Proxy

### ISSUE THREAD

**Issue by keyhan** [robbyrussell/oh-my-zsh#6499]
Trying to install it would fail with following result:
```
PML12962% sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
curl: (22) The requested URL returned error: 407
```
environment is Ubuntu bash in Windows 10.

**Comment by wrecklass** [comment]
That doesn't sound like the installer script, it sounds like your ubuntu shell either doesn't have full internet access or your proxy isn't working. What happens if you set the HTTP proxy like this:

`sh -c "$(curl -proxy "YourProxyHostURL" -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"`
