### ISSUE TITLE
Wrong package being run on zsh

### ISSUE THREAD

**Issue by fclaussen** [robbyrussell/oh-my-zsh#6601]
While attempting to run a yeoman generator, I get a message regarding yarn.
If I run `yo --version` I get yarn's version.
If I go to bash and run the same, I get the correct version and can run yo commands.

What am I doing wrong here?

<img width="648" alt="screen shot 2018-02-04 at 1 23 35 am" src="https://user-images.githubusercontent.com/1021860/35774859-127ce6c0-094a-11e8-8f40-1da1acfe22e9.png">

<img width="462" alt="screen shot 2018-02-04 at 1 24 21 am" src="https://user-images.githubusercontent.com/1021860/35774863-2746920e-094a-11e8-9eb9-e59a4180ca20.png">

**Comment by Jahhein** [comment]
Run a `type -aS yo` to find how its coming to that command. 

for example, my `git` command is aliased to package `hub` , symlinked into my path by my brew package manager, and I also have another `git` that macOS comes with that isn't updated.

```shell
type -aS git
git is an alias for hub
git is /usr/local/bin/git -> /usr/local/bin/../Cellar/git/2.16.1/bin/git
git is /usr/bin/git
```

From here, you can figure out where its coming from.

**Comment by fclaussen** [comment]
Hmm
Thank you for this command @Jahhein 
This is what came up

```
type -aS yo
yo is an alias for yarn outdated
yo is /usr/local/bin/yo -> /usr/local/bin/../lib/node_modules/yo/lib/cli.js
```

Two questions now.
1 - Why is that only the case on zsh and not on bash?
2 - How do I fix this?

**Comment by fclaussen** [comment]
Nevermind! I figured it out.
I added a yarn plugin to zsh that were adding a ton of aliases. As soon as I disabled it to test, it worked.

Thank you for pointing me in the right direction @Jahhein

**Comment by Jahhein** [comment]
@fclaussen no problem buddy! Glad you solved it. 

But to answer your questions regardless: the reason for it being different based on bash or zsh is because the configuration files which contain aliases, functions, variables, etc, are different. 

There is a command that I cannot remember that will actually display where an alias, var, or function is coming from in your environment. However I cannot manage to find it and I’m not at a computer to play in a shell to figure it out. 

I recommend looking at the `whence` command. `type`, `where` , `which` and more commands are based on the `whence` command.
