### ISSUE TITLE
vi-mode plugin breaks history completion bindings

### ISSUE THREAD

**Issue by ovisan** [robbyrussell/oh-my-zsh#6626]
vi-mode plugin breaks arrow-up and arrow-down history-beginning-search-forward and history-beginning-search-backward bindings

**Comment by okapia** [comment]
This is by design. In vi mode, history is bound to j/k/cursors in command-mode. You can manually bind the history bindings back in the viins keymap. Or enable vi mode some other way such as simply binding escape in the emacs keymap to vi-cmd-mode. That way you can keep all the usual emacs mode bindings but still use vi command mode.

**Comment by ovisan** [comment]
Ok, thanks for the solution.

**Comment by github-young** [comment]
You can refer to this reply: <https://github.com/ohmyzsh/ohmyzsh/issues/1720#issuecomment-286366959>
