### ISSUE TITLE
All settings disappear when I edit .zshrc

### ISSUE THREAD

**Issue by yadoyadoya** [robbyrussell/oh-my-zsh#6628]
I'm a beginner so take my issue with a grain of salt.

I run my zsh from both Bash on Ubuntu on Windows and Hyper (Windows).
No issues if I install Oh-my-zsh, but as soon as I edit .zshrc, for example to uncomment a default alias, then all settings are gone. No more colours, not a single alias, including the default ones such as ll.

All it takes for me is to uncomment one line.
![zsh 1](https://user-images.githubusercontent.com/20118433/36283774-79e66dc8-12e0-11e8-8d9e-09f21055ba30.png)
![zsh 2](https://user-images.githubusercontent.com/20118433/36283775-7a19b890-12e0-11e8-9c1c-f3e3b5ba3a02.PNG)

**Comment by mcornella** [comment]
What's your zshrc file before and after it doesn't work anymore?

**Comment by lukefiji** [comment]
I think it may be a permissions issue I tried editing it with VS Code and I had the same issue. If you edit your `.zshrc` file using `vim` you won't have that issue anymore.

**Comment by mcornella** [comment]
I'm not sure you should edit files inside the WSL environment with an external program. The way I do it is I `mv` the file to a folder outside WSL (like `/mnt/c` or `/c`), edit, then `mv` back in. [Here's a pretty good explanation why doing that has risks](https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/).

I'm going to assume this issue is resolved since it's old-ish and has no response. But yeah, permissions problem might be the best guess.
