### ISSUE TITLE
git_commits_ahead echoes an error message if no upstream has been set for the current branch

### ISSUE THREAD

**Issue by wilderjds** [robbyrussell/oh-my-zsh#6656]
I find myself using git_commits_ahead n my prompt; when creating a local branch without upstream the prompt is constantly filled with errors such as

fatal: no upstream configured for branch 'branch-without-upstream'

git-version 2.16.1

**Comment by basus** [comment]
I've been having the same error. The fix is simple. [Line 80 of lib/git.zsh](https://github.com/robbyrussell/oh-my-zsh/blob/d22189848e3549800486d009aeb7d6a692fd55be/lib/git.zsh#L80) has the following:

```
    local commits="$(git rev-list --count @{upstream}..HEAD)"
```

This needs to be changed to 

```
    local commits="$(git rev-list --count @{upstream}..HEAD 2>/dev/null)"
```

So that the fatal error message on `stderr` is directed away. I'm happy to submit this as a PR if that would help.

**Comment by wilderjds** [comment]
Thanks a lot! I already submitted a PR 10 days ago and it is waiting for approval

It's pretty much what you do + some minor things
