### ISSUE TITLE
Font missed?

### ISSUE THREAD

**Issue by srjefers** [robbyrussell/oh-my-zsh#6715]
Hey, I intalled ZSH on OpenSuse Leap 42.3 and now when I installed the default theme of this I see that error, now I'm on i3wm, I tried to move some new fonts to .fonts path but nothing :cry:
Any Idea?, this is in URXVT 
![screenshot_2018-04-08_09-16-17](https://user-images.githubusercontent.com/26731428/38469161-8966f146-3b0d-11e8-82d0-b6e2a8221e0c.png)

**Comment by mcornella** [comment]
You have to set up a suitable font in `.Xdefaults`, as [the Powerline documentation specifies](http://powerline.readthedocs.io/en/master/tips-and-tricks.html#rxvt-unicode). Otherwise, you can just set `TERM` to a working value no?

**Comment by Netoperz** [comment]
I think it is "our" problem, because pushing "default" theme in configuration that does not work on 99% of the shells is not correct. This does not work on ubuntu on wsl, and standard ubuntu, also does not work on 36 machines i manage.  

I think if the owner of the theme "likes it as it is" it should be published as private or optional repo, but on the main "oh my zsh" theme page there is no info about the fonts and how to set them, and if you my friends want more users , please use default theme that is 100% compatible, i think it is better to use some font that is always everywhere in setp that is installed by default. but this is just my "dummy" opinion. 

btw, good work , and thank you for your time , thumbs up.
