### ISSUE TITLE
subl: permission denied

### ISSUE THREAD

**Issue by patrickng** [robbyrussell/oh-my-zsh#6757]
After updating oh-my-zsh tonight, when I try to open sublime with the stt command from the plugin, I get an error "subl: permission denied".

I tracked down the change to this commit: https://github.com/robbyrussell/oh-my-zsh/commit/cea941ce42b5d550489367608dd1ac4401151c97 where if I revert it, it works fine.

I'm on MacOS High Sierra (10.13.4)

**Comment by ssaunier** [comment]
Same here for all our students.

**Comment by greenchapter** [comment]
I have also the problem on macOS since I updated oh-my-zsh.

@ssaunier in the end that is no fix more a workaround because the next update cycle will pull latest version of **sublime.plugin.zsh** an then we have this problem  

I also see that permission issue on this commit https://github.com/robbyrussell/oh-my-zsh/commit/cea941ce42b5d550489367608dd1ac4401151c97 from @mcornella. He replaced `/dev/null 2>&1` with an variable called `_sublime_path` but I don't exactly know why he is doing that.

**Comment by ssaunier** [comment]
Thanks @mcornella for fixing it quickly! For those who used the workaround, you can revert to a normal status with:

```bash
cd ~/.oh-my-zsh
git checkout master
git pull origin master
cd
# Restart terminal
```

Thanks!

**Comment by mcornella** [comment]
Update and all should be fine again. Sorry for the mixup!
