### ISSUE TITLE
can't work fine with `TERM=screen-256color`

### ISSUE THREAD

**Issue by fcying** [robbyrussell/oh-my-zsh#6806]
If I set `TERM=screen-256color` in `.zshrc`, when I print cmd, it will display error, use `TERM=term-256color` work find.

![image](https://user-images.githubusercontent.com/106934/39737428-927254bc-52b7-11e8-943a-af50e6074d86.png)

os:ubuntu 16.04
gnome terminal

**Comment by mcornella** [comment]
It looks like this is an issue with the `title` function: https://github.com/robbyrussell/oh-my-zsh/blob/482587ccc16da0a399f3f91ef4d29def8d22a441/lib/termsupport.zsh#L24-L26

~~It's weird though, the sequence printed should be invisible and only be recognized by the terminal emulator. This must be a bug in gnome-terminal.~~ This is expected behavior: if you're not running screen or tmux that sequence is not swallowed by the underlying terminal, so it makes sense that it shows up in your prompt.
