### ISSUE TITLE
Logo Design Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [robbyrussell/oh-my-zsh#6858]
Greetings Sir @robbyrussell , I am a graphic designer and i noticed that the current logo needs some modifications(In my opinion) for it to be more good looking. I want to contribute to this nice project by proposing a logo design which i will be gladly be giving as a gift for free. If you will permit me I will start to make it asap. 

Thanks and best regards!
-Tobaloidee

**Comment by Tobaloidee** [comment]
Here Sir, i made the current logo monomal and proportion

![omz-01](https://user-images.githubusercontent.com/36028424/40582470-7eeb76b0-61aa-11e8-8000-2d8b6062a1bb.png)

**Comment by bittner** [comment]
I believe, this redesign has some issues. Mainly, it's that it suggests this project has something to do with dollars (aka money). And the person in focus now appears to be male, male only.

While the [current logo](https://github.com/robbyrussell/oh-my-zsh/blob/master/README.md) is difficult to use as a smallish icon it still provides

1. a **clearer direction** to what this project is about (terminal prompt, blinking cursor), and
1. a **more inclusive** message (lots of people, roughly a third even women).

Is this okay as a feedback? I mean to be constructive. _Try again, please!_

**Comment by Tobaloidee** [comment]
Okay Sir, I'll try a new concept and post here when im done. Thanks for the feedback.

**Comment by robbyrussell** [comment]
@Tobaloidee thanks so much for reaching out about this! 

(this isn't an opinion on your take at a new logo -- but a formal response on where I stand on a visual rebrand right now)

With regard to logo adjustments, I'm not currently entertaining this idea as if we go down that route, it would be a paid project so that I can properly own the rights for merchandising. Becca (the designer) and I spent a lot of hours to get this done back in 2013. ..and I get that design is really subjective. :-)

Here is the original designer, who did a great job on that project (and was amazing at working/putting up with me as I can be quite fussy about the details).

![Becca](https://cdn-images-1.medium.com/max/2000/1*k9eGe-BEObD_Gp40MvaN-A.jpeg)

Like some of the comments have said, there was a lot of intention behind the usage of people in the image. While it is oh MY zsh... it is built for and by a _community_ of people vs a sole individual. 

My critics of the current logo design at this point:

* While it's B&W -- I with the silhouettes weren't all white.
* Need a variation for square/thumbnails (as others said above)
* Wish it could convey a sense of delightfulness -- I feel that it's conveying "casual confidence", which I love... but want it to invoke a touch of positive emotion. (could be seen that the confidence of the people standing helps a bit... but I want it to feel a little less serious... a little more delightful/carefree)

Branding is fun. ;-)

With that -- I am curious about exploring a new t-shirt design to go on sale in Sept/Oct. I'll be away for the next month but if you were interested in discussing collaboration on that project, I'd be open to discussing it.

Thanks again, everyone!

**Comment by Tobaloidee** [comment]
Hi Sir, I fully understand :) and i can still be of help regarding shirt design.  Again, thanks for taking time in giving your thoughts and My best regards to the project! - Tobaloidee
