### ISSUE TITLE
Oh-my-zsh can't load theme properly

### ISSUE THREAD

**Issue by Ninzero** [robbyrussell/oh-my-zsh#6877]
My oh-my-zsh can't load themes correctly. It looks like this, it should be theme "agnoster"
![2018-05-30 18 03 36](https://user-images.githubusercontent.com/20299935/40735731-d70dabc0-6433-11e8-98eb-29954ed57e38.png)

**Comment by ckartchner** [comment]
Did you install the powerline fonts?

[Agnoster](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes#agnoster) requires those fonts to be able to display correctly. More details in the provided link.

When I first tried that theme I had the same issue. 
In my Debian based environment, the problem was solved by running "apt-get install fonts-powerline". You will need to restart your terminal for it to take effect.

**Comment by Ninzero** [comment]
I believe I have installed Powerline Fonts @ckartchner

**Comment by ckartchner** [comment]
Those question marks appear when the correct font can't be located. 
What evidence can you provide that the correct fonts are installed? 
For example, if you used apt, you can check in /var/log/apt/history.log. 
What OS are you using?

**Comment by mcornella** [comment]
This is a font issue. Make sure you have a Powerline font set up and are using it in your terminal app. If you can't figure it out, searching for `powerline font <terminal-you're-using>` will get you many links.
