### ISSUE TITLE
When using hashcat, some command-line arguments are matched by zsh errors!

### ISSUE THREAD

**Issue by Droid-MAX** [robbyrussell/oh-my-zsh#6889]
When using hashcat, some command-line arguments are matched by zsh errors, such as ./hashcat -m 5600 -a 3 example.hash ?l?l?l?l?d?d?d?d, where "l?l?l?l?d?d?d?d" This parameter causes a zsh match error.

**Comment by mcornella** [comment]
You need to quote arguments that use characters like question mark `?` and asterisks `*` because zsh interprets them as globbing characters and tries to match it against local files. So if you do `./hashcat -m 5600 -a 3 example.hash "l?l?l?l?d?d?d?d"` it will ignore them. You can learn more if you look at `zsh file expansion` or `zsh globbing characters`.
