### ISSUE TITLE
svn prompt error

### ISSUE THREAD

**Issue by smarteng** [robbyrussell/oh-my-zsh#6891]
error msg :
_svn:33: bad set of key/value pairs for associative array

svn --version
svn, version 1.10.0 (r1827917)
   compiled Apr 22 2018, 07:20:07 on x86_64-apple-darwin17.5.0

mac os 
![image](https://user-images.githubusercontent.com/663786/40971583-b23c631a-68f0-11e8-873d-79a29833c4ab.png)

change svn version to 1.9.7 , is ok
![image](https://user-images.githubusercontent.com/663786/40975102-668a74a0-68fc-11e8-878e-d0bb6d4363a5.png)

**Comment by mcornella** [comment]
Does this happen when completing a particular svn command? I need more information.

**Comment by smarteng** [comment]
Does this happen when completing a particular svn command?

-----------------
no, I type  svn  c  and then  type  tab key , error happed 

![image](https://user-images.githubusercontent.com/663786/41329276-38297ada-6eff-11e8-897b-a4f164242b1e.png)

![image](https://user-images.githubusercontent.com/663786/41329285-525eb956-6eff-11e8-9dfc-3c31ddb66fba.png)

the same question 
https://github.com/zsh-users/zsh-completions/issues/571

**Comment by smarteng** [comment]
please fix it

**Comment by malumoe** [comment]
After the upgrade to MacOS Mojave, I encounter the same error. Any suggestions?

**Comment by mcornella** [comment]
Try downloading the latest version of the svn completion: https://raw.githubusercontent.com/zsh-users/zsh/master/Completion/Unix/Command/_subversion

Then run `source path/of/file`
Then try completing again

If it works, you can put that in your zshrc file, but you'll know that in a zsh version higher than 5.6.2 you'll no longer need it.

Closing because this is a zsh issue, not OMZ.

**Comment by maihacke** [comment]
See suggested fix does not work for me. The error message is gone, but tab completion does not show anything.

**Comment by maihacke** [comment]
Just for the records. You have to source the fixed filed in a new shell.

**Comment by chenhuangkun** [comment]
_svn:33: bad set of key/value pairs for associative array
I have the same problem. Can anyone come up with a solution? Thank you

**Comment by maihacke** [comment]
It's written [above](#issuecomment-424437824). Download latest for svn:

curl https://raw.githubusercontent.com/zsh-users/zsh/master/Completion/Unix/Command/_subversion > zsh_svn_fix

source this file in your .zshrc

**Comment by yongjin-shin** [comment]
Seems the following solution works for me. (You might need to use google translator..)

https://qiita.com/kaityo256/items/4a9310b7ef8b6e812af3#%E5%BF%9C%E6%80%A5%E5%87%A6%E7%BD%AE

**Comment by michele-segata** [comment]
Sorry for commenting on this closed issue, but I've finally found the solution to the problem for me. The problem was that I was using the `zsh` that comes pre-installed with MacOS, which is `zsh 5.3 (x86_64-apple-darwin17.0)`. I have installed a new version using MacPorts (`sudo port install zsh`), which installed me `zsh 5.7.1 (x86_64-apple-darwin17.7.0)`.
After installing it you have to change your default shell with `chsh`, but first you need to edit `/etc/shells`.
Run `sudo vim /etc/shells` and add `/opt/local/bin/zsh` (or whatever the path to the new `zsh` is).
Then run `chsh -s /opt/local/bin/zsh <your username>` to change your default shell. Now open a new terminal and test `svn` command completion.
