### ISSUE TITLE
[first time installing] after installing most of the command are not working!

### ISSUE THREAD

**Issue by SerkanSipahi** [robbyrussell/oh-my-zsh#6921]
This is my first time usage of zsh. Its works well but most of my commands which are located under `/Users/foo/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin` are not working! 
Despite commenting out `export PATH=$HOME/bin:/usr/local/bin:$PATH` in the `.zshrc` and restarting the terminal (iterm2) it could not found e.g. following commands `nvm`, `ng`, `lerna`, ..., ...,

Unfortunately i could not find anything on the internet that could solve my problem. The proposal to enter every entry in the zshrc or something like that is not a good solution.

What happening wrong?

**Comment by mcornella** [comment]
This could be for many reasons. If OMZ is not finding them, that could be because `export PATH=...` has to be before sourcing OMZ (preferably at the top of you zshrc file).

If it is you that can't find them (you get a `command not found` error), it might be because you're missing an entry in you PATH definition. If using bash you can find them, look at what value `$PATH` has and compare it with your zsh one to find the missing entries.

**Comment by mcornella** [comment]
Try to run `zsh -f` or `bash` and see what `$PATH` you have, then put that value at the top of your zshrc file.
