### ISSUE TITLE
Can not complete docker commands after alias with grc

### ISSUE THREAD

**Issue by j16180339887** [robbyrussell/oh-my-zsh#6954]
Can not get docker completion work after alias with [grc](https://github.com/garabik/grc).

```sh
$ alias docker='grc -es --colour=auto /usr/bin/docker'
$ docker <tab> # Not working anymore
```

Any ideas? thanks.

**Comment by mcornella** [comment]
You should specify that you want to use docker completions with the docker alias with `compdef _docker docker`. But you have to also run `setopt completealiases` to disable zsh's behavior of looking at the alias definition to know which completion function to run (in your case, it would try to find completions for the grc command).

Enabling this option will mess up the rest of aliases that don't have an explicit completion defined, so here's a better option: use a function instead of an alias, like so:

```zsh
function docker { grc -es --colour=auto /usr/bin/docker "$@" }
compdef _docker docker
```
