### ISSUE TITLE
shell bugged with 'ghost' characters

### ISSUE THREAD

**Issue by garyAtSegment** [robbyrussell/oh-my-zsh#6985]
Original issue filed here: https://stackoverflow.com/questions/51291531/zsh-command-prompt-has-ghost-characters-when-scrolling-through-history

I'm not sure if this is a bad config in my environment (Although I have disabled all the evals in my .zshrc)

When I first install oh-my-zsh everything works fine, after running for awhile I end up with the situation where my command prompt ends up with a bugged prompt:

Assume that the first command is in history and I up-arrow to it.

    ➜  ~ some-command some-fairly-long-command --with-a-bunch --of-switches

When I down-arrow I expect to see 

    ➜  ~ 

But what I do see:

    ➜  ~ so

If I try to type there:

    ➜  ~ so[new text is inserted after those two characters]

The additional characters are ignored by the shell and I can't backspace over them.  If I hit enter their ignored etc, but it's not just the first two characters, my whole prompt is bugged at that point.  If I make changes to a history command and try to re-execute what I see on the screen isn't what's executed (IE there's some overwriting going on in the buffer that's not apparent).

I'm not sure if this is zsh specific as I've seen this reported: https://unix.stackexchange.com/questions/28827/why-is-my-bash-prompt-getting-bugged-when-i-browse-the-history with bash.

I've scraped out most of the weird stuff in my .zshrc (autocomplete etc) but I still see this.  I have recently re-installed oh-my-zsh and the issue went away for awhile but recently re-occurred.

**Comment by garyAtSegment** [comment]
I have noted that in .zsh_history I can seem to correlate some history  entries that seem to be bugged with a `\` at the end AND a new line:

Below sample includes a line number as first character to show new lines etc.  

```
  6 : 1531328281:0;some long command\
  7 
  8 : 1531328293:0;some other long command\
  9
```

**Comment by garyAtSegment** [comment]
and with some more investigation it now seems to be related to cutting and pasting into the terminal.  

I'm on ubuntu 18.04, something is going on.  I'd like to leave these issues in place so others can report if they see similiar behaviour.

**Comment by xayden** [comment]
I've got the same issue on KDE Konsole

**Comment by egoisticalgoat** [comment]
I've been having trouble with this recently too. It's happening to me regardless of theme (tested spaceship, agnoster, and af-magic) or terminal (tested with gnome-terminal and DomTerm). I couldn't reproduce it without oh-my-zsh.
For me, it happens every time the text in the prompt gets larger than the terminals width (be it by typing, or by pasting, or by scrolling through history.). 
Not entirely sure if it is the same bug or even related, but when my command gets long enough that the prompt has to jump into the next row, the first row becomes completely invisible (and also triggers the bug, though this time with invisible characters). And backspacing till i'm in the first row again doesn't help either.

**Comment by egoisticalgoat** [comment]
I've tried around a bunch, and found a workaround/possible reason for the problem.
I've added the line `export LC_ALL=en_US.UTF-8` to my .zshrc, because i had some encoding problems in another application. Suddenly, the ghost characters stopped happening. I've tried around a bit more, and found that in my case the exact LC_* variable that was causing the problem was LC_CTYPE being set to C (but i suppose it probably happens with all non-UTF8 locales) 

@ the previous commentors: Check `locale` on your terminal and see what your LC_ALL and your LC_CTYPE variables are set to.

**Comment by mcornella** [comment]
So, is this issue resolved?

**Comment by shobhitagarwal1612** [comment]
> I've tried around a bunch, and found a workaround/possible reason for the problem.
I've added the line export LC_ALL=en_US.UTF-8 to my .zshrc, because i had some encoding problems in another application. Suddenly, the ghost characters stopped happening. I've tried around a bit more, and found that in my case the exact LC_* variable that was causing the problem was LC_CTYPE being set to C (but i suppose it probably happens with all non-UTF8 locales)
@ the previous commentors: Check locale on your terminal and see what your LC_ALL and your LC_CTYPE variables are set to.

Thank you so much @egoisticalgoat. Your solution worked like a charm!

**Comment by ssbarnea** [comment]
I got a similar problem on CentOS 7 with defaulg Gnome Terminal and while locale was initiall reporting `LC_ALL=`, adding it to match the other ones did not solve the problem.
<img width="307" alt="181127-royal - royal tsx" src="https://user-images.githubusercontent.com/102495/49105467-7e136e00-f278-11e8-8a75-4de59cc29e1a.png">

**Comment by egoisticalgoat** [comment]
@ssbarnea Those seem less like the above mentioned ghost characters, and more like control characters. I've found [this thread](https://www.reddit.com/r/emacs/comments/5p3njk/help_terminal_zsh_control_characters_in_prompt/) talking about what looks like the exact characters in your screenshot. 
Maybe check your $PS1 / $PROMPT to see if those characters are in there, and if yes, then maybe try to exclude dotfiles to find out where they're coming from?

**Comment by RobbieKatzZappi** [comment]
[egoisticalgoat](/egoisticalgoat) I love you so so much

**Comment by samuela** [comment]
I'm having the same issue on Ubuntu 20.04 with zsh 5.8. I've tried the `LC_ALL` trick to no avail. Here's my home-manager config:
```nix
  programs.zsh = {
    enable = true;
    enableAutosuggestions = true;
    history = {...};
    shellAliases = {...};
    initExtra = ''
      setopt ignore_eof
      export LC_ALL=en_US.UTF-8
    '';
  };
  programs.starship.enable = true;
```
which gives me 
```
❯ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```
but if I do `> lo<TAB>`, and then backspace all the way I still get `> lo` and can't remove it :(

**Comment by SunflowerFuchs** [comment]
@samuela I believe that's an issue with the prompt characters in your constellation, unrelated to oh-my-zsh. I've reproduced your issue, and after changing the default prompt character for starship to something else, e.g. a colon, the issue doesn't occur anymore.

The part i changed, just for reference:
```nix
programs.starship = {
  enable = true;
  settings = {
    character.symbol = ":";
  };
};
```

**Comment by samuela** [comment]
Thanks so much @SunflowerFuchs ! Poking around with my locale didn't work, but setting `character.symbol` seems to do the trick!

**Comment by altosaar** [comment]
Thank you @SunflowerFuchs ! 

On WSL2 in Windows 10 with starship and zsh I had the same issue. 

Changing the locale and the character symbol to have no spaces fixed it for me. Now autocomplete in starship works without ghost characters. 

Relevant part of `starship.toml`:

```
[character]
error_symbol = "[✖](bold red)"
```

Changed to the above from `error_symbol = "[✖](bold red) "` (with trailing space)

**Comment by Soumns777** [comment]
I checked my locale configuration :LC_ALL=" en_us.UTF-8 ", LC_CTYPE=" en_us.UTF-8 ", but now if I type git commit it will say git ommit, and the c is gone, and then when I copy ⚡️, There will be a < FE0F > in the future, I don't know what this belongs to, my computer version is macOS Monterey12.5.1, the terminal I use is OHMYZSH

**Comment by Ddfulton** [comment]
On MacOS with iTerm2 tried to use the union jack as my prompt.
HAVE placed `export LC_ALL=en_US.UTF-8` into my `~/.zshrc` and confirmed with
```
🇬🇧  locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```
But when I type `vim <TAB>` the `vim` becomes `vimvim`:
```
🇬🇧  vimvim
vim       vimdiff   vimtutor
```

**Comment by mcornella** [comment]
Are those locales installed? To make sure what locales are available, first run `locale -a`, then you can use one of those that end in `UTF-8` or `utf8`.

**Comment by fire17** [comment]
For anyone still dealing with this issue,
I've just managed to **fix my problem**, that had to do with bad color formatting (not making them 0 width)
checkout:
https://stackoverflow.com/questions/19305291/remnant-characters-when-tab-completing-with-zsh/76792907#76792907
I recommend Matthew's answer
(I've also added my own solution to show how you can replicate the solution, for your existing prompt)
https://stackoverflow.com/a/76792907/3196006
![image](https://github.com/ohmyzsh/ohmyzsh/assets/9356048/9e9a03b6-b2e5-4e9b-9ee9-62f9e32c3bee)

Good Luck and All the best !

**Comment by EmandM** [comment]
The above answer led me to the fix for my issue, but was a bit unclear to follow. I'm adding a clearer answer here.

To simplify, both Bash and Zsh need to know the width of the command prompt to render things correctly. Anything in the prompt that doesn't result in text being printed needs to be escaped so bash/zsh knows not to count this piece as part of the prompt text length. This applies for any [`$(tput ... )`](https://www.gnu.org/software/termutils/manual/termutils-2.0/html_chapter/tput_1.html) commands or any [zsh visual modifiers](https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html#Visual-effects).

In Bash, these escape characters are `\[...\]` (e.g. `\[$(tput sgr0)\]` rather than `$(tput sgr0)` directly) [[More Info](https://mywiki.wooledge.org/BashFAQ/053)]

In Zsh, the escape characters are `%{...%}`. [[More Info](https://unix.stackexchange.com/a/90876/319716)]

So, if setting `LC_ALL` hasn't fixed the ghost character issues, check wherever you've customised your prompt and ensure any command strings are properly escaped. Especially if you've recently swapped from bash to zsh.

**Comment by arturtamborski** [comment]
I know this is an old and closed issue, but just for reference (uh, some traveller from the future?) here's what do do if neither locale nor EmandM's commend helped fix your problem.

If you happen to use `awesomepanda` theme, then you may have stumbled upon this particular issue: https://github.com/ohmyzsh/ohmyzsh/issues/12645 and if such, here's the fix:

```
omz update
```

I had this case, it took me way too much frustration to figure out why shell letters randomly got eaten after resizing the terminal. Oh well. It's nice that it's fixed.
