### ISSUE TITLE
Link themes to individual terminal user profiles.

### ISSUE THREAD

**Issue by the1byo** [robbyrussell/oh-my-zsh#7022]
### Link (and hence automatically load) a theme to the terminal per individual *user-profile* basis. 

So when I switch between profiles in my zsh terminal, the theme associated with the same must load automatically too!

A huge fan of the work and the project. Love this community! Thanks in advance :)

Cheers!

**Comment by mcornella** [comment]
I don't understand, if you switch to another user you'll have to load an entirely diferent OMZ directory. How do you switch users?

**Comment by the1byo** [comment]
Just to make myself clear, using the term *user* may be misleading to mean *user* at a system level. What I meant is for a given *user*, in a terminal session you have the option of creating and switching between *different **profiles**.* Although most of the customization options are available here, I was wondering if I could link even the shell themes on a *per **profile*** basis. The main idea is, when I am doing certain (for example: dev) projects, I prefer the clean & minimal "robbyrussell" (default) theme look of the environment. But when I am doing certain other projects (for example: server end stuff) I prefer all the bells and whistles and with the *Powerline* plugin, tmux and everything else. Is there a way to minimize the effort by saving settings (shell theme) to "profiles" and simply switching between profiles?

**Comment by mcornella** [comment]
I guess it's not that hard if all you want to do when switching profiles is change the theme. You could have a custom function that sources the right theme according to what profile you pass it. Example:
```
function switch-profile {
  local -A profiles
  profiles=(
    default "$ZSH/themes/robbyrussell.zsh-theme"
    server "$ZSH/themes/agnoster.zsh-theme"
    ...
  )
  source $profiles[$1]
}
```
and doing `switch-profile default` would change the theme (you could also create your aliases to change faster). Another option would be to put these settings in files instead of within the function.

If you also wanted to load plugins you would have to change the $plugins array and reload OMZ. I leave that to you.

**Comment by gusbemacbe** [comment]
@mcornella 

And switching `.zshrc` files on Linux? For example; `.zshrc`, `tilix.zshrc`, `vscode.zshrc`.
