### ISSUE TITLE
Scrolling to page doesn't work on iterm2

### ISSUE THREAD

**Issue by MZIchenjl** [robbyrussell/oh-my-zsh#7025]
Scrolling to page doesn't work when using less on iterm2.
After reverting the merge #6611 , it works again.

Some helpful testings:

```shell
env_default LESS '-R' # work
env_default LESS '-FR' # work
env_default LESS '-RX' # doesn't work
env_default LESS '-FRX' # doesn't work

```

**Comment by Chris911** [comment]
I have the same issue. Adding `-X` breaks scrolling in the iTerm2 and Terminal app (macOS).

**Comment by lukasbalaz** [comment]
I've got the same issue on Ubuntu.

**Comment by roberthawdon** [comment]
I added

```
unset LESS
env_default LESS '-R'
```

to my .zshrc to revert this as it was breaking an application that calls less if the file fit onto the screen.

**Comment by SvSchmidt** [comment]
I can confirm the issue with Cygwin and oh-my-zsh, scrolling paged output especially with `git` commands does not work anymore.

`LESS=-R git log # works`
`LESS=-FR git log # works`
`LESS=-RX git log # nope`
`LESS=-FRX git log # nope`

The fix from @roberthawdon works for me, however.

**Comment by FabianWolff** [comment]
#6611 also breaks ```less``` mouse wheel scrolling in [Terminator](https://launchpad.net/terminator) and [Gnome Terminal](https://wiki.gnome.org/Apps/Terminal). To be honest, I think that merging #6611 was a mistake; I think it does a lot of harm in exchange for very little benefit, and it is probably going to upset a lot of users (myself included).

Of course I can just reset LESS in my ```.zshrc```, but it took me a while to figure out where the sudden change of ```less``` behavior even came from (because I did not expect oh-my-zsh to make such a "frivolous" change...).

**Comment by mcornella** [comment]
> I did not expect oh-my-zsh to make such a "frivolous" change...

I didn't expect there to be any downsides to pushing that change, since (a) there wasn't any negative feedback in months, and (b) I've been using that setting for years and I never even thought of this use case.

That said, it is definitely the sensible decision to revert it back given the outcome. I hope this wasn't a big setback. Cheers!

**Comment by FabianWolff** [comment]
I'm sorry if my reply sounded a bit rude; that wasn't my intention. It was just a little annoying the other day, finding out that `man`, `git log`, `less` itself etc. suddenly became so cumbersome to use...

So, no worries, and thanks for reverting the change!

**Comment by Chris911** [comment]
I'm having the same issue again. Anyone else?

**Comment by mcornella** [comment]
There were no changes, make sure you didn't inadvertently redefine `$LESS` somewhere in your zshrc or dependencies.

**Comment by Chris911** [comment]
I checked and `$LESS` is set to -FR which is the right setting. I think this started happening when I installed the latest macOS patch (not new version just a partial update).

**Comment by elmarco** [comment]
Why was -F removed? Could -F be added back without -X?

**Comment by mcornella** [comment]
@elmarco then less basically does nothing: quits and deletes the contents of the screen. Try it yourself: `LESS=-FR less <file>`
