### ISSUE TITLE
Recent history not being loaded on opening new shell

### ISSUE THREAD

**Issue by zlex7** [robbyrussell/oh-my-zsh#7032]
I am using oh-my-zsh with the default history configuration. After typing a few commands, and then opening a new shell, I expected to be able to search commands that I had executed just 10-15 seconds before. However, none of those commands were searchable through ctrl-r and using the up arrow to navigate past commands gives the same results. For some reason, I can search a few commands that I executed yesterday however. I recently noticed this problem, so I'm not 100% sure if I was experiencing this before. I'm also not sure how one would replicate this unless this is actually some default behavior. Any ideas? 

I'm on MacOS Sierra, using iterm2.

**Comment by mcornella** [comment]
Please post the output of `setopt`.

**Comment by julienfortin** [comment]
Hello @mcornella 

I have the same issue... I recently upgrade to MacOS mojave and did a clean install. Since them my zsh history is completely broken, this is super frustrating.

I use 4 to 10 shells window at the same time... It seems like the history of some of the windows is never saved, and only the one for one or two window is saved. It's quite frustrating, I rely so much on the history and history completion... This is affecting my workflow significantly.

```
[14:21:10] julien:~ $ setopt
alwaystoend
autocd
autopushd
completeinword
extendedhistory
noflowcontrol
histexpiredupsfirst
histignoredups
histignorespace
histverify
incappendhistory
interactive
interactivecomments
login
longlistjobs
monitor
promptsubst
pushdignoredups
pushdminus
sharehistory
shinstdin
zle
```

Here is an extract of my .zshrc

```
[14:21:11] julien:~ $ cat ~/.zshrc
...
...
plugins=(
    git
    colored-man-pages
)

source $ZSH/oh-my-zsh.sh

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

HISTFILE=~/.zsh_history
HISTSIZE=100000
SAVEHIST=10000
setopt SHARE_HISTORY
[14:21:11] julien:~ $
```

Thanks for your help :)

**Comment by mcornella** [comment]
Is it possible the upgrade changed the zsh version? Maybe there's a bug there?

**Comment by Delayless** [comment]
I encountered the same problem. did you solve it?
