### ISSUE TITLE
pygrep alias in Python plugin can be more useful

### ISSUE THREAD

**Issue by DopustimVladimir** [robbyrussell/oh-my-zsh#7053]
...by adding `-r` flag:
```
# Grep among .py files
alias pygrep='grep -r --include="*.py"''
```

**Comment by mcornella** [comment]
Can you submit a PR?

**Comment by DopustimVladimir** [comment]
@mcornella, sorry, i did mistake. You can also type `pygrep -r 'foobar' foo/bar/` Closed

**Comment by maciejmotyka** [comment]
I think the proposed change makes perfect sense. Or I am just completely misunderstanding how pygrep should be used.

* `pygrep "findme" file.py` doesn't do anything more than `grep "findme" file.py`
* `pygrep "findme"` is useless, because it never finishes
* `pygrep "findme" .` throws an error `.: Is a directory`

Therefore `pygrep "findme"` could very well do the job of `pygrep -r "findme"`
```
$ touch file1.py file2.py
$ echo "findme" > file1.py
$ echo "findme2" > file1.py
$ pygrep -r "findme"
file2.py:findme2
file1.py:findme
```

I've created a PR #8217
