### ISSUE TITLE
Dotenv plugin: interpreting variables from `.env` as shell variables

### ISSUE THREAD

**Issue by rikikonikoff** [robbyrussell/oh-my-zsh#7114]
Until a recent update, I never had any problems with this plugin. On Thursday I updated `oh-my-zsh` and started having huge problems when running `rspec` and `rake spec`. After a lot of research, I figured out that the dotenv plugin was causing my `.env` variables to *universally override* the variables in my `.env.test`. Apparently this happens when you define variables as shell environment variables, but I hadn't done that, and this was not an issue until recently.

I was able to fix the variable override issue by removing this plugin from my zsh config.

**Comment by rikikonikoff** [comment]
@mcornella that sounds great, but I just disabled the plugin for now. I'd like to see this be automatically part of the plugin, or for there to be better documentation about this, since this automatic exporting is new functionality.

**Comment by mcornella** [comment]
That's the idea, but I'd like to know if that solves it before I push the changes.

**Comment by mcornella** [comment]
Can you try running that and tell me if you get the right behavior? https://github.com/robbyrussell/oh-my-zsh/issues/7114#issuecomment-419025038

**Comment by rikikonikoff** [comment]
I just tried it out and it does not fix the problem. Perhaps I put it in the wrong order in my zshrc file? Where should it go - before or after defining the plugins to use?

**Comment by mcornella** [comment]
It should go right at the end of the file. But it shouldn't matter if you have disabled the dotenv plugin...

**Comment by rikikonikoff** [comment]
I re-enabled the plugin and added the code you wrote after all the plugin stuff, and it forced the `.env` variables into shell variables again. So, I disabled the plugin again because this was not the behavior I wanted.

**Comment by mcornella** [comment]
The code I wrote is how the plugin was before the changes, it should work as you want. The changes we made were to automatically `export` the variables, which might not be what is expected.

To revert back to the previous behavior of not exporting I should first verify that that is truly the problem here, so if you're willing to help me:
- add `set +a` at the beginning of your `.env` file (to disable the `allexport` setting)
- restart the shell
- navigate back to the directory containing the `.env` file,

then try to reproduce your problem again.
