### ISSUE TITLE
env_default:2: bad assignment

### ISSUE THREAD

**Issue by HollowKnight** [robbyrussell/oh-my-zsh#7117]
Default fresh install got error env_default:2: bad assignment have to press q to return to the shell.

**Comment by mcornella** [comment]
I can't reproduce your issue, please run the following to enable debug mode and post the generated file as a private gist:
```
zsh -xvic exit &> omz-debug.log
```

**Comment by HollowKnight** [comment]
Here you go
https://paste.pound-python.org/show/NQSyoIA6ZpKtOxBVipkT/

**Comment by mcornella** [comment]
You have `LESS` defined as a global alias, with value `|& less -Rs`, in `/etc/zsh/zshrc`:
```
alias -g 'LESS'='|& less -Rs'
+/etc/zsh/zshrc:28> alias -g 'LESS=|& less -Rs'
```
That means that when OMZ runs `env_default LESS '-R'`, zsh runs
`env_default |& less -Rs -R`, which means that `env_default` runs without arguments and that's why you get the error.

That alias looks harmful from my point of view, but we can fix that just by quoting the arguments to env_default, so I'll do just that.

**Comment by HollowKnight** [comment]
Thank you,
That was my fault installed other zsh goodies without carefully looked at the scripts. I am still newbie to zsh. Thanks for lovely OMZ.

Regards,

On Mon, Sep 10, 2018, 12:50 AM Marc Cornellà <notifications@github.com<mailto:notifications@github.com>> wrote:

You have LESS defined as a global alias, with value |& less -Rs, in /etc/zsh/zshrc:

alias -g 'LESS'='|& less -Rs'
+/etc/zsh/zshrc:28> alias -g 'LESS=|& less -Rs'


That means that when OMZ runs env_default LESS '-R', zsh runs
env_default |& less -Rs -R, which means that env_default runs without arguments and that's why you get the error.

That alias looks harmful from my point of view, but we can fix that just by quoting the arguments to env_default, so I'll do just that.
