### ISSUE TITLE
mkdir fails with missing operand$ when creating directory called CA

### ISSUE THREAD

**Issue by johnmccabe** [robbyrussell/oh-my-zsh#7136]
Fresh install of `oh-my-zsh` on Ubuntu 16.04.5 LTS, added the following plugins to `~/.zshrc` (no other changes). (Also seeing this on OSX which has the osx plugin added to this list).

```
plugins=(
  git
  common-aliases
  docker
  dotenv
  tmuxinator
)
```

Attempt to create a directory called `CA`, results in the following:

```
➜  ~ mkdir CA
mkdir: missing operand$
Try 'mkdir --help' for more information.$
```

I can create dirs `C`, `CB` + others without issue.

Rerunning with debug enabled resulted in the following output.

```
^[[?1h^[=^[[?1l^[>mkdir CA
+omz_termsupport_preexec:1> emulate -L zsh
+omz_termsupport_preexec:2> setopt extended_glob
+omz_termsupport_preexec:4> [[ '' == true ]]
+omz_termsupport_preexec:9> local CMD=mkdir
+omz_termsupport_preexec:10> local LINE='mkdir 2>&1 | cat -A'
+omz_termsupport_preexec:12> title '$CMD' '%100>...>$LINE%<<'
+title:1> emulate -L zsh
+title:2> setopt prompt_subst
+title:4> [[ '' == *term* ]]
+title:8> : '%100>...>$LINE%<<'
+title:10> case xterm-256color (cygwin | xterm*)
+title:12> print -Pn '\e]2;%100\>...\>\$LINE%\<\<\a'
^[]2;mkdir 2>&1 | cat -A^G+title:13> print -Pn '\e]1;\$CMD\a'
^[]1;mkdir^G+zsh:1> mkdir
+zsh:1> cat -A
mkdir: missing operand$
Try 'mkdir --help' for more information.$
```

**Comment by mcornella** [comment]
The `common-aliases` plugin adds a bunch of global aliases, one of them being `CA`:
https://github.com/robbyrussell/oh-my-zsh/blob/315eb77336919d907adf1296ce234d8bc778c005/plugins/common-aliases/common-aliases.plugin.zsh#L30

If an alias is global means that anywhere in the command where the name of the alias is, it will be expanded to its value. That's why `mkdir CA` becomes `mkdir 2>&1 | cat -A`, resulting in the `missing operand` error. If you want to prevent global alias expansion you can use quotes: `mkdir "CA"`.

**Comment by johnmccabe** [comment]
Thanks @mcornella makes complete sense.
