### ISSUE TITLE
Calling a function when custom alias called

### ISSUE THREAD

**Issue by Dentrax** [robbyrussell/oh-my-zsh#7401]
I'm writing a script to prevent me from entering some wrong commands like `rm`.

```
anti_RM() {
   echo "STOP!" >&2
   sleep 3
}

alias rm -fr /*="anti_RM"
alias rm -rf /*="anti_RM"
alias rm -fr /.="anti_RM"
alias rm -rf /.="anti_RM"
```

When i coded this alias script in my custom `.zsh` file that calling from `.zshrc`, i get this error:

`/home/dentrax/.zsh/aliases.zsh:20: no matches found: /*=anti_RM`

How do I make this right? Am i missing something? or Do we have to do this a different way for ZSH?

**Comment by mcornella** [comment]
You can't define aliases with spaces in them. More correctly: you *can* define them, but you'll never be able to run them. 

The error you're seeing though is not because of that, but because you're using the `star` character (*) without quoting, which means zsh thinks you want to expand that to filenames of the form `/*=anti_RM`. If you quote it -- `alias 'rm -fr /*'=anti_RM` -- you'll get no error.

But as I said, it will not do what you think it will. You can only alias a command, not the command and its arguments. To do what you want you'd need to alias `rm` to a function, then in that function either stop if the arguments passed match your blacklist, or call `command rm` with the arguments passed otherwise.

Browse [zsh's documentation](http://zsh.sourceforge.net/Doc/Release/zsh_toc.html) for further help.
