### ISSUE TITLE
tmux plugin fails to detect 256-colour support on FreeBSD

### ISSUE THREAD

**Issue by hiliev** [robbyrussell/oh-my-zsh#7407]
Steps to reproduce

* Make sure `TERM` is set to a terminal type that supports 256 colours, e.g., `xterm-256color`
* Activate the `tmux` plugin
* Start `tmux` or have the plugin autostart it

Expected outcome: `$TERM` == `screen-256color`
Actual outcome: `$TERM` == `screen`

The problem seems to be in the way the plugin reads the number of colours supported by the terminal using `tput colors` This doesn't work on FreeBSD where the terminal attribute is named `Co`. Instead, the value of `co` (number of columns in a line) is read.

**Comment by mcornella** [comment]
What does `tput colors` output?

**Comment by hiliev** [comment]
On FreeBSD (and perhaps other `termcap`-based systems), it outputs the current width of the terminal in characters while the plugin expects it to be the number of colours supported by the terminal.

**Comment by mcornella** [comment]
Are you sure you typed `colors` and not `cols`?

**Comment by mcornella** [comment]
Nevermind I see your explanation. The attribute named `Co` you're referring to is the  tcap code (see [terminfo man page](https://www.freebsd.org/cgi/man.cgi?query=terminfo&sektion=5)), while what we want when using `tput` is the capname, which is `colors`. It seems weird that you need Co instead of colors.

Does `echoti colors` work correctly?

**Comment by hiliev** [comment]
The FreeBSD `tput` utility accepts termcap codes, not terminfo capnames.

`echoti colors` works as expected and outputs correctly the number of colours.

**Comment by mcornella** [comment]
> The FreeBSD `tput` utility accepts termcap codes, not terminfo capnames.

Well that's dumb. I'll change it to use `echoti` then.

**Comment by randomphrase** [comment]
This change causes spurious output in the following case. Launch emacs from within tmux, and then launch a sub-shell (eg using `M-x shell`). This produces the following spurious message.

    /home/alastair/.zsh.d/oh-my-zsh/plugins/tmux/tmux.plugin.zsh:echoti:39: no such terminfo capability: colors

From what I can tell emacs sets the `TERM` variable to `dumb`, which in turn causes the message. It seems that in emacs 26.1 or later, the `TERM` value can be customized, and I can confirm that changing it to something else (eg `xterm`) hides the error.

Note that this is all independent of the shell’s `TERM` value before and after invoking tmux. For example, I am running a terminal which sets `TERM` to `xterm-256color`, which in turn becomes `screen-256color` after entering tmux. Emacs itself shows 256 colors, and works fine apart from the error message above.

Suggested fix is to use `${terminfo[colors]}` instead of `echoti colors`.

**Comment by hiliev** [comment]
I can confirm that `${terminfo[colors]}` expands to the correct number of colors on FreeBSD.

**Comment by mcornella** [comment]
Fixed, thanks!

**Comment by randomphrase** [comment]
Confirmed working, thanks for the quick fix!
