### ISSUE TITLE
The `.` command only finds files from PATH

### ISSUE THREAD

**Issue by MerzDaniel** [robbyrussell/oh-my-zsh#7409]
The `.` command only is able to find files in PATH  while the source command is working fine. I only installed oh-my-zsh without modification along with https://github.com/clvv/fasd. 

While looking into this I realized that my Ubuntu18 `shell` has the same behavior while it works fine in `bash`. 

Is it possible to extend the zsh `.` command to run on files in working dir?

**Comment by mcornella** [comment]
You have to give the full path or a relative path. For example, if the file you're trying to source is in the current working directory you'd use `. ./file`. Otherwise, if doing `. file`, it will look for file in the PATH.

As far as I can tell this is a zsh feature. See [the documentation for the dot command](http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html#index-_002e).
