### ISSUE TITLE
Where do I find the zsh theme folder?

### ISSUE THREAD

**Issue by jasonthename** [robbyrussell/oh-my-zsh#7416]
I just installed zsh and set it as my default shell but I don't know where the theme folder is to install themes?

What even is .zshrc that I hear people talking about and where exactly is it located or something?

**Comment by mcornella** [comment]
Have a look at the README: https://github.com/robbyrussell/oh-my-zsh#using-oh-my-zsh

**Comment by GregHilston** [comment]
To save individuals a few clicks, as of writing this, the default location is 
 
>~/.oh-my-zsh (hidden in your home directory)

**Comment by BrunoVernay** [comment]
If you changed the default location and forgot about it: 
```echo $ZSH
/home/bxxxxx/.config/oh-my-zsh
```

**Comment by worc** [comment]
>  where the theme folder is to install themes?

installing zsh and oh-my-zsh for the third time in like the last 10 years and it's funny to me that a couple of things are never really spelled out explicitly with this repo

like, oh-my-zsh is installed by way of keeping a shallow clone of this repo in a hidden directory, aka `~/.oh-my-zsh`. so, built-in themes are located at `~/.oh-my-zsh/themes`, _but those are tracked by version control_

if you want to _install_ themes without managing your own fork of oh-my-zsh, then you'll want to drop them into `~/.oh-my-zsh/custom/themes` which is ignored by version control. you still have to respect the naming convention of `<theme-name>.zsh-theme`, but otherwise you're pretty much free to do whatever you want. and it looks like [naming collisions are supposed to be won by the custom theme, plugin, script, etc in the `custom` directory](https://github.com/ohmyzsh/ohmyzsh/blob/1d09c6bb0a950756a65b02457842933e3aa493eb/custom/example.zsh)
