### ISSUE TITLE
sometime, oh-my-zsh Taking too much time while login

### ISSUE THREAD

**Issue by johnzeng** [robbyrussell/oh-my-zsh#7422]
This happens quit randomly, and it won't happen for a while after a trigger. So any idea that I can save login log into a file, so I can check it out when the issue happen ?

**Comment by respencer** [comment]
Do you have automatic updates running in the background for oh-my-zsh?

**Comment by johnzeng** [comment]
@respencer I checked about it before, auto update is disabled

**Comment by respencer** [comment]
Then I suspect something else is eating up resources in the background.

Unfortunately without having a system monitor running all the time and catching it in the act, it may be hard to pin down.

I don't know what system you are using, as reference on mine first thing in the morning my automated updates spikes system load. In addition Firefox and Thunderbird regularly screws me over if I leave them running longer than a day.

**Comment by johnzeng** [comment]
I use oh my zsh on Mac item 2. I think problem happens on iterm 2 or zsh, but I don’t know where to find the problem

**Comment by mcornella** [comment]
You can use [the zprof module](http://zsh.sourceforge.net/Doc/Release/Zsh-Modules.html#The-zsh_002fzprof-Module) to profile your zsh startup, like this:
```zsh
# zshrc

zmodload zsh/zprof
# beginning of code to be profiled
...
...
# end of code to be profiled
zprof
zmodload -u zsh/zprof
```

The call to `zprof` is what prints out the stats of time spent. You can redirect it to a file of your choosing, that way you can read the profiling only when the startup was slow.

**Comment by xrubioj** [comment]
Thanks @mcornella! Your tip https://github.com/robbyrussell/oh-my-zsh/issues/7422#issuecomment-461095113 helped to diagnose my slow startup time of new shells. In my case, it was because of NVM. 

If it can be of any help, see https://github.com/creationix/nvm/issues/1978 My current workaround is adding `--no-use` to NVM init script and calling `nvm use default` manually later if I need to use `npm`.

`[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" --no-use  # This loads nvm`

**Comment by mcornella** [comment]
Cool, glad to be of service!
