### ISSUE TITLE
Unable to automate update of zsh and make it unattended

### ISSUE THREAD

**Issue by ssbarnea** [robbyrussell/oh-my-zsh#7468]
I love zsh and oh-my-zsh and I use it on multiple machines but the update prompts is a real PITA that break my "flow".

As a power user I do want to configure it to always update without asking me. How can I do that?

**Comment by trenzafeeds** [comment]
There are a couple of options in .zshrc you can change, depending what your ideal situation is. 

If you want the oh-my-zsh to just automatically update when you start the shell without prompting, set
`DISABLE_UPDATE_PROMPT=true`

If you want oh-my-zsh to never do its updating at initialization of zsh, you can set 
`DISABLE_AUTO_UPDATE=true`, then add the command `upgrade_oh_my_zsh` to your auto-update script (if you have one) to have the updates handled by the script instead of oh-my-zsh itself.
