### ISSUE TITLE
config globalias to expand not always

### ISSUE THREAD

**Issue by chuan137** [robbyrussell/oh-my-zsh#7550]
globalias is a nice plugin, but is it possible to disable expansion for some of the aliases. for example the ls,cp,rm commands are commonly aliased, but it's quite annoying to expand them.

**Comment by mcornella** [comment]
You could press `CTRL`+`SPACE` instead of just a regular space so as not to trigger the expansion: [docs](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/globalias/README.md#usage).

**Comment by krissen** [comment]
> globalias is a nice plugin, but is it possible to disable expansion for some of the aliases. for example the ls,cp,rm commands are commonly aliased, but it's quite annoying to expand them.

I was looking for exactly the same. Although `CTRL` + `SPACE` works, it's a chore to remember doing it only for the specific commands --- particularly when precisely those specific commands (like `ls`, `grep` etc.) are used so frequently.

This seems to work for me:

Change `globalias.plugin.zsh` as follows:
```
globalias() {
   zle _expand_alias
   zle expand-word
   zle self-insert
}
```
to something like
```
globalias() {
   if [[ $LBUFFER != 'ls' && $LBUFFER != 'grep' ]]; then
      zle _expand_alias
      zle expand-word
   fi
   zle self-insert
}
```
(Or instead of changing, make a "fork" of the plugin in `.zsh_custom/plugins/`.)

With the latter code, `ls` and `grep` aren't expanded but everything else is. Add commands to your liking.

(I'm sure there's a better way of doing it, but so far this seems to work. 🤷‍♂️)
