### ISSUE TITLE
Issue with my prompt or my server

### ISSUE THREAD

**Issue by kw-andy** [robbyrussell/oh-my-zsh#7559]
Hi,

Not sure why but when using oh-my-zsh, I have this [screen](https://gifyu.com/image/wfHg):
![image](https://user-images.githubusercontent.com/1441704/51992474-56759780-24ad-11e9-943b-61a3600268cc.png)

Not sure if it is my prompt or a server issue?

Thanks

**Comment by schrer** [comment]
I had an issue like that when using zsh in the Ubuntu subsystem on a Windows machine.
This was due to fonts on windows/the subsystem that would not support some signs used in the robbyrussel-theme, i think.

Unfortunately I did not bother to fix it (only used the Windows machine for ~2 weeks), so I don't have a real solution, if this turns out to actually be your problem

**Comment by respencer** [comment]
That looks to me like you don't have the right font installed or are using the wrong font.

Unless you disagree and can provide more information why you think it's an issue with oh-my-zsh, can you please close this issue?

**Comment by mcornella** [comment]
You probably need a [Powerline font](https://github.com/powerline/fonts).
