### ISSUE TITLE
Conditionally add to prompt only if envar is set

### ISSUE THREAD

**Issue by nodesocket** [robbyrussell/oh-my-zsh#7577]
How can I update the robbyrussell theme to include a envar `$CLIENT` in the prompt, only if the envar `$CLIENT` is set?

Doing the following in the theme file always adds the envar:

```
PROMPT='${hostname} [%{$fg[blue]%}$CLIENT%{$fg_bold[black]%}] ${ret_status} %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'
```

So I only want the entire block `[%{$fg[blue]%}$CLIENT%{$fg_bold[black]%}]` to display if `$CLIENT` is set.

**Comment by respencer** [comment]
You should also be able to use %m instead of ${hostname} btw, unless you're doing something extra.

In answer to your question:

if [ -n "$CLIENT" ]
then
PROMPT='${hostname} [%{$fg[blue]%}$CLIENT%{$fg_bold[black]%}] ${ret_status} %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'
else
PROMPT='${hostname} ${ret_status} %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'
fi

Should do it for you.

**Comment by respencer** [comment]
If $CLIENT changes during a session, then you're going to have to be much fancier than that I suspect.

**Comment by nodesocket** [comment]
@respencer awesome. Thanks that worked.
