### ISSUE TITLE
ssh-agent plugin always asks for passphrase after boot

### ISSUE THREAD

**Issue by panosru** [robbyrussell/oh-my-zsh#7600]
Hello, I'm not sure if that is normal behaviour,

I have the following code (part of it) in my `.zshrc` file:

```
  ssh-agent
)

zstyle :omz:plugins:ssh-agent agent-forwarding on
zstyle :omz:plugins:ssh-agent identities id_rsa gitlab github


source $ZSH/oh-my-zsh.sh
```

But every time after the boot of machine, when I run iTerm, I prompted to enter passphrase:

```
Last login: Sun Feb 17 23:34:58 on ttys001
Enter passphrase for /Users/*****/.ssh/id_rsa:
Identity added: /Users/*****/.ssh/id_rsa (/Users/*****/.ssh/id_rsa)
Identity added: /Users/*****/.ssh/gitlab (/Users/*****/.ssh/gitlab)
Enter passphrase for /Users/*****/.ssh/github:
Identity added: /Users/*****/.ssh/github (*******@gmail.com)
```

Once I add my passphrase, then if I close iTerm and start it again it won't ask me again. It only asks me when I boot my computer and launching iTerm for the first time after boot.

Is that normal? And if not, how can I fix it? And if yes, is there a way to prevent it or store my passphrase somewhere in my system so it will automatically read it?

Thank you in advance!

**Comment by mcornella** [comment]
ssh-agent caches your identities so that you don't have to enter the passphrase every time you use an identity, _e.g._ when running ssh or doing a git push.

When you restart your computer the ssh-agent no longer has these cached, so it needs to ask again for the passphrase. It can't store these anywhere since that could be then exploited to extract the passphrases in an offline attack.

I think there are other agents that can set up a master password which is then used to load multiple identities but I can't recommend anything in particular. Look up keychains or keyrings.

**Comment by panosru** [comment]
I see... well that’s frustrating tbh, I think I can live without ssh-agent plugin then.

Cheers!

**Comment by cwoodcox** [comment]
`ssh-add` supports Keychain on macOS and storing the key passphrase in the system keychain so as long as your user account is unlocked, there is no need to type the key passphrase.

There's really no need for the plugin, just add `ssh-add -K` to your `~/.zshrc`, and in your case you could specify other key names as well. Run `ssh-agent -k` to kill your current agent and open a new terminal or run `source ~/.zshrc` and you'll be prompted for your passphrase(s) one last time, unless they are already saved in your keychain.

**Comment by froboy** [comment]
I also resolved this by removing the zsh `ssh-agent` plugin and adding `ssh-add --apple-use-keychain` after the plugins line.

**Comment by LedzZm** [comment]
Is there anything similar we can do for Ubuntu 20.04 (On WSL2 - WIndows 11)?
