### ISSUE TITLE
Installation script shouldn't alter default shell

### ISSUE THREAD

**Issue by DomHudson** [robbyrussell/oh-my-zsh#7721]
## Summary
In the installation script there is a section that attempts to alter the default shell during installation. I don't think this should be the default behaviour as this is quite an intrusive change when you may just want to try out zsh + oh-my-zsh.

What do you think?

## Related
https://github.com/robbyrussell/oh-my-zsh/issues/4261

**Comment by DomHudson** [comment]
Additionally, when uninstalling it changed my default shell back to bash. I use fish as my default shell so this is frustrating.

**Comment by mcornella** [comment]
#5169 has added the option not to change the default shell, as well as properly saving the previous default shell so that it switches back to it when uninstalling.

If you want to help speed up the testing and merge (which should happen early next week), you can wget or curl it from the URL `https://raw.githubusercontent.com/mcornella/oh-my-zsh/refactor-installer/tools/install.sh`. Read the comments at the top of the script to know how to call it.

Thanks!

**Comment by mcornella** [comment]
Closed by #5169.
