### ISSUE TITLE
[git] Alias gsta is broken for git 2.7

### ISSUE THREAD

**Issue by flohw** [robbyrussell/oh-my-zsh#7754]
Hello there!

I often use `gsta` alias to stash some modification within a project for later.
After the update this morning, it didn't work anymore. 
I think the check on the version number of git is wrong.
I am on git 2.7 wich is considered greater than 2.13 (text comparisn instead of float numbers) and the alias set is `git stash push` instead of `git stash save`.

Why not using only `git stash` which is cross version compatible ?

Sorry to not be able to provide a PR as I am not that good with zsh tests.

Thaks!

**Comment by mcornella** [comment]
This was changed in #7486 because parameters past to just `git stash` weren't the same. I pushed a patch that should again make your alias use `save` instead. Thanks for reporting

**Comment by flohw** [comment]
Thank you @mcornella, just pulled and works fine.

**Comment by brainplot** [comment]
@mcornella I think the root of the problem is that you comparison terms wrong when you merged the PR. I just realized that. When you use `=~` for regex matching, `$match` contains the whole string, so `$match -ge '2.13'` will likely perform lexicographic string comparison.
`$match[1]` contains only what's been captured in the capturing group, resulting in this (after expansion): `2.13 -ge '2.7'` and that should work as expected.
I'm pretty sure of this because I tested my solution with hardcoded versions and it worked.
I think that's the proper fix for this issue.

**Comment by mcornella** [comment]
`$match` is a single-element array, so it's the same `$match[1]` than `$match`. The conditional should be, is version greater or equal than 2.13, which is `[[ 2.7 -ge 2.13 ]]`, which fails because it's true (the number 2.7, arithmetically, is greater than 2.13).

**Comment by brainplot** [comment]
Yes, you're right, sorry. I sent a PR with a version that doesn't use `awk`.
Feel free to accept/reject it :)
