### ISSUE TITLE
git-prompt status doesn't respect files ignored in core.excludesfile

### ISSUE THREAD

**Issue by ksofa2** [robbyrussell/oh-my-zsh#7757]
I have core.excludesfile defined in my ~/.gitconfig, but patterns listed there are not respected by git-prompt. The prompt indicates untracked files, but `git status` shows the repo is clean.

I did a `git bisect` on oh-my-zsh and it looks like this bug was introduced in 3cfcf5e.

**Comment by ksofa2** [comment]
Should have added: I'm seeing this on macOS and Ubuntu...

```
% lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic
% zsh --version
zsh 5.5.1 (x86_64-ubuntu-linux-gnu)
% git --version
git version 2.19.1
```

```
% sw_vers
ProductName:    Mac OS X
ProductVersion: 10.14.4
BuildVersion:   18E226
% zsh --version
zsh 5.3 (x86_64-apple-darwin18.0)
% git --version
git version 2.21.0
```

**Comment by mcornella** [comment]
Thanks for reporting this. The call to Popen with an `env` parameter makes it so that the command is executed with a totally clean environment, which makes it so there is no `$HOME` variable pointing to the file (at least that's what I imagine is happening). This is equivalent to calling the `git status` command with [`env -i`](https://unix.stackexchange.com/a/48995). The pushed version adds `LANG=C` to the env, not completely overrides it.

Cheers

**Comment by ksofa2** [comment]
I've tested with 3c8f73c and bug is gone. Thanks for the fix!
