### ISSUE TITLE
Keep terminal cursor at top?

### ISSUE THREAD

**Issue by AnthonyWC** [robbyrussell/oh-my-zsh#7776]
Does anyone know if there is a way to keep the terminal line with the cursor always on top and then just display command output below it?  I have seen some posts (e.g. https://unix.stackexchange.com/questions/88972/how-to-keep-the-terminal-cursor-fixed-at-the-top) that mention editing prompt cursor $PS1 or $PROMPT but it hasn't worked.

While this isn't strictly specifically for oh-my-zsh, omz is my main shell environment.

**Comment by mcornella** [comment]
How would you expect the terminal to look after running a command? i.e. where would the command output be, in respect to the new prompt?

```
############################################################
# NEW-PROMPT$ [CURSOR]                                     #
# output of the last command                               #
# output of the last command                               #
# output of the last command                               #
# output of the last command                               #
# output of the last command                               #
# output of the last command                               #
# output of the last command                               #
# output of the last command                               #
############################################################
```

If what I just draw, that would entail:
1. Keep track of the number of lines of output (N) shown
2. Move the drawing position to the last prompt (N+1 lines above/backward)
3. Scroll back to that line such that it shows as the first line

Not only is this not trivial, this would also have the effect of overwriting the last prompt, being the thing a little confusing. Also you should have to take into account multiline commands, and if triggering completion, the completion entries would override the output of the last command.

As you can see this is not easy and presents many problems (many more than I just described probably). Maybe I'd be easier having a specific terminal emulator that separates prompt line from command output, such that you can have the former pinned wherever in the screen you want. I think that would be many times easier than what you're suggesting.

I'm closing this either way because this is not something we can do now nor in the future.
