### ISSUE TITLE
Agnoster Arrow Bug

### ISSUE THREAD

**Issue by vicenzocesconetto** [robbyrussell/oh-my-zsh#7783]
I am currently using Zsh 5.7.1 with Oh-My-Zsh with agnoster. I installed the Powerline fonts by my arrows are not as stylish as in the screenshot presented in themes and the colors are not the same either - on terminal or iTerm (https://github.com/robbyrussell/oh-my-zsh/wiki/Themes). 

![image](https://user-images.githubusercontent.com/18091914/56452618-2e0d7480-6309-11e9-86a6-8f30a684f0b9.png)
Here is how my iTerm looks like and my settings.

I think its a bug but I fear this could be caused by not installing the file 10-powerline-symbols.conf (https://github.com/powerline/powerline/tree/develop/font) but I dont know where to put it on MacOS Mojave (10.14.4).

What is this bug with OMZ?

**Comment by AXington** [comment]
The colors in iTerm will come from the iTerm settings. If the profile you have selected for iTerm has some transparent color (as it seems to) set for 'blue' or 'green' as the terminal ANSI colors, it will use those values for that. The theme itself doesn't overwrite the colors you have selected for your shell.

Example:
```
199 # Dir: current working directory
200 prompt_dir() {
201   prompt_segment blue $CURRENT_FG '%~'
202 }
```
If you have your ANSI 'blue' set to transparent, it will show that instead of whatever blue you were expecting. 

One thing I'd suggest is to switch from iTerm to iTerm2  or Alacritty. They have much better compatibility and easier settings/etc for these types of things.

Also what do you mean "arrows are not as stylish"? If you're talking about having the full `username@computername` prompt you can also add `prompt_context(){}` to your ~/.zshrc and it will truncate that off for you.

For directions on colors in iTerm2:
https://sourabhbajaj.com/mac-setup/iTerm/README.html

For Alacritty:
https://github.com/jwilm/alacritty
(After installing edit `~/.config/alacritty/alacritty.yaml`)

I use Agnoster daily on Mac, multiple versions of linux, and on WSL in windows. There shouldn't be any bugs in it, pretty sure this is just a configuration issue.

I also do not believe it has anything to do with your fonts, but, here's a guide for installing fonts on mac:
https://support.apple.com/en-us/HT201749

**Comment by mcornella** [comment]
I agree this is a matter of the color scheme of your terminal emulator (he's actually using iTerm2 if you look at the screenshot). One possible fix is to use the solarized dark color scheme if you want agnoster to look like in [the screenshot in the wiki](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes#agnoster).
