### ISSUE TITLE
Did plugin handling change somehow, getting some missing plugins.

### ISSUE THREAD

**Issue by oppsig** [robbyrussell/oh-my-zsh#7785]
Suddenly I'm getting this on in my shells on init.
[oh-my-zsh] plugin 'colored-man' not found
[oh-my-zsh] plugin 'k' not found
[oh-my-zsh] plugin 'pipenv' not found

I think k was at least installed manually, can't remember how because a while back.

**Comment by danielcardoso5** [comment]
I'm also having the same problem but different plugins:
[oh-my-zsh] plugin 'brew,' not found
[oh-my-zsh] plugin 'yarn,' not found
[oh-my-zsh] plugin 'git,' not found

**Comment by mcornella** [comment]
We started having warnings weeks ago, that's the only change. If you search the issues you'll find many issues like this one. 

----
@danielcardoso5 don't use commas in zsh arrays, use spaces as separators instead.

----
@oppsig colored-man was renamed to colored-man-pages long ago

If k was installed manually it should be put in the custom directory if you want to load it as an OMZ plugin, otherwise just source it manually and delete it from the plugins array.

And there is no plugin for pipenv, at least not yet. Maybe try #6698 and +1 it if it works?

**Comment by danielcardoso5** [comment]
Thanks @mcornella. I've removed the commas and the warnings are gone.
