### ISSUE TITLE
In .zshrc I dont have ZSH_THEME. When I add this with some theme it does not works after source .zshrc

### ISSUE THREAD

**Issue by tojkamaster** [robbyrussell/oh-my-zsh#7793]
Like in title..

Wy It does not work ?

ZSH version 5.5.1 in Ubuntu 19

**Comment by Kogam22** [comment]
@tojkamaster Please. The header is for a Heading.

**Comment by mcornella** [comment]
Follow the [zshrc template](https://github.com/robbyrussell/oh-my-zsh/blob/f46476589aa092f75f5911fa4d6f65401a8d3577/templates/zshrc.zsh-template). The ZSH_THEME definition should go at the top of the file.
And to restart the shell use `exec zsh` instead of `source`. It's cleaner, and `source` might have side-effects.

**Comment by mcornella** [comment]
Also make sure to use a valid theme name like those from [the wiki](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes).
