### ISSUE TITLE
zsh terminal not updating when doing a git operation such pull, push, change branch.

### ISSUE THREAD

**Issue by ilyas-shah** [robbyrussell/oh-my-zsh#7815]
Whenever I make a git operation (on VS code) the integrated zsh terminal does not update. For example, if I am on a branch "develop" and I switch to "master" the headline on the terminal will still show "develop"

**Comment by ilyas-shah** [comment]
![image](https://user-images.githubusercontent.com/11559665/56891836-621c2e80-6a9b-11e9-9860-e3429e6952e9.png)

**Comment by ilyas-shah** [comment]
![image](https://user-images.githubusercontent.com/11559665/56891858-78c28580-6a9b-11e9-89be-d4d73e67729b.png)

**Comment by ilyas-shah** [comment]
![image](https://user-images.githubusercontent.com/11559665/56891899-955ebd80-6a9b-11e9-9013-4b3dc699e33c.png)

**Comment by mcornella** [comment]
There are certain themes that only poll git info if a git command has been run, that's why a git operation run outside of the terminal wouldn't trigger an update. In your case though, it looks like you're using agnoster, and it should update on each prompt redraw. Have you tried pressing <kbd>Enter</kbd> to redraw the prompt?

**Comment by ilyas-shah** [comment]
@mcornella yes it works when I press `Enter` I want it to update without pressing any key.

**Comment by mcornella** [comment]
That's not supported in OMZ as of this moment, you should be able to cobble together a solution using `TMOUT` and `TRAPALRM`. See [this example](https://stackoverflow.com/a/17915260). It's been found to mess up with multiline prompts though.
