### ISSUE TITLE
battery plugin displays infinity symbol instead of battery level

### ISSUE THREAD

**Issue by tushardas** [robbyrussell/oh-my-zsh#7816]
This is my robbyrussell.zsh-theme  file : - 

```
local ret_status="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"
PROMPT='${ret_status} $USER@$HOST%{$fg[cyan]%}%~%{$reset_color%} $(git_prompt_info)'
RPROMPT='$(battery_pct_prompt)'
ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}git:(%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[yellow]%}✗"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%})"
```

**Comment by tushardas** [comment]
I have added `battery` to plugins array in ~/.zshrc file

**Comment by mcornella** [comment]
That happens when you've got your laptop plugged in, see https://github.com/robbyrussell/oh-my-zsh/blob/6da85279eb544c48e85a3714e6fe65f72fd78071/plugins/battery/battery.plugin.zsh#L33-L45

**Comment by tushardas** [comment]
Does this plugin work only on MacOS?

**Comment by mcornella** [comment]
> Need clarification:- Does this plugin work only in MacOS?

Oh, I just assumed you were running macOS. Here's the relevant code for Linux: https://github.com/robbyrussell/oh-my-zsh/blob/6da85279eb544c48e85a3714e6fe65f72fd78071/plugins/battery/battery.plugin.zsh#L93-L107

It seems if `acpi` shows battery discharging it will print the remaining battery charge, otherwise it will print the infinity symbol. What does `acpi` show when unplugged?

**Comment by tushardas** [comment]
Thanks. It's working.
