### ISSUE TITLE
autocomplete on command nmcli don't work correctly 

### ISSUE THREAD

**Issue by apten-fors** [robbyrussell/oh-my-zsh#7871]
Autocomplete on command nmcli don't work correctly.
When i'm type in zsh nmcli conn then press tab nothing happens. In bash nmcli conn[tab] will get  command `nmcli connection` 

on zsh: 
~ nmcli conn[tab]
do nothing
 ~ nmcli conn [tab]
con  -- NetworkManager connections
dev  -- devices managed by NetworkManager
nm   -- NetworkManager status

on bash:
$ nmcli conn[tab]
$ nmcli connection
$ nmcli conn [tab]
add      clone    delete   down     edit     export   help     import   load     modify   monitor  reload   show     up       

 - OS: Mint 19.1 tessa / ubuntu mate 18.04
 - Shell: zsh 5.4.2
 - Terminal emulator: mate-terminal, gnome-terminal, terminator

**Comment by mcornella** [comment]
It looks like the completion file in zsh wasn't updated until https://github.com/zsh-users/zsh/commit/c789efbaf0db016256d58c685c5586d7a684170d#diff-4ae5bd820909859d47f74d1bd29864dd, which only made it to zsh 5.5 and newer versions.

If you can, update your zsh version. Otherwise you can download the [`_networkmanager` file](https://github.com/zsh-users/zsh/blob/c789efbaf0db016256d58c685c5586d7a684170d/Completion/Linux/Command/_networkmanager) and put it somewhere in your `$fpath` that supersedes the old `_nmcli` file. You could even overwrite the `_nmcli` file—you will find it searching for it in the directories in `$fpath`, with the oneliner `for d ($fpath); do [[ -f $d/_nmcli ]] && echo $d/_nmcli; done`. This last option will trigger a conflict when zsh is eventually updated though.
