### ISSUE TITLE
overriding `agp` (conflict between 'ubuntu' and 'aws') fails  

### ISSUE THREAD

**Issue by jjangga0214** [robbyrussell/oh-my-zsh#7886]
I placed plugin **aws** later than  **ubuntu**, which should override **ubuntu**'s `agp` to **aws**'s.

```bash
plugins=(
ubuntu
#... some other plugins
aws
)
```

However, override fails. `agp` is still `apt purge`. The error message below is printed every time I open a new shell.

```
/home/gilchan/.oh-my-zsh/plugins/aws/aws.plugin.zsh:1: defining function based on alias `agp'
/home/gilchan/.oh-my-zsh/plugins/aws/aws.plugin.zsh:1: parse error near `()'
```

Before update today, this hasn't happened with the same setting.

**Comment by mcornella** [comment]
This is due to the removal of the `function` keyword before the definition of the function, introduced in 1343ab6.

**Comment by mcornella** [comment]
Fixed in https://github.com/robbyrussell/oh-my-zsh/commit/9930dd6e49df5630ac23c68b85465f0bb801d17f. The error won't appear anymore, but know that the `agp` alias in the ubuntu plugin will still take precedence over the `agp` function in the aws plugin (aliases take precedence over functions, it's the zsh way).
