### ISSUE TITLE
Allow plugins to be specified in custom.zsh files

### ISSUE THREAD

**Issue by danielmillen** [robbyrussell/oh-my-zsh#7889]
It would be great to be able to specify additional plugins in the ~/.oh-my-zsh/custom/*.zsh files. This would make it very easy to contain all customizations in a single file in the case of installing on a new PC or sharing a custom configuration file.

Right now, it seems like some customizations can be done via the .zsh files (theme, maybe some of the other settings).

**Comment by mcornella** [comment]
This would entail making the init process more convoluted and I see no real need to do that. As it is now, you can have a workaround because files directly under `$ZSH_CUSTOM` are read after `$plugins` are sourced, but you could manually source files in one of these `$ZSH_CUSTOM/*.zsh` files. By way of example, this could be file `$ZSH_CUSTOM/01-load.zsh`:
```zsh
plugins=(abc def ghi) # defining the plugins you need
for plugin ($plugins); do
  source $ZSH/plugins/$plugin/$plugin.plugin.zsh
done
```

See the `oh-my-zsh.sh` file in the root folder of the repository to understand a bit more the loading process.
