### ISSUE TITLE
Extra backslash for url parameters

### ISSUE THREAD

**Issue by vkuznet** [robbyrussell/oh-my-zsh#7898]
**Describe the bug**
When I type an url with parameters in my shell, e.g. `http://a.b.com/bla=1`, or paste it from clipboard (OSX), I always get extra backslash in front of parameter's values, i.e. `http://a.b.com/bla\=1`. Originally I thought it was an issue of terminal I use or zsh, but I verified using different shells/computers that it is related to oh-my-zsh settings I have.

**To Reproduce**
1. you can either start typing `http://a.b.com/bla=1`
2. you can copy an url with parameters and paste it in your shell
in both cases I get back the following result
`http://a.b.com/bla\=1`
I found that `=` and `?` are escaped.

**Expected behavior**
I would expect that no escaped backslash will appear when I type or paste my url, if it is a feature I would like to know which shell configuration parameter controls it or how to disable it.

**Screenshots or recordings**

**System:**
 - OS: macOS, 10.14.5
 - Zsh version: zsh 5.3 (x86_64-apple-darwin18.0)
 - Terminal emulator iTerm2

**Additional context**

**Comment by mcornella** [comment]
The backslashes act as quotes to special characters that would otherwise act as globbing characters (used to match filenames), such as those in `?&=[]{}` and probably others. This is allowed by `url-quote-magic`, which is enabled in `misc.zsh`: https://github.com/robbyrussell/oh-my-zsh/blob/9930dd6e49df5630ac23c68b85465f0bb801d17f/lib/misc.zsh#L4-L16

For example:
```
$ curl http://a.b.com/?bla\=1
zsh: no matches found: http://a.b.com/?bla=1
$ curl http://a.b.com/\?bla\=1
curl: (6) Could not resolve host: a.b.com
```

It should work correctly, i.e. only quote these characters if they are not already quoted. However, you can disable this OMZ setting by setting `DISABLE_MAGIC_FUNCTIONS=true` before OMZ is sourced.

**Comment by EvanCarroll** [comment]
@mcornella why is this option there (security?) why doesn't work for me, and why does it work for everyone else.
