### ISSUE TITLE
kubectl plugin fails with permission denied: /usr/share/oh-my-zsh/cache/kubectl_completion

### ISSUE THREAD

**Issue by papanito** [robbyrussell/oh-my-zsh#7903]
**Describe the bug**
I have the `kubectl` plugin installed but I always get the following error when starting the shell:

```bash
/usr/share/oh-my-zsh/plugins/kubectl/kubectl.plugin.zsh:5: permission denied: /usr/share/oh-my-zsh/cache/kubectl_completion
```
The respective code is this

```bash
if (( $+commands[kubectl] )); then
    __KUBECTL_COMPLETION_FILE="${ZSH_CACHE_DIR}/kubectl_completion"

    if [[ ! -f $__KUBECTL_COMPLETION_FILE ]]; then
        kubectl completion zsh >! $__KUBECTL_COMPLETION_FILE
    fi

    [[ -f $__KUBECTL_COMPLETION_FILE ]] && source $__KUBECTL_COMPLETION_FILE

    unset __KUBECTL_COMPLETION_FILE
fi
```
There is no `kubectl_completion` in the `cache` 

**To Reproduce**
1. Enable plugin 'kubectl'
2. Open new terminal
3. See error
```bash
/usr/share/oh-my-zsh/plugins/kubectl/kubectl.plugin.zsh:5: permission denied: /usr/share/oh-my-zsh/cache/kubectl_completion
```

**Expected behavior**
No error at all.

**System:**
 - OS: Linux
 - Zsh version `zsh 5.7.1 (x86_64-pc-linux-gnu)`

**Comment by mcornella** [comment]
The plugin tries to create it in the cache folder but given that it's not writable you get the error. The cache folder should be writable, but since you installed OMZ in `/usr/share/oh-my-zsh` the cache folder is read-only. You can either
- Install OMZ in your home directory, or someplace else with write permissions
- Use another folder with write permissions as the cache dir and set `ZSH_CACHE_DIR=/the/path` in your zshrc file, before OMZ is sourced.

**Comment by papanito** [comment]
Thanks. Didn't realize that my user needs also writhe permissions in the cache folder
