### ISSUE TITLE
tweak tab title when a program is running?

### ISSUE THREAD

**Issue by sorakiu** [robbyrussell/oh-my-zsh#7907]
I sometimes have 3 or 4 tabs running gradlew in iterm2. Whenever I run gradle, the tab title changes to `./gradlew`

Is there a way to alter the tab title so that it includes the last part of the path?

like foo:gradlew where is foo is the last part of the path?  /abc/def/foo

**Comment by mcornella** [comment]
This is done in OMZ by the `omz_termsupport_preexec` function, which ultimately calls the `title` function with two arguments. For what you say, I think what you see is the first argument to `title`, which only prints the first word of the command running. If that's the case, running `title ABC DEF; sleep 3` should show `ABC` in the tab title. 

Having checked that, you can modify the `omz_termsupport_preexec` tab as follows:
```diff
 function omz_termsupport_preexec {
   emulate -L zsh
   setopt extended_glob

   if [[ "$DISABLE_AUTO_TITLE" == true ]]; then
     return
   fi

   # cmd name only, or if this is sudo or ssh, the next cmd
   local CMD=${1[(wr)^(*=*|sudo|ssh|mosh|rake|-*)]:gs/%/%%}
   local LINE="${2:gs/%/%%}"

-  title '$CMD' '%100>...>$LINE%<<'
+  title '$LINE' '%100>...>$LINE%<<'
 }
```

Note that the `LINE` variable uses `$2` instead of `$1`, which means it will expand the aliases in the command run (so if `ll` is an alias to `ls -l`, the title will show `ls -l`). If you don't want that, change the 2 for a 1, i.e. `LINE="${1:gs/%/%%}"`.

The easiest way to modify the function is to copy it and modify it in your zshrc file, after OMZ is sourced.

Hope that's clear enough!

**Comment by sorakiu** [comment]
it was very helpful, but I found that this (more or less) gives me the desired result?

```
   title '%15<..<%~%<< - $CMD' '%100>...>$LINE%<<'
```

I would never have figured this out without your help.  Please accept my sincere thanks!

**Comment by sorakiu** [comment]
![image](https://user-images.githubusercontent.com/291045/58967170-adec8280-8781-11e9-9286-8fb7c14e621d.png)

**Comment by mcornella** [comment]
Oh right, I misunderstood what you needed. Good job figuring out the rest. Cheers!
