### ISSUE TITLE
macOS Catalina default zsh support?

### ISSUE THREAD

**Issue by bsarrazin** [robbyrussell/oh-my-zsh#7956]
I'm a complete terminal n00b, please excuse the dumb questions.

Are there plans to support macOS Catalina's zsh?
It would be great if installation of themes and plugins could be integrated with the native zsh on Catalina without having to install zsh again. Or maybe ohmyzsh has modified zsh to allow plugins/themes?

I just can't seem to find anything (that I understand) on the Internet. Please feel free to close this issue if my question doesn't make any sense. Really appreciate the enlightenment! Thank you!

**Comment by mcornella** [comment]
Since Oh My Zsh lives on top of zsh, you can still run the OMZ installer and expect everything to work correctly. The only difference is that there won't be a necessity to switch the default shell.

> Or maybe ohmyzsh has modified zsh to allow plugins/themes?

You can think of Oh My Zsh as a collection of shell scripts, no need to modify itself.

**Comment by limahatzl** [comment]
I have updated my macbook to Catalina
since then, when I open my terminal it is asking me all the time my zsh password with su command and i receive error msg because is su  command not sudo....

the main thing is that i dont want to be asked for a password all the time i open my terminal

i think oh my zsh has some conflitct after users update to macOs Catalina

any thoughts how do I fix this issue?

**Comment by kmandeville** [comment]
What does this mean if I already have OMZ already set up and working well on pre-Catalina? What will happen if I upgrade to Catalina? Will it still just work? I remember it being a bit of a pain to get my theme working just right

**Comment by mcornella** [comment]
It'll work just the same, do not worry.
