### ISSUE TITLE
Extra space after branch name when using Tab to autocomplete git branch

### ISSUE THREAD

**Issue by hieunguyentrung** [robbyrussell/oh-my-zsh#8033]
**Describe the bug**
Auto add an extra space after branch name when using tab.

**To Reproduce**

1. Enable plugin 'git'
2. Move into a git project folder, example we have branch `demo-test`
3. Type command `git checkout demo`, then press Tab

**Expected behavior**
Auto fill `demo-test` without 2 spaces between branch name and prompt. Only need one.
<img width="392" alt="Screen Shot 2019-07-25 at 05 24 42" src="https://user-images.githubusercontent.com/10509903/61833002-3099e000-ae9d-11e9-8307-51ae1f8fc481.png">

**Screenshots or recordings**
<img width="384" alt="Screen Shot 2019-07-25 at 05 24 32" src="https://user-images.githubusercontent.com/10509903/61833010-3a234800-ae9d-11e9-8f02-0bfcb34dd655.png">

**System:**
 - OS: MacOS 10.14.6
 - Zsh version: zsh 5.7.1 (x86_64-apple-darwin18.2.0)
 - Terminal emulator: iTerm2 and MacOS Terminal
 - Default oh-my-zsh theme
 - Already run `upgrade_oh_my_zsh` to get latest updates

**Additional context**
I have two MacBook Pro, one is 2015 and other is 2019.
I think two machines have same config, theme ... but the problem only happened in 2019, 2015 is still normal.

**Comment by hieunguyentrung** [comment]
I found out that because of git, I installed the latest version of git through brew, so it was like that. Using git default Mac will not be anymore.

**Comment by habibalamin** [comment]
@hieunguyentrung can you reopen this? I get this with Git from Homebrew or built-in Git. This little thing has been bugging me for years.

**Comment by hieunguyentrung** [comment]
@habibalamin Hello, I think the problem is not from oh-my-zsh, but because of the git version. If you install git from brew, then remove it, using the default git following macOS will be fine.

**Comment by habibalamin** [comment]
@hieunguyentrung if that’s the case, this is still a bug. The brewed version is usually newer, and therefore should be fixing bugs, not adding them.

Besides that, oh-my-zsh has to work with both.

I tried with both built-in Git (or rather Xcode Git) and brew Git, even going so far as to remove the Homebrew PATHs. I realise now that I should have uninstalled brew Git completely, as it comes with specific completion scripts that will still get picked up by built-in Git (which I’m guessing are what’s causing the problem, or something else that brew Git is installing that isn’t the binary itself).

Before I realised it had nothing to do with the binary itself, I was going to say that it may be a matter of a specific version of Git and later causes problems, not whether it’s from the built-in or not. So, for example, anything later than `2.19` causes problems, and on an earlier version of macOS, built-in Git is less than that, while on Catalina, built-in version is later.

However, I don’t think if the problems brew Git is causing come from upstream.

That said, as I stated, this needs to be fixed for both, or if the bug is on the brew Git formula itself, it should be fixed there. We cannot have “run an earlier (and possibly insecure) version” be the solution.

**Comment by habibalamin** [comment]
Interestingly, the built in ZSH completion script is almost 8k lines, whereas brew’s flawed completion script is a little under 250 lines. Unlinking the flawed completion script has the same effect as uninstalling brewed Git, and the flawed script actually makes completion feel a tiny bit faster.

These links may be interesting https://github.com/Homebrew/homebrew-core/issues/33275 https://www.raphael-brugier.com/blog/fix-git-completion-zsh-mac-homebrew.

It seems like Git ships with its own ZSH completion scripts and then ZSH ships with better ZSH completion scripts for Git. Homebrew used to let you specify an option to not include the ZSH completion scripts when installing Git, and that would allow the ZSH’s ZSH completion scripts for Git to work.

**Comment by maahd** [comment]
It's Sep 3, 2020 and I'm still having this issue...

**Comment by xh3b4sd** [comment]
Same problem here. This is not about `git`. Have it with all kinds of completions.

**Comment by hieunguyentrung** [comment]
I switched to using the default git that came with the operating system, and didn't have that problem anymore.
