### ISSUE TITLE
no such file or directory: /oh-my-zsh.sh

### ISSUE THREAD

**Issue by baeharam** [robbyrussell/oh-my-zsh#8055]
I looked for lots of solutions in github issues and googling, but I couldn't solve it.

My zsh version

```zsh 5.7.1 (x86_64-apple-darwin18.2.0)```

My `~/.zshrc`

```
export zsh="/users/baeharam/.oh-my-zsh"
zsh_theme="agnoster"
plugins=(git)
source $ZSH/oh-my-zsh.sh
export LANG=ko_KR.UTF-8

source /Users/baeharam/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
prompt_context() {}
prompt_dir() {
  prompt_segment blue black "%$(( $COLUMNS - 61 ))<...<%3~%<<"
}

cd ~/haram/
export PATH="$(yarn global bin):$PATH"
[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh
```

How can I handle this?

**Comment by baeharam** [comment]
The reason was characters of `zsh`. It must be uppercase

**Comment by Philipp91** [comment]
I found this GitHub issue based on an error I got:
```
/home/philipp/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh:source:1: no such file or directory: /home/philipp/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh^M
```

Note the `^M` in the end, which is the characteristic part of this problem. (It's a different problem from then one baeharam had, but I'm still documenting it here, as it might help someone who finds this issue.)

The problem is caused by installing the respective plugin (`zsh-autosuggestions`) in this case with the wrong line endings. I'm using Ubuntu inside WSL under Windows, so I have `core.autocrlf=true` in my config, as most of my repositories are used through Windows applications.

To solve the problem, delete the plugin directory again (`rm -rf /home/philipp/.oh-my-zsh/custom/plugins/zsh-autosuggestions/`) and install it with proper line endings (`git clone -c core.autocrlf=false ...`).
