### ISSUE TITLE
source command does not work

### ISSUE THREAD

**Issue by LeonardoFurtado** [robbyrussell/oh-my-zsh#8100]
**Describe the bug**
the command `. [something here]` does not working when I'm using oh-my-zsh, if i try `. [tab]` i will receive:
` zsh: do you wish to see all 2222 possibilities (1111 lines)?`

**To Reproduce**
using ubuntu 19

> ➜  bin git:(master) ✗ . activate
> .: no such file or directory: activate
> ➜  bin git:(master) ✗ ls
> activate       chardetect    easy_install-3.7  f2py3.7  pip3.7  python3
> activate.csh   decorate      f2py              pip      pyjwt
> activate.fish  easy_install  f2py3             pip3     python
> ➜  bin git:(master) ✗ 

**Expected behavior**
`. activate` should activate my virtual environment.

**Screenshots or recordings**

**System:**
 - OS: ubuntu 19.04 disco dingo
 - Zsh version: zsh 5.5.1 (x86_64-ubuntu-linux-gnu)
 - Terminal emulator: bash, on hyper i receive the same error

**Additional context**
I formatted the computer and just installed zsh and oh-my-zsh, and the problem persists. I don't use any autocomplete tools
![error](https://i.ibb.co/Lr7GDHN/Screenshot-from-2019-08-22-20-25-36.png)

**Comment by mcornella** [comment]
That's a feature of the [`.` (dot) builtin](http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html#index-_002e): if no path is passed to it (i.e. it doesn't contain a slash), it will try to find the argument in `$PATH` instead of the current directory. If the current directory is not in the `$PATH` then it will exit with a not found error. In other words, you need to `. ./activate` or it won't work.

If don't want to have to do that, use the [`source` builtin](http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html#index-source) which looks in the current directory first.

**Comment by LeonardoFurtado** [comment]
> That's a feature of the [`.` (dot) builtin](http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html#index-_002e): if no path is passed to it (i.e. it doesn't contain a slash), it will try to find the argument in `$PATH` instead of the current directory. If the current directory is not in the `$PATH` then it will exit with a not found error. In other words, you need to `. ./activate` or it won't work.
> 
> If don't want to have to do that, use the [`source` builtin](http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html#index-source) which looks in the current directory first.

2021 and this error come back again. And it just occurs on ohmyzsh

**Comment by LeonardoFurtado** [comment]
I'm using source, but it does not work properly too

**Comment by mcornella** [comment]
How does it not work?
