### ISSUE TITLE
(eval):1: bad pattern: *(-/):directories  .... error whenever I press [tab] to autocomplete on OpenBSD octeon zsh 5.7.1 (mips64-unknown-openbsd6.5)

### ISSUE THREAD

**Issue by mchack23** [robbyrussell/oh-my-zsh#8134]
**Describe the bug**

I get this "(eval):1: bad pattern: *(-/):directories"  error message whenever I press [tab] to autocomplete. To be fair it also happens when I uninstall oh-my-zsh but vanishes if I delete compinit from my .zshrc. So it's probably something in compinit and I don't know where to file the issue there. Feel free to delete the Issue if I'm in the complete wrong context here.

**To Reproduce**

Install zsh and oh-my-zsh on openbsd 6.5 on octeon hardware via 
1. pkg_add zsh
2. sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
3. Try and hit tab to autocomplete files like ls test[tab]

**Expected behavior**

in any other installation of oh-my-zsh autocomplete works without this error message

**Screenshots or recordings**

mchack@mcfire ~ $ ls test               
(eval):1: bad pattern: *(-/):directories
mchack@mcfire ~ $ ls test/              
test/  test1  test2                     

**System:**
 - OS: Openbsd 6.5 octeon
 - Zsh version: zsh 5.7.1 (mips64-unknown-openbsd6.5)
 - Terminal emulator: Tilda

**Additional context**
here's the trace when pressing ctrl-x ? instead of pressing [tab]

[zsh14617ls1.txt](https://github.com/robbyrussell/oh-my-zsh/files/3585410/zsh14617ls1.txt)

**Comment by mcornella** [comment]
Can you post the `_files` file? It should be in `$fpath`:
```
for d ($fpath); do [[ -f "$d/_files" ]] && echo $d && break; done
```

**Comment by mchack23** [comment]
sure
[_files.txt](https://github.com/robbyrussell/oh-my-zsh/files/3586803/_files.txt)

**Comment by mcornella** [comment]
The `_files` file is the same one as zsh 5.7.1, so that's all right. Here's what I get in a docker container with that same version:
```
       +_files:81> def=*:globbed-files *(-/):directories
       +_files:82> eval 'def=( \*:globbed-files \*\(-/\):directories )'
        +(eval):1> def=( '*:globbed-files' '*(-/):directories' )
```
and here's what you get:
```
       +_files:81> def=*:globbed-files *(-/):directories
       +_files:82> eval 'def=( *:globbed-files *(-/):directories )'
(eval):1: bad pattern: *(-/):directories
        +(eval):1> def=
```
This is comming from [this code in `_files`](https://github.com/zsh-users/zsh/blob/zsh-5.7.1/Completion/Unix/Type/_files#L77-L82):

```zsh
  pats=( "${${glob:-*}//:/\\:}:globbed-files *(-/):directories" '*:all-files ' )
fi

tried=()
for def in "$pats[@]"; do
  eval "def=( ${${def//\\:/\\\\\\:}//(#b)([][()|*?^#~<>])/\\${match[1]}} )"
```

As you can see in the last line, the command passed to eval is aggressively quoted, so that the stars in `*:globbed-files *(-/):directories` should be prepended with a backslash. This happens in my machine but not in yours, but I haven't been able to find the reason why.

At this point I can't help you any further. Try in the zsh mailing list with the information I've been able to gather: http://zsh.org/mla.
