### ISSUE TITLE
Error while executing curl command

### ISSUE THREAD

**Issue by aTGuz** [robbyrussell/oh-my-zsh#8139]
Hi, there is an error when executing the following command:
```
curl -Lo kops https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
```
try it out and will see the error.

Thanks and congrats for such an awesome command interpreter.

**Comment by mcornella** [comment]
It worked for me after removing the extra quoting behind the first parenthesis (did you get a `parse error`?). If that's the problem, make sure there's no backslash before the first parenthesis:
`...download/$\(curl...` bad, `...download/$(curl...` good.

**Comment by aTGuz** [comment]
Hello, thanks for the quick response
Seems that when you paste the command to the shell it add an extra quot. Removing it solve the problem thanks again!

**Comment by mcornella** [comment]
Yeah this is done by the [`url-quote-magic` widget](https://github.com/zsh-users/zsh/blob/master/Functions/Zle/url-quote-magic) which quotes special characters that zsh interprets but may be in a URL (like square brackets or question marks, or in this case, the `$(`). A possible solution is to wrap the URL in double quotes so that the widget doesn't need to act when pasting it.
