### ISSUE TITLE
Using oh-my-zsh in remote server without affecting others?

### ISSUE THREAD

**Issue by OpenWaygate** [robbyrussell/oh-my-zsh#8147]
I have installed oh-my-zsh in a remote machine and powerline fonts in local PC. This mean if I use zsh, the special characters will not display correctly in other people's terminal.

How to make zsh serve only for me and others use the default one?

**Comment by mcornella** [comment]
You can use a theme that doesn't use special characters. 

Otherwise, other people could use a shell other than zsh:
- If you log in as a different user, zsh configuration is per user so only you would run zsh.
- If you all log in as the same user, you could set the default shell to bash or another shell different than zsh. Then, you would log in and then run zsh.

**Comment by OpenWaygate** [comment]
Thank you @mcornella. For these having similar problem, I write an alias
```
alias ssh_alias='ssh -p 1234 -i ~/path/to/id_rsa name@host -t '\''zsh'\'
```
