### ISSUE TITLE
git branch completion with wrong string

### ISSUE THREAD

**Issue by luvarqpp** [robbyrussell/oh-my-zsh#8233]
**Describe the bug**
There is completion without "fully qualified" branch name, which yelds to invalid parameter for git.

**To Reproduce**

1. Enable plugin 'git'
2. Run commands:
```
mkdir gitCompletionTest
cd gitCompletionTest 
git init
touch somethingWeird.exe
git add .
git commit -m 'commit msg' .
# now create some branches to autocomplete from
git checkout -B feature/someEasyOne
git checkout -B feature/ohMyZshIsSmart
git checkout -B feature/harderOne
```
3. Now try to switch to `feature/ohMyZshIsSmart` using partial branch name and autocompletion. Write: `git checkout Zsh` and hit tab for autocompletion. It will complete command to `git checkout ohMyZshIsSmart`, which will not work

**Expected behavior**
I expect that tab will expand to 'gitcheckout feature/ohMyZshIsSmart' (full name of branch).

**System:**
 - OS: ubuntu 18.04
 - Zsh version: zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
 - Terminal emulator: Gnome terminal in i3wm

**Comment by mcornella** [comment]
If you're just using the `git` plugin that means that the git completion in effect is really the one provided by Zsh, so this is an upstream bug. 

After reproducing your test case:
![image](https://user-images.githubusercontent.com/1441704/66486149-569d4c80-eaaa-11e9-9a31-86f104c26308.png)

It autocompletes to just the last part because there are two entries with the same name, so zsh puts the cursor at the beginning of the argument so you can write in the rest. I think this was a bug seen not long ago that was fixed.

Proved to work in **version 5.7.1** so you can either update to that version or grab the [`_git` completion file from that version](https://github.com/zsh-users/zsh/blob/zsh-5.7.1/Completion/Unix/Command/_git) and put it somewhere in a directory in `$fpath` that comes before the directory that has the `_git` file (find it with `for d ($fpath); do [[ -f $d/_git ]] && echo $d; done`).

**Comment by luvarqpp** [comment]
Thanks, after upgrade, cursor is on correct place.

I have one more question. Why does completion provides me with two same completion values? Both suggested lines have 'feature/ohMyZshIsSmart' value. First completion is having commit message as its comment. Does it make sense to autocomplete to maximum common string from all suggested values (ignoring comments)?

**Comment by mcornella** [comment]
It does make sense but I believe both values were suggested as part of different entry groups and thus zsh doesn't automatically select the maximum possible common string. I seem to recall that was part of the bug so behavior may have changed.
