### ISSUE TITLE
zsh: /etc/profile:35: no matches found: tty[1-6]

### ISSUE THREAD

**Issue by danielesk** [robbyrussell/oh-my-zsh#8279]
**Describe the bug**

![image](https://user-images.githubusercontent.com/10652829/67057388-e1eda080-f182-11e9-9514-9d52c8153e72.png)

**To Reproduce**

**Expected behavior**

**Screenshots or recordings**

**System:**
 - OS: [e.g. deepin 15.11]
 - Zsh version [e.g. zsh 5.5.1 (x86_64-debian-linux-gnu)]
 - Terminal emulator [e.g. deepin terminal]

**Additional context**

**Comment by mcornella** [comment]
The file `/etc/profile`, line 35, has syntax that is incompatible with zsh's wildcard expansion. The [square brackets](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Filename-Generation) look for files that match whatever's inside the square brackets. In this case, zsh interprets as "look for files beginning with tty followed by a number from 1 to 6".

You could run `su` instead, so that you run it with the login shell of root, instead of with zsh. Another option is to edit that file so that zsh can interpret it correctly. Can you post that file? (Closing since this is not OMZ related)

**Comment by danielesk** [comment]
@mcornella The default shell for the root account is ZSH.
