### ISSUE TITLE
`kill -l` output styles are quite different

### ISSUE THREAD

**Issue by danielesk** [robbyrussell/oh-my-zsh#8280]
**Describe the bug**

![image](https://user-images.githubusercontent.com/10652829/67063934-1705ed00-f19b-11e9-92ba-f9660578f1b4.png)

I'm more used to the following style.Please tell me how to do it in ZSH.

**To Reproduce**

**Expected behavior**

**Screenshots or recordings**

**System:**
 - OS: [e.g. deepin 15.11]
 - Zsh version [e.g. 5.6]
 - Terminal emulator [e.g. deepin terminal]

**Additional context**

**Comment by mcornella** [comment]
In bash, `kill` is a builtin that allows either `-l` or `-L` to format the signals nicely.

In zsh, the `kill` builtin doesn't have that feature, but you can use the `kill` command instead of the builtin. To do that, prepend `command` to the kill command and pass in `-L` to get the table formatted nicely (`kill -l` does the same as the zsh builtin). So `command kill -L`. You can also just prepend a backslash: `\kill -L`.

If the nice formatting is something you want to see you can ask for it nicely in the [zsh mailing list](http://zsh.org/mla).
