### ISSUE TITLE
Uninstall zsh/Oh My Zsh

### ISSUE THREAD

**Issue by mdbriones** [robbyrussell/oh-my-zsh#8363]
I tried to uninstall zsh for delay reason. But when I open my ubuntu terminal (installed using WSL [windows 10]), it closes immediately right after I open it. What is happening? I guess I messed up on changing the default shell? Please help.

**Comment by mcornella** [comment]
You can run `bash.exe` to get into the bash shell, then change the default shell with `chsh -s $(which bash)`.

**Comment by mdbriones** [comment]
Thank you so much. I really appreciate your response. In any case, how can
I speed up zsh? I have no loading issue in my pc with ubuntu, but my laptop
with win10 that has ubuntu running on wsl, the loading on every command is
quite delay (2-3s). Do you have any idea?

**Comment by larson-carter** [comment]
@mdbriones Can your please provide me with the specs of your PC?

I'm thinking that it could possibly be a combination of things. Such as all of the plugin and script files. Possibly windows defender slowing down performance.  ZSH, Bash and or TMUX with customized themes can result in a bad user experience via speed due to WSL/DRVFS poor execution of the file system. So disabling themes would be a way to see if that helps. Windows Defender very well may be the one and only culprit.

**Comment by mcornella** [comment]
WSL is a work in progress, I too experience sometimes a delay in running a command. You can browse the issues in the [WSL repository](https://github.com/microsoft/WSL/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) to find your problem, or create a new issue.

**Comment by mdbriones** [comment]
Thank you. For now i will search for any other solutions on this matter.
Thanks.

**Comment by mcornella** [comment]
@mdbriones I recently debugged my issue and found these lines in my zshrc file to be the culprit:
```zsh
# automatic rehashing of commands...
zstyle ':completion:*' rehash true
# ...and checking if they're actually executable before adding them
setopt hashexecutablesonly
```
Just in case you had them.

**Comment by mdbriones** [comment]
Hmm... Gotta check that out.
