### ISSUE TITLE
Uninstall oh-my-zsh

### ISSUE THREAD

**Issue by frknyrlmz** [robbyrussell/oh-my-zsh#8364]
When I open the terminal when I delete it, I see this article.
"/Users/furkanyorulmaz/.zshrc:source:73: no such file or directory: /Users/furkanyorulmaz/.oh-my-zsh/oh-my-zsh.sh" 
how do I make this post disappear? Thank you!

**Comment by larson-carter** [comment]
@frknyrlmz  Hello, have you looked into some of the following attached links for a possible solution?: I attached some mac links to a potential solution just because I don't know your specific OS.

https://unix.stackexchange.com/questions/27851/after-installing-oh-my-zsh-zshrcsource34-no-such-file-or-directory

https://superuser.com/questions/1420641/no-such-file-or-directory-users-username-oh-my-zsh-oh-my-zsh-sh

https://superuser.com/questions/362372/how-to-change-the-login-shell-on-mac-os-x-from-bash-to-zsh/363555#363555

**Comment by mcornella** [comment]
There is a bug in the uninstaller where it won't delete the zshrc completely. If you don't have anything in there you want to save, you can just delete the zshrc file. Otherwise, remove the stuff that loads OMZ, like the `export ZSH=` line and the `source $ZSH/oh-my-zsh.sh` line.
