### ISSUE TITLE
ls Alias issues 

### ISSUE THREAD

**Issue by typkrft** [robbyrussell/oh-my-zsh#8367]
I set an alias function in my .zshrc. It was set at the end of the file after `source $ZSH/oh-my-zsh.sh` in the custom configuration section. When I open a new terminal it gives me the error:

```
Users/brandon/.zshrc:212: defining function based on alias `ls'
/Users/brandon/.zshrc:212: parse error near `()'
```
The alias function I added. 
```
ls() {
  colorls --report --gs --sd $1 $2
}
```
I have tried to follow the directions in [ls alias conflict ? #5783](https://github.com/robbyrussell/oh-my-zsh/issues/5783#issuecomment-275614664). However, I am either following it incorrectly, or it doesn't work. Additionally I have tried creating `~/.oh-my-zsh/custom/aliases.zsh` and adding it there, but unfortnutately I can't get it to work with out commenting out `ls -G . &>/dev/null && alias ls='ls -G' ` in `/Users/brandon/.oh-my-zsh/lib/theme-and-appearance.zsh`. It's not the end of the world or anything, just looking to use the preferred method. 

macOS 10.15.1 (19B88)
iTerm Build 3.3.6

**Comment by mcornella** [comment]
This is due to how zsh parses commands: since there is an alias with the name ls, it expands that such that it reads `ls alias value() {`. Recent versions have been modified to just throw the error you're getting, instead of silently evaluating the previous line I wrote.

You want to prefix the function definition with the keyword `function`: `function ls() {`. The parentheses are optional when using the function keyword.

Another option, since you're passing arguments at the end of the colorls line, is to use the `alias ls=''` construct, which will override the ls alias instead.
